/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（事業所票）h03-04
    Date: 2019/02/26 01:21:49
----------------------------------------------------------------------*/


capture label variable var1 "調査IDT"
capture label variable var2 "調査年"
capture label variable var3 "調査月(期)"
capture label variable var4 "調査票区分"
capture label variable var5 "地域番号"
capture label variable var6 "都道府県番号"
capture label variable var7 "事業所番号"
capture label variable var8 "大分類"
capture label variable var9 "中分類"
capture label variable var10 "抽出符号"
capture label variable var11 "事業所規模"
capture label variable var12 "企業規模"
capture label variable var13 "産業分類"
capture label variable var14 "事業所規模"
capture label variable var15 "性別"
capture label variable var16 "就業形態"
capture label variable var17 "乗率"
capture label variable var18 "入職者"
capture label variable var19 "転入者等"
capture label variable var20 "常用に切り替えられた者"
capture label variable var21 "離職者"
capture label variable var22 "転出者等"
capture label variable var23 "期末常用労働者"
capture label variable var24 "入職者"
capture label variable var25 "転入者等"
capture label variable var26 "常用に切り替えられた者"
capture label variable var27 "離職者"
capture label variable var28 "転出者等"
capture label variable var29 "期末常用労働者"
capture label variable var30 "入職者"
capture label variable var31 "転入者等"
capture label variable var32 "常用に切り替えられた者"
capture label variable var33 "離職者"
capture label variable var34 "転出者等"
capture label variable var35 "期末常用労働者"
capture label variable var36 "入職者"
capture label variable var37 "転入者等"
capture label variable var38 "常用に切り替えられた者"
capture label variable var39 "離職者"
capture label variable var40 "転出者等"
capture label variable var41 "期末常用労働者"
capture label variable var42 "入職者"
capture label variable var43 "転入者等"
capture label variable var44 "常用に切り替えられた者"
capture label variable var45 "離職者"
capture label variable var46 "転出者等"
capture label variable var47 "期末常用労働者"
capture label variable var48 "入職者"
capture label variable var49 "転入者等"
capture label variable var50 "常用に切り替えられた者"
capture label variable var51 "離職者"
capture label variable var52 "転出者等"
capture label variable var53 "期末常用労働者"
capture label variable var54 "入職者"
capture label variable var55 "転入者等"
capture label variable var56 "常用に切り替えられた者"
capture label variable var57 "離職者"
capture label variable var58 "転出者等"
capture label variable var59 "期末常用労働者"
capture label variable var60 "入職者"
capture label variable var61 "転入者等"
capture label variable var62 "常用に切り替えられた者"
capture label variable var63 "離職者"
capture label variable var64 "転出者等"
capture label variable var65 "期末常用労働者"
capture label variable var66 "19歳以下"
capture label variable var67 "20~24歳"
capture label variable var68 "25~29歳"
capture label variable var69 "30~34歳"
capture label variable var70 "35~44歳"
capture label variable var71 "45~54歳"
capture label variable var72 "55~59歳"
capture label variable var73 "60~64歳"
capture label variable var74 "65歳以上"
capture label variable var75 "19歳以下"
capture label variable var76 "20~24歳"
capture label variable var77 "25~29歳"
capture label variable var78 "30~34歳"
capture label variable var79 "35~44歳"
capture label variable var80 "45~54歳"
capture label variable var81 "55~59歳"
capture label variable var82 "60~64歳"
capture label variable var83 "65歳以上"
capture label variable var84 "19歳以下"
capture label variable var85 "20~24歳"
capture label variable var86 "25~29歳"
capture label variable var87 "30~34歳"
capture label variable var88 "35~44歳"
capture label variable var89 "45~54歳"
capture label variable var90 "55~59歳"
capture label variable var91 "60~64歳"
capture label variable var92 "65歳以上"
capture label variable var93 "19歳以下"
capture label variable var94 "20~24歳"
capture label variable var95 "25~29歳"
capture label variable var96 "30~34歳"
capture label variable var97 "35~44歳"
capture label variable var98 "45~54歳"
capture label variable var99 "55~59歳"
capture label variable var100 "60~64歳"
capture label variable var101 "65歳以上"
