cap label var YEAR "調査年月" 
cap label var N_CITY "市町村番号" 
cap label var N_CHOSAKU "調査区符号" 
cap label var N_SETAI "世帯番号" 
cap label var N_SETAIIN "世帯員番号" 
cap label var KC_SETAIINSU "10歳以上の世帯員数" 
cap label var KC_SETAIINSU_U10 "10歳未満の世帯員数" 
cap label var KC_HITORI "一人の世帯" 
cap label var KC_SEX "１男女の別" 
cap label var KC_TSUDUKI "２世帯主との続き柄" 
cap label var KC_GENGO "３出生元号" 
cap label var KC_YEAR "３出生年" 
cap label var KC_MONTH "３出生月" 
cap label var KC_HAIGU "４配偶者の有無" 
cap label var KC_ZAIGAKU "５教育（在学か否か）" 
cap label var KC_KYOIKU "５教育（学校の種類）" 
cap label var KC_KAIGO1 "65歳以上の家族を介護(自宅内)" 
cap label var KC_KAIGO2 "65歳以上の家族を介護(自宅外)" 
cap label var KC_KAIGO3 "その他の家族を介護(自宅内)" 
cap label var KC_KAIGO4 "その他の家族を介護(自宅外)" 
cap label var KC_KAIGO5 "介護はしていない" 
cap label var KC_CHILDHOME "８あなたの子はどこに住んでいますか" 
cap label var KC_JOB "９ふだん仕事をしていますか" 
cap label var KC_WANTJOB "10仕事をしたいと思っていますか" 
cap label var KC_TSUTOME "11勤めか自営かの別" 
cap label var KC_SHOKU_NAIYO "記入の有無" 
cap label var KC_SHOKUGYO "職業符号" 
cap label var KC_JYUGYO "13勤め先・業主などの企業全体の従業者数" 
cap label var KC_SYUGYO "14ふだんの１週間の就業時間" 
cap label var KC_TSUKIN "15ふだんの片道の通勤時間" 
cap label var KC_SYUKYU "16週休制度" 
cap label var KC_TIME_DATE "日にち" 
cap label var KC_TIME_KIND1 "旅行" 
cap label var KC_TIME_KIND2 "行楽" 
cap label var KC_TIME_KIND3 "行事または冠婚葬祭" 
cap label var KC_TIME_KIND4 "出張・研修など" 
cap label var KC_TIME_KIND5 "療養" 
cap label var KC_TIME_KIND6 "休みの日" 
cap label var KC_TIME_KIND7 "その他" 
cap label var KC_TIME_WEATHER "天気" 
cap label var KC_HOUSE "25住居の種類" 
cap label var KC_CAR "27自家用車の有無" 
cap label var KC_SYUNYU "28世帯の年間収入(税込み)" 
cap label var KC_HELP "29ふだん世帯以外の人から介護の手助けを受けていますか" 
cap label var KC_TANSHIN1 "いない" 
cap label var KC_TANSHIN2 "配偶者" 
cap label var KC_TANSHIN3 "父母または配偶者の父母" 
cap label var KC_TANSHIN4 "子または子の配偶者" 
cap label var KC_TANSHIN5 "その他" 
cap label var KC_NYUIN1 "いない" 
cap label var KC_NYUIN2 "配偶者" 
cap label var KC_NYUIN3 "父母または配偶者の父母" 
cap label var KC_NYUIN4 "子または子の配偶者" 
cap label var KC_NYUIN5 "その他" 
cap label var KC_U10_TSUDUKI1 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE1 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU1 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI2 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE2 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU2 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI3 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE3 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU3 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI4 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE4 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU4 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI5 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE5 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU5 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI6 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE6 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU6 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI7 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE7 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU7 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI8 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE8 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU8 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI9 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE9 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU9 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI10 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE10 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU10 "33(10歳未満)在学・在園の状況" 
cap label var KC_AGE "年齢" 
cap label var JORITSU "集計用乗率" 
cap label var KEN "都道府県" 
cap label var CITY "市区町村" 
cap label var DAITOSHI "大都市圏符号" 
cap label var TOSHI "都市階級符号" 
cap label var DIDKBN "人口集中・非集中の別" 
cap label var Chiiki "14地域" 
cap label var HINITI "1日目か2日目か" 
cap label var Youbi7 "7区分（曜日）" 
cap label var  "行動時間" 
cap label var var1_1 "時間区分" 
cap label var var2_1 "行動の種類" 
cap label var var3_1 "一人で（一緒にいた人）" 
cap label var var4_1 "家族（一緒にいた人）" 
cap label var var5_1 "学校・職場の人（一緒にいた人）" 
cap label var var6_1 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_2 "時間区分" 
cap label var var2_2 "行動の種類" 
cap label var var3_2 "一人で（一緒にいた人）" 
cap label var var4_2 "家族（一緒にいた人）" 
cap label var var5_2 "学校・職場の人（一緒にいた人）" 
cap label var var6_2 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_3 "時間区分" 
cap label var var2_3 "行動の種類" 
cap label var var3_3 "一人で（一緒にいた人）" 
cap label var var4_3 "家族（一緒にいた人）" 
cap label var var5_3 "学校・職場の人（一緒にいた人）" 
cap label var var6_3 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_4 "時間区分" 
cap label var var2_4 "行動の種類" 
cap label var var3_4 "一人で（一緒にいた人）" 
cap label var var4_4 "家族（一緒にいた人）" 
cap label var var5_4 "学校・職場の人（一緒にいた人）" 
cap label var var6_4 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_5 "時間区分" 
cap label var var2_5 "行動の種類" 
cap label var var3_5 "一人で（一緒にいた人）" 
cap label var var4_5 "家族（一緒にいた人）" 
cap label var var5_5 "学校・職場の人（一緒にいた人）" 
cap label var var6_5 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_6 "時間区分" 
cap label var var2_6 "行動の種類" 
cap label var var3_6 "一人で（一緒にいた人）" 
cap label var var4_6 "家族（一緒にいた人）" 
cap label var var5_6 "学校・職場の人（一緒にいた人）" 
cap label var var6_6 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_7 "時間区分" 
cap label var var2_7 "行動の種類" 
cap label var var3_7 "一人で（一緒にいた人）" 
cap label var var4_7 "家族（一緒にいた人）" 
cap label var var5_7 "学校・職場の人（一緒にいた人）" 
cap label var var6_7 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_8 "時間区分" 
cap label var var2_8 "行動の種類" 
cap label var var3_8 "一人で（一緒にいた人）" 
cap label var var4_8 "家族（一緒にいた人）" 
cap label var var5_8 "学校・職場の人（一緒にいた人）" 
cap label var var6_8 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_9 "時間区分" 
cap label var var2_9 "行動の種類" 
cap label var var3_9 "一人で（一緒にいた人）" 
cap label var var4_9 "家族（一緒にいた人）" 
cap label var var5_9 "学校・職場の人（一緒にいた人）" 
cap label var var6_9 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_10 "時間区分" 
cap label var var2_10 "行動の種類" 
cap label var var3_10 "一人で（一緒にいた人）" 
cap label var var4_10 "家族（一緒にいた人）" 
cap label var var5_10 "学校・職場の人（一緒にいた人）" 
cap label var var6_10 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_11 "時間区分" 
cap label var var2_11 "行動の種類" 
cap label var var3_11 "一人で（一緒にいた人）" 
cap label var var4_11 "家族（一緒にいた人）" 
cap label var var5_11 "学校・職場の人（一緒にいた人）" 
cap label var var6_11 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_12 "時間区分" 
cap label var var2_12 "行動の種類" 
cap label var var3_12 "一人で（一緒にいた人）" 
cap label var var4_12 "家族（一緒にいた人）" 
cap label var var5_12 "学校・職場の人（一緒にいた人）" 
cap label var var6_12 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_13 "時間区分" 
cap label var var2_13 "行動の種類" 
cap label var var3_13 "一人で（一緒にいた人）" 
cap label var var4_13 "家族（一緒にいた人）" 
cap label var var5_13 "学校・職場の人（一緒にいた人）" 
cap label var var6_13 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_14 "時間区分" 
cap label var var2_14 "行動の種類" 
cap label var var3_14 "一人で（一緒にいた人）" 
cap label var var4_14 "家族（一緒にいた人）" 
cap label var var5_14 "学校・職場の人（一緒にいた人）" 
cap label var var6_14 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_15 "時間区分" 
cap label var var2_15 "行動の種類" 
cap label var var3_15 "一人で（一緒にいた人）" 
cap label var var4_15 "家族（一緒にいた人）" 
cap label var var5_15 "学校・職場の人（一緒にいた人）" 
cap label var var6_15 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_16 "時間区分" 
cap label var var2_16 "行動の種類" 
cap label var var3_16 "一人で（一緒にいた人）" 
cap label var var4_16 "家族（一緒にいた人）" 
cap label var var5_16 "学校・職場の人（一緒にいた人）" 
cap label var var6_16 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_17 "時間区分" 
cap label var var2_17 "行動の種類" 
cap label var var3_17 "一人で（一緒にいた人）" 
cap label var var4_17 "家族（一緒にいた人）" 
cap label var var5_17 "学校・職場の人（一緒にいた人）" 
cap label var var6_17 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_18 "時間区分" 
cap label var var2_18 "行動の種類" 
cap label var var3_18 "一人で（一緒にいた人）" 
cap label var var4_18 "家族（一緒にいた人）" 
cap label var var5_18 "学校・職場の人（一緒にいた人）" 
cap label var var6_18 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_19 "時間区分" 
cap label var var2_19 "行動の種類" 
cap label var var3_19 "一人で（一緒にいた人）" 
cap label var var4_19 "家族（一緒にいた人）" 
cap label var var5_19 "学校・職場の人（一緒にいた人）" 
cap label var var6_19 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_20 "時間区分" 
cap label var var2_20 "行動の種類" 
cap label var var3_20 "一人で（一緒にいた人）" 
cap label var var4_20 "家族（一緒にいた人）" 
cap label var var5_20 "学校・職場の人（一緒にいた人）" 
cap label var var6_20 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_21 "時間区分" 
cap label var var2_21 "行動の種類" 
cap label var var3_21 "一人で（一緒にいた人）" 
cap label var var4_21 "家族（一緒にいた人）" 
cap label var var5_21 "学校・職場の人（一緒にいた人）" 
cap label var var6_21 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_22 "時間区分" 
cap label var var2_22 "行動の種類" 
cap label var var3_22 "一人で（一緒にいた人）" 
cap label var var4_22 "家族（一緒にいた人）" 
cap label var var5_22 "学校・職場の人（一緒にいた人）" 
cap label var var6_22 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_23 "時間区分" 
cap label var var2_23 "行動の種類" 
cap label var var3_23 "一人で（一緒にいた人）" 
cap label var var4_23 "家族（一緒にいた人）" 
cap label var var5_23 "学校・職場の人（一緒にいた人）" 
cap label var var6_23 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_24 "時間区分" 
cap label var var2_24 "行動の種類" 
cap label var var3_24 "一人で（一緒にいた人）" 
cap label var var4_24 "家族（一緒にいた人）" 
cap label var var5_24 "学校・職場の人（一緒にいた人）" 
cap label var var6_24 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_25 "時間区分" 
cap label var var2_25 "行動の種類" 
cap label var var3_25 "一人で（一緒にいた人）" 
cap label var var4_25 "家族（一緒にいた人）" 
cap label var var5_25 "学校・職場の人（一緒にいた人）" 
cap label var var6_25 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_26 "時間区分" 
cap label var var2_26 "行動の種類" 
cap label var var3_26 "一人で（一緒にいた人）" 
cap label var var4_26 "家族（一緒にいた人）" 
cap label var var5_26 "学校・職場の人（一緒にいた人）" 
cap label var var6_26 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_27 "時間区分" 
cap label var var2_27 "行動の種類" 
cap label var var3_27 "一人で（一緒にいた人）" 
cap label var var4_27 "家族（一緒にいた人）" 
cap label var var5_27 "学校・職場の人（一緒にいた人）" 
cap label var var6_27 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_28 "時間区分" 
cap label var var2_28 "行動の種類" 
cap label var var3_28 "一人で（一緒にいた人）" 
cap label var var4_28 "家族（一緒にいた人）" 
cap label var var5_28 "学校・職場の人（一緒にいた人）" 
cap label var var6_28 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_29 "時間区分" 
cap label var var2_29 "行動の種類" 
cap label var var3_29 "一人で（一緒にいた人）" 
cap label var var4_29 "家族（一緒にいた人）" 
cap label var var5_29 "学校・職場の人（一緒にいた人）" 
cap label var var6_29 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_30 "時間区分" 
cap label var var2_30 "行動の種類" 
cap label var var3_30 "一人で（一緒にいた人）" 
cap label var var4_30 "家族（一緒にいた人）" 
cap label var var5_30 "学校・職場の人（一緒にいた人）" 
cap label var var6_30 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_31 "時間区分" 
cap label var var2_31 "行動の種類" 
cap label var var3_31 "一人で（一緒にいた人）" 
cap label var var4_31 "家族（一緒にいた人）" 
cap label var var5_31 "学校・職場の人（一緒にいた人）" 
cap label var var6_31 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_32 "時間区分" 
cap label var var2_32 "行動の種類" 
cap label var var3_32 "一人で（一緒にいた人）" 
cap label var var4_32 "家族（一緒にいた人）" 
cap label var var5_32 "学校・職場の人（一緒にいた人）" 
cap label var var6_32 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_33 "時間区分" 
cap label var var2_33 "行動の種類" 
cap label var var3_33 "一人で（一緒にいた人）" 
cap label var var4_33 "家族（一緒にいた人）" 
cap label var var5_33 "学校・職場の人（一緒にいた人）" 
cap label var var6_33 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_34 "時間区分" 
cap label var var2_34 "行動の種類" 
cap label var var3_34 "一人で（一緒にいた人）" 
cap label var var4_34 "家族（一緒にいた人）" 
cap label var var5_34 "学校・職場の人（一緒にいた人）" 
cap label var var6_34 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_35 "時間区分" 
cap label var var2_35 "行動の種類" 
cap label var var3_35 "一人で（一緒にいた人）" 
cap label var var4_35 "家族（一緒にいた人）" 
cap label var var5_35 "学校・職場の人（一緒にいた人）" 
cap label var var6_35 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_36 "時間区分" 
cap label var var2_36 "行動の種類" 
cap label var var3_36 "一人で（一緒にいた人）" 
cap label var var4_36 "家族（一緒にいた人）" 
cap label var var5_36 "学校・職場の人（一緒にいた人）" 
cap label var var6_36 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_37 "時間区分" 
cap label var var2_37 "行動の種類" 
cap label var var3_37 "一人で（一緒にいた人）" 
cap label var var4_37 "家族（一緒にいた人）" 
cap label var var5_37 "学校・職場の人（一緒にいた人）" 
cap label var var6_37 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_38 "時間区分" 
cap label var var2_38 "行動の種類" 
cap label var var3_38 "一人で（一緒にいた人）" 
cap label var var4_38 "家族（一緒にいた人）" 
cap label var var5_38 "学校・職場の人（一緒にいた人）" 
cap label var var6_38 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_39 "時間区分" 
cap label var var2_39 "行動の種類" 
cap label var var3_39 "一人で（一緒にいた人）" 
cap label var var4_39 "家族（一緒にいた人）" 
cap label var var5_39 "学校・職場の人（一緒にいた人）" 
cap label var var6_39 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_40 "時間区分" 
cap label var var2_40 "行動の種類" 
cap label var var3_40 "一人で（一緒にいた人）" 
cap label var var4_40 "家族（一緒にいた人）" 
cap label var var5_40 "学校・職場の人（一緒にいた人）" 
cap label var var6_40 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_41 "時間区分" 
cap label var var2_41 "行動の種類" 
cap label var var3_41 "一人で（一緒にいた人）" 
cap label var var4_41 "家族（一緒にいた人）" 
cap label var var5_41 "学校・職場の人（一緒にいた人）" 
cap label var var6_41 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_42 "時間区分" 
cap label var var2_42 "行動の種類" 
cap label var var3_42 "一人で（一緒にいた人）" 
cap label var var4_42 "家族（一緒にいた人）" 
cap label var var5_42 "学校・職場の人（一緒にいた人）" 
cap label var var6_42 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_43 "時間区分" 
cap label var var2_43 "行動の種類" 
cap label var var3_43 "一人で（一緒にいた人）" 
cap label var var4_43 "家族（一緒にいた人）" 
cap label var var5_43 "学校・職場の人（一緒にいた人）" 
cap label var var6_43 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_44 "時間区分" 
cap label var var2_44 "行動の種類" 
cap label var var3_44 "一人で（一緒にいた人）" 
cap label var var4_44 "家族（一緒にいた人）" 
cap label var var5_44 "学校・職場の人（一緒にいた人）" 
cap label var var6_44 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_45 "時間区分" 
cap label var var2_45 "行動の種類" 
cap label var var3_45 "一人で（一緒にいた人）" 
cap label var var4_45 "家族（一緒にいた人）" 
cap label var var5_45 "学校・職場の人（一緒にいた人）" 
cap label var var6_45 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_46 "時間区分" 
cap label var var2_46 "行動の種類" 
cap label var var3_46 "一人で（一緒にいた人）" 
cap label var var4_46 "家族（一緒にいた人）" 
cap label var var5_46 "学校・職場の人（一緒にいた人）" 
cap label var var6_46 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_47 "時間区分" 
cap label var var2_47 "行動の種類" 
cap label var var3_47 "一人で（一緒にいた人）" 
cap label var var4_47 "家族（一緒にいた人）" 
cap label var var5_47 "学校・職場の人（一緒にいた人）" 
cap label var var6_47 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_48 "時間区分" 
cap label var var2_48 "行動の種類" 
cap label var var3_48 "一人で（一緒にいた人）" 
cap label var var4_48 "家族（一緒にいた人）" 
cap label var var5_48 "学校・職場の人（一緒にいた人）" 
cap label var var6_48 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_49 "時間区分" 
cap label var var2_49 "行動の種類" 
cap label var var3_49 "一人で（一緒にいた人）" 
cap label var var4_49 "家族（一緒にいた人）" 
cap label var var5_49 "学校・職場の人（一緒にいた人）" 
cap label var var6_49 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_50 "時間区分" 
cap label var var2_50 "行動の種類" 
cap label var var3_50 "一人で（一緒にいた人）" 
cap label var var4_50 "家族（一緒にいた人）" 
cap label var var5_50 "学校・職場の人（一緒にいた人）" 
cap label var var6_50 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_51 "時間区分" 
cap label var var2_51 "行動の種類" 
cap label var var3_51 "一人で（一緒にいた人）" 
cap label var var4_51 "家族（一緒にいた人）" 
cap label var var5_51 "学校・職場の人（一緒にいた人）" 
cap label var var6_51 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_52 "時間区分" 
cap label var var2_52 "行動の種類" 
cap label var var3_52 "一人で（一緒にいた人）" 
cap label var var4_52 "家族（一緒にいた人）" 
cap label var var5_52 "学校・職場の人（一緒にいた人）" 
cap label var var6_52 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_53 "時間区分" 
cap label var var2_53 "行動の種類" 
cap label var var3_53 "一人で（一緒にいた人）" 
cap label var var4_53 "家族（一緒にいた人）" 
cap label var var5_53 "学校・職場の人（一緒にいた人）" 
cap label var var6_53 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_54 "時間区分" 
cap label var var2_54 "行動の種類" 
cap label var var3_54 "一人で（一緒にいた人）" 
cap label var var4_54 "家族（一緒にいた人）" 
cap label var var5_54 "学校・職場の人（一緒にいた人）" 
cap label var var6_54 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_55 "時間区分" 
cap label var var2_55 "行動の種類" 
cap label var var3_55 "一人で（一緒にいた人）" 
cap label var var4_55 "家族（一緒にいた人）" 
cap label var var5_55 "学校・職場の人（一緒にいた人）" 
cap label var var6_55 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_56 "時間区分" 
cap label var var2_56 "行動の種類" 
cap label var var3_56 "一人で（一緒にいた人）" 
cap label var var4_56 "家族（一緒にいた人）" 
cap label var var5_56 "学校・職場の人（一緒にいた人）" 
cap label var var6_56 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_57 "時間区分" 
cap label var var2_57 "行動の種類" 
cap label var var3_57 "一人で（一緒にいた人）" 
cap label var var4_57 "家族（一緒にいた人）" 
cap label var var5_57 "学校・職場の人（一緒にいた人）" 
cap label var var6_57 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_58 "時間区分" 
cap label var var2_58 "行動の種類" 
cap label var var3_58 "一人で（一緒にいた人）" 
cap label var var4_58 "家族（一緒にいた人）" 
cap label var var5_58 "学校・職場の人（一緒にいた人）" 
cap label var var6_58 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_59 "時間区分" 
cap label var var2_59 "行動の種類" 
cap label var var3_59 "一人で（一緒にいた人）" 
cap label var var4_59 "家族（一緒にいた人）" 
cap label var var5_59 "学校・職場の人（一緒にいた人）" 
cap label var var6_59 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_60 "時間区分" 
cap label var var2_60 "行動の種類" 
cap label var var3_60 "一人で（一緒にいた人）" 
cap label var var4_60 "家族（一緒にいた人）" 
cap label var var5_60 "学校・職場の人（一緒にいた人）" 
cap label var var6_60 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_61 "時間区分" 
cap label var var2_61 "行動の種類" 
cap label var var3_61 "一人で（一緒にいた人）" 
cap label var var4_61 "家族（一緒にいた人）" 
cap label var var5_61 "学校・職場の人（一緒にいた人）" 
cap label var var6_61 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_62 "時間区分" 
cap label var var2_62 "行動の種類" 
cap label var var3_62 "一人で（一緒にいた人）" 
cap label var var4_62 "家族（一緒にいた人）" 
cap label var var5_62 "学校・職場の人（一緒にいた人）" 
cap label var var6_62 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_63 "時間区分" 
cap label var var2_63 "行動の種類" 
cap label var var3_63 "一人で（一緒にいた人）" 
cap label var var4_63 "家族（一緒にいた人）" 
cap label var var5_63 "学校・職場の人（一緒にいた人）" 
cap label var var6_63 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_64 "時間区分" 
cap label var var2_64 "行動の種類" 
cap label var var3_64 "一人で（一緒にいた人）" 
cap label var var4_64 "家族（一緒にいた人）" 
cap label var var5_64 "学校・職場の人（一緒にいた人）" 
cap label var var6_64 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_65 "時間区分" 
cap label var var2_65 "行動の種類" 
cap label var var3_65 "一人で（一緒にいた人）" 
cap label var var4_65 "家族（一緒にいた人）" 
cap label var var5_65 "学校・職場の人（一緒にいた人）" 
cap label var var6_65 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_66 "時間区分" 
cap label var var2_66 "行動の種類" 
cap label var var3_66 "一人で（一緒にいた人）" 
cap label var var4_66 "家族（一緒にいた人）" 
cap label var var5_66 "学校・職場の人（一緒にいた人）" 
cap label var var6_66 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_67 "時間区分" 
cap label var var2_67 "行動の種類" 
cap label var var3_67 "一人で（一緒にいた人）" 
cap label var var4_67 "家族（一緒にいた人）" 
cap label var var5_67 "学校・職場の人（一緒にいた人）" 
cap label var var6_67 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_68 "時間区分" 
cap label var var2_68 "行動の種類" 
cap label var var3_68 "一人で（一緒にいた人）" 
cap label var var4_68 "家族（一緒にいた人）" 
cap label var var5_68 "学校・職場の人（一緒にいた人）" 
cap label var var6_68 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_69 "時間区分" 
cap label var var2_69 "行動の種類" 
cap label var var3_69 "一人で（一緒にいた人）" 
cap label var var4_69 "家族（一緒にいた人）" 
cap label var var5_69 "学校・職場の人（一緒にいた人）" 
cap label var var6_69 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_70 "時間区分" 
cap label var var2_70 "行動の種類" 
cap label var var3_70 "一人で（一緒にいた人）" 
cap label var var4_70 "家族（一緒にいた人）" 
cap label var var5_70 "学校・職場の人（一緒にいた人）" 
cap label var var6_70 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_71 "時間区分" 
cap label var var2_71 "行動の種類" 
cap label var var3_71 "一人で（一緒にいた人）" 
cap label var var4_71 "家族（一緒にいた人）" 
cap label var var5_71 "学校・職場の人（一緒にいた人）" 
cap label var var6_71 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_72 "時間区分" 
cap label var var2_72 "行動の種類" 
cap label var var3_72 "一人で（一緒にいた人）" 
cap label var var4_72 "家族（一緒にいた人）" 
cap label var var5_72 "学校・職場の人（一緒にいた人）" 
cap label var var6_72 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_73 "時間区分" 
cap label var var2_73 "行動の種類" 
cap label var var3_73 "一人で（一緒にいた人）" 
cap label var var4_73 "家族（一緒にいた人）" 
cap label var var5_73 "学校・職場の人（一緒にいた人）" 
cap label var var6_73 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_74 "時間区分" 
cap label var var2_74 "行動の種類" 
cap label var var3_74 "一人で（一緒にいた人）" 
cap label var var4_74 "家族（一緒にいた人）" 
cap label var var5_74 "学校・職場の人（一緒にいた人）" 
cap label var var6_74 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_75 "時間区分" 
cap label var var2_75 "行動の種類" 
cap label var var3_75 "一人で（一緒にいた人）" 
cap label var var4_75 "家族（一緒にいた人）" 
cap label var var5_75 "学校・職場の人（一緒にいた人）" 
cap label var var6_75 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_76 "時間区分" 
cap label var var2_76 "行動の種類" 
cap label var var3_76 "一人で（一緒にいた人）" 
cap label var var4_76 "家族（一緒にいた人）" 
cap label var var5_76 "学校・職場の人（一緒にいた人）" 
cap label var var6_76 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_77 "時間区分" 
cap label var var2_77 "行動の種類" 
cap label var var3_77 "一人で（一緒にいた人）" 
cap label var var4_77 "家族（一緒にいた人）" 
cap label var var5_77 "学校・職場の人（一緒にいた人）" 
cap label var var6_77 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_78 "時間区分" 
cap label var var2_78 "行動の種類" 
cap label var var3_78 "一人で（一緒にいた人）" 
cap label var var4_78 "家族（一緒にいた人）" 
cap label var var5_78 "学校・職場の人（一緒にいた人）" 
cap label var var6_78 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_79 "時間区分" 
cap label var var2_79 "行動の種類" 
cap label var var3_79 "一人で（一緒にいた人）" 
cap label var var4_79 "家族（一緒にいた人）" 
cap label var var5_79 "学校・職場の人（一緒にいた人）" 
cap label var var6_79 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_80 "時間区分" 
cap label var var2_80 "行動の種類" 
cap label var var3_80 "一人で（一緒にいた人）" 
cap label var var4_80 "家族（一緒にいた人）" 
cap label var var5_80 "学校・職場の人（一緒にいた人）" 
cap label var var6_80 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_81 "時間区分" 
cap label var var2_81 "行動の種類" 
cap label var var3_81 "一人で（一緒にいた人）" 
cap label var var4_81 "家族（一緒にいた人）" 
cap label var var5_81 "学校・職場の人（一緒にいた人）" 
cap label var var6_81 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_82 "時間区分" 
cap label var var2_82 "行動の種類" 
cap label var var3_82 "一人で（一緒にいた人）" 
cap label var var4_82 "家族（一緒にいた人）" 
cap label var var5_82 "学校・職場の人（一緒にいた人）" 
cap label var var6_82 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_83 "時間区分" 
cap label var var2_83 "行動の種類" 
cap label var var3_83 "一人で（一緒にいた人）" 
cap label var var4_83 "家族（一緒にいた人）" 
cap label var var5_83 "学校・職場の人（一緒にいた人）" 
cap label var var6_83 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_84 "時間区分" 
cap label var var2_84 "行動の種類" 
cap label var var3_84 "一人で（一緒にいた人）" 
cap label var var4_84 "家族（一緒にいた人）" 
cap label var var5_84 "学校・職場の人（一緒にいた人）" 
cap label var var6_84 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_85 "時間区分" 
cap label var var2_85 "行動の種類" 
cap label var var3_85 "一人で（一緒にいた人）" 
cap label var var4_85 "家族（一緒にいた人）" 
cap label var var5_85 "学校・職場の人（一緒にいた人）" 
cap label var var6_85 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_86 "時間区分" 
cap label var var2_86 "行動の種類" 
cap label var var3_86 "一人で（一緒にいた人）" 
cap label var var4_86 "家族（一緒にいた人）" 
cap label var var5_86 "学校・職場の人（一緒にいた人）" 
cap label var var6_86 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_87 "時間区分" 
cap label var var2_87 "行動の種類" 
cap label var var3_87 "一人で（一緒にいた人）" 
cap label var var4_87 "家族（一緒にいた人）" 
cap label var var5_87 "学校・職場の人（一緒にいた人）" 
cap label var var6_87 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_88 "時間区分" 
cap label var var2_88 "行動の種類" 
cap label var var3_88 "一人で（一緒にいた人）" 
cap label var var4_88 "家族（一緒にいた人）" 
cap label var var5_88 "学校・職場の人（一緒にいた人）" 
cap label var var6_88 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_89 "時間区分" 
cap label var var2_89 "行動の種類" 
cap label var var3_89 "一人で（一緒にいた人）" 
cap label var var4_89 "家族（一緒にいた人）" 
cap label var var5_89 "学校・職場の人（一緒にいた人）" 
cap label var var6_89 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_90 "時間区分" 
cap label var var2_90 "行動の種類" 
cap label var var3_90 "一人で（一緒にいた人）" 
cap label var var4_90 "家族（一緒にいた人）" 
cap label var var5_90 "学校・職場の人（一緒にいた人）" 
cap label var var6_90 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_91 "時間区分" 
cap label var var2_91 "行動の種類" 
cap label var var3_91 "一人で（一緒にいた人）" 
cap label var var4_91 "家族（一緒にいた人）" 
cap label var var5_91 "学校・職場の人（一緒にいた人）" 
cap label var var6_91 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_92 "時間区分" 
cap label var var2_92 "行動の種類" 
cap label var var3_92 "一人で（一緒にいた人）" 
cap label var var4_92 "家族（一緒にいた人）" 
cap label var var5_92 "学校・職場の人（一緒にいた人）" 
cap label var var6_92 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_93 "時間区分" 
cap label var var2_93 "行動の種類" 
cap label var var3_93 "一人で（一緒にいた人）" 
cap label var var4_93 "家族（一緒にいた人）" 
cap label var var5_93 "学校・職場の人（一緒にいた人）" 
cap label var var6_93 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_94 "時間区分" 
cap label var var2_94 "行動の種類" 
cap label var var3_94 "一人で（一緒にいた人）" 
cap label var var4_94 "家族（一緒にいた人）" 
cap label var var5_94 "学校・職場の人（一緒にいた人）" 
cap label var var6_94 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_95 "時間区分" 
cap label var var2_95 "行動の種類" 
cap label var var3_95 "一人で（一緒にいた人）" 
cap label var var4_95 "家族（一緒にいた人）" 
cap label var var5_95 "学校・職場の人（一緒にいた人）" 
cap label var var6_95 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var var1_96 "時間区分" 
cap label var var2_96 "行動の種類" 
cap label var var3_96 "一人で（一緒にいた人）" 
cap label var var4_96 "家族（一緒にいた人）" 
cap label var var5_96 "学校・職場の人（一緒にいた人）" 
cap label var var6_96 "その他の人（一緒にいた人）" 
