cap label var YEAR "調査年月" 
cap label var N_CITY "市町村番号" 
cap label var N_CHOSAKU "調査区符号" 
cap label var N_SETAI "世帯番号" 
cap label var N_SETAIIN "世帯員番号" 
cap label var KC_SETAIINSU "10歳以上の世帯員数" 
cap label var KC_SETAIINSU_U10 "10歳未満の世帯員数" 
cap label var KC_HITORI "一人の世帯" 
cap label var KC_SEX "１男女の別" 
cap label var KC_TSUDUKI "２世帯主との続き柄" 
cap label var KC_GENGO "３出生元号" 
cap label var KC_YEAR "３出生年" 
cap label var KC_MONTH "３出生月" 
cap label var KC_HAIGU "４配偶者の有無" 
cap label var KC_ZAIGAKU "５教育（在学か否か）" 
cap label var KC_KYOIKU "５教育（学校の種類）" 
cap label var KC_KAIGO1 "65歳以上の家族を介護(自宅内)" 
cap label var KC_KAIGO2 "65歳以上の家族を介護(自宅外)" 
cap label var KC_KAIGO3 "その他の家族を介護(自宅内)" 
cap label var KC_KAIGO4 "その他の家族を介護(自宅外)" 
cap label var KC_KAIGO5 "介護はしていない" 
cap label var KC_CHILDHOME "８あなたの子はどこに住んでいますか" 
cap label var KC_JOB "９ふだん仕事をしていますか" 
cap label var KC_WANTJOB "10仕事をしたいと思っていますか" 
cap label var KC_TSUTOME "11勤めか自営かの別" 
cap label var KC_SHOKU_NAIYO "記入の有無" 
cap label var KC_SHOKUGYO "職業符号" 
cap label var KC_JYUGYO "13勤め先・業主などの企業全体の従業者数" 
cap label var KC_SYUGYO "14ふだんの１週間の就業時間" 
cap label var KC_TSUKIN "15ふだんの片道の通勤時間" 
cap label var KC_SYUKYU "16週休制度" 
cap label var KC_TIME_DATE "日にち" 
cap label var KC_TIME_KIND1 "旅行" 
cap label var KC_TIME_KIND2 "行楽" 
cap label var KC_TIME_KIND3 "行事または冠婚葬祭" 
cap label var KC_TIME_KIND4 "出張・研修など" 
cap label var KC_TIME_KIND5 "療養" 
cap label var KC_TIME_KIND6 "休みの日" 
cap label var KC_TIME_KIND7 "その他" 
cap label var KC_TIME_WEATHER "天気" 
cap label var KC_HOUSE "25住居の種類" 
cap label var KC_CAR "27自家用車の有無" 
cap label var KC_SYUNYU "28世帯の年間収入(税込み)" 
cap label var KC_HELP "29ふだん世帯以外の人から介護の手助けを受けていますか" 
cap label var KC_TANSHIN1 "いない" 
cap label var KC_TANSHIN2 "配偶者" 
cap label var KC_TANSHIN3 "父母または配偶者の父母" 
cap label var KC_TANSHIN4 "子または子の配偶者" 
cap label var KC_TANSHIN5 "その他" 
cap label var KC_NYUIN1 "いない" 
cap label var KC_NYUIN2 "配偶者" 
cap label var KC_NYUIN3 "父母または配偶者の父母" 
cap label var KC_NYUIN4 "子または子の配偶者" 
cap label var KC_NYUIN5 "その他" 
cap label var KC_U10_TSUDUKI1 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE1 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU1 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI2 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE2 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU2 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI3 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE3 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU3 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI4 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE4 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU4 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI5 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE5 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU5 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI6 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE6 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU6 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI7 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE7 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU7 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI8 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE8 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU8 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI9 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE9 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU9 "33(10歳未満)在学・在園の状況" 
cap label var KC_U10_TSUDUKI10 "31(10歳未満)世帯主との続き柄" 
cap label var KC_U10_AGE10 "32(10歳未満)年齢" 
cap label var KC_U10_ZAIGAKU10 "33(10歳未満)在学・在園の状況" 
cap label var KC_AGE "年齢" 
cap label var JORITSU "集計用乗率" 
cap label var KEN "都道府県" 
cap label var CITY "市区町村" 
cap label var DAITOSHI "大都市圏符号" 
cap label var TOSHI "都市階級符号" 
cap label var DIDKBN "人口集中・非集中の別" 
cap label var Chiiki "14地域" 
cap label var var1 "学習・研究(1)総数　実施の有無" 
cap label var var2 "ブランク" 
cap label var var3 "目的　自分の教養を高めるため" 
cap label var var4 "目的　仕事につくため" 
cap label var var5 "目的　現在の仕事に役立てるため" 
cap label var var6 "目的　その他" 
cap label var var7 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var8 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var9 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var10 "方法　講演会など" 
cap label var var11 "方法　通信教育" 
cap label var var12 "方法　テレビ・ラジオ" 
cap label var var13 "方法　職場での時間外" 
cap label var var14 "方法　各種学校・専修学校" 
cap label var var15 "方法　職業能力開発校など" 
cap label var var16 "方法　その他" 
cap label var var17 "学習・研究(2)外国語　実施の有無" 
cap label var var18 "ブランク" 
cap label var var19 "目的　自分の教養を高めるため" 
cap label var var20 "目的　仕事につくため" 
cap label var var21 "目的　現在の仕事に役立てるため" 
cap label var var22 "目的　その他" 
cap label var var23 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var24 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var25 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var26 "方法　講演会など" 
cap label var var27 "方法　通信教育" 
cap label var var28 "方法　テレビ・ラジオ" 
cap label var var29 "方法　職場での時間外" 
cap label var var30 "方法　各種学校・専修学校" 
cap label var var31 "方法　職業能力開発校など" 
cap label var var32 "方法　その他" 
cap label var var33 "学習・研究(3)英語　実施の有無" 
cap label var var34 "頻度" 
cap label var var35 "頻度階級中央値" 
cap label var var36 "目的　自分の教養を高めるため" 
cap label var var37 "目的　仕事につくため" 
cap label var var38 "目的　現在の仕事に役立てるため" 
cap label var var39 "目的　その他" 
cap label var var40 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var41 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var42 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var43 "方法　講演会など" 
cap label var var44 "方法　通信教育" 
cap label var var45 "方法　テレビ・ラジオ" 
cap label var var46 "方法　職場での時間外" 
cap label var var47 "方法　各種学校・専修学校" 
cap label var var48 "方法　職業能力開発校など" 
cap label var var49 "方法　その他" 
cap label var var50 "学習・研究(4)英語以外の外国語　実施の有無" 
cap label var var51 "頻度" 
cap label var var52 "頻度階級中央値" 
cap label var var53 "目的　自分の教養を高めるため" 
cap label var var54 "目的　仕事につくため" 
cap label var var55 "目的　現在の仕事に役立てるため" 
cap label var var56 "目的　その他" 
cap label var var57 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var58 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var59 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var60 "方法　講演会など" 
cap label var var61 "方法　通信教育" 
cap label var var62 "方法　テレビ・ラジオ" 
cap label var var63 "方法　職場での時間外" 
cap label var var64 "方法　各種学校・専修学校" 
cap label var var65 "方法　職業能力開発校など" 
cap label var var66 "方法　その他" 
cap label var var67 "学習・研究(5)商業・ビジネス(総数)　実施の有無" 
cap label var var68 "ブランク" 
cap label var var69 "目的　自分の教養を高めるため" 
cap label var var70 "目的　仕事につくため" 
cap label var var71 "目的　現在の仕事に役立てるため" 
cap label var var72 "目的　その他" 
cap label var var73 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var74 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var75 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var76 "方法　講演会など" 
cap label var var77 "方法　通信教育" 
cap label var var78 "方法　テレビ・ラジオ" 
cap label var var79 "方法　職場での時間外" 
cap label var var80 "方法　各種学校・専修学校" 
cap label var var81 "方法　職業能力開発校など" 
cap label var var82 "方法　その他" 
cap label var var83 "学習・研究(6)パソコンなど…　実施の有無" 
cap label var var84 "頻度" 
cap label var var85 "頻度階級中央値" 
cap label var var86 "目的　自分の教養を高めるため" 
cap label var var87 "目的　仕事につくため" 
cap label var var88 "目的　現在の仕事に役立てるため" 
cap label var var89 "目的　その他" 
cap label var var90 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var91 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var92 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var93 "方法　講演会など" 
cap label var var94 "方法　通信教育" 
cap label var var95 "方法　テレビ・ラジオ" 
cap label var var96 "方法　職場での時間外" 
cap label var var97 "方法　各種学校・専修学校" 
cap label var var98 "方法　職業能力開発校など" 
cap label var var99 "方法　その他" 
cap label var var100 "学習・研究(7)商業実務…　実施の有無" 
cap label var var101 "頻度" 
cap label var var102 "頻度階級中央値" 
cap label var var103 "目的　自分の教養を高めるため" 
cap label var var104 "目的　仕事につくため" 
cap label var var105 "目的　現在の仕事に役立てるため" 
cap label var var106 "目的　その他" 
cap label var var107 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var108 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var109 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var110 "方法　講演会など" 
cap label var var111 "方法　通信教育" 
cap label var var112 "方法　テレビ・ラジオ" 
cap label var var113 "方法　職場での時間外" 
cap label var var114 "方法　各種学校・専修学校" 
cap label var var115 "方法　職業能力開発校など" 
cap label var var116 "方法　その他" 
cap label var var117 "学習・研究(8)介護関係　実施の有無" 
cap label var var118 "頻度" 
cap label var var119 "頻度階級中央値" 
cap label var var120 "目的　自分の教養を高めるため" 
cap label var var121 "目的　仕事につくため" 
cap label var var122 "目的　現在の仕事に役立てるため" 
cap label var var123 "目的　その他" 
cap label var var124 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var125 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var126 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var127 "方法　講演会など" 
cap label var var128 "方法　通信教育" 
cap label var var129 "方法　テレビ・ラジオ" 
cap label var var130 "方法　職場での時間外" 
cap label var var131 "方法　各種学校・専修学校" 
cap label var var132 "方法　職業能力開発校など" 
cap label var var133 "方法　その他" 
cap label var var134 "学習・研究(9)家政・家事　実施の有無" 
cap label var var135 "頻度" 
cap label var var136 "頻度階級中央値" 
cap label var var137 "目的　自分の教養を高めるため" 
cap label var var138 "目的　仕事につくため" 
cap label var var139 "目的　現在の仕事に役立てるため" 
cap label var var140 "目的　その他" 
cap label var var141 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var142 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var143 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var144 "方法　講演会など" 
cap label var var145 "方法　通信教育" 
cap label var var146 "方法　テレビ・ラジオ" 
cap label var var147 "方法　職場での時間外" 
cap label var var148 "方法　各種学校・専修学校" 
cap label var var149 "方法　職業能力開発校など" 
cap label var var150 "方法　その他" 
cap label var var151 "学習・研究(10)人文・社会・自然科学　実施の有無" 
cap label var var152 "頻度" 
cap label var var153 "頻度階級中央値" 
cap label var var154 "目的　自分の教養を高めるため" 
cap label var var155 "目的　仕事につくため" 
cap label var var156 "目的　現在の仕事に役立てるため" 
cap label var var157 "目的　その他" 
cap label var var158 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var159 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var160 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var161 "方法　講演会など" 
cap label var var162 "方法　通信教育" 
cap label var var163 "方法　テレビ・ラジオ" 
cap label var var164 "方法　職場での時間外" 
cap label var var165 "方法　各種学校・専修学校" 
cap label var var166 "方法　職業能力開発校など" 
cap label var var167 "方法　その他" 
cap label var var168 "学習・研究(11)芸術・文化　実施の有無" 
cap label var var169 "頻度" 
cap label var var170 "頻度階級中央値" 
cap label var var171 "目的　自分の教養を高めるため" 
cap label var var172 "目的　仕事につくため" 
cap label var var173 "目的　現在の仕事に役立てるため" 
cap label var var174 "目的　その他" 
cap label var var175 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var var176 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var var177 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var var178 "方法　講演会など" 
cap label var var179 "方法　通信教育" 
cap label var var180 "方法　テレビ・ラジオ" 
cap label var var181 "方法　職場での時間外" 
cap label var var182 "方法　各種学校・専修学校" 
cap label var var183 "方法　職業能力開発校など" 
cap label var var184 "方法　その他" 
cap label var var185 "学習・研究(12)その他　実施の有無" 
cap label var var186 "ブランク" 
cap label var var187 "ボランティア(1)総数　実施の有無" 
cap label var var188 "ブランク" 
cap label var var189 "団体に加入　ボランティアを目的としている団体" 
cap label var var190 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var191 "団体に加入　その他の団体" 
cap label var var192 "加入しない　家族と" 
cap label var var193 "加入しない　学校・職場の人と" 
cap label var var194 "加入しない　地域の人と" 
cap label var var195 "加入しない　友人・知人・その他の人と" 
cap label var var196 "加入しない　一人で" 
cap label var var197 "ボランティア(2)健康や医療サービス…　実施の有無" 
cap label var var198 "頻度" 
cap label var var199 "頻度階級中央値" 
cap label var var200 "団体に加入　ボランティアを目的としている団体" 
cap label var var201 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var202 "団体に加入　その他の団体" 
cap label var var203 "加入しない　家族と" 
cap label var var204 "加入しない　学校・職場の人と" 
cap label var var205 "加入しない　地域の人と" 
cap label var var206 "加入しない　友人・知人・その他の人と" 
cap label var var207 "加入しない　一人で" 
cap label var var208 "ボランティア(3)高齢者を対象…　実施の有無" 
cap label var var209 "頻度" 
cap label var var210 "頻度階級中央値" 
cap label var var211 "団体に加入　ボランティアを目的としている団体" 
cap label var var212 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var213 "団体に加入　その他の団体" 
cap label var var214 "加入しない　家族と" 
cap label var var215 "加入しない　学校・職場の人と" 
cap label var var216 "加入しない　地域の人と" 
cap label var var217 "加入しない　友人・知人・その他の人と" 
cap label var var218 "加入しない　一人で" 
cap label var var219 "ボランティア(4)障害者を対象…　実施の有無" 
cap label var var220 "頻度" 
cap label var var221 "頻度階級中央値" 
cap label var var222 "団体に加入　ボランティアを目的としている団体" 
cap label var var223 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var224 "団体に加入　その他の団体" 
cap label var var225 "加入しない　家族と" 
cap label var var226 "加入しない　学校・職場の人と" 
cap label var var227 "加入しない　地域の人と" 
cap label var var228 "加入しない　友人・知人・その他の人と" 
cap label var var229 "加入しない　一人で" 
cap label var var230 "ボランティア(5)子供を対象…　実施の有無" 
cap label var var231 "頻度" 
cap label var var232 "頻度階級中央値" 
cap label var var233 "団体に加入　ボランティアを目的としている団体" 
cap label var var234 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var235 "団体に加入　その他の団体" 
cap label var var236 "加入しない　家族と" 
cap label var var237 "加入しない　学校・職場の人と" 
cap label var var238 "加入しない　地域の人と" 
cap label var var239 "加入しない　友人・知人・その他の人と" 
cap label var var240 "加入しない　一人で" 
cap label var var241 "ボランティア(6)スポーツ・文化…　実施の有無" 
cap label var var242 "頻度" 
cap label var var243 "頻度階級中央値" 
cap label var var244 "団体に加入　ボランティアを目的としている団体" 
cap label var var245 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var246 "団体に加入　その他の団体" 
cap label var var247 "加入しない　家族と" 
cap label var var248 "加入しない　学校・職場の人と" 
cap label var var249 "加入しない　地域の人と" 
cap label var var250 "加入しない　友人・知人・その他の人と" 
cap label var var251 "加入しない　一人で" 
cap label var var252 "ボランティア(7)まちづくり…　実施の有無" 
cap label var var253 "頻度" 
cap label var var254 "頻度階級中央値" 
cap label var var255 "団体に加入　ボランティアを目的としている団体" 
cap label var var256 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var257 "団体に加入　その他の団体" 
cap label var var258 "加入しない　家族と" 
cap label var var259 "加入しない　学校・職場の人と" 
cap label var var260 "加入しない　地域の人と" 
cap label var var261 "加入しない　友人・知人・その他の人と" 
cap label var var262 "加入しない　一人で" 
cap label var var263 "ボランティア(8)安全な生活…　実施の有無" 
cap label var var264 "頻度" 
cap label var var265 "頻度階級中央値" 
cap label var var266 "団体に加入　ボランティアを目的としている団体" 
cap label var var267 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var268 "団体に加入　その他の団体" 
cap label var var269 "加入しない　家族と" 
cap label var var270 "加入しない　学校・職場の人と" 
cap label var var271 "加入しない　地域の人と" 
cap label var var272 "加入しない　友人・知人・その他の人と" 
cap label var var273 "加入しない　一人で" 
cap label var var274 "ボランティア(9)自然や環境…　実施の有無" 
cap label var var275 "頻度" 
cap label var var276 "頻度階級中央値" 
cap label var var277 "団体に加入　ボランティアを目的としている団体" 
cap label var var278 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var279 "団体に加入　その他の団体" 
cap label var var280 "加入しない　家族と" 
cap label var var281 "加入しない　学校・職場の人と" 
cap label var var282 "加入しない　地域の人と" 
cap label var var283 "加入しない　友人・知人・その他の人と" 
cap label var var284 "加入しない　一人で" 
cap label var var285 "ボランティア(10)災害…　実施の有無" 
cap label var var286 "頻度" 
cap label var var287 "頻度階級中央値" 
cap label var var288 "団体に加入　ボランティアを目的としている団体" 
cap label var var289 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var290 "団体に加入　その他の団体" 
cap label var var291 "加入しない　家族と" 
cap label var var292 "加入しない　学校・職場の人と" 
cap label var var293 "加入しない　地域の人と" 
cap label var var294 "加入しない　友人・知人・その他の人と" 
cap label var var295 "加入しない　一人で" 
cap label var var296 "ボランティア(11)国際協力　実施の有無" 
cap label var var297 "頻度" 
cap label var var298 "頻度階級中央値" 
cap label var var299 "団体に加入　ボランティアを目的としている団体" 
cap label var var300 "団体に加入　町内会・青年団・老人クラブなど" 
cap label var var301 "団体に加入　その他の団体" 
cap label var var302 "加入しない　家族と" 
cap label var var303 "加入しない　学校・職場の人と" 
cap label var var304 "加入しない　地域の人と" 
cap label var var305 "加入しない　友人・知人・その他の人と" 
cap label var var306 "加入しない　一人で" 
cap label var var307 "ボランティア(12)その他　実施の有無" 
cap label var var308 "ブランク" 
cap label var var309 "スポーツ(1)総数　実施の有無" 
cap label var var310 "ブランク" 
cap label var var311 "スポーツ(2)野球　実施の有無" 
cap label var var312 "頻度" 
cap label var var313 "頻度階級中央値" 
cap label var var314 "親の行動の有無" 
cap label var var315 "スポーツ(3)ソフトボール　実施の有無" 
cap label var var316 "頻度" 
cap label var var317 "頻度階級中央値" 
cap label var var318 "親の行動の有無" 
cap label var var319 "スポーツ(4)バレーボール　実施の有無" 
cap label var var320 "頻度" 
cap label var var321 "頻度階級中央値" 
cap label var var322 "親の行動の有無" 
cap label var var323 "スポーツ(5)バスケットボール　実施の有無" 
cap label var var324 "頻度" 
cap label var var325 "頻度階級中央値" 
cap label var var326 "親の行動の有無" 
cap label var var327 "スポーツ(6)サッカー　実施の有無" 
cap label var var328 "頻度" 
cap label var var329 "頻度階級中央値" 
cap label var var330 "親の行動の有無" 
cap label var var331 "スポーツ(7)卓球　実施の有無" 
cap label var var332 "頻度" 
cap label var var333 "頻度階級中央値" 
cap label var var334 "親の行動の有無" 
cap label var var335 "スポーツ(8)テニス　実施の有無" 
cap label var var336 "頻度" 
cap label var var337 "頻度階級中央値" 
cap label var var338 "親の行動の有無" 
cap label var var339 "スポーツ(9)バドミントン　実施の有無" 
cap label var var340 "頻度" 
cap label var var341 "頻度階級中央値" 
cap label var var342 "親の行動の有無" 
cap label var var343 "スポーツ(10)ゴルフ　実施の有無" 
cap label var var344 "頻度" 
cap label var var345 "頻度階級中央値" 
cap label var var346 "親の行動の有無" 
cap label var var347 "スポーツ(11)柔道　実施の有無" 
cap label var var348 "頻度" 
cap label var var349 "頻度階級中央値" 
cap label var var350 "親の行動の有無" 
cap label var var351 "スポーツ(12)剣道　実施の有無" 
cap label var var352 "頻度" 
cap label var var353 "頻度階級中央値" 
cap label var var354 "親の行動の有無" 
cap label var var355 "スポーツ(13)ゲートボール　実施の有無" 
cap label var var356 "頻度" 
cap label var var357 "頻度階級中央値" 
cap label var var358 "親の行動の有無" 
cap label var var359 "スポーツ(14)ボウリング　実施の有無" 
cap label var var360 "頻度" 
cap label var var361 "頻度階級中央値" 
cap label var var362 "親の行動の有無" 
cap label var var363 "スポーツ(15)つり　実施の有無" 
cap label var var364 "頻度" 
cap label var var365 "頻度階級中央値" 
cap label var var366 "親の行動の有無" 
cap label var var367 "スポーツ(16)水泳　実施の有無" 
cap label var var368 "頻度" 
cap label var var369 "頻度階級中央値" 
cap label var var370 "親の行動の有無" 
cap label var var371 "スポーツ(17)スキー・スノーボード　実施の有無" 
cap label var var372 "頻度" 
cap label var var373 "頻度階級中央値" 
cap label var var374 "親の行動の有無" 
cap label var var375 "スポーツ(18)登山・ハイキング　実施の有無" 
cap label var var376 "頻度" 
cap label var var377 "頻度階級中央値" 
cap label var var378 "親の行動の有無" 
cap label var var379 "スポーツ(19)サイクリング　実施の有無" 
cap label var var380 "頻度" 
cap label var var381 "頻度階級中央値" 
cap label var var382 "親の行動の有無" 
cap label var var383 "スポーツ(20)ジョギング・マラソン　実施の有無" 
cap label var var384 "頻度" 
cap label var var385 "頻度階級中央値" 
cap label var var386 "親の行動の有無" 
cap label var var387 "スポーツ(21)ウォーキング・軽い体操　実施の有無" 
cap label var var388 "頻度" 
cap label var var389 "頻度階級中央値" 
cap label var var390 "親の行動の有無" 
cap label var var391 "スポーツ(22)器具を使ったトレーニング　実施の有無" 
cap label var var392 "頻度" 
cap label var var393 "頻度階級中央値" 
cap label var var394 "親の行動の有無" 
cap label var var395 "スポーツ(23)その他　実施の有無" 
cap label var var396 "ブランク" 
cap label var var397 "親の行動の有無" 
cap label var var398 "趣味・娯楽(1)総数　実施の有無" 
cap label var var399 "ブランク" 
cap label var var400 "趣味・娯楽(2)スポーツ観覧　実施の有無" 
cap label var var401 "頻度" 
cap label var var402 "頻度階級中央値" 
cap label var var403 "親の行動の有無" 
cap label var var404 "趣味・娯楽(3)美術鑑賞　実施の有無" 
cap label var var405 "頻度" 
cap label var var406 "頻度階級中央値" 
cap label var var407 "親の行動の有無" 
cap label var var408 "趣味・娯楽(4)演芸・演劇・舞踊鑑賞　実施の有無" 
cap label var var409 "頻度" 
cap label var var410 "頻度階級中央値" 
cap label var var411 "親の行動の有無" 
cap label var var412 "趣味・娯楽(5)映画鑑賞　実施の有無" 
cap label var var413 "頻度" 
cap label var var414 "頻度階級中央値" 
cap label var var415 "親の行動の有無" 
cap label var var416 "趣味・娯楽(6)音楽会などによるクラシック音楽鑑賞　実施の有無" 
cap label var var417 "頻度" 
cap label var var418 "頻度階級中央値" 
cap label var var419 "親の行動の有無" 
cap label var var420 "趣味・娯楽(7)音楽会などによるポピュラー音楽…　実施の有無" 
cap label var var421 "頻度" 
cap label var var422 "頻度階級中央値" 
cap label var var423 "親の行動の有無" 
cap label var var424 "趣味・娯楽(8)ＣＤ・テープ…　実施の有無" 
cap label var var425 "頻度" 
cap label var var426 "頻度階級中央値" 
cap label var var427 "親の行動の有無" 
cap label var var428 "趣味・娯楽(9)ＤＶＤ・ビデオ…　実施の有無" 
cap label var var429 "頻度" 
cap label var var430 "頻度階級中央値" 
cap label var var431 "親の行動の有無" 
cap label var var432 "趣味・娯楽(10)楽器の演奏　実施の有無" 
cap label var var433 "頻度" 
cap label var var434 "頻度階級中央値" 
cap label var var435 "親の行動の有無" 
cap label var var436 "趣味・娯楽(11)邦楽　実施の有無" 
cap label var var437 "頻度" 
cap label var var438 "頻度階級中央値" 
cap label var var439 "親の行動の有無" 
cap label var var440 "趣味・娯楽(12)コーラス・声楽　実施の有無" 
cap label var var441 "頻度" 
cap label var var442 "頻度階級中央値" 
cap label var var443 "親の行動の有無" 
cap label var var444 "趣味・娯楽(13)邦舞・おどり　実施の有無" 
cap label var var445 "頻度" 
cap label var var446 "頻度階級中央値" 
cap label var var447 "親の行動の有無" 
cap label var var448 "趣味・娯楽(14)洋舞・社交ダンス　実施の有無" 
cap label var var449 "頻度" 
cap label var var450 "頻度階級中央値" 
cap label var var451 "親の行動の有無" 
cap label var var452 "趣味・娯楽(15)書道　実施の有無" 
cap label var var453 "頻度" 
cap label var var454 "頻度階級中央値" 
cap label var var455 "親の行動の有無" 
cap label var var456 "趣味・娯楽(16)華道　実施の有無" 
cap label var var457 "頻度" 
cap label var var458 "頻度階級中央値" 
cap label var var459 "親の行動の有無" 
cap label var var460 "趣味・娯楽(17)茶道　実施の有無" 
cap label var var461 "頻度" 
cap label var var462 "頻度階級中央値" 
cap label var var463 "親の行動の有無" 
cap label var var464 "趣味・娯楽(18)和裁・洋裁　実施の有無" 
cap label var var465 "頻度" 
cap label var var466 "頻度階級中央値" 
cap label var var467 "親の行動の有無" 
cap label var var468 "趣味・娯楽(19)編み物・手芸　実施の有無" 
cap label var var469 "頻度" 
cap label var var470 "頻度階級中央値" 
cap label var var471 "親の行動の有無" 
cap label var var472 "趣味・娯楽(20)趣味としての料理…　実施の有無" 
cap label var var473 "頻度" 
cap label var var474 "頻度階級中央値" 
cap label var var475 "親の行動の有無" 
cap label var var476 "趣味・娯楽(21)園芸・庭いじり…　実施の有無" 
cap label var var477 "頻度" 
cap label var var478 "頻度階級中央値" 
cap label var var479 "親の行動の有無" 
cap label var var480 "趣味・娯楽(22)日曜大工　実施の有無" 
cap label var var481 "頻度" 
cap label var var482 "頻度階級中央値" 
cap label var var483 "親の行動の有無" 
cap label var var484 "趣味・娯楽(23)絵画・彫刻の制作　実施の有無" 
cap label var var485 "頻度" 
cap label var var486 "頻度階級中央値" 
cap label var var487 "親の行動の有無" 
cap label var var488 "趣味・娯楽(24)陶芸・工芸　実施の有無" 
cap label var var489 "頻度" 
cap label var var490 "頻度階級中央値" 
cap label var var491 "親の行動の有無" 
cap label var var492 "趣味・娯楽(25)写真の撮影・プリント　実施の有無" 
cap label var var493 "頻度" 
cap label var var494 "頻度階級中央値" 
cap label var var495 "親の行動の有無" 
cap label var var496 "趣味・娯楽(26)詩・和歌…　実施の有無" 
cap label var var497 "頻度" 
cap label var var498 "頻度階級中央値" 
cap label var var499 "親の行動の有無" 
cap label var var500 "趣味・娯楽(27)趣味としての読書　実施の有無" 
cap label var var501 "頻度" 
cap label var var502 "頻度階級中央値" 
cap label var var503 "親の行動の有無" 
cap label var var504 "趣味・娯楽(28)囲碁　実施の有無" 
cap label var var505 "頻度" 
cap label var var506 "頻度階級中央値" 
cap label var var507 "親の行動の有無" 
cap label var var508 "趣味・娯楽(29)将棋　実施の有無" 
cap label var var509 "頻度" 
cap label var var510 "頻度階級中央値" 
cap label var var511 "親の行動の有無" 
cap label var var512 "趣味・娯楽(30)パチンコ　実施の有無" 
cap label var var513 "頻度" 
cap label var var514 "頻度階級中央値" 
cap label var var515 "親の行動の有無" 
cap label var var516 "趣味・娯楽(31)カラオケ　実施の有無" 
cap label var var517 "頻度" 
cap label var var518 "頻度階級中央値" 
cap label var var519 "親の行動の有無" 
cap label var var520 "趣味・娯楽(32)テレビゲーム…　実施の有無" 
cap label var var521 "頻度" 
cap label var var522 "頻度階級中央値" 
cap label var var523 "親の行動の有無" 
cap label var var524 "趣味・娯楽(33)遊園地，動植物園…　実施の有無" 
cap label var var525 "頻度" 
cap label var var526 "頻度階級中央値" 
cap label var var527 "親の行動の有無" 
cap label var var528 "趣味・娯楽(34)キャンプ　実施の有無" 
cap label var var529 "頻度" 
cap label var var530 "頻度階級中央値" 
cap label var var531 "親の行動の有無" 
cap label var var532 "趣味・娯楽(35)その他　実施の有無" 
cap label var var533 "ブランク" 
cap label var var534 "親の行動の有無" 
cap label var var535 "旅行・行楽(1)総数　実施の有無" 
cap label var var536 "ブランク" 
cap label var var537 "頻度" 
cap label var var538 "共にした人　家族と" 
cap label var var539 "共にした人　学校・職場の人と" 
cap label var var540 "共にした人　地域の人と" 
cap label var var541 "共にした人　友人・知人・その他の人と" 
cap label var var542 "共にした人　一人で" 
cap label var var543 "旅行・行楽(2)行楽（日帰り）　実施の有無" 
cap label var var544 "頻度（最終チェック済データ）" 
cap label var var545 "頻度" 
cap label var var546 "共にした人　家族と" 
cap label var var547 "共にした人　学校・職場の人と" 
cap label var var548 "共にした人　地域の人と" 
cap label var var549 "共にした人　友人・知人・その他の人と" 
cap label var var550 "共にした人　一人で" 
cap label var var551 "旅行・行楽(3)旅行（1泊2日以上）　実施の有無" 
cap label var var552 "ブランク" 
cap label var var553 "頻度" 
cap label var var554 "共にした人　家族と" 
cap label var var555 "共にした人　学校・職場の人と" 
cap label var var556 "共にした人　地域の人と" 
cap label var var557 "共にした人　友人・知人・その他の人と" 
cap label var var558 "共にした人　一人で" 
cap label var var559 "旅行・行楽(4)国内　実施の有無" 
cap label var var560 "ブランク" 
cap label var var561 "頻度" 
cap label var var562 "共にした人　家族と" 
cap label var var563 "共にした人　学校・職場の人と" 
cap label var var564 "共にした人　地域の人と" 
cap label var var565 "共にした人　友人・知人・その他の人と" 
cap label var var566 "共にした人　一人で" 
cap label var var567 "旅行・行楽(5)国内　観光旅行　実施の有無" 
cap label var var568 "頻度（最終チェック済データ）" 
cap label var var569 "頻度" 
cap label var var570 "共にした人　家族と" 
cap label var var571 "共にした人　学校・職場の人と" 
cap label var var572 "共にした人　地域の人と" 
cap label var var573 "共にした人　友人・知人・その他の人と" 
cap label var var574 "共にした人　一人で" 
cap label var var575 "旅行・行楽(6)国内　帰省・訪問などの旅行　実施の有無" 
cap label var var576 "頻度（最終チェック済データ）" 
cap label var var577 "頻度" 
cap label var var578 "共にした人　家族と" 
cap label var var579 "共にした人　学校・職場の人と" 
cap label var var580 "共にした人　地域の人と" 
cap label var var581 "共にした人　友人・知人・その他の人と" 
cap label var var582 "共にした人　一人で" 
cap label var var583 "旅行・行楽(7)国内　業務出張…　実施の有無" 
cap label var var584 "頻度（最終チェック済データ）" 
cap label var var585 "頻度" 
cap label var var586 "共にした人　家族と" 
cap label var var587 "共にした人　学校・職場の人と" 
cap label var var588 "共にした人　地域の人と" 
cap label var var589 "共にした人　友人・知人・その他の人と" 
cap label var var590 "共にした人　一人で" 
cap label var var591 "旅行・行楽(8)海外　実施の有無" 
cap label var var592 "ブランク" 
cap label var var593 "頻度" 
cap label var var594 "共にした人　家族と" 
cap label var var595 "共にした人　学校・職場の人と" 
cap label var var596 "共にした人　地域の人と" 
cap label var var597 "共にした人　友人・知人・その他の人と" 
cap label var var598 "共にした人　一人で" 
cap label var var599 "旅行・行楽(9)海外　観光旅行　実施の有無" 
cap label var var600 "頻度（最終チェック済データ）" 
cap label var var601 "頻度" 
cap label var var602 "共にした人　家族と" 
cap label var var603 "共にした人　学校・職場の人と" 
cap label var var604 "共にした人　地域の人と" 
cap label var var605 "共にした人　友人・知人・その他の人と" 
cap label var var606 "共にした人　一人で" 
cap label var var607 "旅行・行楽(10)海外　業務出張…　実施の有無" 
cap label var var608 "頻度（最終チェック済データ）" 
cap label var var609 "頻度" 
cap label var var610 "共にした人　家族と" 
cap label var var611 "共にした人　学校・職場の人と" 
cap label var var612 "共にした人　地域の人と" 
cap label var var613 "共にした人　友人・知人・その他の人と" 
cap label var var614 "共にした人　一人で" 
