/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/レイアウト/01_2 昭和60年抽出詳細集計.xls
    Date: 2019/04/14 14:46:11
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str CHONEN 3-6
        str CHOTUKI 7-8
        str KEN 11-12
        str CITY 13-15
        str RITSU 24-25
        str TOKEIKU 26-27
        str SHUBAN 31-34
        str KOUCHI 35-35
        str BUNKATU 36-37
        str BUNCTL 38-39
        str AZA 41-43
        str DTKBN 67-67
        str SETORG 72-74
        str ISKBN 75-75
        str FJKBN 76-76
        str JUNKBN 77-77
        str SETAI 78-78
        str TATE 79-79
        str KAISU 80-80
        str JYUKYO 81-81
        str HEYA 84-85
        str TATAMI 87-89
        str SETJIN 92-95
        str SETINORG 145-147
        str SEX 149-149
        str TUZUKI 150-151
        str GENGO 152-152
        str NEN 153-154
        str TUKI 155-155
        str NENREI 156-158
        str HAIGU 161-161
        str KOKUSEKI 162-162
        str GAIKOKU 163-163
        str RODO3 164-164
        str RODO8 165-165
        str JYUTU3 166-166
        str JYUTU6 167-167
        str JKEN 168-169
        str JCITY 170-172
        str CHII3 176-176
        str CHII6 177-177
        str SAND 179-180
        str SANC 181-182
        str SANS 186-188
        str SHOD 190-191
        str SHOC 192-193
        str SHOS 197-199
    using "data";
#delimit cr
