/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/14 14:46:11
-----------------------------------------------------------------------------*/


capture label define CHONEN 1985 "調査の年" 
capture label values CHONEN CHONEN

capture label define CHOTUKI 10 "調査の月" 
capture label values CHOTUKI CHOTUKI

capture label define RITSU 1 "準世帯、自衛隊、矯正" 2 "10,000人未満" 3 "10,000~29,999人" 4 "30,000~49,999人" 5 "50,000~99,999人" 6 "100,000~199,999人" 8 "200,000~299,999人" 10 "300,000人以上" 
capture label values RITSU RITSU

capture label define KOUCHI 1 "一般の調査区" 2 "山岳・森林・無人島" 3 "広大な工場・学校" 4 "社会施設・病院" 5 "刑務所・拘置所" 6 "自衛隊区域" 7 "駐留軍区域" 8 "50人以上の準世帯" 9 "水面調査区" 
capture label values KOUCHI KOUCHI

capture label define ISKBN 1 "一般の世帯,一人世帯" 2 "施設等の世帯" 
capture label values ISKBN ISKBN

capture label define FJKBN 1 "普通世帯" 2 "一人世帯の間借り・下宿等(一人世帯のその他含む)" 3 "一人世帯の会社等の独身寮" 4 "寮・寄宿舎" 5 "病院・療養所" 6 "社会施設" 7 "自衛隊営舎内居住世帯" 8 "矯正施設入居世帯" 9 "その他" 
capture label values FJKBN FJKBN

capture label define JUNKBN 1 "1人" 2 "2~29人" 3 "30~49人" 4 "50人以上" 
capture label values JUNKBN JUNKBN

capture label define SETAI 1 "一般の世帯" 2 "一人世帯" 3 "寮・寄宿舎" 4 "病院・療養所" 5 "社会施設" 6 "その他" 7 "自衛隊営舎内居住者" 8 "矯正施設入居者" 
capture label values SETAI SETAI

capture label define TATE 1 "一戸建" 2 "長屋建" 3 "共同住宅" 4 "その他" 
capture label values TATE TATE

capture label define KAISU 1 "1・2階" 2 "3~5階" 3 "6~10階" 4 "11階以上" 
capture label values KAISU KAISU

capture label define JYUKYO 1 "持ち家" 2 "公営借家" 3 "公団・公社借家" 4 "民営借家" 5 "給与住宅" 6 "間借り" 7 "会社等の独身寮・寄宿舎" 8 "その他" 
capture label values JYUKYO JYUKYO

capture label define HEYA 1 "1室" 2 "2室" 3 "3室" 4 "4室" 5 "5室" 6 "6室" 7 "7室" 8 "8室" 9 "9室" 10 "10室以上" 
capture label values HEYA HEYA

capture label define SEX 1 "男" 2 "女" 
capture label values SEX SEX

capture label define TUZUKI 1 "世帯主又は代表者" 2 "世帯主の配偶者" 3 "子" 4 "子の配偶者" 5 "孫" 6 "父母" 7 "祖父母" 8 "兄弟姉妹" 9 "他の親族" 10 "住み込みの雇人(家事)" 11 "住み込みの雇人(営業)" 12 "その他" 
capture label values TUZUKI TUZUKI

capture label define GENGO 1 "明治" 2 "大正" 3 "昭和" 
capture label values GENGO GENGO

capture label define TUKI 1 "1~3月" 2 "4~6月" 3 "7~9月" 4 "10~12月" 
capture label values TUKI TUKI

capture label define HAIGU 1 "未婚" 2 "有配偶" 3 "死別" 4 "離別" 
capture label values HAIGU HAIGU

capture label define KOKUSEKI 1 "日本" 2 "外国" 
capture label values KOKUSEKI KOKUSEKI

capture label define GAIKOKU 1 "韓国・朝鮮" 2 "中国" 3 "アメリカ" 4 "その他" 
capture label values GAIKOKU GAIKOKU

capture label define RODO3 1 "就業者" 2 "完全失業者" 3 "非労働力人口" 
capture label values RODO3 RODO3

capture label define RODO8 1 "主に仕事" 2 "家事などのほかに仕事" 3 "通学のかたわら仕事" 4 "仕事を休んでいた(休業者)" 5 "仕事を探していた(完全失業者)" 6 "家事" 7 "通学" 8 "その他" 
capture label values RODO8 RODO8

capture label define JYUTU3 1 "自宅又は住み込み" 2 "同じ市区町村" 3 "他の市区町村" 
capture label values JYUTU3 JYUTU3

capture label define JYUTU6 1 "従業も通学もしていない" 2 "自宅で従業" 3 "自宅外の自市区町村" 4 "自市内他区" 5 "県内他市町村" 6 "他県" 
capture label values JYUTU6 JYUTU6

capture label define CHII3 1 "雇用者" 2 "自営業主" 3 "家族従業者" 
capture label values CHII3 CHII3

capture label define CHII6 1 "雇用者" 2 "会社などの役員" 3 "雇人のある業主" 4 "雇人のない業主" 5 "家族従業者" 6 "家庭内の賃仕事" 
capture label values CHII6 CHII6

capture label define SAND 1 "農業" 2 "林業" 3 "漁業" 4 "鉱業" 5 "建設業" 6 "製造業" 7 "電気・ガス・熱供給・水道業" 8 "運輸・通信業" 9 "卸売・小売業,飲食店" 10 "金融・保険業" 11 "不動産業" 12 "サービス業" 13 "公務(他に分類されないもの)" 14 "分類不能の産業" 
capture label values SAND SAND

capture label define SANC 1 "農業" 2 "林業" 3 "漁業" 4 "水産養殖業" 5 "鉱業" 6 "建設業" 7 "食料品製造業" 8 "飲料・飼料・たばこ製造業" 9 "繊維工業(衣服,その他の繊維製品を除く)" 10 "衣服・その他の繊維製品製造業" 11 "木材・木製品製造業(家具を除く)" 12 "家具・装備品製造業" 13 "パルプ・紙・紙加工品製造業" 14 "出版・印刷・同関連産業" 15 "化学工業" 16 "石油製品・石炭製品製造業" 17 "プラスチック製品製造業(別掲を除く)" 18 "ゴム製品製造業" 19 "なめし革・同製品・毛皮製造業" 20 "窯業・土石製品製造業" 21 "鉄鋼業" 22 "非鉄金属製造業" 23 "金属製品製造業" 24 "一般機械器具製造業" 25 "電気機械器具製造業" 26 "輸送用機械器具製造業" 27 "精密機械器具製造業" 28 "その他の製造業" 29 "電気・ガス・熱供給・水道業" 30 "鉄道業" 31 "道路旅客運送業" 32 "道路貨物運送業" 33 "水運業" 34 "航空運輸業" 35 "倉庫業" 36 "運輸に附帯するサービス業" 37 "通信業" 38 "卸売業" 39 "百貨店" 40 "織物・衣服・身の回り品小売業" 41 "飲食料品小売業" 42 "自動車・自転車小売業" 43 "家具・建具・じゅう器小売業" 44 "その他の小売業" 45 "一般飲食店" 46 "その他の飲食店" 47 "金融・保険業" 48 "不動産業" 49 "物品賃貸業" 50 "旅館,その他の宿泊所" 51 "家事サービス業" 52 "洗濯・理容・浴場業" 53 "その他の個人サービス業" 54 "映画・娯楽業" 55 "放送業" 56 "駐車場業" 57 "自動車整備業" 58 "その他の修理業" 59 "協同組合(他に分類されないもの)" 60 "情報サービス・調査・広告業" 61 "その他の事業サービス業" 62 "専門サービス業(他に分類されないもの)" 63 "医療業" 64 "保健衛生" 65 "廃棄物処理業" 66 "宗教" 67 "教育" 68 "社会保険,社会福祉" 69 "学術研究機関" 70 "政治・経済・文化団体" 71 "その他のサービス業" 72 "外国公務" 73 "国家公務" 74 "地方公務" 75 "分類不能の産業" 
capture label values SANC SANC

capture label define SHOD 1 "専門的・技術的職業従事者" 2 "管理的職業従事者" 3 "事務従事者" 4 "販売従事者" 5 "農林漁業作業者" 6 "採掘作業者" 7 "運輸・通信従事者" 8 "技能工・生産工程作業者及び労務作業者" 9 "保安職業従事者" 10 "サービス職業従事者" 11 "分類不能の職業" 
capture label values SHOD SHOD

capture label define SHOC 1 "科学研究者" 2 "技術者" 3 "保健医療従事者" 4 "法務従事者" 5 "公認会計士,税理士" 6 "教員" 7 "宗教家" 8 "文芸家,記者,編集者" 9 "美術家,写真家,デザイナー" 
capture label values SHOC SHOC

