/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx
    Date: 2019/03/03 16:49:29
----------------------------------------------------------------------*/


capture label variable var1 "調査情報: 調査IDT"
capture label variable var2 "調査情報: 調査年"
capture label variable var3 "調査情報: 調査月"
capture label variable var4 "調査票区分"
capture label variable var5 "乗率"
capture label variable var6 "共通項目: 都道府県番号"
capture label variable var7 "共通項目: 事業所番号"
capture label variable var8 "共通項目: 産業中分類"
capture label variable var9 "共通項目: 抽出番号"
capture label variable var10 "共通項目: 事業所規模"
capture label variable var11 "共通項目: 企業規模"
capture label variable var12 "異動状況1常用名義男(2)増加常用労働者: イ入職者"
capture label variable var13 "異動状況1常用名義男(2)増加常用労働者: ロ転入者等"
capture label variable var14 "異動状況1常用名義男: (3)常用に切り替えられた者"
capture label variable var15 "異動状況1常用名義男(4)減少常用労働者: イ離職者"
capture label variable var16 "異動状況1常用名義男(4)減少常用労働者: ロ転出者等"
capture label variable var17 "異動状況1常用名義男: (5)期末常用労働者"
capture label variable var18 "異動状況2臨時・日雇い名義男(2)増加常用労働者: イ入職者"
capture label variable var19 "異動状況2臨時・日雇い名義男(2)増加常用労働者: ロ転入者等"
capture label variable var20 "異動状況2臨時・日雇い名義男: (3)常用に切り替えられた者"
capture label variable var21 "異動状況2臨時・日雇い名義男(4)減少常用労働者: イ離職者"
capture label variable var22 "異動状況2臨時・日雇い名義男(4)減少常用労働者: ロ転出者等"
capture label variable var23 "異動状況2臨時・日雇い名義男: (5)期末常用労働者"
capture label variable var24 "異動状況3常用名義女(2)増加常用労働者: イ入職者"
capture label variable var25 "異動状況3常用名義女(2)増加常用労働者: ロ転入者等"
capture label variable var26 "異動状況3常用名義女: (3)常用に切り替えられた者"
capture label variable var27 "異動状況3常用名義女(4)減少常用労働者: イ離職者"
capture label variable var28 "異動状況3常用名義女(4)減少常用労働者: ロ転出者等"
capture label variable var29 "異動状況3常用名義女: (5)期末常用労働者"
capture label variable var30 "異動状況4臨時・日雇い名義女(2)増加常用労働者: イ入職者"
capture label variable var31 "異動状況4臨時・日雇い名義女(2)増加常用労働者: ロ転入者等"
capture label variable var32 "異動状況4臨時・日雇い名義女: (3)常用に切り替えられた者"
capture label variable var33 "異動状況4臨時・日雇い名義女(4)減少常用労働者: イ離職者"
capture label variable var34 "異動状況4臨時・日雇い名義女(4)減少常用労働者: ロ転出者等"
capture label variable var35 "異動状況4臨時・日雇い名義女: (5)期末常用労働者"
capture label variable var36 "異動状況5合計(2)増加常用労働者: イ入職者"
capture label variable var37 "異動状況5合計(2)増加常用労働者: ロ転入者等"
capture label variable var38 "異動状況5合計(4)減少常用労働者: イ離職者"
capture label variable var39 "異動状況5合計(4)減少常用労働者: ロ転出者等"
capture label variable var40 "異動状況5合計: (5)期末常用労働者"
capture label variable var41 "異動状況6うちパートタイム男(2)増加常用労働者: イ入職者"
capture label variable var42 "異動状況6うちパートタイム男(2)増加常用労働者: ロ転入者等"
capture label variable var43 "異動状況6うちパートタイム男(4)減少常用労働者: イ離職者"
capture label variable var44 "異動状況6うちパートタイム男(4)減少常用労働者: ロ転出者等"
capture label variable var45 "異動状況6うちパートタイム男: (5)期末常用労働者"
capture label variable var46 "異動状況7うちパートタイム女(2)増加常用労働者: イ入職者"
capture label variable var47 "異動状況7うちパートタイム女(2)増加常用労働者: ロ転入者等"
capture label variable var48 "異動状況7うちパートタイム女(4)減少常用労働者: イ離職者"
capture label variable var49 "異動状況7うちパートタイム女(4)減少常用労働者: ロ転出者等"
capture label variable var50 "異動状況7うちパートタイム女: (5)期末常用労働者"
capture label variable var51 "異動状況8うち出向者: (2)増加常用労働者イ入職者"
capture label variable var52 "異動状況8うち出向者: (4)減少常用労働者イ離職者"
capture label variable var53 "異動状況8うち出向者: (5)期末常用労働者"
capture label variable var54 "性・年齢階級別常用労働者数9常用労働者男1: 19歳以下"
capture label variable var55 "性・年齢階級別常用労働者数9常用労働者男2: 20~24歳"
capture label variable var56 "性・年齢階級別常用労働者数9常用労働者男3: 25~29歳"
capture label variable var57 "性・年齢階級別常用労働者数9常用労働者男4: 30~34歳"
capture label variable var58 "性・年齢階級別常用労働者数9常用労働者男5: 35~39歳"
capture label variable var59 "性・年齢階級別常用労働者数9常用労働者男6: 40~44歳"
capture label variable var60 "性・年齢階級別常用労働者数9常用労働者男7: 45~49歳"
capture label variable var61 "性・年齢階級別常用労働者数9常用労働者男8: 50~54歳"
capture label variable var62 "性・年齢階級別常用労働者数9常用労働者男9: 55~59歳"
capture label variable var63 "性・年齢階級別常用労働者数9常用労働者男10: 60~64歳"
capture label variable var64 "性・年齢階級別常用労働者数9常用労働者男11: 65歳以上"
capture label variable var65 "性・年齢階級別常用労働者数10うちパートタイム男1: 19歳以下"
capture label variable var66 "性・年齢階級別常用労働者数10うちパートタイム男2: 20~24歳"
capture label variable var67 "性・年齢階級別常用労働者数10うちパートタイム男3: 25~29歳"
capture label variable var68 "性・年齢階級別常用労働者数10うちパートタイム男4: 30~34歳"
capture label variable var69 "性・年齢階級別常用労働者数10うちパートタイム男5: 35~39歳"
capture label variable var70 "性・年齢階級別常用労働者数10うちパートタイム男6: 40~44歳"
capture label variable var71 "性・年齢階級別常用労働者数10うちパートタイム男7: 45~49歳"
capture label variable var72 "性・年齢階級別常用労働者数10うちパートタイム男8: 50~54歳"
capture label variable var73 "性・年齢階級別常用労働者数10うちパートタイム男9: 55~59歳"
capture label variable var74 "性・年齢階級別常用労働者数10うちパートタイム男10: 60~64歳"
capture label variable var75 "性・年齢階級別常用労働者数10うちパートタイム男11: 65歳以上"
capture label variable var76 "性・年齢階級別常用労働者数11常用労働者女1: 19歳以下"
capture label variable var77 "性・年齢階級別常用労働者数11常用労働者女2: 20~24歳"
capture label variable var78 "性・年齢階級別常用労働者数11常用労働者女3: 25~29歳"
capture label variable var79 "性・年齢階級別常用労働者数11常用労働者女4: 30~34歳"
capture label variable var80 "性・年齢階級別常用労働者数11常用労働者女5: 35~39歳"
capture label variable var81 "性・年齢階級別常用労働者数11常用労働者女6: 40~44歳"
capture label variable var82 "性・年齢階級別常用労働者数11常用労働者女7: 45~49歳"
capture label variable var83 "性・年齢階級別常用労働者数11常用労働者女8: 50~54歳"
capture label variable var84 "性・年齢階級別常用労働者数11常用労働者女9: 55~59歳"
capture label variable var85 "性・年齢階級別常用労働者数11常用労働者女10: 60~64歳"
capture label variable var86 "性・年齢階級別常用労働者数11常用労働者女11: 65歳以上"
capture label variable var87 "性・年齢階級別常用労働者数12うちパートタイム女1: 19歳以下"
capture label variable var88 "性・年齢階級別常用労働者数12うちパートタイム女2: 20~24歳"
capture label variable var89 "性・年齢階級別常用労働者数12うちパートタイム女3: 25~29歳"
capture label variable var90 "性・年齢階級別常用労働者数12うちパートタイム女4: 30~34歳"
capture label variable var91 "性・年齢階級別常用労働者数12うちパートタイム女5: 35~39歳"
capture label variable var92 "性・年齢階級別常用労働者数12うちパートタイム女6: 40~44歳"
capture label variable var93 "性・年齢階級別常用労働者数12うちパートタイム女7: 45~49歳"
capture label variable var94 "性・年齢階級別常用労働者数12うちパートタイム女8: 50~54歳"
capture label variable var95 "性・年齢階級別常用労働者数12うちパートタイム女9: 55~59歳"
capture label variable var96 "性・年齢階級別常用労働者数12うちパートタイム女10: 60~64歳"
capture label variable var97 "性・年齢階級別常用労働者数12うちパートタイム女11: 65歳以上"
capture label variable var98 "職業別常用労働者数13常用労働者1: 専門・技術"
capture label variable var99 "職業別常用労働者数13常用労働者2: 管理"
capture label variable var100 "職業別常用労働者数13常用労働者3: 事務"
capture label variable var101 "職業別常用労働者数13常用労働者4: 販売"
capture label variable var102 "職業別常用労働者数13常用労働者5: サービス"
capture label variable var103 "職業別常用労働者数13常用労働者6: 保安"
capture label variable var104 "職業別常用労働者数13常用労働者7: 運輸・通信"
capture label variable var105 "職業別常用労働者数13常用労働者8: 生産・労務"
capture label variable var106 "職業別常用労働者数13常用労働者9: その他"
capture label variable var107 "職業別常用労働者数14うちパート1: 専門・技術"
capture label variable var108 "職業別常用労働者数14うちパート2: 管理"
capture label variable var109 "職業別常用労働者数14うちパート3: 事務"
capture label variable var110 "職業別常用労働者数14うちパート4: 販売"
capture label variable var111 "職業別常用労働者数14うちパート5: サービス"
capture label variable var112 "職業別常用労働者数14うちパート6: 保安"
capture label variable var113 "職業別常用労働者数14うちパート7: 運輸・通信"
capture label variable var114 "職業別常用労働者数14うちパート8: 生産・労務"
capture label variable var115 "職業別常用労働者数14うちパート9: その他"
capture label variable var116 "職業別常用労働者数15未充足求人数1: 専門・技術"
capture label variable var117 "職業別常用労働者数15未充足求人数2: 管理"
capture label variable var118 "職業別常用労働者数15未充足求人数3: 事務"
capture label variable var119 "職業別常用労働者数15未充足求人数4: 販売"
capture label variable var120 "職業別常用労働者数15未充足求人数5: サービス"
capture label variable var121 "職業別常用労働者数15未充足求人数6: 保安"
capture label variable var122 "職業別常用労働者数15未充足求人数7: 運輸・通信"
capture label variable var123 "職業別常用労働者数15未充足求人数8: 生産・労務"
capture label variable var124 "職業別常用労働者数15未充足求人数9: その他"
capture label variable var125 "職業別常用労働者数16うちパート1: 専門・技術"
capture label variable var126 "職業別常用労働者数16うちパート2: 管理"
capture label variable var127 "職業別常用労働者数16うちパート3: 事務"
capture label variable var128 "職業別常用労働者数16うちパート4: 販売"
capture label variable var129 "職業別常用労働者数16うちパート5: サービス"
capture label variable var130 "職業別常用労働者数16うちパート6: 保安"
capture label variable var131 "職業別常用労働者数16うちパート7: 運輸・通信"
capture label variable var132 "職業別常用労働者数16うちパート8: 生産・労務"
capture label variable var133 "職業別常用労働者数16うちパート9: その他"
capture label variable var134 "入・離の抽出: 調査入職者数"
capture label variable var135 "入・離の抽出: 調査離職者数"
