/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（入職者票）h16-28.xlsx
    Date: 2019/02/25 04:50:48
----------------------------------------------------------------------*/


capture label define var3 1 "上半期" 
capture label values var3 var3

capture label define var7 1 "県番号:01" 3 "県番号:08~10,19,20" 5 "県番号:15~18" 7 "県番号:25~30" 9 "県番号:36~39" 
capture label values var7 var7

capture label define var8 1 "県番号:01" 3 "県番号:08~10,19,20" 5 "県番号:15~18" 7 "県番号:25,29,30" 9 "県番号:31,32" 11 "県番号:36~39" 13 "県番号:43,45~47" 
capture label values var8 var8

capture label define var16 1 "500人以上" 3 "30~99人" 
capture label values var16 var16

capture label define var17 1 "1000人以上" 3 "100~299人" 5 "5~29人" 
capture label values var17 var17

capture label define var20 1 "500人以上" 3 "30~99人" 
capture label values var20 var20

capture label define var21 1 "男" 
capture label values var21 var21

capture label define var22 1 "一般労働者" 
capture label values var22 var22

capture label define var28 1 "男" 
capture label values var28 var28

capture label define var29 1 "19歳以下" 3 "24~29歳" 5 "35~39歳" 7 "45~49歳" 9 "55~59歳" 11 "65歳以上" 
capture label values var29 var29

capture label define var30 1 "年齢チェック済:01" 3 "年齢チェック済:03" 5 "年齢チェック済:05" 7 "年齢チェック済:07" 9 "年齢チェック済:09" 12 "年齢チェック済:11" 
capture label values var30 var30

capture label define var31 1 "新中・旧小" 3 "専修学校(専門課程)" 5 "新大・旧大・大学院(文科系)" 
capture label values var31 var31

capture label define var32 1 "学歴チェック済:1" 3 "学歴チェック済:3" 5 "学歴チェック済:5,6" 
capture label values var32 var32

capture label define var33 1 "新中・旧小" 3 "専修学校(専門課程)" 6 "新大・旧大・大学院(文科系)" 
capture label values var33 var33

capture label define var34 1 "平成18年3月新卒" 
capture label values var34 var34

capture label define var35 1 "安定所" 3 "学校" 5 "出向" 7 "縁故" 9 "その他" 
capture label values var35 var35

capture label define var36 1 "入職経路チェック済:1" 3 "入職経路チェック済:3" 5 "入職経路チェック済:5" 7 "入職経路チェック済:7" 9 "入職経路チェック済:9" 
capture label values var36 var36

capture label define var37 1 "一般労働者" 
capture label values var37 var37

capture label define var38 1 "専門的・技術的職業従事者" 3 "事務従事者" 5 "サービス職業従事者" 7 "運輸・通信従事者" 9 "その他の職業従事者" 
capture label values var38 var38

capture label define var39 1 "仕事の内容チェック済:1~4" 3 "仕事の内容チェック済:5,6,9" 
capture label values var39 var39

capture label define var40 1 "ある(入職前1年以内)" 3 "ない(入職前2年間)" 
capture label values var40 var40

capture label define var41 2 "就業の経験:2、卒業年度:1" 4 "就業の経験:1" 
capture label values var41 var41

capture label define var42 3 "就業の経験:2、卒業年度:1" 6 "就業の経験:2、卒業年度:2" 9 "就業の経験:1、卒業年度:1" 
capture label values var42 var42

capture label define var43 3 "就業の経験:2、卒業年度:1、学歴:1" 5 "就業の経験:2、卒業年度:1、学歴:3" 7 "就業の経験:2、卒業年度:1、学歴:5,6" 9 "就業の経験:1" 
capture label values var43 var43

capture label define var44 2 "就業の経験:1、離職期間:1" 4 "就業の経験:1、離職期間:3" 6 "就業の経験:1、離職期間:5" 9 "就業の経験:2、離職期間:6" 11 "就業の経験:2、離職期間:V" 
capture label values var44 var44

capture label define var48 1 "勤めている" 
capture label values var48 var48

capture label define var49 1 "農林漁業" 3 "建設業" 5 "電気・ガス・熱供給・水道業" 7 "運輸業" 9 "金融・保険業" 11 "飲食店、宿泊業" 13 "教育、学習支援業" 15 "サービス業" 
capture label values var49 var49

capture label define var50 1 "専門的・技術的職業従事者" 3 "事務従事者" 5 "サービス職業従事者" 7 "運輸・通信従事者" 9 "その他の職業従事者" 
capture label values var50 var50

capture label define var51 1 "前職の仕事の内容チェック済:1~4" 3 "前職の仕事の内容チェック済:5,6,9" 
capture label values var51 var51

capture label define var52 1 "雇用者(一般労働者)" 3 "自営業主、家族従業者" 
capture label values var52 var52

capture label define var53 2 "前職の従業上の地位チェック済:1" 4 "前職の従業上の地位チェック済:3" 
capture label values var53 var53

capture label define var54 0 "" 11 "" 
capture label values var54 var54

capture label define var55 0 "" 22 "" 
capture label values var55 var55

capture label define var56 1 "15日未満" 3 "1ヶ月~3ヶ月未満" 5 "6ヶ月~1年未満" 7 "1年6ヶ月~2年未満" 
capture label values var56 var56

capture label define var57 1 "1000人以上" 3 "100~299人" 5 "5~29人" 7 "官公営" 
capture label values var57 var57

capture label define var59 1 "仕事の内容が不満" 3 "職場の人間関係" 5 "収入が少ない" 7 "結婚・出産・育児・介護" 9 "会社都合" 
capture label values var59 var59

capture label define var60 1 "前の勤め先を辞めた理由チェック済:01" 3 "前の勤め先を辞めた理由チェック済:03" 5 "前の勤め先を辞めた理由チェック済:05" 7 "前の勤め先を辞めた理由チェック済:07" 9 "前の勤め先を辞めた理由チェック済:09" 
capture label values var60 var60

capture label define var61 1 "前の勤め先を辞めた理由チェック済:01" 3 "前の勤め先を辞めた理由チェック済:03" 5 "前の勤め先を辞めた理由チェック済:05" 7 "前の勤め先を辞めた理由チェック済:07" 9 "前の勤め先を辞めた理由チェック済:09" 
capture label values var61 var61

capture label define var62 11 "仕事の内容に興味" 13 "会社の将来に期待" 15 "労働条件がよい" 17 "とにかく仕事につきたかった" 
capture label values var62 var62

capture label define var63 11 "現在の勤め先を選んだ理由チェック済:11" 13 "現在の勤め先を選んだ理由チェック済:13" 15 "現在の勤め先を選んだ理由チェック済:15" 17 "現在の勤め先を選んだ理由チェック済:17" 
capture label values var63 var63

capture label define var64 1 "現在の勤め先を選んだ理由チェック済:11" 3 "現在の勤め先を選んだ理由チェック済:13" 5 "現在の勤め先を選んだ理由チェック済:15" 7 "現在の勤め先を選んだ理由チェック済:17" 
capture label values var64 var64

capture label define var65 1 "増加3割以上" 3 "増加1割未満" 5 "減少1割未満" 7 "減少3割以上" 
capture label values var65 var65

capture label define var66 1 "賃金変動チェック済:1,2" 3 "賃金変動チェック済:4" 5 "賃金変動チェック済:6,7" 
capture label values var66 var66

capture label define var67 1 "賃金変動チェック済:1" 3 "賃金変動チェック済:6" 
capture label values var67 var67

