/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/14 14:46:11
-----------------------------------------------------------------------------*/


capture label variable YEAR "調査に関する事項: 調査年"
capture label variable MONTH "調査に関する事項: 調査月"
capture label variable KEN "所在地に関する事項市区町村情報市区町村符号: 都道府県"
capture label variable CITY "所在地に関する事項市区町村情報市区町村符号: 市区町村"
capture label variable var1 "所在地に関する事項市区町村情報: 推計乗率"
capture label variable TOKEKU "所在地に関する事項: 統計区番号"
capture label variable ZENCHI "所在地に関する事項調査区情報調査区番号: 前置番号"
capture label variable SHUBAN "所在地に関する事項調査区情報調査区番号: 主番号"
capture label variable KOHCHI "所在地に関する事項調査区情報調査区番号: 後置番号"
capture label variable BUNKA "所在地に関する事項調査区情報調査区番号: 分割(区)番号"
capture label variable CHOCTL "所在地に関する事項調査区情報調査区番号: 調査区分割符号"
capture label variable AZA "所在地に関する事項調査区情報: 町丁・字番号"
capture label variable DTKBN "データ区分"
capture label variable SETAIO "世帯に関する事項世帯番号: オリジナルコード"
capture label variable SKBNFJ "世帯に関する事項世帯区分: 普通世帯・準世帯の別"
capture label variable SKBNIS "世帯に関する事項世帯区分: 一般世帯・施設等の世帯の別"
capture label variable SKIND "世帯に関する事項世帯区分: 世帯の種類(8区分)"
capture label variable TATEKA "世帯に関する事項住宅の建て方: 建て方の種類"
capture label variable KAISU "世帯に関する事項住宅の建て方: 建て物の階数"
capture label variable JYUKYO "世帯に関する事項: 住居の種類"
capture label variable HEYA "世帯に関する事項居住室: 室数"
capture label variable TATAMI "世帯に関する事項居住室の畳数: 畳数"
capture label variable MNYOMO "世帯に関する事項家計の収入の種類: 主な収入の種類"
capture label variable MNYJYU1 "世帯に関する事項家計の収入の種類従な収入の種類: 賃金・給料"
capture label variable MNYJYU2 "世帯に関する事項家計の収入の種類従な収入の種類: 農業収入"
capture label variable MNYJYU3 "世帯に関する事項家計の収入の種類従な収入の種類: 農業以外の事業収入"
capture label variable MNYJYU4 "世帯に関する事項家計の収入の種類従な収入の種類: 内職収入"
capture label variable MNYJYU5 "世帯に関する事項家計の収入の種類従な収入の種類: 家賃・地代"
capture label variable MNYJYU6 "世帯に関する事項家計の収入の種類従な収入の種類: 利子・配当"
capture label variable MNYJYU7 "世帯に関する事項家計の収入の種類従な収入の種類: 恩給・年金"
capture label variable MNYJYU8 "世帯に関する事項家計の収入の種類従な収入の種類: 雇用保険"
capture label variable MNYJYU9 "世帯に関する事項家計の収入の種類従な収入の種類: 生活保護"
capture label variable MNYJYU10 "世帯に関する事項家計の収入の種類従な収入の種類: 仕送り"
capture label variable MNYJYU11 "世帯に関する事項家計の収入の種類従な収入の種類: その他の収入"
capture label variable MNY14 "世帯に関する事項家計の収入の種類: 14区分"
capture label variable SETJIN "世帯に関する事項: 世帯人員"
capture label variable SETINNO "個人に関する事項: 世帯員番号"
capture label variable TUZUKI "個人に関する事項: 世帯主との続き柄"
capture label variable SEX "個人に関する事項: 男女の別"
capture label variable NENGO "個人に関する事項年齢出生の年月: 元号"
capture label variable NENSU "個人に関する事項年齢出生の年月: 年"
capture label variable TUKIKBN "個人に関する事項年齢出生の年月: 月区分"
capture label variable AGE "個人に関する事項年齢: 各歳"
capture label variable HAIGU "個人に関する事項: 配偶関係"
capture label variable KOKUSEKI "個人に関する事項国籍: 日本・外国の別"
capture label variable GAIKOKU "個人に関する事項国籍: 外国区分"
capture label variable NYUKYO "個人に関する事項: 入居の時期"
capture label variable ZENJYU3 "個人に関する事項前住地区分: 3区分"
capture label variable ZENJYU6 "個人に関する事項前住地区分: 6区分"
capture label variable ZENKEN "個人に関する事項前住地前住地コード: 都道府県"
capture label variable ZENCTY "個人に関する事項前住地前住地コード: 市区町村"
capture label variable GAKU "個人に関する事項教育: 在学中・卒業・未就学の別"
capture label variable GAKKO "個人に関する事項教育: 学校区分"
capture label variable RODO3 "個人に関する事項労働力状態: 3区分"
capture label variable RODO8 "個人に関する事項労働力状態: 8区分"
capture label variable JYTUKBN3 "個人に関する事項従業地・通学地: 3区分"
capture label variable JYTUKBN6 "個人に関する事項従業地・通学地: 常住地による従業地・通学地区分"
capture label variable JYTUKEN "個人に関する事項従業地・通学地従通地コード: 都道府県"
capture label variable JYTUCTY "個人に関する事項従業地・通学地従通地コード: 市区町村"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 徒歩だけ"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 国鉄"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 国鉄以外の鉄道・電車"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 乗合バス"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 勤め先・学校のバス"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 自家用車"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: ハイヤー・タクシー"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: オートバイ"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: 自転車"
capture label variable RIYO10 "個人に関する事項利用交通手段10区分: その他"
capture label variable RIYO14 "個人に関する事項利用交通手段: 14区分"
capture label variable RIYO41 "個人に関する事項利用交通手段: 41区分"
capture label variable CHII3 "個人に関する事項従業上の地位: 3区分"
capture label variable CHII6 "個人に関する事項従業上の地位: 6区分"
capture label variable SANDF "個人に関する事項産業大分類: チェック済コード"
capture label variable SANC "個人に関する事項産業: 中分類"
capture label variable SANSF "個人に関する事項産業小分類: チェック済コード"
capture label variable SHODF "個人に関する事項職業大分類: チェック済コード"
capture label variable SHOC "個人に関する事項職業: 中分類"
capture label variable SHOSF "個人に関する事項職業小分類: チェック済コード"
