/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/レイアウト/00_2 昭和55年抽出詳細集計.xlsx
    Date: 2019/04/14 14:46:11
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str YEAR 3-6
        str MONTH 7-8
        str KEN 11-12
        str CITY 13-15
        str var1 24-34
        str TOKEKU 35-36
        str ZENCHI 38-39
        str SHUBAN 40-43
        str KOHCHI 44-44
        str BUNKA 45-47
        str CHOCTL 48-50
        str AZA 52-54
        str DTKBN 84-84
        str SETAIO 88-90
        str SKBNFJ 91-91
        str SKBNIS 92-92
        str SKIND 93-93
        str TATEKA 95-95
        str KAISU 96-96
        str JYUKYO 97-97
        str HEYA 98-99
        str TATAMI 101-103
        str MNYOMO 106-107
        str MNYJYU1 108-108
        str MNYJYU2 109-109
        str MNYJYU3 110-110
        str MNYJYU4 111-111
        str MNYJYU5 112-112
        str MNYJYU6 113-113
        str MNYJYU7 114-114
        str MNYJYU8 115-115
        str MNYJYU9 116-116
        str MNYJYU10 117-117
        str MNYJYU11 118-118
        str MNY14 119-120
        str SETJIN 125-128
        str SETINNO 174-177
        str TUZUKI 178-179
        str SEX 180-180
        str NENGO 181-181
        str NENSU 182-183
        str TUKIKBN 184-184
        str AGE 185-187
        str HAIGU 190-190
        str KOKUSEKI 191-191
        str GAIKOKU 192-192
        str NYUKYO 193-193
        str ZENJYU3 194-194
        str ZENJYU6 195-195
        str ZENKEN 198-199
        str ZENCTY 200-202
        str GAKU 206-206
        str GAKKO 207-207
        str RODO3 208-208
        str RODO8 209-209
        str JYTUKBN3 210-210
        str JYTUKBN6 211-211
        str JYTUKEN 212-213
        str JYTUCTY 214-216
        str RIYO10 220-220
        str RIYO10 221-221
        str RIYO10 222-222
        str RIYO10 223-223
        str RIYO10 224-224
        str RIYO10 225-225
        str RIYO10 226-226
        str RIYO10 227-227
        str RIYO10 228-228
        str RIYO10 229-229
        str RIYO14 230-231
        str RIYO41 232-233
        str CHII3 234-234
        str CHII6 235-235
        str SANDF 237-238
        str SANC 239-240
        str SANSF 244-246
        str SHODF 248-249
        str SHOC 250-251
        str SHOSF 255-257
    using "data";
#delimit cr
