/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/14 14:46:09
-----------------------------------------------------------------------------*/


capture label variable NENTUKI "RID調査区に関する事項: 調査年月"
capture label variable KEN "RID市区町村コード: 都道府県"
capture label variable CITY "RID市区町村コード: 市区町村"
capture label variable SHUBAN "RID調査区番号: 主番号"
capture label variable KOUCHI "RID調査区番号: 後置番号"
capture label variable BUNKATU "RID調査区番号: 単位番号"
capture label variable DTKBN "データ区分"
capture label variable SETORG "世帯番号オリジナルコード"
capture label variable SETINREN "世帯員番号"
capture label variable RITSU_B "所在地に関する事項市区町村情報: 線形乗率(B)"
capture label variable RITSU_C "所在地に関する事項市区町村情報: 比推定乗率(C)"
capture label variable AZACODE "所在地に関する事項調査区情報基本単位区番号: 町字コード"
capture label variable TANIKUCODE "所在地に関する事項調査区情報基本単位区番号: 基本単位区コード"
capture label variable RITSU_A "所在地に関する事項調査区情報: 線形乗率(A)"
capture label variable RITSU "所在地に関する事項: 集計用乗率(A×B×C)"
capture label variable SETAI "世帯に関する事項世帯区分: 世帯の種類"
capture label variable ISKBN "世帯に関する事項世帯区分: 一般・施設等の別"
capture label variable TATE "世帯に関する事項住宅の建て方: 建て方の種類"
capture label variable KAISU "世帯に関する事項住宅の建て方建物全体の階数: 階建"
capture label variable KAI5 "世帯に関する事項住宅の建て方建物全体の階数: 5区分"
capture label variable LIVE "世帯に関する事項住宅の建て方世帯が住んでいる階: 階"
capture label variable LIVE5 "世帯に関する事項住宅の建て方世帯が住んでいる階: 5区分"
capture label variable JYUKYO "世帯に関する事項住宅の建て方住居の種類・住宅所有の関係: 8区分"
capture label variable JYUKYO4 "世帯に関する事項住宅の建て方住居の種類・住宅所有の関係: 4区分"
capture label variable NOBEAREA "世帯に関する事項延べ面積: m2換算済"
capture label variable NOBE14 "世帯に関する事項延べ面積: 14区分"
capture label variable NOBE6 "世帯に関する事項延べ面積: 6区分"
capture label variable SETJIN "世帯に関する事項世帯人員: 総数"
capture label variable SETJIN_M "世帯に関する事項世帯人員: 男"
capture label variable SETJIN_F "世帯に関する事項世帯人員: 女"
capture label variable TUZUKI "個人に関する事項: 世帯主との続柄12区分"
capture label variable SEX "個人に関する事項: 男女の別"
capture label variable GENGO "個人に関する事項年齢出生の年月: 元号"
capture label variable NEN "個人に関する事項年齢出生の年月: 年"
capture label variable TUKI "個人に関する事項年齢出生の年月月: オリジナルコード"
capture label variable TUKI4 "個人に関する事項年齢出生の年月月: 4区分"
capture label variable NENREI "個人に関する事項年齢: 各歳"
capture label variable HAIGU "個人に関する事項: 配偶者の有無"
capture label variable KOKUSEKI "個人に関する事項国籍: 日本・外国の別"
capture label variable GAIKOKU "個人に関する事項国籍: 外国区分"
capture label variable KOKU12 "個人に関する事項国籍: 国籍(12区分)"
capture label variable RODO3 "個人に関する事項労働力状態: 3区分"
capture label variable RODO5 "個人に関する事項労働力状態: 5区分"
capture label variable RODO8 "個人に関する事項労働力状態: 8区分"
capture label variable JIKAN "個人に関する事項1週間に仕事をした時間: オリジナルコード"
capture label variable JIKAN14 "個人に関する事項1週間に仕事をした時間: 14区分"
capture label variable JIKAN10 "個人に関する事項1週間に仕事をした時間: 10区分"
capture label variable JYU3 "個人に関する事項従業地・通学地: 3区分"
capture label variable JYU4 "個人に関する事項従業地・通学地: 就業・通学4区分"
capture label variable JYU6A "個人に関する事項従業地・通学地: 常住地による従通6区分"
capture label variable JYUKEN "個人に関する事項従業地・通学地コード: 都道府県"
capture label variable JYUCITY "個人に関する事項従業地・通学地コード: 市区町村"
capture label variable CHII7 "個人に関する事項従業上の地位: 7区分"
capture label variable CHII3 "個人に関する事項従業上の地位: 3区分"
capture label variable SAND "個人に関する事項産業大分類: 集計用連番"
capture label variable SANC "個人に関する事項産業抽出集計用: 中分類集計用連番"
capture label variable SANS "個人に関する事項産業抽出集計用小分類: 集計用連番"
capture label variable SHOKD "個人に関する事項職業大分類: 集計用連番"
capture label variable SHOKC "個人に関する事項職業抽出集計用: 中分類集計用連番"
capture label variable SHOKS "個人に関する事項職業抽出集計用小分類: 集計用連番"
