/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx
    Date: 2019/02/22 13:15:29
----------------------------------------------------------------------*/


// Base data: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査IDT"    "調査IDT"
    Variable Name:  "var1"    "var1" 
    Variable values:
        Base data:   KE5: ,
        Match data:  KE7: ,

----------------------------------------------------------------------*/
capture rename var1 var1


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査年"    "調査年"
    Variable Name:  "var2"    "var2" 
    Variable values:
        Base data:   2004/2005: 西暦(年),
        Match data:  2006/2007: 西暦(年),

----------------------------------------------------------------------*/
capture rename var2 var2


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査月"    "調査月"
    Variable Name:  "var3"    "var3" 
    Variable values:
        Base data:   01: 上半期,
        Match data:  01: 上半期,

----------------------------------------------------------------------*/
capture rename var3 var3


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票区分"    "調査票区分"
    Variable Name:  "var4"    "var4" 
    Variable values:
        Base data:   J: 事業所票,
        Match data:  J: 事業所票,

----------------------------------------------------------------------*/
capture rename var4 var4


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM1"    "DLM1"
    Variable Name:  "var5"    "var5" 
    Variable values:
        Base data:   **: ,
        Match data:  **: ,

----------------------------------------------------------------------*/
capture rename var5 var5


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "空白1"    "空白1"
    Variable Name:  "var6"    "var6" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var6 var6


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "地域番号"    "地域番号"
    Variable Name:  "var7"    "var7" 
    Variable values:
        Base data:   01: 県番号:01, 02: 県番号:02~07, 03: 県番号:08~10,19,20, 04: 県番号:11~14, 05: 県番号:15~18, 06: 県番号:21~24, 07: 県番号:25,29,30, 08: 県番号:26~28, 09: 県番号:31,32, 10: 県番号:33~35, 11: 県番号:36~39, 12: 県番号:40~42, 13: 県番号:43,45~47,
        Match data:  01: 県番号:01, 02: 県番号:02~07, 03: 県番号:08~10,19,20, 04: 県番号:11~14, 05: 県番号:15~18, 06: 県番号:21~24, 07: 県番号:25,29,30, 08: 県番号:26~28, 09: 県番号:31,32, 10: 県番号:33~35, 11: 県番号:36~39, 12: 県番号:40~42,44, 13: 県番号:43,45~47,

----------------------------------------------------------------------*/
capture rename var7 var7


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "都道府県番号"    "都道府県番号"
    Variable Name:  "var8"    "var8" 
    Variable values:
        Base data:   01~47: ,
        Match data:  01~47: ,

----------------------------------------------------------------------*/
capture rename var8 var8


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所番号"    "事業所番号"
    Variable Name:  "var9"    "var9" 
    Variable values:
        Base data:   0001~: ,
        Match data:  0001~: ,

----------------------------------------------------------------------*/
capture rename var9 var9


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大分類"    "大分類"
    Variable Name:  "var10"    "var10" 
    Variable values:
        Base data:   D~Q: ,
        Match data:  D~Q: ,

----------------------------------------------------------------------*/
capture rename var10 var10


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "中分類"    "中分類"
    Variable Name:  "var11"    "var11" 
    Variable values:
        Base data:   05~93: ,
        Match data:  05~93: ,

----------------------------------------------------------------------*/
capture rename var11 var11


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM2"    "DLM2"
    Variable Name:  "var12"    "var12" 
    Variable values:
        Base data:   *: ,
        Match data:  *: ,

----------------------------------------------------------------------*/
capture rename var12 var12


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出符号"    "抽出符号"
    Variable Name:  "var13"    "var13" 
    Variable values:
        Base data:   001~999: 抽出率逆数,
        Match data:  001~999: 抽出率逆数,

----------------------------------------------------------------------*/
capture rename var13 var13


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM3"    "DLM3"
    Variable Name:  "var14"    "var14" 
    Variable values:
        Base data:   *: ,
        Match data:  *: ,

----------------------------------------------------------------------*/
capture rename var14 var14


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所規模"    "事業所規模"
    Variable Name:  "var15"    "var15" 
    Variable values:
        Base data:   1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,
        Match data:  1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,

----------------------------------------------------------------------*/
capture rename var15 var15


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "企業規模"    "企業規模"
    Variable Name:  "var16"    "var16" 
    Variable values:
        Base data:   1: 1000人以上, 2: 300~999人, 3: 100~299人, 4: 30~99人, 5: 5~29人, 6: 官公営,
        Match data:  1: 1000人以上, 2: 300~999人, 3: 100~299人, 4: 30~99人, 5: 5~29人, 6: 官公営,

----------------------------------------------------------------------*/
capture rename var16 var16


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM4"    "DLM4"
    Variable Name:  "var17"    "var17" 
    Variable values:
        Base data:   *: ,
        Match data:  *: ,

----------------------------------------------------------------------*/
capture rename var17 var17


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用産業分類"    "乗率用産業分類"
    Variable Name:  "var18"    "var18" 
    Variable values:
        Base data:   02,03,05~3032~39,41~45(04,31,40は除く): ,
        Match data:  01~44: 01,02,04~29,31~38,40~44(03,30,39は除く),

----------------------------------------------------------------------*/
capture rename var18 var18


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用事業所規模"    "乗率用事業所規模"
    Variable Name:  "var19"    "var19" 
    Variable values:
        Base data:   1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,
        Match data:  1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,

----------------------------------------------------------------------*/
capture rename var19 var19


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用性別"    "乗率用性別"
    Variable Name:  "var20"    "var20" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var20 var20


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用就業形態"    "乗率用就業形態"
    Variable Name:  "var21"    "var21" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var21 var21


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM5"    "DLM5"
    Variable Name:  "var22"    "var22" 
    Variable values:
        Base data:   *: ,
        Match data:  *: ,

----------------------------------------------------------------------*/
capture rename var22 var22


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "空白2"    "空白2"
    Variable Name:  "var23"    "var23" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var23 var23


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM6"    "DLM6"
    Variable Name:  "var24"    "var24" 
    Variable values:
        Base data:   *: ,
        Match data:  *: ,

----------------------------------------------------------------------*/
capture rename var24 var24


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率"    "乗率"
    Variable Name:  "var25"    "var25" 
    Variable values:
        Base data:   0~9999999999: ,
        Match data:  0~9999999999: ,

----------------------------------------------------------------------*/
capture rename var25 var25


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "DLM7"    "DLM7"
    Variable Name:  "var26"    "var26" 
    Variable values:
        Base data:   ***: ,
        Match data:  ***: ,

----------------------------------------------------------------------*/
capture rename var26 var26


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var27"    "var69" 
    Variable values:
        Base data:   0~999999: 以下右詰0補足,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var27


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var28"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var28


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var29"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var29


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var30"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var30


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var31"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var31


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var32"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var32


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var33"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var33


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var34"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var34


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var35"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var35


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var36"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var36


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var37"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var37


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var38"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var38


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var39"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var39


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var40"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var40


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var41"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var41


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var42"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var42


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var43"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var43


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var44"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var44


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var45"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var45


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var46"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var46


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var47"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var47


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var48"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var48


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var49"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var49


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var50"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var50


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var51"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var51


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var52"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var52


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var53"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var53


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var54"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var54


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var55"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var55


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var56"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var56


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var57"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var57


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var58"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var58


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var59"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var59


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var60"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var60


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var61"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var61


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var62"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var62


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var63"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var63


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var64"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var64


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var65"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var65


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var66"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var66


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var67"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var67


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var68"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var68


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var69"    "var69" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var69 var69


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var70"    "var70" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var70 var70


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var71"    "var71" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var71 var71


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var72"    "var72" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var72 var72


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var73"    "var73" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var73 var73


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var74"    "var74" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var74 var74


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var75"    "var111" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var111 var75


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var76"    "var112" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var112 var76


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var77"    "var113" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var113 var77


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var78"    "var114" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var114 var78


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var79"    "var115" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var115 var79


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var80"    "var116" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var116 var80


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var81"    "var117" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var117 var81


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var82"    "var118" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var118 var82


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var83"    "var119" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var119 var83


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var84"    "var120" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var120 var84


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var85"    "var121" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var121 var85


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var86"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var86


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var87"    "var111" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var111 var87


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var88"    "var112" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var112 var88


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var89"    "var113" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var113 var89


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var90"    "var114" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var114 var90


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var91"    "var115" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var115 var91


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var92"    "var116" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var116 var92


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var93"    "var117" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var117 var93


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var94"    "var118" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var118 var94


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var95"    "var119" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var119 var95


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var96"    "var120" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var120 var96


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var97"    "var121" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var121 var97


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var98"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var98


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var99"    "var111" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var111 var99


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var100"    "var112" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var112 var100


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var101"    "var113" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var113 var101


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var102"    "var114" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var114 var102


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var103"    "var115" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var115 var103


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var104"    "var116" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var116 var104


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var105"    "var117" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var117 var105


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var106"    "var118" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var118 var106


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var107"    "var119" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var119 var107


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var108"    "var120" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var120 var108


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var109"    "var121" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var121 var109


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var110"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var110


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var111"    "var111" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var111 var111


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var112"    "var112" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var112 var112


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var113"    "var113" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var113 var113


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var114"    "var114" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var114 var114


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var115"    "var115" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var115 var115


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var116"    "var116" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var116 var116


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var117"    "var117" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var117 var117


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var118"    "var118" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var118 var118


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var119"    "var119" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var119 var119


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var120"    "var120" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var120 var120


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var121"    "var121" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var121 var121


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var122"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var122


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var123"    "var153" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var153 var123


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var124"    "var154" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var154 var124


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var125"    "var155" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var155 var125


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var126"    "var156" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var156 var126


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var127"    "var157" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var157 var127


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var128"    "var158" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var158 var128


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var129"    "var159" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var159 var129


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var130"    "var160" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var160 var130


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var131"    "var161" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var161 var131


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var132"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var132


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var133"    "var153" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var153 var133


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var134"    "var154" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var154 var134


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var135"    "var155" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var155 var135


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var136"    "var156" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var156 var136


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var137"    "var157" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var157 var137


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var138"    "var158" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var158 var138


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var139"    "var159" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var159 var139


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var140"    "var160" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var160 var140


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var141"    "var161" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var161 var141


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var142"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var142


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var143"    "var153" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var153 var143


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var144"    "var154" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var154 var144


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var145"    "var155" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var155 var145


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var146"    "var156" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var156 var146


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var147"    "var157" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var157 var147


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var148"    "var158" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var158 var148


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var149"    "var159" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var159 var149


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var150"    "var160" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var160 var150


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var151"    "var161" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var161 var151


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var152"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var152


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var153"    "var153" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var153 var153


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var154"    "var154" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var154 var154


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var155"    "var155" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var155 var155


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var156"    "var156" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var156 var156


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var157"    "var157" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var157 var157


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var158"    "var158" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var158 var158


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var159"    "var159" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var159 var159


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var160"    "var160" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var160 var160


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var161"    "var161" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var161 var161


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "合計"    "合計"
    Variable Name:  "var162"    "var162" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var162 var162


