/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成27年レイアウト＆符号表.xlsx
    Date: 2019/04/12 17:05:43
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str DTKBN 1-1
        str NENTSUKI 2-7
        str KEN 8-9
        str CITY 10-12
        str SHUBAN 13-16
        str KOCHI 17-17
        str TANI 18-19
        str SETAI 20-22
        str SETNINME 23-26
        str AZACODE 27-30
        str TANIKUCODE 31-35
        str SENKEI_A 36-48
        str SENKEI_B 49-61
        str SENKEI_AB 62-74
        str JOSU 75-87
        str JORITSU 88-100
        str KC_5_GENGO 101-101
        str KC_5_NEN 102-105
        str KC_5_TSUKI 106-107
        str SKIND 108-108
        str ISKBN 109-109
        str TATEKIND 110-110
        str TATEKAISU 111-112
        str LIVEKAISU 113-114
        str JYUKYO8 115-115
        str SETJIN 116-118
        str TSUZUKI 119-120
        str SEX 121-121
        str TSUKI4 122-122
        str NENREI 123-125
        str HAIGU 126-126
        str KOKUSEKI 127-127
        str KYOJU6 128-128
        str ZEN6A 129-129
        str ZENJKEN 130-131
        str ZENJCITY 132-134
        str RODO8 135-135
        str JYU7A 136-136
        str JYUKEN 137-138
        str JYUCITY 139-141
        str CHII8 142-142
        str SAND 143-144
        str SANC 145-146
        str SANS 147-149
        str SHOKD 150-151
        str SHOKC 152-153
        str SHOKS 154-156
    using "data";
#delimit cr
