/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/12 17:05:43
-----------------------------------------------------------------------------*/


capture label variable DTKBN "RID調査に関する事項: データ区分"
capture label variable NENTSUKI "RID調査に関する事項: 調査年月"
capture label variable KEN "RID市区町村コード: 都道府県"
capture label variable CITY "RID市区町村コード: 市区町村"
capture label variable SHUBAN "RID調査区番号: 主番号"
capture label variable KOCHI "RID調査区番号: 後置番号"
capture label variable TANI "RID調査区番号: 単位番号"
capture label variable SETAI "RID: 世帯番号"
capture label variable SETNINME "RID: 世帯員番号"
capture label variable AZACODE "所在地に関する事項調査区情報基本単位区番号: 町字コード"
capture label variable TANIKUCODE "所在地に関する事項調査区情報基本単位区番号: 基本単位区コード"
capture label variable SENKEI_A "乗率: 線形推定用乗率A(調査区内の当該世帯の抽出率の逆数)"
capture label variable SENKEI_B "乗率: 線形推定用乗率B(集計単位の市区町村内の当該調査区の抽出率の逆数)"
capture label variable SENKEI_AB "乗率: 線形推定用乗率(線形推定用乗率A*線形推定用乗率B)"
capture label variable JOSU "乗率: 乗数(集計用乗率/線形推定用乗率)"
capture label variable JORITSU "乗率: 集計用乗率"
capture label variable KC_5_GENGO "オリジナル情報(最終チェック済データ)個人事項出生の年月: 元号・西暦"
capture label variable KC_5_NEN "オリジナル情報(最終チェック済データ)個人事項出生の年月: 年"
capture label variable KC_5_TSUKI "オリジナル情報(最終チェック済データ)個人事項出生の年月: 月"
capture label variable SKIND "世帯に関する事項世帯区分: 世帯の種類"
capture label variable ISKBN "世帯に関する事項世帯区分: 一般・施設等の別"
capture label variable TATEKIND "世帯に関する事項住宅の建て方: 建て方の種類"
capture label variable TATEKAISU "世帯に関する事項住宅の建て方建物全体の階数: 建物の階数"
capture label variable LIVEKAISU "世帯に関する事項住宅の建て方世帯が住んでいる階: 住んでいる階"
capture label variable JYUKYO8 "世帯に関する事項住宅の建て方住居の種類・住宅の所有の関係: 8区分"
capture label variable SETJIN "世帯に関する事項世帯人員: 総数"
capture label variable TSUZUKI "個人に関する事項: 世帯主との続柄12区分"
capture label variable SEX "個人に関する事項: 男女の別"
capture label variable TSUKI4 "個人に関する事項年齢出生の月: 4区分"
capture label variable NENREI "個人に関する事項年齢: 各歳"
capture label variable HAIGU "個人に関する事項: 配偶者の有無"
capture label variable KOKUSEKI "個人に関する事項国籍: 日本・外国の別"
capture label variable KYOJU6 "個人に関する事項: 居住期間(6区分)"
capture label variable ZEN6A "個人に関する事項5年前の常住地: 6区分"
capture label variable ZENJKEN "個人に関する事項5年前の常住地前住地コード: 都道府県"
capture label variable ZENJCITY "個人に関する事項5年前の常住地前住地コード: 市区町村"
capture label variable RODO8 "個人に関する事項5年前の常住地: 8区分"
capture label variable JYU7A "個人に関する事項従業地・通学地: 常住地による従通7区分"
capture label variable JYUKEN "個人に関する事項従業地・通学地従通地コード: 都道府県"
capture label variable JYUCITY "個人に関する事項従業地・通学地従通地コード: 市区町村"
capture label variable CHII8 "個人に関する事項従業上の地位: 8区分"
capture label variable SAND "個人に関する事項産業大分類: 集計用連番"
capture label variable SANC "個人に関する事項産業抽出集計用: 中分類集計用連番"
capture label variable SANS "個人に関する事項産業抽出集計用小分類: 集計用連番"
capture label variable SHOKD "個人に関する事項職業大分類: 集計用連番"
capture label variable SHOKC "個人に関する事項職業抽出集計用: 中分類集計用連番"
capture label variable SHOKS "個人に関する事項職業抽出集計用小分類: 集計用連番"
