/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（離職者票）h7-28.xlsx
    Date: 2019/02/25 04:50:59
----------------------------------------------------------------------*/


capture label define var3 1 "上半期" 
capture label values var3 var3

capture label define var7 1 "県番号:01" 3 "県番号:08~10,19,20" 5 "県番号:15~18" 7 "県番号:25,29,30" 9 "県番号:31,32" 11 "県番号:36~39" 13 "県番号:43,45~47" 
capture label values var7 var7

capture label define var15 1 "500人以上" 3 "30~99人" 
capture label values var15 var15

capture label define var16 1 "1000人以上" 3 "100~299人" 5 "5~29人" 
capture label values var16 var16

capture label define var19 1 "500人以上" 3 "30~99人" 
capture label values var19 var19

capture label define var20 1 "男" 
capture label values var20 var20

capture label define var21 1 "一般労働者" 
capture label values var21 var21

capture label define var28 1 "男" 
capture label values var28 var28

capture label define var29 1 "19歳以下" 3 "24~29歳" 5 "35~39歳" 7 "45~49歳" 9 "55~59歳" 11 "65歳以上" 
capture label values var29 var29

capture label define var30 1 "年齢チェック済:01" 3 "年齢チェック済:03" 5 "年齢チェック済:05" 7 "年齢チェック済:07" 9 "年齢チェック済:09" 12 "年齢チェック済:11" 
capture label values var30 var30

capture label define var31 1 "新中・旧小" 3 "専修学校(専門課程)" 5 "新大・旧大・大学院(文科系)" 
capture label values var31 var31

capture label define var32 1 "平成19年3月新卒" 
capture label values var32 var32

capture label define var33 1 "一般労働者" 
capture label values var33 var33

capture label define var34 1 "専門的・技術的職業従事者" 3 "事務従事者" 5 "サービス職業従事者" 7 "運輸・通信従事者" 9 "その他の職業従事者" 
capture label values var34 var34

capture label define var35 1 "6ヶ月未満" 3 "1年~2年未満" 5 "5年~10年未満" 
capture label values var35 var35

capture label define var36 1 "契約期間の満了" 3 "出向" 5 "定年" 7 "結婚" 9 "介護" 11 "その他の個人的理由" 
capture label values var36 var36

capture label define var37 1 "離職理由チェック済:01" 4 "離職理由チェック済:03" 6 "離職理由チェック済:05" 8 "離職理由チェック済:11" 10 "離職理由チェック済:08" 12 "離職理由チェック済:10" 
capture label values var37 var37

