capture label variable var1 "調査IDT"
capture label variable var2 "調査年"
capture label variable var3 "調査月"
capture label variable var4 "スペース１"
capture label variable var5 "調査票区分"
capture label variable var6 "スペース２"
capture label variable var7 "乗率"
capture label variable var8 "都道府県番号"
capture label variable var9 "事業所番号"
capture label variable var10 "産業中分類"
capture label variable var11 "抽出番号"
capture label variable var12 "事業所規模"
capture label variable var13 "企業規模"
capture label variable var14 " イ　入職者"
capture label variable var15 " ロ　転入者等"
capture label variable var16 "（３）常用に切り替えられた者"
capture label variable var17 " イ　離職者"
capture label variable var18 " ロ　転出者等"
capture label variable var19 "（５）期末常用労働者"
capture label variable var20 " イ　入職者"
capture label variable var21 " ロ　転入者等"
capture label variable var22 "（３）常用に切り替えられた者"
capture label variable var23 " イ　離職者"
capture label variable var24 " ロ　転出者等"
capture label variable var25 "（５）期末常用労働者"
capture label variable var26 " イ　入職者"
capture label variable var27 " ロ　転入者等"
capture label variable var28 "（３）常用に切り替えられた者"
capture label variable var29 " イ　離職者"
capture label variable var30 " ロ　転出者等"
capture label variable var31 "（５）期末常用労働者"
capture label variable var32 " イ　入職者"
capture label variable var33 " ロ　転入者等"
capture label variable var34 "（３）常用に切り替えられた者"
capture label variable var35 " イ　離職者"
capture label variable var36 " ロ　転出者等"
capture label variable var37 "（５）期末常用労働者"
capture label variable var38 " イ　入職者"
capture label variable var39 " ロ　転入者等"
capture label variable var40 " イ　離職者"
capture label variable var41 " ロ　転出者等"
capture label variable var42 "（５）期末常用労働者"
capture label variable var43 " イ　入職者"
capture label variable var44 " ロ　転入者等"
capture label variable var45 " イ　離職者"
capture label variable var46 " ロ　転出者等"
capture label variable var47 "（５）期末常用労働者"
capture label variable var48 " イ　入職者"
capture label variable var49 " ロ　転入者等"
capture label variable var50 " イ　離職者"
capture label variable var51 " ロ　転出者等"
capture label variable var52 "（５）期末常用労働者"
capture label variable var53 "（２）増加常用労働者  イ　入職者"
capture label variable var54 "（４）減少常用労働者  イ　離職者"
capture label variable var55 "（５）期末常用労働者"
capture label variable var56 "19歳以下"
capture label variable var57 "20～24歳"
capture label variable var58 "25～29歳"
capture label variable var59 "30～34歳"
capture label variable var60 "35～39歳"
capture label variable var61 "40～44歳"
capture label variable var62 "45～49歳"
capture label variable var63 "50～54歳"
capture label variable var64 "55～59歳"
capture label variable var65 "60～64歳"
capture label variable var66 "65歳以上"
capture label variable var67 "19歳以下"
capture label variable var68 "20～24歳"
capture label variable var69 "25～29歳"
capture label variable var70 "30～34歳"
capture label variable var71 "35～39歳"
capture label variable var72 "40～44歳"
capture label variable var73 "45～49歳"
capture label variable var74 "50～54歳"
capture label variable var75 "55～59歳"
capture label variable var76 "60～64歳"
capture label variable var77 "65歳以上"
capture label variable var78 "19歳以下"
capture label variable var79 "20～24歳"
capture label variable var80 "25～29歳"
capture label variable var81 "30～34歳"
capture label variable var82 "35～39歳"
capture label variable var83 "40～44歳"
capture label variable var84 "45～49歳"
capture label variable var85 "50～54歳"
capture label variable var86 "55～59歳"
capture label variable var87 "60～64歳"
capture label variable var88 "65歳以上"
capture label variable var89 "19歳以下"
capture label variable var90 "20～24歳"
capture label variable var91 "25～29歳"
capture label variable var92 "30～34歳"
capture label variable var93 "35～39歳"
capture label variable var94 "40～44歳"
capture label variable var95 "45～49歳"
capture label variable var96 "50～54歳"
capture label variable var97 "55～59歳"
capture label variable var98 "60～64歳"
capture label variable var99 "65歳以上"
capture label variable var100 "専門・技術"
capture label variable var101 "管理"
capture label variable var102 "事務"
capture label variable var103 "販売"
capture label variable var104 "サービス"
capture label variable var105 "保安"
capture label variable var106 "運輸・通信"
capture label variable var107 "生産・労務"
capture label variable var108 "その他"
capture label variable var109 "専門・技術"
capture label variable var110 "管理"
capture label variable var111 "事務"
capture label variable var112 "販売"
capture label variable var113 "サービス"
capture label variable var114 "保安"
capture label variable var115 "運輸・通信"
capture label variable var116 "生産・労務"
capture label variable var117 "その他"
capture label variable var118 "専門・技術"
capture label variable var119 "管理"
capture label variable var120 "事務"
capture label variable var121 "販売"
capture label variable var122 "サービス"
capture label variable var123 "保安"
capture label variable var124 "運輸・通信"
capture label variable var125 "生産・労務"
capture label variable var126 "その他"
capture label variable var127 "専門・技術"
capture label variable var128 "管理"
capture label variable var129 "事務"
capture label variable var130 "販売"
capture label variable var131 "サービス"
capture label variable var132 "保安"
capture label variable var133 "運輸・通信"
capture label variable var134 "生産・労務"
capture label variable var135 "その他"
capture label variable var136 "調査入職者数"
capture label variable var137 "調査離職者数"
