/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx
    Date: 2019/02/22 13:15:30
----------------------------------------------------------------------*/


// Base data: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査IDT"    "調査IDT"
    Variable Name:  "var1"    "var1" 
    Variable values:
        Base data:   KE5: ,
        Match data:  KE: ,

----------------------------------------------------------------------*/
capture rename var1 var1


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査年"    "調査年"
    Variable Name:  "var2"    "var2" 
    Variable values:
        Base data:   2004/2005: 西暦(年),
        Match data:  2008: ,

----------------------------------------------------------------------*/
capture rename var2 var2


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査月"    "調査月"
    Variable Name:  "var3"    "var3" 
    Variable values:
        Base data:   01: 上半期,
        Match data:  01: 上半期,

----------------------------------------------------------------------*/
capture rename var3 var3


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票区分"    "調査票区分"
    Variable Name:  "var4"    "var5" 
    Variable values:
        Base data:   J: 事業所票,
        Match data:  J: 事業所票,

----------------------------------------------------------------------*/
capture rename var5 var4


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "地域番号"    "抽出番号"
    Variable Name:  "var7"    "var12" 
    Variable values:
        Base data:   01: 県番号:01, 02: 県番号:02~07, 03: 県番号:08~10,19,20, 04: 県番号:11~14, 05: 県番号:15~18, 06: 県番号:21~24, 07: 県番号:25,29,30, 08: 県番号:26~28, 09: 県番号:31,32, 10: 県番号:33~35, 11: 県番号:36~39, 12: 県番号:40~42, 13: 県番号:43,45~47,
        Match data:  001~999: 抽出率逆数,

----------------------------------------------------------------------*/
capture rename var12 var7


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "都道府県番号"    "都道府県番号"
    Variable Name:  "var8"    "var9" 
    Variable values:
        Base data:   01~47: ,
        Match data:  01~47: ,

----------------------------------------------------------------------*/
capture rename var9 var8


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所番号"    "事業所番号"
    Variable Name:  "var9"    "var10" 
    Variable values:
        Base data:   0001~: ,
        Match data:  0001~: ,

----------------------------------------------------------------------*/
capture rename var10 var9


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大分類"    "中分類"
    Variable Name:  "var10"    "var11" 
    Variable values:
        Base data:   D~Q: ,
        Match data:  05~93: ,

----------------------------------------------------------------------*/
capture rename var11 var10


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "中分類"    "中分類"
    Variable Name:  "var11"    "var11" 
    Variable values:
        Base data:   05~93: ,
        Match data:  05~93: ,

----------------------------------------------------------------------*/
capture rename var11 var11


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出符号"    "抽出番号"
    Variable Name:  "var13"    "var12" 
    Variable values:
        Base data:   001~999: 抽出率逆数,
        Match data:  001~999: 抽出率逆数,

----------------------------------------------------------------------*/
capture rename var12 var13


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所規模"    "事業所規模"
    Variable Name:  "var15"    "var13" 
    Variable values:
        Base data:   1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,
        Match data:  1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,

----------------------------------------------------------------------*/
capture rename var13 var15


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "企業規模"    "企業規模"
    Variable Name:  "var16"    "var14" 
    Variable values:
        Base data:   1: 1000人以上, 2: 300~999人, 3: 100~299人, 4: 30~99人, 5: 5~29人, 6: 官公営,
        Match data:  1: 1000人以上, 2: 300~999人, 3: 100~299人, 4: 30~99人, 5: 5~29人, 6: 官公営,

----------------------------------------------------------------------*/
capture rename var14 var16


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用産業分類"    "中分類"
    Variable Name:  "var18"    "var11" 
    Variable values:
        Base data:   02,03,05~3032~39,41~45(04,31,40は除く): ,
        Match data:  05~93: ,

----------------------------------------------------------------------*/
capture rename var11 var18


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用事業所規模"    "事業所規模"
    Variable Name:  "var19"    "var13" 
    Variable values:
        Base data:   1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,
        Match data:  1: 500人以上, 2: 100~499人, 3: 30~99人, 4: 5~29人,

----------------------------------------------------------------------*/
capture rename var13 var19


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用性別"    "乗率"
    Variable Name:  "var20"    "var7" 
    Variable values:
        Base data:   : ,
        Match data:  : 整数部3桁、小数部7桁,

----------------------------------------------------------------------*/
capture rename var7 var20


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率用就業形態"    "乗率"
    Variable Name:  "var21"    "var7" 
    Variable values:
        Base data:   : ,
        Match data:  : 整数部3桁、小数部7桁,

----------------------------------------------------------------------*/
capture rename var7 var21


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "乗率"    "乗率"
    Variable Name:  "var25"    "var7" 
    Variable values:
        Base data:   0~9999999999: ,
        Match data:  : 整数部3桁、小数部7桁,

----------------------------------------------------------------------*/
capture rename var7 var25


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var27"    "var54" 
    Variable values:
        Base data:   0~999999: 以下右詰0補足,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var27


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var28"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var28


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var29"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var29


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var30"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var30


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var31"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var31


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var32"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var32


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var33"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var33


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var34"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var34


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var35"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var35


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var36"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var36


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var37"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var37


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var38"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var38


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var39"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var39


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var40"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var40


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var41"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var41


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var42"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var42


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var43"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var43


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var44"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var44


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var45"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var45


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var46"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var46


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var47"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var47


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var48"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var48


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var49"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var49


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var50"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var50


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var51"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var51


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var52"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var52


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var53"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var53


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var54"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var54


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var55"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var55


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var56"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var56


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var57"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var57


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var58"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var58


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var59"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var59


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var60"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var60


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var61"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var61


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var62"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var62


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var63"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var63


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var64"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var64


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var65"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var65


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var66"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var66


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var67"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var67


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var68"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var68


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ入職者"    "イ入職者"
    Variable Name:  "var69"    "var54" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var54 var69


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転入者等"    "ロ転入者等"
    Variable Name:  "var70"    "var50" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var50 var70


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(3)常用に切り替えられた者"    "(3)常用に切り替えられた者"
    Variable Name:  "var71"    "var35" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var35 var71


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "イ離職者"    "イ離職者"
    Variable Name:  "var72"    "var55" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var55 var72


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "ロ転出者等"    "ロ転出者等"
    Variable Name:  "var73"    "var52" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var52 var73


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "(5)期末常用労働者"    "(5)期末常用労働者"
    Variable Name:  "var74"    "var56" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var56 var74


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var75"    "var90" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var90 var75


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var76"    "var91" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var91 var76


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var77"    "var92" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var92 var77


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var78"    "var93" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var93 var78


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var79"    "var94" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var94 var79


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var80"    "var95" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var95 var80


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var81"    "var96" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var96 var81


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var82"    "var97" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var97 var82


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var83"    "var98" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var98 var83


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var84"    "var99" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var99 var84


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var85"    "var100" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var100 var85


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var87"    "var90" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var90 var87


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var88"    "var91" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var91 var88


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var89"    "var92" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var92 var89


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var90"    "var93" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var93 var90


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var91"    "var94" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var94 var91


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var92"    "var95" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var95 var92


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var93"    "var96" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var96 var93


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var94"    "var97" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var97 var94


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var95"    "var98" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var98 var95


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var96"    "var99" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var99 var96


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var97"    "var100" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var100 var97


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var99"    "var90" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var90 var99


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var100"    "var91" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var91 var100


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var101"    "var92" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var92 var101


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var102"    "var93" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var93 var102


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var103"    "var94" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var94 var103


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var104"    "var95" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var95 var104


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var105"    "var96" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var96 var105


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var106"    "var97" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var97 var106


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var107"    "var98" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var98 var107


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var108"    "var99" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var99 var108


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var109"    "var100" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var100 var109


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "19歳以下"    "19歳以下"
    Variable Name:  "var111"    "var90" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var90 var111


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "20~24歳"    "20~24歳"
    Variable Name:  "var112"    "var91" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var91 var112


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "25~29歳"    "25~29歳"
    Variable Name:  "var113"    "var92" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var92 var113


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "30~34歳"    "30~34歳"
    Variable Name:  "var114"    "var93" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var93 var114


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "35~39歳"    "35~39歳"
    Variable Name:  "var115"    "var94" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var94 var115


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "40~44歳"    "40~44歳"
    Variable Name:  "var116"    "var95" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var95 var116


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "45~49歳"    "45~49歳"
    Variable Name:  "var117"    "var96" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var96 var117


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "50~54歳"    "50~54歳"
    Variable Name:  "var118"    "var97" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var97 var118


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "55~59歳"    "55~59歳"
    Variable Name:  "var119"    "var98" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var98 var119


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "60~64歳"    "60~64歳"
    Variable Name:  "var120"    "var99" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var99 var120


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "65歳以上"    "65歳以上"
    Variable Name:  "var121"    "var100" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var100 var121


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var123"    "var128" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var128 var123


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var124"    "var129" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var129 var124


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var125"    "var130" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var130 var125


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var126"    "var131" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var131 var126


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var127"    "var132" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var132 var127


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var128"    "var133" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var133 var128


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var129"    "var134" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var134 var129


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var130"    "var135" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var135 var130


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var131"    "var136" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var136 var131


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var133"    "var128" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var128 var133


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var134"    "var129" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var129 var134


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var135"    "var130" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var130 var135


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var136"    "var131" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var131 var136


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var137"    "var132" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var132 var137


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var138"    "var133" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var133 var138


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var139"    "var134" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var134 var139


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var140"    "var135" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var135 var140


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var141"    "var136" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var136 var141


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var143"    "var128" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var128 var143


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var144"    "var129" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var129 var144


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var145"    "var130" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var130 var145


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var146"    "var131" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var131 var146


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var147"    "var132" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var132 var147


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var148"    "var133" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var133 var148


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var149"    "var134" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var134 var149


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var150"    "var135" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var135 var150


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var151"    "var136" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var136 var151


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "専門・技術"    "専門・技術"
    Variable Name:  "var153"    "var128" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var128 var153


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "管理"    "管理"
    Variable Name:  "var154"    "var129" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var129 var154


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事務"    "事務"
    Variable Name:  "var155"    "var130" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var130 var155


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "販売"    "販売"
    Variable Name:  "var156"    "var131" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var131 var156


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "サービス"    "サービス"
    Variable Name:  "var157"    "var132" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var132 var157


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "保安"    "保安"
    Variable Name:  "var158"    "var133" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var133 var158


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "運輸・通信"    "運輸・通信"
    Variable Name:  "var159"    "var134" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var134 var159


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "生産・労務"    "生産・労務"
    Variable Name:  "var160"    "var135" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var135 var160


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "その他"    "その他"
    Variable Name:  "var161"    "var136" 
    Variable values:
        Base data:   0~999999: ,
        Match data:  0~999999: ,

----------------------------------------------------------------------*/
capture rename var136 var161


