/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成17年レイアウト＆符号表.xlsx
    Date: 2019/04/12 17:05:43
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 1-6
        str KEN 7-8
        str CITY 9-11
        str SHUBAN 12-15
        str KOUCHI 16-16
        str BUNKATU 17-18
        str DTKBN 19-19
        str SETORG 20-22
        str SETINREN 23-26
        str RITSU_B 27-38
        str RITSU_C 39-48
        str AZACODE 49-52
        str TANIKUCODE 53-57
        str RITSU_A 58-69
        str RITSU 70-81
        str SETAI 82-82
        str ISKBN 83-83
        str TATE 84-84
        str KAISU 85-86
        str LIVE 87-88
        str JYUKYO 89-89
        str NOBETANI 90-90
        str NOBE 91-94
        str NOBEAREA 95-101
        str SETJIN 102-105
        str TUZUKI 106-107
        str SEX 108-108
        str GENGO 109-109
        str NEN 110-113
        str TUKI 114-115
        str TUKI4 116-116
        str NENREI 117-119
        str HAIGU 120-120
        str KOKUSEKI 121-121
        str RODO8 122-122
        str JYU6A 123-123
        str JYUKEN 124-125
        str JYUCITY 126-128
        str SANDF 129-129
        str SAND 130-131
        str SANC 132-133
        str SANSF 134-136
        str SANS 137-139
        str SHOKDF 140-140
        str SHOKD 141-142
        str SHOKC 143-144
        str SHOKSF 145-147
        str SHOKS 148-150
    using "data";
#delimit cr
