/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成02年レイアウト＆符号表（抽出詳細集計）.xlsx
    Date: 2019/04/12 17:05:44
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 1-6
        str KEN 7-8
        str CITY 9-11
        str SHUBAN 12-15
        str KOUCHI 16-16
        str BUNKATU 17-18
        str DTKBN 19-19
        str SETORG 20-22
        str SETINREN 23-26
        str CHOURITSU 27-28
        str AZACODE 29-32
        str TANIKUCODE 33-37
        str ISKBN 38-38
        str SETAI 39-39
        str TATE 40-40
        str KAISU 41-41
        str JYUKYO 42-42
        str NOBETANI 43-43
        str NOBE 44-46
        str NOBEAREA 47-51
        str SETJIN 52-55
        str TUZUKI 56-57
        str SEN 58-58
        str GENGO 59-59
        str NEN 60-61
        str TUKI 62-62
        str NENREI 63-65
        str HAIGU 66-66
        str KOKUSEKI 67-67
        str ZENJ6 68-68
        str ZENJKEN 69-70
        str ZENJCITY 71-73
        str KYOIKU 74-74
        str KYOKBN 75-75
        str RODO8 76-76
        str JYU6A 77-77
        str JYUKEN 78-79
        str JYUCITY 80-82
        str CHII6 83-83
        str SANDF 84-84
        str SAND 85-86
        str SANC 87-88
        str SANSF 89-91
        str SANS 92-94
        str SHOD 95-96
        str SHOC 97-98
        str SHOSF 99-101
        str SHOS 102-104
    using "data";
#delimit cr
