/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/12 17:05:44
-----------------------------------------------------------------------------*/


capture label define NENTUKI 199010 "1990年10月" 
capture label values NENTUKI NENTUKI

capture label define KOUCHI 1 "一般の調査区" 2 "山岳・森林・原野地帯等の区域" 3 "都市的施設のある区域" 4 "社会施設・大きな病院のある区域" 5 "刑務所・拘置所のある区域" 6 "自衛隊区域" 7 "駐留軍区域" 8 "おおむね50人以上の単身者が居住している寄宿舎、寮等の区域" 9 "水面調査区" 
capture label values KOUCHI KOUCHI

capture label define CHOURITSU 1 "2千未満町村" 2 "2千以上5千未満町村" 3 "5千以上1万未満市町村" 4 "1万以上2万未満市町村" 5 "2万以上3万未満市町村、3万以上5万未満区" 6 "3万以上5万未満市町村、5万以上10万未満市" 8 "5万以上10万未満区" 9 "10万以上20万未満市区" 12 "20万以上30万未満市区" 16 "30万以上50万未満市区" 20 "50万以上市区" 
capture label values CHOURITSU CHOURITSU

capture label define ISKBN 1 "一般世帯" 2 "施設等の世帯" 
capture label values ISKBN ISKBN

capture label define SETAI 1 "一般の世帯" 2 "一人世帯(会社等の独身寮入居者を含む)" 3 "寮・寄宿舎" 4 "病院・療養所" 5 "社会施設" 7 "自衛隊営舎内居住" 8 "矯正施設入居者" 6 "その他" 
capture label values SETAI SETAI

capture label define TATE 1 "一戸建" 2 "長屋建て" 3 "共同住宅" 4 "その他" 
capture label values TATE TATE

capture label define KAISU 1 "1・2階" 2 "3~5階" 3 "6~10階" 4 "11階以上" 
capture label values KAISU KAISU

capture label define JYUKYO 1 "持ち家" 2 "公営借家" 3 "公団・公社借家" 4 "民営借家" 5 "給与住宅" 6 "間借り" 7 "会社等の独身寮・寄宿舎" 8 "その他" 
capture label values JYUKYO JYUKYO

capture label define NOBETANI 1 "平方メートル" 2 "坪" 
capture label values NOBETANI NOBETANI

capture label define TUZUKI 1 "世帯主又は代表者" 2 "世帯主の配偶者" 3 "子" 4 "子の配偶者" 5 "孫" 6 "父母" 7 "祖父母" 8 "兄弟姉妹" 9 "他の親族" 10 "家事使用人" 11 "営業使用人" 12 "その他" 
capture label values TUZUKI TUZUKI

capture label define SEN 1 "男" 2 "女" 
capture label values SEN SEN

capture label define GENGO 1 "明治" 2 "大正" 3 "昭和" 4 "平成" 
capture label values GENGO GENGO

capture label define TUKI 1 "1~3月" 2 "4~6月" 3 "7~9月" 4 "10~12月" 
capture label values TUKI TUKI

capture label define HAIGU 1 "未婚" 2 "有配偶" 3 "死別" 4 "離別" 
capture label values HAIGU HAIGU

capture label define KOKUSEKI 1 "日本" 2 "外国" 
capture label values KOKUSEKI KOKUSEKI

capture label define ZENJ6 1 "現住所" 2 "自市区町村内" 3 "自市内他区" 4 "県内他市区町村" 5 "他県" 6 "転入(国外から)" 
capture label values ZENJ6 ZENJ6

capture label define KYOIKU 1 "在学中" 2 "卒業" 3 "未就学" 
capture label values KYOIKU KYOIKU

capture label define KYOKBN 1 "小学・中学" 2 "高校・旧中" 3 "短大・高専" 4 "大学・大学院" 5 "幼稚園" 6 "保育園・保育所" 7 "乳児・その他" 
capture label values KYOKBN KYOKBN

capture label define RODO8 1 "主に仕事" 2 "家事のほか仕事" 3 "通学のかたわら仕事" 4 "休業者" 5 "完全失業者" 6 "家事" 7 "通学" 8 "その他" 
capture label values RODO8 RODO8

capture label define JYU6A 1 "従業も通学もしていない" 2 "自宅で従業" 3 "自宅外の自市区町村で従業・通学" 4 "自市内他区で従業・通学" 5 "県内他市区町村で従業・通学" 6 "他県で従業・通学" 
capture label values JYU6A JYU6A

capture label define CHII6 1 "雇用者" 2 "役員" 3 "雇人のある業主" 4 "雇人のない業主" 5 "家族従業者" 6 "家庭内職者" 
capture label values CHII6 CHII6

capture label define SAND 1 "農業" 2 "林業" 3 "漁業" 4 "鉱業" 5 "建設業" 6 "製造業" 7 "電気・ガス・熱供給・水道業" 8 "運輸・通信業" 9 "卸売・小売業,飲食店" 10 "金融・保険業" 11 "不動産業" 12 "サービス業" 13 "公務(他に分類されないもの)" 14 "分類不能の産業" 
capture label values SAND SAND

capture label define SHOD 1 "専門的・技術的職業従事者" 2 "管理的職業従事者" 3 "事務従事者" 4 "販売従事者" 5 "サービス職業従事者" 6 "保安職業従事者" 7 "農林漁業作業者" 8 "運輸・通信従事者" 9 "技能工、採掘・製造・建設作業者及び労務作業者" 10 "分類不能の職業" 
capture label values SHOD SHOD

