capture label variable var1 "調査年月"
capture label variable var2 "県"
capture label variable var3 "市区町村"
capture label variable var4 "調査区符号"
capture label variable var5 "日中の天気 １日目"
capture label variable var6 "日中の天気 ２日目"
capture label variable var7 "調査日 １日目"
capture label variable var8 "調査日 ２日目"
capture label variable var9 "曜日 １日目"
capture label variable var10 "曜日 ２日目"
capture label variable var11 "乗率　個人票１"
capture label variable var12 "生活時間票１日目　乗率"
capture label variable var13 "生活時間票２日目　乗率"
capture label variable var14 "世帯番号"
capture label variable var15 "住居の種類"
capture label variable var16 "居住室数"
capture label variable var17 "世帯の年間収入"
capture label variable var18 "世帯人数"
capture label variable var19 "ブランク"
capture label variable var20 "世帯番号"
capture label variable var21 "性"
capture label variable var22 "続柄"
capture label variable var23 "年令"
capture label variable var24 "配属関係"
capture label variable var25 "在学中の学校"
capture label variable var26 "最終卒業学校"
capture label variable var27 "ふだんの活動状態"
capture label variable var28 "仕事の内容"
capture label variable var29 "従業者数"
capture label variable var30 "就業時間"
capture label variable var31 "週休制度"
capture label variable var32 "ブランク"
capture label variable var33 "各種学校 （１）この１年にしたか"
capture label variable var34 "各種学校 （２）ふだんの程度"
capture label variable var35 "各種学校 （３）おもな目的"
capture label variable var36 "各種学校 （４）おもな内容"
capture label variable var37 "各種学校 〃"0""
capture label variable var38 "学級・講座など （１）この１年にしたか"
capture label variable var39 "学級・講座など （２）ふだんの程度"
capture label variable var40 "学級・講座など （３）おもな目的"
capture label variable var41 "学級・講座など （４）おもな内容"
capture label variable var42 "学級・講座など 〃"0""
capture label variable var43 "講演会など （１）この１年にしたか"
capture label variable var44 "講演会など （２）ふだんの程度"
capture label variable var45 "講演会など （３）おもな目的"
capture label variable var46 "講演会など （４）おもな内容"
capture label variable var47 "講演会など 〃"0""
capture label variable var48 "通信教育など （１）この１年にしたか"
capture label variable var49 "通信教育など （２）ふだんの程度"
capture label variable var50 "通信教育など （３）おもな目的"
capture label variable var51 "通信教育など （４）おもな内容"
capture label variable var52 "通信教育など 〃"0""
capture label variable var53 "ラジオ・テレビによる教育講座 （１）この１年にしたか"
capture label variable var54 "ラジオ・テレビによる教育講座 （２）ふだんの程度"
capture label variable var55 "ラジオ・テレビによる教育講座 （３）おもな目的"
capture label variable var56 "ラジオ・テレビによる教育講座 （４）おもな内容"
capture label variable var57 "ラジオ・テレビによる教育講座 〃"0""
capture label variable var58 "その他 （１）この１年にしたか"
capture label variable var59 "その他 （２）ふだんの程度"
capture label variable var60 "その他 （３）おもな目的"
capture label variable var61 "その他 （４）おもな内容"
capture label variable var62 "その他 〃"0""
capture label variable var63 "華道 （１）この１年にしたか"
capture label variable var64 "華道 （２）ふだんの程度"
capture label variable var65 "華道 （３）おもな相手"
capture label variable var66 "華道 （４）おもな使用場所"
capture label variable var67 "華道 （５）団体・サークルに加入しているか"
capture label variable var68 "茶道 （１）この１年にしたか"
capture label variable var69 "茶道 （２）ふだんの程度"
capture label variable var70 "茶道 （３）おもな相手"
capture label variable var71 "茶道 （４）おもな使用場所"
capture label variable var72 "茶道 （５）団体・サークルに加入しているか"
capture label variable var73 "スポーツ見物 （１）この１年にしたか"
capture label variable var74 "スポーツ見物 （２）ふだんの程度"
capture label variable var75 "スポーツ見物 （３）おもな相手"
capture label variable var76 "スポーツ見物 （４）おもな使用場所"
capture label variable var77 "スポーツ見物 （５）団体・サークルに加入しているか"
capture label variable var78 "映画鑑賞 （１）この１年にしたか"
capture label variable var79 "映画鑑賞 （２）ふだんの程度"
capture label variable var80 "映画鑑賞 （３）おもな相手"
capture label variable var81 "映画鑑賞 （４）おもな使用場所"
capture label variable var82 "映画鑑賞 （５）団体・サークルに加入しているか"
capture label variable var83 "楽器演奏 （１）この１年にしたか"
capture label variable var84 "楽器演奏 （２）ふだんの程度"
capture label variable var85 "楽器演奏 （３）おもな相手"
capture label variable var86 "楽器演奏 （４）おもな使用場所"
capture label variable var87 "楽器演奏 （５）団体・サークルに加入しているか"
capture label variable var88 "園芸庭いじり （１）この１年にしたか"
capture label variable var89 "園芸庭いじり （２）ふだんの程度"
capture label variable var90 "園芸庭いじり （３）おもな相手"
capture label variable var91 "園芸庭いじり （４）おもな使用場所"
capture label variable var92 "園芸庭いじり （５）団体・サークルに加入しているか"
capture label variable var93 "囲碁 （１）この１年にしたか"
capture label variable var94 "囲碁 （２）ふだんの程度"
capture label variable var95 "囲碁 （３）おもな相手"
capture label variable var96 "囲碁 （４）おもな使用場所"
capture label variable var97 "囲碁 （５）団体・サークルに加入しているか"
capture label variable var98 "競馬 （１）この１年にしたか"
capture label variable var99 "競馬 （２）ふだんの程度"
capture label variable var100 "競馬 "0""
capture label variable var101 "パチンコ （１）この１年にしたか"
capture label variable var102 "パチンコ （２）ふだんの程度"
capture label variable var103 "パチンコ "0""
capture label variable var104 "その他１ （１）この１年にしたか"
capture label variable var105 "その他１ （２）ふだんの程度"
capture label variable var106 "その他１ （３）おもな相手"
capture label variable var107 "その他１ （４）おもな使用場所"
capture label variable var108 "その他１ （５）団体・サークルに加入しているか"
capture label variable var109 "その他２ （１）この１年にしたか"
capture label variable var110 "その他２ （２）ふだんの程度"
capture label variable var111 "その他２ （３）おもな相手"
capture label variable var112 "その他２ （４）おもな使用場所"
capture label variable var113 "その他２ （５）団体・サークルに加入しているか"
capture label variable var114 "野球 （１）この１年にしたか"
capture label variable var115 "野球 （２）ふだんの程度"
capture label variable var116 "野球 （３）おもな相手"
capture label variable var117 "野球 （４）おもな使用場所"
capture label variable var118 "野球 （５）団体・サークルに加入しているか"
capture label variable var119 "バレーボール （１）この１年にしたか"
capture label variable var120 "バレーボール （２）ふだんの程度"
capture label variable var121 "バレーボール （３）おもな相手"
capture label variable var122 "バレーボール （４）おもな使用場所"
capture label variable var123 "バレーボール （５）団体・サークルに加入しているか"
capture label variable var124 "卓球 （１）この１年にしたか"
capture label variable var125 "卓球 （２）ふだんの程度"
capture label variable var126 "卓球 （３）おもな相手"
capture label variable var127 "卓球 （４）おもな使用場所"
capture label variable var128 "卓球 （５）団体・サークルに加入しているか"
capture label variable var129 "柔道 （１）この１年にしたか"
capture label variable var130 "柔道 （２）ふだんの程度"
capture label variable var131 "柔道 （３）おもな相手"
capture label variable var132 "柔道 （４）おもな使用場所"
capture label variable var133 "柔道 （５）団体・サークルに加入しているか"
capture label variable var134 "水泳 （１）この１年にしたか"
capture label variable var135 "水泳 （２）ふだんの程度"
capture label variable var136 "水泳 （３）おもな相手"
capture label variable var137 "水泳 （４）おもな使用場所"
capture label variable var138 "水泳 （５）団体・サークルに加入しているか"
capture label variable var139 "ハイキング （１）この１年にしたか"
capture label variable var140 "ハイキング （２）ふだんの程度"
capture label variable var141 "ハイキング （３）おもな相手"
capture label variable var142 "ハイキング （４）おもな使用場所"
capture label variable var143 "ハイキング （５）団体・サークルに加入しているか"
capture label variable var144 "ゴルフ （１）この１年にしたか"
capture label variable var145 "ゴルフ （２）ふだんの程度"
capture label variable var146 "ゴルフ （３）おもな相手"
capture label variable var147 "ゴルフ （４）おもな使用場所"
capture label variable var148 "ゴルフ （５）団体・サークルに加入しているか"
capture label variable var149 "ラジオ体操 （１）この１年にしたか"
capture label variable var150 "ラジオ体操 （２）ふだんの程度"
capture label variable var151 "ラジオ体操 （３）おもな相手"
capture label variable var152 "ラジオ体操 （４）おもな使用場所"
capture label variable var153 "ラジオ体操 （５）団体・サークルに加入しているか"
capture label variable var154 "運動としての散歩 （１）この１年にしたか"
capture label variable var155 "運動としての散歩 （２）ふだんの程度"
capture label variable var156 "運動としての散歩 （３）おもな相手"
capture label variable var157 "運動としての散歩 （４）おもな使用場所"
capture label variable var158 "運動としての散歩 （５）団体・サークルに加入しているか"
capture label variable var159 "つり （１）この１年にしたか"
capture label variable var160 "つり （２）ふだんの程度"
capture label variable var161 "つり （３）おもな相手"
capture label variable var162 "つり （４）おもな使用場所"
capture label variable var163 "つり （５）団体・サークルに加入しているか"
capture label variable var164 "その他１ （１）この１年にしたか"
capture label variable var165 "その他１ （２）ふだんの程度"
capture label variable var166 "その他１ （３）おもな相手"
capture label variable var167 "その他１ （４）おもな使用場所"
capture label variable var168 "その他１ （５）団体・サークルに加入しているか"
capture label variable var169 "その他２ （１）この１年にしたか"
capture label variable var170 "その他２ （２）ふだんの程度"
capture label variable var171 "その他２ （３）おもな相手"
capture label variable var172 "その他２ （４）おもな使用場所"
capture label variable var173 "その他２ （５）団体・サークルに加入しているか"
capture label variable var174 "全スポーツを通じて （１）この１年にしたか"
capture label variable var175 "全スポーツを通じて （２）ふだんの程度"
capture label variable var176 "全スポーツを通じて "0""
capture label variable var177 "A欄 趣味・娯楽　１"
capture label variable var178 "A欄 趣味・娯楽　２"
capture label variable var179 "A欄 スポーツ　１"
capture label variable var180 "A欄 スポーツ　２"
capture label variable var181 "A欄 ブランク"
capture label variable var182 "A欄 全項目不詳"
capture label variable var183 "社会奉仕 （１）この１年にしたか"
capture label variable var184 "社会奉仕 （２）ふだんの程度"
capture label variable var185 "社会奉仕 （３）おもな相手"
capture label variable var186 "社会奉仕 （４）団体・サークルに加入しているか"
capture label variable var187 "地域共同作業 （１）この１年にしたか"
capture label variable var188 "地域共同作業 （２）ふだんの程度"
capture label variable var189 "地域共同作業 "0""
capture label variable var190 "地域団体の世話 （１）この１年にしたか"
capture label variable var191 "地域団体の世話 （２）ふだんの程度"
capture label variable var192 "地域団体の世話 "0""
capture label variable var193 "PTAの世話 （１）この１年にしたか"
capture label variable var194 "PTAの世話 （２）ふだんの程度"
capture label variable var195 "PTAの世話 "0""
capture label variable var196 "その他の団体の世話 （１）この１年にしたか"
capture label variable var197 "その他の団体の世話 （２）ふだんの程度"
capture label variable var198 "その他の団体の世話 "0""
capture label variable var199 "公的な活動 （１）この１年にしたか"
capture label variable var200 "公的な活動 （２）ふだんの程度"
capture label variable var201 "公的な活動 "0""
capture label variable var202 "その他 （１）この１年にしたか"
capture label variable var203 "その他 （２）ふだんの程度"
capture label variable var204 "その他 "0""
capture label variable var205 "家族 （１）この１年にしたか"
capture label variable var206 "家族 （２）この一年の旅行した回数"
capture label variable var207 "職場の人 （１）この１年にしたか"
capture label variable var208 "職場の人 （２）この一年の旅行した回数"
capture label variable var209 "学校の人 （１）この１年にしたか"
capture label variable var210 "学校の人 （２）この一年の旅行した回数"
capture label variable var211 "地域の人 （１）この１年にしたか"
capture label variable var212 "地域の人 （２）この一年の旅行した回数"
capture label variable var213 "友人、知人 （１）この１年にしたか"
capture label variable var214 "友人、知人 （２）この一年の旅行した回数"
capture label variable var215 "その他の人 （１）この１年にしたか"
capture label variable var216 "その他の人 （２）この一年の旅行した回数"
capture label variable var217 "ひとりで （１）この１年にしたか"
capture label variable var218 "ひとりで （２）この一年の旅行した回数"
capture label variable var219 "その他の旅行 （１）この１年にしたか"
capture label variable var220 "その他の旅行 （２）この一年の旅行した回数"
capture label variable var221 "観光・リクリエーション 一年の合計旅行日数"
capture label variable var222 "その他の旅行 一年の合計旅行日数"
capture label variable var223 "国民宿舎 利用したか"
capture label variable var224 "ユースホステル 利用したか"
capture label variable var225 "診療所 利用したか"
capture label variable var226 "旅館ホテル 利用したか"
capture label variable var227 "民宿 利用したか"
capture label variable var228 "その他 利用したか"
capture label variable var229 "公民館公営 （１）一年に利用したか"
capture label variable var230 "公民館公営 （２）利用の程度"
capture label variable var231 "図書館公営 （１）一年に利用したか"
capture label variable var232 "図書館公営 （２）利用の程度"
capture label variable var233 "美術館公営 （１）一年に利用したか"
capture label variable var234 "美術館公営 （２）利用の程度"
capture label variable var235 "美術館民営 （１）一年に利用したか"
capture label variable var236 "美術館民営 （２）利用の程度"
capture label variable var237 "青年の家公営 （１）一年に利用したか"
capture label variable var238 "青年の家公営 （２）利用の程度"
capture label variable var239 "病院 （１）この一年の入院・診療・治療の有無"
capture label variable var240 "病院 （２）一年間の入院した日数"
capture label variable var241 "病院 （３）入院を除いた診療・治療した日数"
capture label variable var242 "一般の診療所 （１）この一年の入院・診療・治療の有無"
capture label variable var243 "一般の診療所 （２）一年間の入院した日数"
capture label variable var244 "一般の診療所 （３）入院を除いた診療・治療した日数"
capture label variable var245 "職場の診療所 （１）この一年の入院・診療・治療の有無"
capture label variable var246 "職場の診療所 "0""
capture label variable var247 "職場の診療所 （３）入院を除いた診療・治療した日数"
capture label variable var248 "歯科診療所 （１）この一年の入院・診療・治療の有無"
capture label variable var249 "歯科診療所 （２）一年間の入院した日数"
capture label variable var250 "歯科診療所 （３）入院を除いた診療・治療した日数"
capture label variable var251 "あんま・はり （１）この一年の入院・診療・治療の有無"
capture label variable var252 "あんま・はり "0""
capture label variable var253 "あんま・はり （３）入院を除いた診療・治療した日数"
capture label variable var254 "あんま・はり ブランク"
capture label variable var255 "生活時間　１日目 旅行・診療等"
capture label variable var256 "生活時間　１日目 1 睡眠"
capture label variable var257 "生活時間　１日目 2 身の回りの用事"
capture label variable var258 "生活時間　１日目 3 食事"
capture label variable var259 "生活時間　１日目 4 家事・育児"
capture label variable var260 "生活時間　１日目 5 買物"
capture label variable var261 "生活時間　１日目 6 移動（通勤・通学）"
capture label variable var262 "生活時間　１日目 7 移動（その他の移動）"
capture label variable var263 "生活時間　１日目 8 仕事"
capture label variable var264 "生活時間　１日目 9 勉強・研究"
capture label variable var265 "生活時間　１日目 10 趣味・娯楽"
capture label variable var266 "生活時間　１日目 11 スポーツ"
capture label variable var267 "生活時間　１日目 12 交際"
capture label variable var268 "生活時間　１日目 13 奉仕的な活動"
capture label variable var269 "生活時間　１日目 14 ラジオ・テレビ・新聞・雑誌"
capture label variable var270 "生活時間　１日目 15 休養・くつろぎ"
capture label variable var271 "生活時間　１日目 16 受診・診療"
capture label variable var272 "生活時間　１日目 17 その他の行動"
capture label variable var273 "生活時間　２日目 旅行・診療等"
capture label variable var274 "生活時間　２日目 1 睡眠"
capture label variable var275 "生活時間　２日目 2 身の回りの用事"
capture label variable var276 "生活時間　２日目 3 食事"
capture label variable var277 "生活時間　２日目 4 家事・育児"
capture label variable var278 "生活時間　２日目 5 買物"
capture label variable var279 "生活時間　２日目 6 移動（通勤・通学）"
capture label variable var280 "生活時間　２日目 7 移動（その他の移動）"
capture label variable var281 "生活時間　２日目 8 仕事"
capture label variable var282 "生活時間　２日目 9 勉強・研究"
capture label variable var283 "生活時間　２日目 10 趣味・娯楽"
capture label variable var284 "生活時間　２日目 11 スポーツ"
capture label variable var285 "生活時間　２日目 12 交際"
capture label variable var286 "生活時間　２日目 13 奉仕的な活動"
capture label variable var287 "生活時間　２日目 14 ラジオ・テレビ・新聞・雑誌"
capture label variable var288 "生活時間　２日目 15 休養・くつろぎ"
capture label variable var289 "生活時間　２日目 16 受診・診療"
capture label variable var290 "生活時間　２日目 17 その他の行動"
capture label variable var291 "都市階級符号"
