capture label variable var292 "調査年月"
capture label variable var293 "県"
capture label variable var294 "市区町村"
capture label variable var295 "調査区符号"
capture label variable var296 "日中の天気 １日目"
capture label variable var297 "日中の天気 ２日目"
capture label variable var298 "ブランク"
capture label variable var299 "乗率個人票Ⅰ"
capture label variable var300 "世帯番号"
capture label variable var301 "住宅の種類"
capture label variable var302 "居住室数"
capture label variable var303 "世帯の年間収入"
capture label variable var304 "世帯人員"
capture label variable var305 "15才未満人員"
capture label variable var306 "（1人目）性"
capture label variable var307 "（1人目）続柄"
capture label variable var308 "（1人目）年令"
capture label variable var309 "（1人目）在学状況"
capture label variable var310 "（1人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var311 "（1人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var312 "（1人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var313 "（1人目）塾・家庭教師・けいこごと その他"
capture label variable var314 "（1人目）塾・家庭教師・けいこごと 学習"
capture label variable var315 "（1人目）塾・家庭教師・けいこごと 珠算"
capture label variable var316 "（1人目）塾・家庭教師・けいこごと 習字"
capture label variable var317 "（1人目）塾・家庭教師・けいこごと 外国語"
capture label variable var318 "（1人目）塾・家庭教師・けいこごと 音楽"
capture label variable var319 "（1人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var320 "（1人目）塾・家庭教師・けいこごと その他"
capture label variable var321 "（2人目）性"
capture label variable var322 "（2人目）続柄"
capture label variable var323 "（2人目）年令"
capture label variable var324 "（2人目）在学状況"
capture label variable var325 "（2人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var326 "（2人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var327 "（2人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var328 "（2人目）塾・家庭教師・けいこごと その他"
capture label variable var329 "（2人目）塾・家庭教師・けいこごと 学習"
capture label variable var330 "（2人目）塾・家庭教師・けいこごと 珠算"
capture label variable var331 "（2人目）塾・家庭教師・けいこごと 習字"
capture label variable var332 "（2人目）塾・家庭教師・けいこごと 外国語"
capture label variable var333 "（2人目）塾・家庭教師・けいこごと 音楽"
capture label variable var334 "（2人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var335 "（2人目）塾・家庭教師・けいこごと その他"
capture label variable var336 "（3人目）性"
capture label variable var337 "（3人目）続柄"
capture label variable var338 "（3人目）年令"
capture label variable var339 "（3人目）在学状況"
capture label variable var340 "（3人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var341 "（3人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var342 "（3人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var343 "（3人目）塾・家庭教師・けいこごと その他"
capture label variable var344 "（3人目）塾・家庭教師・けいこごと 学習"
capture label variable var345 "（3人目）塾・家庭教師・けいこごと 珠算"
capture label variable var346 "（3人目）塾・家庭教師・けいこごと 習字"
capture label variable var347 "（3人目）塾・家庭教師・けいこごと 外国語"
capture label variable var348 "（3人目）塾・家庭教師・けいこごと 音楽"
capture label variable var349 "（3人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var350 "（3人目）塾・家庭教師・けいこごと その他"
capture label variable var351 "（4人目）性"
capture label variable var352 "（4人目）続柄"
capture label variable var353 "（4人目）年令"
capture label variable var354 "（4人目）在学状況"
capture label variable var355 "（4人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var356 "（4人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var357 "（4人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var358 "（4人目）塾・家庭教師・けいこごと その他"
capture label variable var359 "（4人目）塾・家庭教師・けいこごと 学習"
capture label variable var360 "（4人目）塾・家庭教師・けいこごと 珠算"
capture label variable var361 "（4人目）塾・家庭教師・けいこごと 習字"
capture label variable var362 "（4人目）塾・家庭教師・けいこごと 外国語"
capture label variable var363 "（4人目）塾・家庭教師・けいこごと 音楽"
capture label variable var364 "（4人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var365 "（4人目）塾・家庭教師・けいこごと その他"
capture label variable var366 "（5人目）性"
capture label variable var367 "（5人目）続柄"
capture label variable var368 "（5人目）年令"
capture label variable var369 "（5人目）在学状況"
capture label variable var370 "（5人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var371 "（5人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var372 "（5人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var373 "（5人目）塾・家庭教師・けいこごと その他"
capture label variable var374 "（5人目）塾・家庭教師・けいこごと 学習"
capture label variable var375 "（5人目）塾・家庭教師・けいこごと 珠算"
capture label variable var376 "（5人目）塾・家庭教師・けいこごと 習字"
capture label variable var377 "（5人目）塾・家庭教師・けいこごと 外国語"
capture label variable var378 "（5人目）塾・家庭教師・けいこごと 音楽"
capture label variable var379 "（5人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var380 "（5人目）塾・家庭教師・けいこごと その他"
capture label variable var381 "（6人目）性"
capture label variable var382 "（6人目）続柄"
capture label variable var383 "（6人目）年令"
capture label variable var384 "（6人目）在学状況"
capture label variable var385 "（6人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var386 "（6人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var387 "（6人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var388 "（6人目）塾・家庭教師・けいこごと その他"
capture label variable var389 "（6人目）塾・家庭教師・けいこごと 学習"
capture label variable var390 "（6人目）塾・家庭教師・けいこごと 珠算"
capture label variable var391 "（6人目）塾・家庭教師・けいこごと 習字"
capture label variable var392 "（6人目）塾・家庭教師・けいこごと 外国語"
capture label variable var393 "（6人目）塾・家庭教師・けいこごと 音楽"
capture label variable var394 "（6人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var395 "（6人目）塾・家庭教師・けいこごと その他"
capture label variable var396 "（7人目）性"
capture label variable var397 "（7人目）続柄"
capture label variable var398 "（7人目）年令"
capture label variable var399 "（7人目）在学状況"
capture label variable var400 "（7人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var401 "（7人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var402 "（7人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var403 "（7人目）塾・家庭教師・けいこごと その他"
capture label variable var404 "（7人目）塾・家庭教師・けいこごと 学習"
capture label variable var405 "（7人目）塾・家庭教師・けいこごと 珠算"
capture label variable var406 "（7人目）塾・家庭教師・けいこごと 習字"
capture label variable var407 "（7人目）塾・家庭教師・けいこごと 外国語"
capture label variable var408 "（7人目）塾・家庭教師・けいこごと 音楽"
capture label variable var409 "（7人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var410 "（7人目）塾・家庭教師・けいこごと その他"
capture label variable var411 "（8人目）性"
capture label variable var412 "（8人目）続柄"
capture label variable var413 "（8人目）年令"
capture label variable var414 "（8人目）在学状況"
capture label variable var415 "（8人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var416 "（8人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var417 "（8人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var418 "（8人目）塾・家庭教師・けいこごと その他"
capture label variable var419 "（8人目）塾・家庭教師・けいこごと 学習"
capture label variable var420 "（8人目）塾・家庭教師・けいこごと 珠算"
capture label variable var421 "（8人目）塾・家庭教師・けいこごと 習字"
capture label variable var422 "（8人目）塾・家庭教師・けいこごと 外国語"
capture label variable var423 "（8人目）塾・家庭教師・けいこごと 音楽"
capture label variable var424 "（8人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var425 "（8人目）塾・家庭教師・けいこごと その他"
capture label variable var426 "（9人目）性"
capture label variable var427 "（9人目）続柄"
capture label variable var428 "（9人目）年令"
capture label variable var429 "（9人目）在学状況"
capture label variable var430 "（9人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var431 "（9人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var432 "（9人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var433 "（9人目）塾・家庭教師・けいこごと その他"
capture label variable var434 "（9人目）塾・家庭教師・けいこごと 学習"
capture label variable var435 "（9人目）塾・家庭教師・けいこごと 珠算"
capture label variable var436 "（9人目）塾・家庭教師・けいこごと 習字"
capture label variable var437 "（9人目）塾・家庭教師・けいこごと 外国語"
capture label variable var438 "（9人目）塾・家庭教師・けいこごと 音楽"
capture label variable var439 "（9人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var440 "（9人目）塾・家庭教師・けいこごと その他"
capture label variable var441 "（10人目）性"
capture label variable var442 "（10人目）続柄"
capture label variable var443 "（10人目）年令"
capture label variable var444 "（10人目）在学状況"
capture label variable var445 "（10人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var446 "（10人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var447 "（10人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var448 "（10人目）塾・家庭教師・けいこごと その他"
capture label variable var449 "（10人目）塾・家庭教師・けいこごと 学習"
capture label variable var450 "（10人目）塾・家庭教師・けいこごと 珠算"
capture label variable var451 "（10人目）塾・家庭教師・けいこごと 習字"
capture label variable var452 "（10人目）塾・家庭教師・けいこごと 外国語"
capture label variable var453 "（10人目）塾・家庭教師・けいこごと 音楽"
capture label variable var454 "（10人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var455 "（10人目）塾・家庭教師・けいこごと その他"
capture label variable var456 "（11人目）性"
capture label variable var457 "（11人目）続柄"
capture label variable var458 "（11人目）年令"
capture label variable var459 "（11人目）在学状況"
capture label variable var460 "（11人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var461 "（11人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var462 "（11人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var463 "（11人目）塾・家庭教師・けいこごと その他"
capture label variable var464 "（11人目）塾・家庭教師・けいこごと 学習"
capture label variable var465 "（11人目）塾・家庭教師・けいこごと 珠算"
capture label variable var466 "（11人目）塾・家庭教師・けいこごと 習字"
capture label variable var467 "（11人目）塾・家庭教師・けいこごと 外国語"
capture label variable var468 "（11人目）塾・家庭教師・けいこごと 音楽"
capture label variable var469 "（11人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var470 "（11人目）塾・家庭教師・けいこごと その他"
capture label variable var471 "（12人目）性"
capture label variable var472 "（12人目）続柄"
capture label variable var473 "（12人目）年令"
capture label variable var474 "（12人目）在学状況"
capture label variable var475 "（12人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var476 "（12人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var477 "（12人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var478 "（12人目）塾・家庭教師・けいこごと その他"
capture label variable var479 "（12人目）塾・家庭教師・けいこごと 学習"
capture label variable var480 "（12人目）塾・家庭教師・けいこごと 珠算"
capture label variable var481 "（12人目）塾・家庭教師・けいこごと 習字"
capture label variable var482 "（12人目）塾・家庭教師・けいこごと 外国語"
capture label variable var483 "（12人目）塾・家庭教師・けいこごと 音楽"
capture label variable var484 "（12人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var485 "（12人目）塾・家庭教師・けいこごと その他"
capture label variable var486 "（13人目）性"
capture label variable var487 "（13人目）続柄"
capture label variable var488 "（13人目）年令"
capture label variable var489 "（13人目）在学状況"
capture label variable var490 "（13人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var491 "（13人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var492 "（13人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var493 "（13人目）塾・家庭教師・けいこごと その他"
capture label variable var494 "（13人目）塾・家庭教師・けいこごと 学習"
capture label variable var495 "（13人目）塾・家庭教師・けいこごと 珠算"
capture label variable var496 "（13人目）塾・家庭教師・けいこごと 習字"
capture label variable var497 "（13人目）塾・家庭教師・けいこごと 外国語"
capture label variable var498 "（13人目）塾・家庭教師・けいこごと 音楽"
capture label variable var499 "（13人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var500 "（13人目）塾・家庭教師・けいこごと その他"
capture label variable var501 "（14人目）性"
capture label variable var502 "（14人目）続柄"
capture label variable var503 "（14人目）年令"
capture label variable var504 "（14人目）在学状況"
capture label variable var505 "（14人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var506 "（14人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var507 "（14人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var508 "（14人目）塾・家庭教師・けいこごと その他"
capture label variable var509 "（14人目）塾・家庭教師・けいこごと 学習"
capture label variable var510 "（14人目）塾・家庭教師・けいこごと 珠算"
capture label variable var511 "（14人目）塾・家庭教師・けいこごと 習字"
capture label variable var512 "（14人目）塾・家庭教師・けいこごと 外国語"
capture label variable var513 "（14人目）塾・家庭教師・けいこごと 音楽"
capture label variable var514 "（14人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var515 "（14人目）塾・家庭教師・けいこごと その他"
capture label variable var516 "（15人目）性"
capture label variable var517 "（15人目）続柄"
capture label variable var518 "（15人目）年令"
capture label variable var519 "（15人目）在学状況"
capture label variable var520 "（15人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var521 "（15人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var522 "（15人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var523 "（15人目）塾・家庭教師・けいこごと その他"
capture label variable var524 "（15人目）塾・家庭教師・けいこごと 学習"
capture label variable var525 "（15人目）塾・家庭教師・けいこごと 珠算"
capture label variable var526 "（15人目）塾・家庭教師・けいこごと 習字"
capture label variable var527 "（15人目）塾・家庭教師・けいこごと 外国語"
capture label variable var528 "（15人目）塾・家庭教師・けいこごと 音楽"
capture label variable var529 "（15人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var530 "（15人目）塾・家庭教師・けいこごと その他"
capture label variable var531 "（16人目）性"
capture label variable var532 "（16人目）続柄"
capture label variable var533 "（16人目）年令"
capture label variable var534 "（16人目）在学状況"
capture label variable var535 "（16人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var536 "（16人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var537 "（16人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var538 "（16人目）塾・家庭教師・けいこごと その他"
capture label variable var539 "（16人目）塾・家庭教師・けいこごと 学習"
capture label variable var540 "（16人目）塾・家庭教師・けいこごと 珠算"
capture label variable var541 "（16人目）塾・家庭教師・けいこごと 習字"
capture label variable var542 "（16人目）塾・家庭教師・けいこごと 外国語"
capture label variable var543 "（16人目）塾・家庭教師・けいこごと 音楽"
capture label variable var544 "（16人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var545 "（16人目）塾・家庭教師・けいこごと その他"
capture label variable var546 "（17人目）性"
capture label variable var547 "（17人目）続柄"
capture label variable var548 "（17人目）年令"
capture label variable var549 "（17人目）在学状況"
capture label variable var550 "（17人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var551 "（17人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var552 "（17人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var553 "（17人目）塾・家庭教師・けいこごと その他"
capture label variable var554 "（17人目）塾・家庭教師・けいこごと 学習"
capture label variable var555 "（17人目）塾・家庭教師・けいこごと 珠算"
capture label variable var556 "（17人目）塾・家庭教師・けいこごと 習字"
capture label variable var557 "（17人目）塾・家庭教師・けいこごと 外国語"
capture label variable var558 "（17人目）塾・家庭教師・けいこごと 音楽"
capture label variable var559 "（17人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var560 "（17人目）塾・家庭教師・けいこごと その他"
capture label variable var561 "（18人目）性"
capture label variable var562 "（18人目）続柄"
capture label variable var563 "（18人目）年令"
capture label variable var564 "（18人目）在学状況"
capture label variable var565 "（18人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var566 "（18人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var567 "（18人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var568 "（18人目）塾・家庭教師・けいこごと その他"
capture label variable var569 "（18人目）塾・家庭教師・けいこごと 学習"
capture label variable var570 "（18人目）塾・家庭教師・けいこごと 珠算"
capture label variable var571 "（18人目）塾・家庭教師・けいこごと 習字"
capture label variable var572 "（18人目）塾・家庭教師・けいこごと 外国語"
capture label variable var573 "（18人目）塾・家庭教師・けいこごと 音楽"
capture label variable var574 "（18人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var575 "（18人目）塾・家庭教師・けいこごと その他"
capture label variable var576 "（19人目）性"
capture label variable var577 "（19人目）続柄"
capture label variable var578 "（19人目）年令"
capture label variable var579 "（19人目）在学状況"
capture label variable var580 "（19人目）塾・家庭教師・けいこごと 習っていない"
capture label variable var581 "（19人目）塾・家庭教師・けいこごと 塾・教室"
capture label variable var582 "（19人目）塾・家庭教師・けいこごと 個人教師"
capture label variable var583 "（19人目）塾・家庭教師・けいこごと その他"
capture label variable var584 "（19人目）塾・家庭教師・けいこごと 学習"
capture label variable var585 "（19人目）塾・家庭教師・けいこごと 珠算"
capture label variable var586 "（19人目）塾・家庭教師・けいこごと 習字"
capture label variable var587 "（19人目）塾・家庭教師・けいこごと 外国語"
capture label variable var588 "（19人目）塾・家庭教師・けいこごと 音楽"
capture label variable var589 "（19人目）塾・家庭教師・けいこごと スポーツ"
capture label variable var590 "（19人目）塾・家庭教師・けいこごと その他"
capture label variable var591 "都市階級符号"
