/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（入職者票）h15.xlsx
    Date: 2019/02/27 01:44:09
----------------------------------------------------------------------*/


capture label define var2 2003 "" 
capture label values var2 var2

capture label define var3 1 "上半期" 7 "下半期" 
capture label values var3 var3

capture label define var5 1 "県番号:01" 2 "県番号:02~07" 3 "県番号:08~10,19,20" 4 "県番号:11~14" 5 "県番号:15~18" 6 "県番号:21~24" 7 "県番号:25~30" 8 "県番号:31~35" 9 "県番号:36~39" 10 "県番号:40~47" 
capture label values var5 var5

capture label define var6 1 "県番号:01" 2 "県番号:02~07" 3 "県番号:08~10,19,20" 4 "県番号:11~14" 5 "県番号:15~18" 6 "県番号:21~24" 7 "県番号:25,29,30" 8 "県番号:26~28" 9 "県番号:31,32" 10 "県番号:33~35" 11 "県番号:36~39" 12 "県番号:40~42,44" 13 "県番号:43,45~47" 
capture label values var6 var6

capture label define var12 1 "" 2 "" 3 "" 4 "" 
capture label values var12 var12

capture label define var13 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 
capture label values var13 var13

capture label define var15 1 "" 2 "" 3 "" 4 "" 
capture label values var15 var15

capture label define var16 1 "男" 2 "女" 
capture label values var16 var16

capture label define var17 1 "一般労働者" 2 "パートタイム労働者" 
capture label values var17 var17

capture label define var19 1 "" 2 "" 
capture label values var19 var19

capture label define var20 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 10 "" 11 "" 
capture label values var20 var20

capture label define var22 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 
capture label values var22 var22

capture label define var25 1 "" 2 "" 
capture label values var25 var25

capture label define var26 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 
capture label values var26 var26

capture label define var28 1 "" 2 "" 
capture label values var28 var28

capture label define var29 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 
capture label values var29 var29

capture label define var31 1 "" 2 "" 3 "" 
capture label values var31 var31

capture label define var39 1 "" 2 "" 
capture label values var39 var39

capture label define var41 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 
capture label values var41 var41

capture label define var42 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 
capture label values var42 var42

capture label define var44 1 "" 2 "" 3 "" 
capture label values var44 var44

capture label define var48 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 
capture label values var48 var48

capture label define var49 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 
capture label values var49 var49

capture label define var50 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 
capture label values var50 var50

capture label define var53 10 "" 11 "" 12 "" 13 "" 14 "" 15 "" 16 "" 17 "" 
capture label values var53 var53

capture label define var56 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 
capture label values var56 var56

