/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 
    Date: 2019/02/25 04:50:16
----------------------------------------------------------------------*/


global DoFilePathTemp = "D:/GitHub/MicroDataCleaning/do-file/賃金構造基本統計調査/個人票"
global DataFilePathTemp = ""

tempvar dataclear
set more off

run "${DoFilePathTemp}/h17/h17_const.do"
run "${DoFilePathTemp}/h17/h17_var.do"
run "${DoFilePathTemp}/h17/h17_val.do"
run "${DoFilePathTemp}/h17/h17_validate.do"
save "${DataFilePathTemp}/h17_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h18/h18_const.do"
run "${DoFilePathTemp}/h18/h18_var.do"
run "${DoFilePathTemp}/h18/h18_val.do"
run "${DoFilePathTemp}/h18/h18_validate.do"
save "${DataFilePathTemp}/h18_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h19/h19_const.do"
run "${DoFilePathTemp}/h19/h19_var.do"
run "${DoFilePathTemp}/h19/h19_val.do"
run "${DoFilePathTemp}/h19/h19_validate.do"
save "${DataFilePathTemp}/h19_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h20/h20_const.do"
run "${DoFilePathTemp}/h20/h20_var.do"
run "${DoFilePathTemp}/h20/h20_val.do"
run "${DoFilePathTemp}/h20/h20_validate.do"
save "${DataFilePathTemp}/h20_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h21/h21_const.do"
run "${DoFilePathTemp}/h21/h21_var.do"
run "${DoFilePathTemp}/h21/h21_val.do"
run "${DoFilePathTemp}/h21/h21_validate.do"
save "${DataFilePathTemp}/h21_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h22/h22_const.do"
run "${DoFilePathTemp}/h22/h22_var.do"
run "${DoFilePathTemp}/h22/h22_val.do"
run "${DoFilePathTemp}/h22/h22_validate.do"
save "${DataFilePathTemp}/h22_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h23/h23_const.do"
run "${DoFilePathTemp}/h23/h23_var.do"
run "${DoFilePathTemp}/h23/h23_val.do"
run "${DoFilePathTemp}/h23/h23_validate.do"
save "${DataFilePathTemp}/h23_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h24/h24_const.do"
run "${DoFilePathTemp}/h24/h24_var.do"
run "${DoFilePathTemp}/h24/h24_val.do"
run "${DoFilePathTemp}/h24/h24_validate.do"
save "${DataFilePathTemp}/h24_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h25/h25_const.do"
run "${DoFilePathTemp}/h25/h25_var.do"
run "${DoFilePathTemp}/h25/h25_val.do"
run "${DoFilePathTemp}/h25/h25_validate.do"
save "${DataFilePathTemp}/h25_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h26/h26_const.do"
run "${DoFilePathTemp}/h26/h26_var.do"
run "${DoFilePathTemp}/h26/h26_val.do"
run "${DoFilePathTemp}/h26/h26_validate.do"
save "${DataFilePathTemp}/h26_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h27/h27_const.do"
run "${DoFilePathTemp}/h27/h27_var.do"
run "${DoFilePathTemp}/h27/h27_val.do"
run "${DoFilePathTemp}/h27/h27_validate.do"
save "${DataFilePathTemp}/h27_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h28/h28_const.do"
run "${DoFilePathTemp}/h28/h28_var.do"
run "${DoFilePathTemp}/h28/h28_val.do"
run "${DoFilePathTemp}/h28/h28_validate.do"
save "${DataFilePathTemp}/h28_k-chin.dta", replace

clear


run "${DoFilePathTemp}/h29/h29_const.do"
run "${DoFilePathTemp}/h29/h29_var.do"
run "${DoFilePathTemp}/h29/h29_val.do"
run "${DoFilePathTemp}/h29/h29_validate.do"
save "${DataFilePathTemp}/h29_k-chin.dta", replace

clear


append using ///
    "${DataFilePathTemp}/h17_k-chin.dta" ///
    "${DataFilePathTemp}/h18_k-chin.dta" ///
    "${DataFilePathTemp}/h19_k-chin.dta" ///
    "${DataFilePathTemp}/h20_k-chin.dta" ///
    "${DataFilePathTemp}/h21_k-chin.dta" ///
    "${DataFilePathTemp}/h22_k-chin.dta" ///
    "${DataFilePathTemp}/h23_k-chin.dta" ///
    "${DataFilePathTemp}/h24_k-chin.dta" ///
    "${DataFilePathTemp}/h25_k-chin.dta" ///
    "${DataFilePathTemp}/h26_k-chin.dta" ///
    "${DataFilePathTemp}/h27_k-chin.dta" ///
    "${DataFilePathTemp}/h28_k-chin.dta" ///
    "${DataFilePathTemp}/h29_k-chin.dta" ///
    , gen(`data')

run "${DoFilePathTemp}/rename.do"

macro drop DoFilePathTemp
macro drop DataFilePathTemp
