/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成17～29年_賃金構造基本統計調査_事業所票（初任給）.xls
    Date: 2019/03/03 16:49:03
----------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str var1 1-4
        str var3 6-7
        str var4 8-12
        str var5 13-13
        str var7 15-17
        str var8 18-21
        str var10 24-27
        str var12 29-31
        str var13 32-32
        str var14 33-33
        str var15 34-34
        str var18 39-41
        str var19 42-42
        str var20 43-43
        str var21 44-44
        str var22 45-48
        str var23 49-50
        str var24 51-52
        str var26 54-54
        str var27 55-55
        str var28 56-56
        str var30 58-62
        str var31 63-67
        str var32 68-72
        str var33 73-77
        str var34 78-82
        str var35 83-83
        str var36 84-85
        str var37 86-86
        str var38 87-88
        str var39 89-89
        str var41 91-94
        str var42 95-98
        str var43 99-102
        str var44 103-106
        str var45 107-110
        str var46 111-114
        str var47 115-118
        str var48 119-122
        str var49 123-126
        str var50 127-130
        str var51 131-134
        str var52 135-138
        str var53 139-142
        str var54 143-146
        str var55 147-150
        str var56 151-154
        str var57 155-158
        str var58 159-162
        str var59 163-166
        str var60 167-170
    using "/media/HD-LXU3/WageCensus_EmploymentTrend/raw/調査票情報/賃金構造基本統計調査/h01-29_j-chin/h20_j-chin.txt";
#delimit cr
