/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成17～29年_賃金構造基本統計調査_事業所票（初任給）.xls
    Date: 2019/02/25 04:50:17
----------------------------------------------------------------------*/


#delimit ;
    quietly infix
        var1 1-4
        var2 6-7
        var3 8-12
        var4 13-13
        var5 15-17
        var6 18-21
        var7 24-27
        var8 29-31
        var9 32-32
        var10 33-33
        var11 34-34
        var13 39-41
        var14 42-42
        var15 43-43
        var16 44-44
        var17 45-48
        var18 49-50
        var19 51-52
        var20 54-54
        var21 55-55
        var22 56-56
        var24 58-62
        var25 63-67
        var26 68-72
        var27 73-77
        var28 78-82
        var29 83-83
        var30 84-85
        var31 86-86
        var32 87-88
        var33 89-89
        var34 91-94
        var35 95-98
        var36 99-102
        var37 103-106
        var38 107-110
        var39 111-114
        var40 115-118
        var41 119-122
        var42 123-126
        var43 127-130
        var44 131-134
        var45 135-138
        var46 139-142
        var47 143-146
        var48 147-150
        var49 151-154
        var50 155-158
        var51 159-162
        var52 163-166
        var53 167-170
    using "/media/HD-LXU3/WageCensus_EmploymentTrend/raw/調査票情報/賃金構造基本統計調査/h01-29_j-chin/h20_j-chin.txt";
#delimit cr
