/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成17～29年_賃金構造基本統計調査_事業所票（初任給）.xls
    Date: 2019/02/25 04:50:17
----------------------------------------------------------------------*/


capture assert inlist(var1, 2008, .)
if _rc!=0 {
    display as error "WARNING: {bf:var1} (調査年) may have invalid values (Check layout sheet)"
}
count if var1==.
if r(N)==_N {
    display as error "Only missing value: {bf:var1} (調査年)"
}

capture assert inlist(var9, 0, 2, 4, 6, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var9} (事業所規模番号) may have invalid values (Check layout sheet)"
}
count if var9==.
if r(N)==_N {
    display as error "Only missing value: {bf:var9} (事業所規模番号)"
}

capture assert inlist(var10, 1, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var10} (臨時雇用者規模番号) may have invalid values (Check layout sheet)"
}
count if var10==.
if r(N)==_N {
    display as error "Only missing value: {bf:var10} (臨時雇用者規模番号)"
}

capture assert inlist(var11, 1, 3, 5, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var11} (企業規模番号) may have invalid values (Check layout sheet)"
}
count if var11==.
if r(N)==_N {
    display as error "Only missing value: {bf:var11} (企業規模番号)"
}

capture assert inlist(var14, 0, 2, 4, 6, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var14} (事業所規模番号) may have invalid values (Check layout sheet)"
}
count if var14==.
if r(N)==_N {
    display as error "Only missing value: {bf:var14} (事業所規模番号)"
}

capture assert inlist(var15, 1, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var15} (臨時雇用者規模番号) may have invalid values (Check layout sheet)"
}
count if var15==.
if r(N)==_N {
    display as error "Only missing value: {bf:var15} (臨時雇用者規模番号)"
}

capture assert inlist(var16, 1, 3, 5, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var16} (企業規模番号) may have invalid values (Check layout sheet)"
}
count if var16==.
if r(N)==_N {
    display as error "Only missing value: {bf:var16} (企業規模番号)"
}

capture assert inlist(var20, 1, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var20} (本・支区分) may have invalid values (Check layout sheet)"
}
count if var20==.
if r(N)==_N {
    display as error "Only missing value: {bf:var20} (本・支区分)"
}

capture assert inlist(var21, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:var21} (民・公区分) may have invalid values (Check layout sheet)"
}
count if var21==.
if r(N)==_N {
    display as error "Only missing value: {bf:var21} (民・公区分)"
}

capture assert inlist(var22, 1, 3, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var22} (種類) may have invalid values (Check layout sheet)"
}
count if var22==.
if r(N)==_N {
    display as error "Only missing value: {bf:var22} (種類)"
}

capture assert inlist(var33, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:var33} (確定・未確定) may have invalid values (Check layout sheet)"
}
count if var33==.
if r(N)==_N {
    display as error "Only missing value: {bf:var33} (確定・未確定)"
}

