/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成12年レイアウト＆符号表.xlsx
    Date: 2019/04/12 17:05:44
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 1-6
        str KEN 7-8
        str CITY 9-11
        str SHUBAN 12-15
        str KOUCHI 16-16
        str BUNKATU 17-18
        str DTKBN 19-19
        str SETORG 20-22
        str SETINREN 23-26
        str RITSU_B 27-38
        str RITSU_C 39-48
        str AZACODE 49-52
        str TANIKUCODE 53-57
        str RITSU_A 58-69
        str RITSU 70-81
        str SETAI 82-82
        str ISKBN 83-83
        str TATE 84-84
        str KAISU 85-86
        str LIVE 87-88
        str JYUKYO 89-89
        str JYUKYO4 90-90
        str NOBETANI 91-91
        str NOBE 92-95
        str NOBEAREA 96-102
        str SETJIN 103-106
        str TUZUKI 107-108
        str SEX 109-109
        str GENGO 110-110
        str NEN 111-114
        str TUKI 115-116
        str TUKI4 117-117
        str NENREI 118-120
        str HAIGU 121-121
        str KOKUSEKI 122-122
        str KIKAN 123-123
        str ZENJ6 124-124
        str ZENJKEN 125-126
        str ZENJCITY 127-129
        str KYOIKU 130-130
        str KYOKBN 131-131
        str RODO8 132-132
        str JYU6A 133-133
        str JYUKEN 134-135
        str JYUCITY 136-138
        str CHII7 139-139
        str SANDF 140-140
        str SAND 141-142
        str SANC 143-144
        str SANSF 145-147
        str SANS 148-150
        str SHOKDF 151-151
        str SHOKD 152-153
        str SHOKC 154-155
        str SHOKSF 156-158
        str SHOKS 159-161
    using "data";
#delimit cr
