/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（事業所票）h16-28.xlsx
    Date: 2019/02/25 04:50:21
----------------------------------------------------------------------*/


capture label define var3 7 "下半期" 
capture label values var3 var3

capture label define var7 1 "県番号:01" 3 "県番号:08~10,19,20" 5 "県番号:15~18" 7 "県番号:25,29,30" 9 "県番号:31,32" 11 "県番号:36~39" 13 "県番号:43,45~47" 
capture label values var7 var7

capture label define var15 1 "500人以上" 3 "30~99人" 
capture label values var15 var15

capture label define var16 1 "1000人以上" 3 "100~299人" 5 "5~29人" 
capture label values var16 var16

capture label define var19 1 "500人以上" 3 "30~99人" 
capture label values var19 var19

