/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx
    Date: 2019/02/25 04:50:11
----------------------------------------------------------------------*/


capture label variable var1 "調査年"
capture label variable var2 "府県ごとの括通し番号"
capture label variable var3 "都道府県番号"
capture label variable var4 "事業所一連番号"
capture label variable var5 "チェックディジット"
capture label variable var6 "○○枚目"
capture label variable var7 "労働者一連番号"
capture label variable var8 "市区町村番号"
capture label variable var9 "基本調査区番号"
capture label variable var10 "事業所番号"
capture label variable var11 "産業分類番号"
capture label variable var12 "事業所規模"
capture label variable var13 "臨時雇用者規模番号"
capture label variable var14 "企業規模"
capture label variable var16 "産業分類番号"
capture label variable var17 "事業所規模"
capture label variable var18 "臨時雇用者規模番号"
capture label variable var19 "企業規模"
capture label variable var20 "事業所"
capture label variable var21 "常用労働者"
capture label variable var22 "臨時労働者"
capture label variable var23 "復元倍率"
capture label variable var24 "本・支区分"
capture label variable var25 "民・公区分"
capture label variable var26 "種類"
capture label variable var28 "男"
capture label variable var29 "女"
capture label variable var30 "男"
capture label variable var31 "女"
capture label variable var32 "臨時労働者数"
capture label variable var33 "大"
capture label variable var34 "中"
capture label variable var35 "小"
capture label variable var37 "性別"
capture label variable var38 "雇用形態"
capture label variable var39 "就業形態"
capture label variable var40 "最終学歴"
capture label variable var41 "年齢"
capture label variable var42 "勤続年数"
capture label variable var43 "労働者の種類"
capture label variable var44 "役職・職種番号"
capture label variable var45 "経験年数"
capture label variable var46 "実労働日数"
capture label variable var47 "所定内実労働時間数"
capture label variable var48 "超過実労働時間数"
capture label variable var49 "決まって支給する現金給与額"
capture label variable var50 "超過労働給与額"
capture label variable var51 "所定内給与額"
capture label variable var52 "通勤手当"
capture label variable var53 "精皆勤手当"
capture label variable var54 "家族手当"
capture label variable var55 "昨年1年間の賞与期末手当等特別支給額"
