/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx
    Date: 2019/02/21 18:51:46
----------------------------------------------------------------------*/


#delimit ;
    quietly infix
        var1 1-4
        var2 5-6
        var3 7-9
        var4 10-11
        var5 12-16
        var6 17-17
        var7 18-19
        var8 20-21
        var9 22-24
        var10 25-30
        var11 31-34
        var12 35-35
        var13 36-38
        var14 39-39
        var15 40-40
        var16 41-41
        var17 42-44
        var18 45-45
        var19 46-48
        var20 49-49
        var21 50-50
        var22 51-51
        var23 52-55
        var24 56-57
        var25 58-59
        var26 60-65
        var27 66-66
        var28 67-67
        var29 68-68
        var30 69-69
        var31 70-74
        var32 75-79
        var33 80-84
        var34 85-89
        var35 90-94
        var36 95-95
        var37 96-97
        var38 98-98
        var39 99-103
        var40 104-104
        var41 105-105
        var42 106-106
        var43 107-107
        var44 108-109
        var45 110-111
        var46 112-112
        var47 113-115
        var48 116-116
        var49 117-118
        var50 119-121
        var51 122-124
        var52 125-129
        var53 130-133
        var54 134-138
        var55 139-141
        var56 142-144
        var57 145-147
        var58 148-153
    using "/media/HD-LXU3/WageCensus_EmploymentTrend/raw/調査票情報/賃金構造基本統計調査/h01-29_k-chin/h20_k-chin.txt";
#delimit cr
