/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx
    Date: 2019/02/25 04:50:11
----------------------------------------------------------------------*/


#delimit ;
    quietly infix
        var1 1-4
        var2 5-6
        var3 10-11
        var4 12-16
        var5 17-17
        var6 18-19
        var7 20-21
        var8 22-24
        var9 25-30
        var10 31-34
        var11 36-38
        var12 39-39
        var13 40-40
        var14 41-41
        var16 46-48
        var17 49-49
        var18 50-50
        var19 51-51
        var20 52-55
        var21 56-57
        var22 58-59
        var23 60-65
        var24 66-66
        var25 67-67
        var26 68-68
        var28 70-74
        var29 75-79
        var30 80-84
        var31 85-89
        var32 90-94
        var33 95-95
        var34 96-97
        var35 98-98
        var37 104-104
        var38 105-105
        var39 106-106
        var40 107-107
        var41 108-109
        var42 110-111
        var43 112-112
        var44 113-115
        var45 116-116
        var46 117-118
        var47 119-121
        var48 122-124
        var49 125-129
        var50 130-133
        var51 134-138
        var52 139-141
        var53 142-144
        var54 145-147
        var55 148-153
    using "/media/HD-LXU3/WageCensus_EmploymentTrend/raw/調査票情報/賃金構造基本統計調査/h01-29_k-chin/h20_k-chin.txt";
#delimit cr
