/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 
    Date: 2019/03/29 17:30:39
----------------------------------------------------------------------*/


/*----------------------------------------------------------------------
    Description (Base):    "チェックディジット"
    Description (Data 1):  "チェックディジット"
    Description (Data 2):  "チェックディジット"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  

----------------------------------------------------------------------*/
gen Digit_ToBeDropped_NEWVARIABLE = "."
capture replace Digit_ToBeDropped_NEWVARIABLE = Digit  if flag_tmp_NEWVARIABLE==1
capture replace Digit_ToBeDropped_NEWVARIABLE = Digit  if flag_tmp_NEWVARIABLE==2
capture label variable Digit_ToBeDropped_NEWVARIABLE "チェックディジット"


/*----------------------------------------------------------------------
    Description (Base):    "○○枚目"
    Description (Data 1):  "○○枚目"
    Description (Data 2):  "○○枚目"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  

----------------------------------------------------------------------*/
gen Maime_ToBeDropped_NEWVARIABLE = "."
capture replace Maime_ToBeDropped_NEWVARIABLE = Maime  if flag_tmp_NEWVARIABLE==1
capture replace Maime_ToBeDropped_NEWVARIABLE = Maime  if flag_tmp_NEWVARIABLE==2
capture label variable Maime_ToBeDropped_NEWVARIABLE "○○枚目"


keep *_NEWVARIABLE
rename *_NEWVARIABLE *
