/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（入職者票）h11.xlsx
    Date: 2019/02/27 01:44:09
----------------------------------------------------------------------*/


capture label variable var1 "調査IDT"
capture label variable var2 "西暦年"
capture label variable var3 "調査月"
capture label variable var4 "調査区分"
capture label variable var5 "地域番号"
capture label variable var6 "都道府県番号"
capture label variable var7 "事業所番号"
capture label variable var8 "大分類"
capture label variable var9 "中分類"
capture label variable var10 "抽出符号"
capture label variable var11 "事業所規模"
capture label variable var12 "企業規模"
capture label variable var13 "産業連番"
capture label variable var14 "事業所規模"
capture label variable var15 "性別"
capture label variable var16 "就業形態"
capture label variable var17 "乗率"
capture label variable var18 "性別"
capture label variable var19 "チェック済"
capture label variable var21 "地区"
capture label variable var22 "都道府県"
capture label variable var23 "チェック済"
capture label variable var26 "卒業時期"
capture label variable var27 "チェック済"
capture label variable var29 "就業形態"
capture label variable var30 "チェック済"
capture label variable var32 "チェック済"
capture label variable var36 "地域"
capture label variable var37 "都道府県"
capture label variable var38 "在籍の有無"
capture label variable var39 "就業の動機"
capture label variable var40 "前職の産業"
capture label variable var41 "チェック済"
capture label variable var43 "チェック済"
capture label variable var47 "離職期間"
capture label variable var48 "前職の従業員数"
capture label variable var49 "転職理由数"
capture label variable var50 "チェック済"
capture label variable var52 "チェック済"
capture label variable var54 "チェック済"
capture label variable var56 "チェック済"
capture label variable var59 "製造業分類"
