/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/ESSレイアウト/h19.xls
    Date: 2019/08/15 18:51:22
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str RESEARCH_YEAR 4-7
        str RESEARCH_MONTH 8-9
        str C_KEN 71-72
        str C_CITY 73-75
        str C_CHOSAKU_KEN 81-82
        str C_CHOSAKU_KENNAI 83-86
        str R_SYUKEI 159-171
        str SETAI1 174-174
        str SETAI2 175-177
        str SETAI3 178-179
        str SETAIIN 180-181
        str S_IPPAN 184-184
        str S_KAZOKURUI12 187-188
        str S_NENREI0 197-197
        str S_NENREI1 198-198
        str S_NENREI2 199-199
        str S_NENREI3 200-200
        str S_NENREI4 201-201
        str S_NENREI5 202-202
        str S_NENREI6 203-203
        str S_NENREI7 204-204
        str S_NENREI8 205-205
        str S_NENREI9 206-206
        str S_NENREI10 207-207
        str S_NENREI11 208-208
        str S_NENREI12 209-209
        str S_NENREI13 210-210
        str S_NENREI14 211-211
        str S_MIMAN15 212-213
        str S_JININ 214-215
        str S_OMOSYU 240-241
        str S_JYU1 242-242
        str S_JYU2 243-243
        str S_JYU3 244-244
        str S_JYU4 245-245
        str S_JYU5 246-246
        str S_JYU6 247-247
        str S_JYU7 248-248
        str S_JYU8 249-249
        str S_JYU9 250-250
        str S_JYU10 251-251
        str S_SYUNYU 253-254
        str K_SEX 266-266
        str K_HAIGU 267-267
        str K_TUZUKI 268-269
        str K_GENGO 270-270
        str K_NEN 271-274
        str K_TUKI 275-276
        str K_AGE 277-279
        str K_AGE5 280-281
        str K_AGE10 282-282
        str K_KYOIKU 283-283
        str K_GAKKO 284-284
        str K_ZENJYU 285-285
        str K_ZENJYUKEN 286-287
        str K_SYUGYO 290-290
        str YH_CHII8 300-300
        str YH_KEITAI 301-301
        str YH_KIGYO 302-302
        str YH_KEIEI 303-303
        str YH_NOHINO 305-305
        str YH_SANDAI 306-307
        str YH_SANSYO 308-310
        str YH_SHODAI 311-312
        str YH_SHOSYO 313-315
        str YH_JYUKIBO 316-317
        str YH_NISSU 318-318
        str YH_KISOKU 319-319
        str YH_JIKAN 320-321
        str YH_SYUNYU 322-323
        str YH_SYUKIBO 324-324
        str YH_SYUZOGEN 325-325
        str YH_TENRIYU 326-326
        str YH_SYUKEITAI 327-327
        str YH_KYUUMU 328-328
        str YH_GENGO 329-329
        str YH_NEN 330-333
        str YH_TUKI 334-335
        str YH_SYURIYU 342-342
        str YF_UMU 345-345
        str YF_KBN 346-346
        str YF_NOHINO 347-347
        str YF_SANDAI 348-348
        str Y_ZENSYUGYO 351-351
        str Y_ZENUMU 352-352
        str M_SYUKIBO 361-361
        str M_SYURIYU 362-362
        str M_SHOKUSHU 363-364
        str M_KEITAI 365-365
        str M_KYUUMU 366-366
        str M_HIKYURIYU 367-368
        str M_KBN 369-369
        str M_NEN 370-371
        str M_TUKI 372-373
        str M_KIBOJIKI 376-376
        str M_HISYURIYU 377-378
        str M_ZENSYUGYO 379-379
        str M_ZENUMU 380-380
        str Z_RIJIKI 386-386
        str Z_GENGO 387-387
        str Z_NEN 388-391
        str Z_TUKI 392-393
        str Z_RIRIYU 394-395
        str Z_JYUCHII8 396-396
        str Z_KEITAI 398-398
        str Z_SANDAI 399-399
        str Z_SYODAI 400-400
        str Z_JYUKIBO 401-402
        str Z_KEINEN2 403-403
        str Z_KEINEN 404-405
        str Z_KEITUKI 406-407
        str Z_SKBN 410-410
        str Z_SGENGO 411-411
        str Z_SNEN 412-415
        str Z_STUKI 416-417
        str Z_SCHIKEI 422-423
        str J_UMU 430-430
        str J_COMP0 431-431
        str J_COMP1 432-432
        str J_COMP2 433-433
        str J_COMP3 434-434
        str J_COMP4 435-435
        str J_COMP5 436-436
        str J_COMP6 437-437
        str J_COMP7 438-438
        str J_COMP9 439-439
        str J_JIHATU0 440-440
        str J_JIHATU2 441-441
        str J_JIHATU3 442-442
        str J_JIHATU4 443-443
        str J_JIHATU5 444-444
        str J_JIHATU6 445-445
        str J_JIHATU7 446-446
        str J_JIHATU8 447-447
        str J_JIHATU9 448-448
        str J_JOSEI0 449-449
        str J_JOSEI2 450-450
        str J_JOSEI3 451-451
        str J_JOSEI4 452-452
        str J_JOSEI5 453-453
        str J_JOSEI6 454-454
        str J_JOSEI7 455-455
        str J_JOSEI9 456-456
        str ISHUKAN 457-458
        str S_YH_NOHINO 701-701
        str S_YH_SANDAI 702-703
        str S_YH_SANSYO 704-706
        str S_YF_NOHINO 707-707
        str S_YF_SANDAI 708-708
        str S_Z_SANDAI 709-709
        str S_YH_SHODAI 720-721
        str S_YH_SHOSYO 722-724
        str S_Z_SYODAI 725-725
    using "${DataFilePathTemp}/L5_2007_RCD_NA-KOBETSUkk_A.txt";
#delimit cr
