/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/08/15 18:51:22
-----------------------------------------------------------------------------*/


capture count if RESEARCH_YEAR==.
if r(N)==_N {
    display as error "Only missing value: {bf:RESEARCH_YEAR} (年)"
}
capture assert inlist(RESEARCH_YEAR, 2007, .)
if _rc!=0 {
    display as error "WARNING: {bf:RESEARCH_YEAR} (年) may have invalid values (Check layout sheet)"
}


capture count if RESEARCH_MONTH==.
if r(N)==_N {
    display as error "Only missing value: {bf:RESEARCH_MONTH} (月)"
}
capture assert inlist(RESEARCH_MONTH, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:RESEARCH_MONTH} (月) may have invalid values (Check layout sheet)"
}


capture count if C_KEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:C_KEN} (都道府県番号)"
}
capture assert inlist(C_KEN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, .)
if _rc!=0 {
    display as error "WARNING: {bf:C_KEN} (都道府県番号) may have invalid values (Check layout sheet)"
}


capture count if C_CITY==.
if r(N)==_N {
    display as error "Only missing value: {bf:C_CITY} (市区町村番号)"
}


capture count if C_CHOSAKU_KEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:C_CHOSAKU_KEN} (都道府県番号)"
}


capture count if C_CHOSAKU_KENNAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:C_CHOSAKU_KENNAI} (県内一連番号)"
}


capture count if R_SYUKEI==.
if r(N)==_N {
    display as error "Only missing value: {bf:R_SYUKEI} (集計用乗率)"
}


capture count if SETAI1==.
if r(N)==_N {
    display as error "Only missing value: {bf:SETAI1} (居住者の有無)"
}


capture count if SETAI2==.
if r(N)==_N {
    display as error "Only missing value: {bf:SETAI2} (抽出単位番号)"
}


capture count if SETAI3==.
if r(N)==_N {
    display as error "Only missing value: {bf:SETAI3} (一連番号)"
}


capture count if SETAIIN==.
if r(N)==_N {
    display as error "Only missing value: {bf:SETAIIN} (世帯員番号)"
}


capture count if S_IPPAN==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_IPPAN} (一般・単身の別)"
}
capture assert inlist(S_IPPAN, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_IPPAN} (一般・単身の別) may have invalid values (Check layout sheet)"
}


capture count if S_KAZOKURUI12==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_KAZOKURUI12} (12区分)"
}
capture assert inlist(S_KAZOKURUI12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_KAZOKURUI12} (12区分) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI0==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI0} (0歳)"
}
capture assert inlist(S_NENREI0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI0} (0歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI1==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI1} (1歳)"
}
capture assert inlist(S_NENREI1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI1} (1歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI2==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI2} (2歳)"
}
capture assert inlist(S_NENREI2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI2} (2歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI3==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI3} (3歳)"
}
capture assert inlist(S_NENREI3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI3} (3歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI4==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI4} (4歳)"
}
capture assert inlist(S_NENREI4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI4} (4歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI5==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI5} (5歳)"
}
capture assert inlist(S_NENREI5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI5} (5歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI6==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI6} (6歳)"
}
capture assert inlist(S_NENREI6, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI6} (6歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI7==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI7} (7歳)"
}
capture assert inlist(S_NENREI7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI7} (7歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI8==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI8} (8歳)"
}
capture assert inlist(S_NENREI8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI8} (8歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI9==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI9} (9歳)"
}
capture assert inlist(S_NENREI9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI9} (9歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI10==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI10} (10歳)"
}
capture assert inlist(S_NENREI10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI10} (10歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI11==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI11} (11歳)"
}
capture assert inlist(S_NENREI11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI11} (11歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI12==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI12} (12歳)"
}
capture assert inlist(S_NENREI12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI12} (12歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI13==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI13} (13歳)"
}
capture assert inlist(S_NENREI13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI13} (13歳) may have invalid values (Check layout sheet)"
}


capture count if S_NENREI14==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_NENREI14} (14歳)"
}
capture assert inlist(S_NENREI14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_NENREI14} (14歳) may have invalid values (Check layout sheet)"
}


capture count if S_MIMAN15==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_MIMAN15} (15歳未満の合計)"
}


capture count if S_JININ==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JININ} (15歳以上の合計)"
}


capture count if S_OMOSYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_OMOSYU} (おもな収入)"
}
capture assert inlist(S_OMOSYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_OMOSYU} (おもな収入) may have invalid values (Check layout sheet)"
}


capture count if S_JYU1==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU1} (賃金・給料)"
}
capture assert inlist(S_JYU1, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU1} (賃金・給料) may have invalid values (Check layout sheet)"
}


capture count if S_JYU2==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU2} (農業収入)"
}
capture assert inlist(S_JYU2, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU2} (農業収入) may have invalid values (Check layout sheet)"
}


capture count if S_JYU3==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU3} (その他の事業収入)"
}
capture assert inlist(S_JYU3, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU3} (その他の事業収入) may have invalid values (Check layout sheet)"
}


capture count if S_JYU4==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU4} (内職収入)"
}
capture assert inlist(S_JYU4, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU4} (内職収入) may have invalid values (Check layout sheet)"
}


capture count if S_JYU5==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU5} (家賃・地代)"
}
capture assert inlist(S_JYU5, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU5} (家賃・地代) may have invalid values (Check layout sheet)"
}


capture count if S_JYU6==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU6} (利子・配当)"
}
capture assert inlist(S_JYU6, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU6} (利子・配当) may have invalid values (Check layout sheet)"
}


capture count if S_JYU7==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU7} (年金・恩給)"
}
capture assert inlist(S_JYU7, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU7} (年金・恩給) may have invalid values (Check layout sheet)"
}


capture count if S_JYU8==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU8} (雇用保険)"
}
capture assert inlist(S_JYU8, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU8} (雇用保険) may have invalid values (Check layout sheet)"
}


capture count if S_JYU9==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU9} (仕送り)"
}
capture assert inlist(S_JYU9, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU9} (仕送り) may have invalid values (Check layout sheet)"
}


capture count if S_JYU10==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_JYU10} (その他)"
}
capture assert inlist(S_JYU10, 1, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_JYU10} (その他) may have invalid values (Check layout sheet)"
}


capture count if S_SYUNYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_SYUNYU} (世帯の収入階級)"
}
capture assert inlist(S_SYUNYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_SYUNYU} (世帯の収入階級) may have invalid values (Check layout sheet)"
}


capture count if K_SEX==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_SEX} (性別)"
}
capture assert inlist(K_SEX, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_SEX} (性別) may have invalid values (Check layout sheet)"
}


capture count if K_HAIGU==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_HAIGU} (配偶者の有無)"
}
capture assert inlist(K_HAIGU, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_HAIGU} (配偶者の有無) may have invalid values (Check layout sheet)"
}


capture count if K_TUZUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_TUZUKI} (世帯主との続き柄)"
}
capture assert inlist(K_TUZUKI, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_TUZUKI} (世帯主との続き柄) may have invalid values (Check layout sheet)"
}


capture count if K_GENGO==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_GENGO} (元号)"
}
capture assert inlist(K_GENGO, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_GENGO} (元号) may have invalid values (Check layout sheet)"
}


capture count if K_NEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_NEN} (年)"
}


capture count if K_TUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_TUKI} (月)"
}


capture count if K_AGE==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_AGE} (各歳)"
}


capture count if K_AGE5==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_AGE5} (5歳階級)"
}
capture assert inlist(K_AGE5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_AGE5} (5歳階級) may have invalid values (Check layout sheet)"
}


capture count if K_AGE10==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_AGE10} (10歳階級)"
}
capture assert inlist(K_AGE10, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_AGE10} (10歳階級) may have invalid values (Check layout sheet)"
}


capture count if K_KYOIKU==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_KYOIKU} (教育区分)"
}
capture assert inlist(K_KYOIKU, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_KYOIKU} (教育区分) may have invalid values (Check layout sheet)"
}


capture count if K_GAKKO==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_GAKKO} (学校区分)"
}
capture assert inlist(K_GAKKO, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_GAKKO} (学校区分) may have invalid values (Check layout sheet)"
}


capture count if K_ZENJYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_ZENJYU} (区分)"
}
capture assert inlist(K_ZENJYU, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_ZENJYU} (区分) may have invalid values (Check layout sheet)"
}


capture count if K_ZENJYUKEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_ZENJYUKEN} (県番号)"
}
capture assert inlist(K_ZENJYUKEN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 99, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_ZENJYUKEN} (県番号) may have invalid values (Check layout sheet)"
}


capture count if K_SYUGYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:K_SYUGYO} (就業状態)"
}
capture assert inlist(K_SYUGYO, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:K_SYUGYO} (就業状態) may have invalid values (Check layout sheet)"
}


capture count if YH_CHII8==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_CHII8} (8区分)"
}
capture assert inlist(YH_CHII8, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_CHII8} (8区分) may have invalid values (Check layout sheet)"
}


capture count if YH_KEITAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_KEITAI} (雇用形態)"
}
capture assert inlist(YH_KEITAI, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_KEITAI} (雇用形態) may have invalid values (Check layout sheet)"
}


capture count if YH_KIGYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_KIGYO} (起業の有無)"
}
capture assert inlist(YH_KIGYO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_KIGYO} (起業の有無) may have invalid values (Check layout sheet)"
}


capture count if YH_KEIEI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_KEIEI} (経営組織)"
}
capture assert inlist(YH_KEIEI, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_KEIEI} (経営組織) may have invalid values (Check layout sheet)"
}


capture count if YH_NOHINO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_NOHINO} (農林・非農林)"
}
capture assert inlist(YH_NOHINO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_NOHINO} (農林・非農林) may have invalid values (Check layout sheet)"
}


capture count if YH_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SANDAI} (大分類)"
}
capture assert inlist(YH_SANDAI, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SANDAI} (大分類) may have invalid values (Check layout sheet)"
}


capture count if YH_SANSYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SANSYO} (小分類)"
}
capture assert inlist(YH_SANSYO, 11, 13, 20, 30, 40, 50, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SANSYO} (小分類) may have invalid values (Check layout sheet)"
}


capture count if YH_SHODAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SHODAI} (大分類)"
}
capture assert inlist(YH_SHODAI, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SHODAI} (大分類) may have invalid values (Check layout sheet)"
}


capture count if YH_SHOSYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SHOSYO} (小分類)"
}
capture assert inlist(YH_SHOSYO, 0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SHOSYO} (小分類) may have invalid values (Check layout sheet)"
}


capture count if YH_JYUKIBO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_JYUKIBO} (従業者規模)"
}
capture assert inlist(YH_JYUKIBO, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_JYUKIBO} (従業者規模) may have invalid values (Check layout sheet)"
}


capture count if YH_NISSU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_NISSU} (年間就業日数)"
}
capture assert inlist(YH_NISSU, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_NISSU} (年間就業日数) may have invalid values (Check layout sheet)"
}


capture count if YH_KISOKU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_KISOKU} (就業の規則性)"
}
capture assert inlist(YH_KISOKU, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_KISOKU} (就業の規則性) may have invalid values (Check layout sheet)"
}


capture count if YH_JIKAN==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_JIKAN} (週間就業時間)"
}
capture assert inlist(YH_JIKAN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_JIKAN} (週間就業時間) may have invalid values (Check layout sheet)"
}


capture count if YH_SYUNYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SYUNYU} (個人所得)"
}
capture assert inlist(YH_SYUNYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SYUNYU} (個人所得) may have invalid values (Check layout sheet)"
}


capture count if YH_SYUKIBO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SYUKIBO} (就業希望意識)"
}
capture assert inlist(YH_SYUKIBO, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SYUKIBO} (就業希望意識) may have invalid values (Check layout sheet)"
}


capture count if YH_SYUZOGEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SYUZOGEN} (就業時間希望)"
}
capture assert inlist(YH_SYUZOGEN, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SYUZOGEN} (就業時間希望) may have invalid values (Check layout sheet)"
}


capture count if YH_TENRIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_TENRIYU} (転職希望理由)"
}
capture assert inlist(YH_TENRIYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_TENRIYU} (転職希望理由) may have invalid values (Check layout sheet)"
}


capture count if YH_SYUKEITAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SYUKEITAI} (希望仕事形態)"
}
capture assert inlist(YH_SYUKEITAI, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SYUKEITAI} (希望仕事形態) may have invalid values (Check layout sheet)"
}


capture count if YH_KYUUMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_KYUUMU} (求職活動の有無)"
}
capture assert inlist(YH_KYUUMU, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_KYUUMU} (求職活動の有無) may have invalid values (Check layout sheet)"
}


capture count if YH_GENGO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_GENGO} (元号)"
}
capture assert inlist(YH_GENGO, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_GENGO} (元号) may have invalid values (Check layout sheet)"
}


capture count if YH_NEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_NEN} (年)"
}


capture count if YH_TUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_TUKI} (月)"
}


capture count if YH_SYURIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YH_SYURIYU} (就業理由)"
}
capture assert inlist(YH_SYURIYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:YH_SYURIYU} (就業理由) may have invalid values (Check layout sheet)"
}


capture count if YF_UMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:YF_UMU} (有無)"
}
capture assert inlist(YF_UMU, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:YF_UMU} (有無) may have invalid values (Check layout sheet)"
}


capture count if YF_KBN==.
if r(N)==_N {
    display as error "Only missing value: {bf:YF_KBN} (区分)"
}
capture assert inlist(YF_KBN, 0, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:YF_KBN} (区分) may have invalid values (Check layout sheet)"
}


capture count if YF_NOHINO==.
if r(N)==_N {
    display as error "Only missing value: {bf:YF_NOHINO} (農林・非農林)"
}
capture assert inlist(YF_NOHINO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:YF_NOHINO} (農林・非農林) may have invalid values (Check layout sheet)"
}


capture count if YF_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:YF_SANDAI} (大分類)"
}


capture count if Y_ZENSYUGYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:Y_ZENSYUGYO} (1年前の就業状態)"
}
capture assert inlist(Y_ZENSYUGYO, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:Y_ZENSYUGYO} (1年前の就業状態) may have invalid values (Check layout sheet)"
}


capture count if Y_ZENUMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:Y_ZENUMU} (前職の有無)"
}
capture assert inlist(Y_ZENUMU, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:Y_ZENUMU} (前職の有無) may have invalid values (Check layout sheet)"
}


capture count if M_SYUKIBO==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_SYUKIBO} (有無)"
}
capture assert inlist(M_SYUKIBO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_SYUKIBO} (有無) may have invalid values (Check layout sheet)"
}


capture count if M_SYURIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_SYURIYU} (理由)"
}
capture assert inlist(M_SYURIYU, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_SYURIYU} (理由) may have invalid values (Check layout sheet)"
}


capture count if M_SHOKUSHU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_SHOKUSHU} (希望職種)"
}
capture assert inlist(M_SHOKUSHU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_SHOKUSHU} (希望職種) may have invalid values (Check layout sheet)"
}


capture count if M_KEITAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_KEITAI} (仕事の形態)"
}
capture assert inlist(M_KEITAI, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_KEITAI} (仕事の形態) may have invalid values (Check layout sheet)"
}


capture count if M_KYUUMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_KYUUMU} (有無)"
}
capture assert inlist(M_KYUUMU, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_KYUUMU} (有無) may have invalid values (Check layout sheet)"
}


capture count if M_HIKYURIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_HIKYURIYU} (非求職理由)"
}
capture assert inlist(M_HIKYURIYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_HIKYURIYU} (非求職理由) may have invalid values (Check layout sheet)"
}


capture count if M_KBN==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_KBN} (2区分)"
}
capture assert inlist(M_KBN, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_KBN} (2区分) may have invalid values (Check layout sheet)"
}


capture count if M_NEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_NEN} (年)"
}


capture count if M_TUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_TUKI} (月)"
}


capture count if M_KIBOJIKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_KIBOJIKI} (就業希望時期)"
}
capture assert inlist(M_KIBOJIKI, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_KIBOJIKI} (就業希望時期) may have invalid values (Check layout sheet)"
}


capture count if M_HISYURIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_HISYURIYU} (非就業希望理由)"
}
capture assert inlist(M_HISYURIYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_HISYURIYU} (非就業希望理由) may have invalid values (Check layout sheet)"
}


capture count if M_ZENSYUGYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_ZENSYUGYO} (1年前の就業状態)"
}
capture assert inlist(M_ZENSYUGYO, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_ZENSYUGYO} (1年前の就業状態) may have invalid values (Check layout sheet)"
}


capture count if M_ZENUMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:M_ZENUMU} (前職の有無)"
}
capture assert inlist(M_ZENUMU, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:M_ZENUMU} (前職の有無) may have invalid values (Check layout sheet)"
}


capture count if Z_RIJIKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_RIJIKI} (区分)"
}
capture assert inlist(Z_RIJIKI, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_RIJIKI} (区分) may have invalid values (Check layout sheet)"
}


capture count if Z_GENGO==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_GENGO} (元号)"
}
capture assert inlist(Z_GENGO, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_GENGO} (元号) may have invalid values (Check layout sheet)"
}


capture count if Z_NEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_NEN} (年)"
}


capture count if Z_TUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_TUKI} (月)"
}


capture count if Z_RIRIYU==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_RIRIYU} (離職理由)"
}
capture assert inlist(Z_RIRIYU, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_RIRIYU} (離職理由) may have invalid values (Check layout sheet)"
}


capture count if Z_JYUCHII8==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_JYUCHII8} (8区分)"
}
capture assert inlist(Z_JYUCHII8, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_JYUCHII8} (8区分) may have invalid values (Check layout sheet)"
}


capture count if Z_KEITAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_KEITAI} (雇用形態)"
}
capture assert inlist(Z_KEITAI, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_KEITAI} (雇用形態) may have invalid values (Check layout sheet)"
}


capture count if Z_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SANDAI} (大分類)"
}


capture count if Z_SYODAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SYODAI} (大分類)"
}
capture assert inlist(Z_SYODAI, 0, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_SYODAI} (大分類) may have invalid values (Check layout sheet)"
}


capture count if Z_JYUKIBO==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_JYUKIBO} (従業者規模)"
}
capture assert inlist(Z_JYUKIBO, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_JYUKIBO} (従業者規模) may have invalid values (Check layout sheet)"
}


capture count if Z_KEINEN2==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_KEINEN2} (区分)"
}
capture assert inlist(Z_KEINEN2, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_KEINEN2} (区分) may have invalid values (Check layout sheet)"
}


capture count if Z_KEINEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_KEINEN} (年)"
}


capture count if Z_KEITUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_KEITUKI} (か月)"
}


capture count if Z_SKBN==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SKBN} (現職・前職との関係)"
}
capture assert inlist(Z_SKBN, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_SKBN} (現職・前職との関係) may have invalid values (Check layout sheet)"
}


capture count if Z_SGENGO==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SGENGO} (元号)"
}
capture assert inlist(Z_SGENGO, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_SGENGO} (元号) may have invalid values (Check layout sheet)"
}


capture count if Z_SNEN==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SNEN} (年)"
}


capture count if Z_STUKI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_STUKI} (月)"
}


capture count if Z_SCHIKEI==.
if r(N)==_N {
    display as error "Only missing value: {bf:Z_SCHIKEI} (従業上の地位・雇用形態)"
}
capture assert inlist(Z_SCHIKEI, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:Z_SCHIKEI} (従業上の地位・雇用形態) may have invalid values (Check layout sheet)"
}


capture count if J_UMU==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_UMU} (訓練・自己啓発の有無)"
}
capture assert inlist(J_UMU, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_UMU} (訓練・自己啓発の有無) may have invalid values (Check layout sheet)"
}


capture count if J_COMP0==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP0} (有無)"
}
capture assert inlist(J_COMP0, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP0} (有無) may have invalid values (Check layout sheet)"
}


capture count if J_COMP1==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP1} (勤め先での研修)"
}
capture assert inlist(J_COMP1, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP1} (勤め先での研修) may have invalid values (Check layout sheet)"
}


capture count if J_COMP2==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP2} (大学・大学院の講座の受講)"
}
capture assert inlist(J_COMP2, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP2} (大学・大学院の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_COMP3==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP3} (専修学校・各種学校の講座の受講)"
}
capture assert inlist(J_COMP3, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP3} (専修学校・各種学校の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_COMP4==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP4} (公共職業能力開発施設の講座を受講)"
}
capture assert inlist(J_COMP4, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP4} (公共職業能力開発施設の講座を受講) may have invalid values (Check layout sheet)"
}


capture count if J_COMP5==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP5} (講習会・セミナーの傍聴)"
}
capture assert inlist(J_COMP5, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP5} (講習会・セミナーの傍聴) may have invalid values (Check layout sheet)"
}


capture count if J_COMP6==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP6} (勉強会・研修会への参加)"
}
capture assert inlist(J_COMP6, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP6} (勉強会・研修会への参加) may have invalid values (Check layout sheet)"
}


capture count if J_COMP7==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP7} (通信教育の受講)"
}
capture assert inlist(J_COMP7, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP7} (通信教育の受講) may have invalid values (Check layout sheet)"
}


capture count if J_COMP9==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_COMP9} (その他)"
}
capture assert inlist(J_COMP9, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_COMP9} (その他) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU0==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU0} (有無)"
}
capture assert inlist(J_JIHATU0, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU0} (有無) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU2==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU2} (大学・大学院の講座の受講)"
}
capture assert inlist(J_JIHATU2, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU2} (大学・大学院の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU3==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU3} (専修学校・各種学校の講座の受講)"
}
capture assert inlist(J_JIHATU3, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU3} (専修学校・各種学校の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU4==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU4} (公共職業能力開発施設の講座を受講)"
}
capture assert inlist(J_JIHATU4, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU4} (公共職業能力開発施設の講座を受講) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU5==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU5} (講習会・セミナーの傍聴)"
}
capture assert inlist(J_JIHATU5, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU5} (講習会・セミナーの傍聴) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU6==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU6} (勉強会・研修会への参加)"
}
capture assert inlist(J_JIHATU6, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU6} (勉強会・研修会への参加) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU7==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU7} (通信教育の受講)"
}
capture assert inlist(J_JIHATU7, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU7} (通信教育の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU8==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU8} (自学・自習)"
}
capture assert inlist(J_JIHATU8, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU8} (自学・自習) may have invalid values (Check layout sheet)"
}


capture count if J_JIHATU9==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JIHATU9} (その他)"
}
capture assert inlist(J_JIHATU9, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JIHATU9} (その他) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI0==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI0} (有無)"
}
capture assert inlist(J_JOSEI0, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI0} (有無) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI2==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI2} (大学・大学院の講座の受講)"
}
capture assert inlist(J_JOSEI2, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI2} (大学・大学院の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI3==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI3} (専修学校・各種学校の講座の受講)"
}
capture assert inlist(J_JOSEI3, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI3} (専修学校・各種学校の講座の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI4==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI4} (公共職業能力開発施設の講座を受講)"
}
capture assert inlist(J_JOSEI4, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI4} (公共職業能力開発施設の講座を受講) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI5==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI5} (講習会・セミナーの傍聴)"
}
capture assert inlist(J_JOSEI5, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI5} (講習会・セミナーの傍聴) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI6==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI6} (勉強会・研修会への参加)"
}
capture assert inlist(J_JOSEI6, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI6} (勉強会・研修会への参加) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI7==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI7} (通信教育の受講)"
}
capture assert inlist(J_JOSEI7, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI7} (通信教育の受講) may have invalid values (Check layout sheet)"
}


capture count if J_JOSEI9==.
if r(N)==_N {
    display as error "Only missing value: {bf:J_JOSEI9} (その他)"
}
capture assert inlist(J_JOSEI9, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:J_JOSEI9} (その他) may have invalid values (Check layout sheet)"
}


capture count if ISHUKAN==.
if r(N)==_N {
    display as error "Only missing value: {bf:ISHUKAN} (9月末1週間の状況)"
}
capture assert inlist(ISHUKAN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, .)
if _rc!=0 {
    display as error "WARNING: {bf:ISHUKAN} (9月末1週間の状況) may have invalid values (Check layout sheet)"
}


capture count if S_YH_NOHINO==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YH_NOHINO} (農林・非農林)"
}
capture assert inlist(S_YH_NOHINO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YH_NOHINO} (農林・非農林) may have invalid values (Check layout sheet)"
}


capture count if S_YH_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YH_SANDAI} (大分類)"
}
capture assert inlist(S_YH_SANDAI, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YH_SANDAI} (大分類) may have invalid values (Check layout sheet)"
}


capture count if S_YH_SANSYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YH_SANSYO} (小分類)"
}
capture assert inlist(S_YH_SANSYO, 11, 13, 20, 30, 40, 50, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YH_SANSYO} (小分類) may have invalid values (Check layout sheet)"
}


capture count if S_YF_NOHINO==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YF_NOHINO} (農林・非農林)"
}
capture assert inlist(S_YF_NOHINO, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YF_NOHINO} (農林・非農林) may have invalid values (Check layout sheet)"
}


capture count if S_YF_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YF_SANDAI} (大分類)"
}


capture count if S_Z_SANDAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_Z_SANDAI} (前職大分類)"
}


capture count if S_YH_SHODAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YH_SHODAI} (大分類)"
}
capture assert inlist(S_YH_SHODAI, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YH_SHODAI} (大分類) may have invalid values (Check layout sheet)"
}


capture count if S_YH_SHOSYO==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_YH_SHOSYO} (小分類)"
}
capture assert inlist(S_YH_SHOSYO, 0, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_YH_SHOSYO} (小分類) may have invalid values (Check layout sheet)"
}


capture count if S_Z_SYODAI==.
if r(N)==_N {
    display as error "Only missing value: {bf:S_Z_SYODAI} (前職大分類)"
}
capture assert inlist(S_Z_SYODAI, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:S_Z_SYODAI} (前職大分類) may have invalid values (Check layout sheet)"
}


