/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成22年レイアウト＆符号表.xlsx
    Date: 2019/04/12 17:05:42
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 1-6
        str KEN 7-8
        str CITY 9-11
        str SHUBAN 12-15
        str KOUCHI 16-16
        str BUNKATU 17-18
        str SETORG 19-21
        str DTKBN 22-22
        str SETINREN 23-26
        str AZACODE 27-30
        str TANIKUCODE 31-35
        str RITSU_A 36-48
        str RITSU_B 49-61
        str RITSU_C 62-74
        str RITSU 75-87
        str RITSU_AB 88-100
        str KC_GENGO 101-101
        str KC_NEN 102-105
        str KC_TSUKI 106-107
        str SETAI 108-108
        str ISKBN 109-109
        str TATE 110-110
        str KAISU 111-112
        str LIVE 113-114
        str JYUKYO 115-115
        str NOBE14 116-117
        str SETJIN 118-121
        str TUZUKI 122-123
        str SEX 124-124
        str TUKI4 125-125
        str NENREI 126-128
        str HAIGU 129-129
        str KOKUSEKI 130-130
        str KYOJU6 131-131
        str ZENJ6 132-132
        str ZENJKEN 133-134
        str ZENJCITY 135-137
        str KYOIKU 138-138
        str KYOKBN 139-139
        str RODO8 140-140
        str JYU7A 141-141
        str JYUKEN 142-143
        str JYUCITY 144-146
        str CHII8 147-147
        str SAND 148-149
        str SANC 150-151
        str SANS 152-154
        str SHOKD 155-156
        str SHOKC 157-158
        str SHOKS 159-161
    using "data";
#delimit cr
