/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/ESSレイアウト/h14.xls
    Date: 2019/08/15 18:51:21
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str YEAR 4-9
        str JOHO20 73-74
        str JOHO21 75-78
        str JOHO22 79-79
        str JOHO23 80-82
        str JOHO24 83-84
        str JOHO25 85-86
        str CHIKI_KEN 89-90
        str CHIKI_CITY 91-93
        str CHIKI_CHOKEN 94-95
        str CHIKI_CHONO 96-99
        str W_SYUKEI 149-161
        str S_SETNO 164-165
        str S_SETINNO 166-167
        str S_IPPAN 170-170
        str S_KAZOKURUI12 173-174
        str S_JIN0 183-183
        str S_JIN1 184-184
        str S_JIN2 185-185
        str S_JIN3 186-186
        str S_JIN4 187-187
        str S_JIN5 188-188
        str S_JIN6 189-189
        str S_JIN7 190-190
        str S_JIN8 191-191
        str S_JIN9 192-192
        str S_JIN10 193-193
        str S_JIN11 194-194
        str S_JIN12 195-195
        str S_JIN13 196-196
        str S_JIN14 197-197
        str S_JIN15MI 198-199
        str S_JIN15IJO 200-201
        str S_OMOSYU 226-227
        str S_JYU1 228-228
        str S_JYU2 229-229
        str S_JYU3 230-230
        str S_JYU4 231-231
        str S_JYU5 232-232
        str S_JYU6 233-233
        str S_JYU7 234-234
        str S_JYU8 235-235
        str S_JYU9 236-236
        str S_JYU10 237-237
        str S_SYUNYU 239-240
        str K_SEX 244-244
        str K_HAIGU 245-245
        str K_TUZUKI 246-247
        str K_GENGO 248-248
        str K_NEN 249-252
        str K_TUKI 253-254
        str K_KYOIKU 255-255
        str K_GAKKO 256-256
        str K_AGE 257-259
        str K_AGE5 260-261
        str K_AGE10 262-262
        str K_GGENGO 263-263
        str K_GNEN 264-267
        str K_GTUKI 268-269
        str K_GRIYU 270-271
        str K_ZENJYU 272-272
        str K_ZENJYUKEN 273-274
        str K_SYUGYO 279-279
        str YH_JYUTII8 289-289
        str YH_KEITAI 290-290
        str YH_KEIEI 291-291
        str YH_NOHINO 293-293
        str YH_SANDAI 294-295
        str YH_SANCHU 296-297
        str YH_SANSHIN 298-299
        str YH_SHODAI 300-301
        str YH_SHOCHU 302-303
        str YH_JYUKIBO 304-305
        str YH_NISSU 306-306
        str YH_KISOKU 307-307
        str YH_JIKAN 308-309
        str YH_SYUNYU 310-311
        str YH_SYUKIBO 312-312
        str YH_SYUZOGEN 313-313
        str YH_TENRIYU 314-314
        str YH_SYUKEITAI 315-315
        str YH_KYUUMU 316-316
        str YH_GENGO 317-317
        str YH_NEN 318-321
        str YH_TUKI 322-323
        str YH_SYURIYU 330-330
        str YF_FUKU 333-333
        str YF_NOHINO 334-334
        str YF_SANDAI 335-336
        str YF_SANCHU 337-338
        str YF_SANSHIN 339-340
        str YF_ZENSYUGYO 344-344
        str YF_ZENUMU 345-345
        str M_SYUKIBO 348-348
        str M_SYURIYU 349-349
        str M_SHOKUSHU 350-351
        str M_KEITAI 352-352
        str M_KYUUMU 353-353
        str M_HIKYURIYU 354-354
        str M_KBN 355-355
        str M_NEN 356-357
        str M_TUKI 358-359
        str M_KIBOJIKI 362-362
        str M_ZENSYUGYO 363-363
        str M_ZENUMU 364-364
        str Z_RIJIKI 367-367
        str Z_GENGO 368-368
        str Z_NEN 369-372
        str Z_TUKI 373-374
        str Z_RIRIYU 375-376
        str Z_JYUTII8 377-377
        str Z_KEITAI 379-379
        str Z_SANDAI 380-381
        str Z_SANCHU 382-383
        str Z_SANSHIN 384-385
        str Z_SYODAI 386-387
        str Z_SYOCHU 388-389
        str Z_JYUKIBO 390-391
        str Z_KEINEN2 392-392
        str Z_KEINEN 393-394
        str Z_KEITUKI 395-396
        str ISHUKAN 405-405
    using "${DataFilePathTemp}/L5_2002_RCD_HA6-kk_A_S.txt";
#delimit cr
