/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: E:/20190412/layoutFukai/平成07年レイアウト＆符号表.xlsx
    Date: 2019/04/12 17:05:44
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 1-6
        str KEN 7-8
        str CITY 9-11
        str SHUBAN 12-15
        str KOUCHI 16-16
        str BUNKATU 17-18
        str DTKBN 19-19
        str SETORG 20-22
        str SETINREN 23-26
        str RITSU 27-37
        str TOKEIKU 38-39
        str CHORITSU 40-49
        str AZACODE 50-53
        str TANIKUCODE 54-58
        str ISKBN 59-59
        str SETAI 60-60
        str TATE 61-61
        str KAISU 62-62
        str LIVE 63-63
        str JYUKYO 64-64
        str NOBETANI 65-65
        str NOBE 66-68
        str NOBEAREA 69-73
        str SETJIN 74-77
        str TUZUKI 78-79
        str SEX 80-80
        str GENGO 81-81
        str NEN 82-83
        str TUKI 84-84
        str NENREI 85-87
        str HAIGU 88-88
        str KOKUSEKI 89-89
        str RODO8 90-90
        str JYU6A 91-91
        str JYUKEN 92-93
        str JYUCITY 94-96
        str CHII6 97-97
        str SANDF 98-98
        str SAND 99-100
        str SANC 101-102
        str SANSF 103-105
        str SANS 106-108
        str SHOKDF 109-109
        str SHOKD 110-111
        str SHOKC 112-113
        str SHOKSF 114-116
        str SHOKS 117-119
    using "data";
#delimit cr
