/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/レイアウト/06_1 平成22年全数・抽出詳細集計.xlsx
    Date: 2019/04/14 14:46:08
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 3-8
        str KEN 9-10
        str CITY 11-13
        str SHUBAN 14-17
        str KOUCHI 18-18
        str BUNKATU 19-20
        str SETORG 21-23
        str DTKBN 27-27
        str SETINREN 30-33
        str AZACODE 76-79
        str TANIKUCODE 80-84
        str RITSU_A 129-141
        str RITSU_B 142-154
        str RITSU_C 155-167
        str RITSU 168-180
        str RITSU_AB 181-193
        str KC_GENGO 215-215
        str KC_NEN 216-219
        str KC_TSUKI 220-221
        str SETAI 271-271
        str ISKBN 272-272
        str TATE 274-274
        str KAISU 275-276
        str KAI5 277-277
        str LIVE 278-279
        str LIVE5 280-280
        str JYUKYO 281-281
        str JYUKYO4 282-282
        str NOBE14 283-284
        str NOBE6 285-285
        str SETJIN 286-289
        str SETJIN_M 290-293
        str SETJIN_F 294-297
        str TUZUKI 424-425
        str SEX 426-426
        str TUKI4 427-427
        str NENREI 428-430
        str HAIGU 436-436
        str KOKUSEKI 437-437
        str GAIKOKU 438-439
        str KOKU12 440-441
        str KYOJU6 442-442
        str ZENJ6 443-443
        str ZENJKEN 446-447
        str ZENJCITY 448-450
        str KYOIKU 471-471
        str KYOKBN 472-472
        str RODO3 473-473
        str RODO5 474-474
        str RODO8 475-475
        str JYU3 491-491
        str JYU4 492-492
        str JYU7A 493-493
        str JYUKEN 494-495
        str JYUCITY 496-498
        str KOTU31 521-522
        str KOTU16 523-524
        str CHII8 525-525
        str CHII3 526-526
        str SAND 527-528
        str SANC 529-530
        str SANS 531-533
        str SHOKD 534-535
        str SHOKC 536-537
        str SHOKS 538-540
    using "data";
#delimit cr
