/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: （参考）符号表_雇用動向調査（離職者票）h3-4
    Date: 2019/03/03 16:55:59
----------------------------------------------------------------------*/


capture label define var2 1992 "" 
capture label values var2 var2

capture label define var3 1 "上半期" 7 "下半期" 
capture label values var3 var3

capture label define var6 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 10 "" 11 "" 12 "" 13 "" 
capture label values var6 var6

capture label define var12 1 "500人以上" 2 "100~499人" 3 "30~99人" 4 "5~29人" 
capture label values var12 var12

capture label define var13 1 "1000人以上" 2 "300~999人" 3 "100~299人" 4 "30~99人" 5 "5~29人" 6 "官公営" 
capture label values var13 var13

capture label define var15 1 "" 2 "" 3 "" 4 "" 
capture label values var15 var15

capture label define var16 1 "男" 2 "女" 
capture label values var16 var16

capture label define var17 1 "一般労働者" 2 "パートタイム" 
capture label values var17 var17

capture label define var20 1 "男" 2 "女" 
capture label values var20 var20

capture label define var21 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 
capture label values var21 var21

capture label define var22 1 "" 2 "" 3 "" 4 "" 
capture label values var22 var22

capture label define var23 1 "" 2 "" 
capture label values var23 var23

capture label define var24 1 "一般" 2 "パート" 
capture label values var24 var24

capture label define var25 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 
capture label values var25 var25

capture label define var26 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 
capture label values var26 var26

capture label define var27 1 "" 2 "" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 10 "" 
capture label values var27 var27

capture label define var28 1 "分類表29を参照" 3 "" 4 "" 5 "" 6 "" 7 "" 8 "" 9 "" 10 "" 
capture label values var28 var28

