/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成17～29年_賃金構造基本統計調査_事業所票（初任給）.xls
    Date: 2019/02/22 13:15:17
----------------------------------------------------------------------*/


// Base data: 平成17～29年_賃金構造基本統計調査_事業所票（初任給）.xls


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査年"    "調査年"
    Variable Name:  "var1"    "var1" 
    Variable values:
        Base data:   2005: ,
        Match data:  2006: ,

----------------------------------------------------------------------*/
capture rename var1 var1


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var2"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var2


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "都道府県番号"    "都道府県番号"
    Variable Name:  "var3"    "var3" 
    Variable values:
        Base data:   01~47: ,
        Match data:  01~47: ,

----------------------------------------------------------------------*/
capture rename var3 var3


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所一連番号"    "事業所一連番号"
    Variable Name:  "var4"    "var4" 
    Variable values:
        Base data:   100010~: ,
        Match data:  100010~: ,

----------------------------------------------------------------------*/
capture rename var4 var4


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var5"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var5


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "市区町村番号"    "市区町村番号"
    Variable Name:  "var6"    "var6" 
    Variable values:
        Base data:   101~: ,
        Match data:  101~: ,

----------------------------------------------------------------------*/
capture rename var6 var6


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "基本調査区番号"    "基本調査区番号"
    Variable Name:  "var7"    "var7" 
    Variable values:
        Base data:   000001~: ,
        Match data:  000001~: ,

----------------------------------------------------------------------*/
capture rename var7 var7


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所番号"    "事業所番号"
    Variable Name:  "var8"    "var8" 
    Variable values:
        Base data:   0001~: ,
        Match data:  0001~: ,

----------------------------------------------------------------------*/
capture rename var8 var8


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var9"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var9


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "マスター産業番号"    "マスター産業番号"
    Variable Name:  "var10"    "var10" 
    Variable values:
        Base data:   051~939: ,
        Match data:  051~939: ,

----------------------------------------------------------------------*/
capture rename var10 var10


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "マスター事業所規模"    "マスター事業所規模"
    Variable Name:  "var11"    "var11" 
    Variable values:
        Base data:   0: 15,000人以上, 1: 5,000~14,999人, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 50~99人, 7: 30~49人, 8: 10~29人, 9: 5~9人,
        Match data:  0: 15,000人以上, 1: 5,000~14,999人, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 50~99人, 7: 30~49人, 8: 10~29人, 9: 5~9人,

----------------------------------------------------------------------*/
capture rename var11 var11


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "マスター臨時雇用者規模番号"    "マスター臨時雇用者規模番号"
    Variable Name:  "var12"    "var12" 
    Variable values:
        Base data:   1: 0~9人, 2: 10~99人, 3: 100人以上,
        Match data:  1: 0~9人, 2: 10~99人, 3: 100人以上,

----------------------------------------------------------------------*/
capture rename var12 var12


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "マスター企業規模"    "マスター企業規模"
    Variable Name:  "var13"    "var13" 
    Variable values:
        Base data:   1: 5,000人以上, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 30~99人, 7: 10~29人, 8: 5~9人,
        Match data:  1: 5,000人以上, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 30~99人, 7: 10~29人, 8: 5~9人,

----------------------------------------------------------------------*/
capture rename var13 var13


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var14"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var14


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票産業番号"    "調査票産業番号"
    Variable Name:  "var15"    "var15" 
    Variable values:
        Base data:   051~939: ,
        Match data:  051~939: ,

----------------------------------------------------------------------*/
capture rename var15 var15


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票事業所規模"    "調査票事業所規模"
    Variable Name:  "var16"    "var16" 
    Variable values:
        Base data:   0: 15,000人以上, 1: 5,000~14,999人, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 50~99人, 7: 30~49人, 8: 10~29人, 9: 5~9人,
        Match data:  0: 15,000人以上, 1: 5,000~14,999人, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 50~99人, 7: 30~49人, 8: 10~29人, 9: 5~9人,

----------------------------------------------------------------------*/
capture rename var16 var16


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票臨時雇用者規模番号"    "調査票臨時雇用者規模番号"
    Variable Name:  "var17"    "var17" 
    Variable values:
        Base data:   1: 0~9人, 2: 10~99人, 3: 100人以上,
        Match data:  1: 0~9人, 2: 10~99人, 3: 100人以上,

----------------------------------------------------------------------*/
capture rename var17 var17


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票企業規模"    "調査票企業規模"
    Variable Name:  "var18"    "var18" 
    Variable values:
        Base data:   1: 5,000人以上, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 30~99人, 7: 10~29人, 8: 5~9人,
        Match data:  1: 5,000人以上, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 30~99人, 7: 10~29人, 8: 5~9人,

----------------------------------------------------------------------*/
capture rename var18 var18


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出率事業所"    "抽出率事業所"
    Variable Name:  "var19"    "var19" 
    Variable values:
        Base data:   0001~: ,
        Match data:  0001~: ,

----------------------------------------------------------------------*/
capture rename var19 var19


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出率常用労働者"    "抽出率常用労働者"
    Variable Name:  "var20"    "var20" 
    Variable values:
        Base data:   01~: ,
        Match data:  01~: ,

----------------------------------------------------------------------*/
capture rename var20 var20


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出率臨時労働者"    "抽出率臨時労働者"
    Variable Name:  "var21"    "var21" 
    Variable values:
        Base data:   01~: ,
        Match data:  01~: ,

----------------------------------------------------------------------*/
capture rename var21 var21


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var22"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var22


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "本支区分"    "本支区分"
    Variable Name:  "var23"    "var23" 
    Variable values:
        Base data:   1: 単独, 2: 本社, 3: 支社,
        Match data:  1: 単独, 2: 本社, 3: 支社,

----------------------------------------------------------------------*/
capture rename var23 var23


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "民公区分"    "民公区分"
    Variable Name:  "var24"    "var24" 
    Variable values:
        Base data:   4: 民営事業所, 5: 公営事業所,
        Match data:  4: 民営事業所, 5: 公営事業所,

----------------------------------------------------------------------*/
capture rename var24 var24


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "種類"    "種類"
    Variable Name:  "var25"    "var25" 
    Variable values:
        Base data:   1: 国, 2: 都道府県, 3: 市区町村, 4: 独立行政法人, 5: その他,
        Match data:  1: 国, 2: 都道府県, 3: 市区町村, 4: 独立行政法人, 5: その他,

----------------------------------------------------------------------*/
capture rename var25 var25


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var26"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var26


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員・男"    "常用労働者・正社員・男"
    Variable Name:  "var27"    "var27" 
    Variable values:
        Base data:   00000~: (人),
        Match data:  00000~: (人),

----------------------------------------------------------------------*/
capture rename var27 var27


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員・女"    "常用労働者・正社員・女"
    Variable Name:  "var28"    "var28" 
    Variable values:
        Base data:   00000~: (人),
        Match data:  00000~: (人),

----------------------------------------------------------------------*/
capture rename var28 var28


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員以外・男"    "常用労働者・正社員以外・男"
    Variable Name:  "var29"    "var29" 
    Variable values:
        Base data:   00000~: (人),
        Match data:  00000~: (人),

----------------------------------------------------------------------*/
capture rename var29 var29


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員以外・女"    "常用労働者・正社員以外・女"
    Variable Name:  "var30"    "var30" 
    Variable values:
        Base data:   00000~: (人),
        Match data:  00000~: (人),

----------------------------------------------------------------------*/
capture rename var30 var30


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "臨時労働者数"    "臨時労働者数"
    Variable Name:  "var31"    "var31" 
    Variable values:
        Base data:   00000~: (人),
        Match data:  00000~: (人),

----------------------------------------------------------------------*/
capture rename var31 var31


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "初任給用産業番号大"    "初任給用産業番号大"
    Variable Name:  "var32"    "var32" 
    Variable values:
        Base data:   D: 051~059:鉱業, E: 061~089:建設業, F: 091~329:製造業, G: 331~363:電気・ガス・熱供給・水道業, H: 371~415:情報通信業, I: 421~489:運輸業, J: 491~609:卸売・小売業, K: 611~675:金融・保険業, L: 681~694:不動産業, M: 701~711、713~729:飲食店、宿泊業, N: 731~736、742、749、751、753~759医療・福祉, O: 761~779:教育、学習支援業, P: 781~792:複合サービス業, Q: 801~824、829、831、833~939:サービス業,
        Match data:  D: 051~059:鉱業, E: 061~089:建設業, F: 091~329:製造業, G: 331~363:電気・ガス・熱供給・水道業, H: 371~415:情報通信業, I: 421~489:運輸業, J: 491~609:卸売・小売業, K: 611~675:金融・保険業, L: 681~694:不動産業, M: 701~711、713~729:飲食店、宿泊業, N: 731~736、742、749、751、753~759医療・福祉, O: 761~779:教育、学習支援業, P: 781~792:複合サービス業, Q: 801~824、829、831、833~939:サービス業,

----------------------------------------------------------------------*/
capture rename var32 var32


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "初任給用産業番号中"    "初任給用産業番号中"
    Variable Name:  "var33"    "var33" 
    Variable values:
        Base data:   05~93: 産業番号上2桁,
        Match data:  05~93: 産業番号上2桁,

----------------------------------------------------------------------*/
capture rename var33 var33


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "初任給用産業番号小"    "初任給用産業番号小"
    Variable Name:  "var34"    "var34" 
    Variable values:
        Base data:   1,: I481のみ,
        Match data:  1,: I481のみ,

----------------------------------------------------------------------*/
capture rename var34 var34


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "初任給用企業規模"    "初任給用企業規模"
    Variable Name:  "var35"    "var35" 
    Variable values:
        Base data:   T2: 1,000人以上, 53: 100~999人, 76: 10~99人, 88: 5~9人,
        Match data:  T2: 1,000人以上, 53: 100~999人, 76: 10~99人, 88: 5~9人,

----------------------------------------------------------------------*/
capture rename var35 var35


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "確定・未確定"    "確定・未確定"
    Variable Name:  "var36"    "var36" 
    Variable values:
        Base data:   1: 確定, 2: 未確定,
        Match data:  1: 確定, 2: 未確定,

----------------------------------------------------------------------*/
capture rename var36 var36


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var37"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var37


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高卒・男・初任給額"    "高卒・男・初任給額"
    Variable Name:  "var38"    "var38" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var38 var38


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高卒・男・採用人員"    "高卒・男・採用人員"
    Variable Name:  "var39"    "var39" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var39 var39


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高卒・女・初任給額"    "高卒・女・初任給額"
    Variable Name:  "var40"    "var40" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var40 var40


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高卒・女・採用人数"    "高卒・女・採用人数"
    Variable Name:  "var41"    "var41" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var41 var41


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高専短大・男・初任給額"    "高専短大・男・初任給額"
    Variable Name:  "var42"    "var42" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var42 var42


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高専短大・男・採用人数"    "高専短大・男・採用人数"
    Variable Name:  "var43"    "var43" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var43 var43


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高専短大・女・初任給額"    "高専短大・女・初任給額"
    Variable Name:  "var44"    "var44" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var44 var44


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "高専短大・女・採用人数"    "高専短大・女・採用人数"
    Variable Name:  "var45"    "var45" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var45 var45


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・事務系・男・初任給額"    "大卒・事務系・男・初任給額"
    Variable Name:  "var46"    "var46" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var46 var46


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・事務系・男・採用人数"    "大卒・事務系・男・採用人数"
    Variable Name:  "var47"    "var47" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var47 var47


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・事務系・女・初任給額"    "大卒・事務系・女・初任給額"
    Variable Name:  "var48"    "var48" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var48 var48


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・事務系・女・採用人数"    "大卒・事務系・女・採用人数"
    Variable Name:  "var49"    "var49" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var49 var49


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・技術系・男・初任給額"    "大卒・技術系・男・初任給額"
    Variable Name:  "var50"    "var50" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var50 var50


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・技術系・男・採用人数"    "大卒・技術系・男・採用人数"
    Variable Name:  "var51"    "var51" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var51 var51


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・技術系・女・初任給額"    "大卒・技術系・女・初任給額"
    Variable Name:  "var52"    "var52" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var52 var52


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大卒・技術系・女・採用人数"    "大卒・技術系・女・採用人数"
    Variable Name:  "var53"    "var53" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var53 var53


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大学院・男・初任給額"    "大学院・男・初任給額"
    Variable Name:  "var54"    "var54" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var54 var54


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大学院・男・採用人員"    "大学院・男・採用人員"
    Variable Name:  "var55"    "var55" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var55 var55


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大学院・女・初任給額"    "大学院・女・初任給額"
    Variable Name:  "var56"    "var56" 
    Variable values:
        Base data:   0000~9999: (百円),
        Match data:  0000~9999: (百円),

----------------------------------------------------------------------*/
capture rename var56 var56


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "大学院・女・採用人員"    "大学院・女・採用人員"
    Variable Name:  "var57"    "var57" 
    Variable values:
        Base data:   0000~9999: (人),
        Match data:  0000~9999: (人),

----------------------------------------------------------------------*/
capture rename var57 var57


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var58"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var58


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "集計不能コード"    "集計不能コード"
    Variable Name:  "var59"    "var59" 
    Variable values:
        Base data:   1~7、: ,
        Match data:  1~7、: ,

----------------------------------------------------------------------*/
capture rename var59 var59


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "スペース"    "スペース"
    Variable Name:  "var60"    "var60" 
    Variable values:
        Base data:   : ,
        Match data:  : ,

----------------------------------------------------------------------*/
capture rename var60 var60


