/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 
    Date: 2019/04/11 21:04:27
----------------------------------------------------------------------*/



clear all
set more off
capture log close _all

global DoFilePathTemp = "D:/GitHub/MicroDataCleaning/demo/do-files"
global DataFilePathTemp = ""

capture mkdir "${DoFilePathTemp}/log"
log using "${DoFilePathTemp}/log/log.smcl", replace

tempvar data

run "${DoFilePathTemp}/data1/data1_const.do"
run "${DoFilePathTemp}/data1/data1_var.do"
save "${DataFilePathTemp}/data1_str.dta", replace
destring *, replace
run "${DoFilePathTemp}/data1/data1_val.do"
run "${DoFilePathTemp}/data1/data1_validate.do"
save "${DataFilePathTemp}/data1.dta", replace

clear


run "${DoFilePathTemp}/data2/data2_const.do"
run "${DoFilePathTemp}/data2/data2_var.do"
save "${DataFilePathTemp}/data2_str.dta", replace
destring *, replace
run "${DoFilePathTemp}/data2/data2_val.do"
run "${DoFilePathTemp}/data2/data2_validate.do"
save "${DataFilePathTemp}/data2.dta", replace

clear


append using ///
    "${DataFilePathTemp}/data1_str.dta" ///
    "${DataFilePathTemp}/data2_str.dta" ///
    , gen(flag_tmp_NEWVARIABLE)

run "${DoFilePathTemp}/rename.do"
DestringAll
capture drop *_ToBeDropped

*run "${DoFilePathTemp}/data_cleaning/data_cleaning.do"
    // data_cleaning.do should be prepared by yourself

save "${DataFilePathTemp}/data_appended.dta", replace

CheckAppendValidity, data_id(flag_tmp) tol(0.1) stats("mean sd")

macro drop DoFilePathTemp
macro drop DataFilePathTemp
log close

