cap label var SEIREKI "調査西暦年" 
cap label var YOUBI "曜日" 
cap label var C_KEN "都道府県番号" 
cap label var C_KUBAN "調査区番号" 
cap label var SETAI_NO "世帯番号" 
cap label var SETAIIN_NO "世帯員番号" 
cap label var KEN_NO "都道府県番号" 
cap label var CITY_NO "市番号" 
cap label var DAITOSHI "6大都市圏" 
cap label var TOSHIKAIKYU "都市階級符号" 
cap label var TIIKI_14 "14地域区分" 
cap label var KENCHO "県庁所在都市" 
cap label var SEIREI "政令指定都市" 
cap label var SEX "性別" 
cap label var ZOKUGARA "続柄" 
cap label var NENREI "年齢" 
cap label var HAIGUU "配偶者の有無" 
cap label var KYOUIKU "教育" 
cap label var KAIGO "家族の介護･看護" 
cap label var SHYUUGYO_UMU "就業の有無" 
cap label var KIN_JI "勤めか自営の別" 
cap label var SHIGOTO "仕事の種類" 
cap label var JYUUGYOSHA "従業者数" 
cap label var SYUUGYO_JIKAN "一週間の就業時間" 
cap label var SYUUKYU "週休制度" 
cap label var M_IZURENOHI "いずれの日(マトリクス)" 
cap label var JYUUKYO "住居の種類" 
cap label var MY_CAR "自家用車の有無" 
cap label var NENSYU "世帯の年間収入" 
cap label var WEIGHT "乗率(行動・時間)" 
cap label var var1 "FILLER" 
cap label var var2 "行動セル数" 
cap label var var3 "△" 
cap label var  "△" 
cap label var var4_1 "行動時間" 
cap label var var5_1 "符号" 
cap label var var6_1 "FILLER" 
cap label var  "△" 
cap label var var4_2 "行動時間" 
cap label var var5_2 "符号" 
cap label var var6_2 "FILLER" 
cap label var  "△" 
cap label var var4_3 "行動時間" 
cap label var var5_3 "符号" 
cap label var var6_3 "FILLER" 
cap label var  "△" 
cap label var var4_4 "行動時間" 
cap label var var5_4 "符号" 
cap label var var6_4 "FILLER" 
cap label var  "△" 
cap label var var4_5 "行動時間" 
cap label var var5_5 "符号" 
cap label var var6_5 "FILLER" 
cap label var  "△" 
cap label var var4_6 "行動時間" 
cap label var var5_6 "符号" 
cap label var var6_6 "FILLER" 
cap label var  "△" 
cap label var var4_7 "行動時間" 
cap label var var5_7 "符号" 
cap label var var6_7 "FILLER" 
cap label var  "△" 
cap label var var4_8 "行動時間" 
cap label var var5_8 "符号" 
cap label var var6_8 "FILLER" 
cap label var  "△" 
cap label var var4_9 "行動時間" 
cap label var var5_9 "符号" 
cap label var var6_9 "FILLER" 
cap label var  "△" 
cap label var var4_10 "行動時間" 
cap label var var5_10 "符号" 
cap label var var6_10 "FILLER" 
cap label var  "△" 
cap label var var4_11 "行動時間" 
cap label var var5_11 "符号" 
cap label var var6_11 "FILLER" 
cap label var  "△" 
cap label var var4_12 "行動時間" 
cap label var var5_12 "符号" 
cap label var var6_12 "FILLER" 
cap label var  "△" 
cap label var var4_13 "行動時間" 
cap label var var5_13 "符号" 
cap label var var6_13 "FILLER" 
cap label var  "△" 
cap label var var4_14 "行動時間" 
cap label var var5_14 "符号" 
cap label var var6_14 "FILLER" 
cap label var  "△" 
cap label var var4_15 "行動時間" 
cap label var var5_15 "符号" 
cap label var var6_15 "FILLER" 
cap label var  "△" 
cap label var var4_16 "行動時間" 
cap label var var5_16 "符号" 
cap label var var6_16 "FILLER" 
cap label var  "△" 
cap label var var4_17 "行動時間" 
cap label var var5_17 "符号" 
cap label var var6_17 "FILLER" 
cap label var  "△" 
cap label var var4_18 "行動時間" 
cap label var var5_18 "符号" 
cap label var var6_18 "FILLER" 
cap label var  "△" 
cap label var var4_19 "行動時間" 
cap label var var5_19 "符号" 
cap label var var6_19 "FILLER" 
cap label var  "△" 
cap label var var4_20 "行動時間" 
cap label var var5_20 "符号" 
cap label var var6_20 "FILLER" 
cap label var  "△" 
cap label var var4_21 "行動時間" 
cap label var var5_21 "符号" 
cap label var var6_21 "FILLER" 
cap label var  "△" 
cap label var var4_22 "行動時間" 
cap label var var5_22 "符号" 
cap label var var6_22 "FILLER" 
cap label var  "△" 
cap label var var4_23 "行動時間" 
cap label var var5_23 "符号" 
cap label var var6_23 "FILLER" 
cap label var  "△" 
cap label var var4_24 "行動時間" 
cap label var var5_24 "符号" 
cap label var var6_24 "FILLER" 
cap label var  "△" 
cap label var var4_25 "行動時間" 
cap label var var5_25 "符号" 
cap label var var6_25 "FILLER" 
cap label var  "△" 
cap label var var4_26 "行動時間" 
cap label var var5_26 "符号" 
cap label var var6_26 "FILLER" 
cap label var  "△" 
cap label var var4_27 "行動時間" 
cap label var var5_27 "符号" 
cap label var var6_27 "FILLER" 
cap label var  "△" 
cap label var var4_28 "行動時間" 
cap label var var5_28 "符号" 
cap label var var6_28 "FILLER" 
cap label var  "△" 
cap label var var4_29 "行動時間" 
cap label var var5_29 "符号" 
cap label var var6_29 "FILLER" 
cap label var  "△" 
cap label var var4_30 "行動時間" 
cap label var var5_30 "符号" 
cap label var var6_30 "FILLER" 
cap label var  "△" 
cap label var var4_31 "行動時間" 
cap label var var5_31 "符号" 
cap label var var6_31 "FILLER" 
cap label var  "△" 
cap label var var4_32 "行動時間" 
cap label var var5_32 "符号" 
cap label var var6_32 "FILLER" 
cap label var  "△" 
cap label var var4_33 "行動時間" 
cap label var var5_33 "符号" 
cap label var var6_33 "FILLER" 
cap label var  "△" 
cap label var var4_34 "行動時間" 
cap label var var5_34 "符号" 
cap label var var6_34 "FILLER" 
cap label var  "△" 
cap label var var4_35 "行動時間" 
cap label var var5_35 "符号" 
cap label var var6_35 "FILLER" 
cap label var  "△" 
cap label var var4_36 "行動時間" 
cap label var var5_36 "符号" 
cap label var var6_36 "FILLER" 
cap label var  "△" 
cap label var var4_37 "行動時間" 
cap label var var5_37 "符号" 
cap label var var6_37 "FILLER" 
cap label var  "△" 
cap label var var4_38 "行動時間" 
cap label var var5_38 "符号" 
cap label var var6_38 "FILLER" 
cap label var  "△" 
cap label var var4_39 "行動時間" 
cap label var var5_39 "符号" 
cap label var var6_39 "FILLER" 
cap label var  "△" 
cap label var var4_40 "行動時間" 
cap label var var5_40 "符号" 
cap label var var6_40 "FILLER" 
cap label var  "△" 
cap label var var4_41 "行動時間" 
cap label var var5_41 "符号" 
cap label var var6_41 "FILLER" 
cap label var  "△" 
cap label var var4_42 "行動時間" 
cap label var var5_42 "符号" 
cap label var var6_42 "FILLER" 
cap label var  "△" 
cap label var var4_43 "行動時間" 
cap label var var5_43 "符号" 
cap label var var6_43 "FILLER" 
cap label var  "△" 
cap label var var4_44 "行動時間" 
cap label var var5_44 "符号" 
cap label var var6_44 "FILLER" 
cap label var  "△" 
cap label var var4_45 "行動時間" 
cap label var var5_45 "符号" 
cap label var var6_45 "FILLER" 
cap label var  "△" 
cap label var var4_46 "行動時間" 
cap label var var5_46 "符号" 
cap label var var6_46 "FILLER" 
cap label var  "△" 
cap label var var4_47 "行動時間" 
cap label var var5_47 "符号" 
cap label var var6_47 "FILLER" 
cap label var  "△" 
cap label var var4_48 "行動時間" 
cap label var var5_48 "符号" 
cap label var var6_48 "FILLER" 
cap label var  "△" 
cap label var var4_49 "行動時間" 
cap label var var5_49 "符号" 
cap label var var6_49 "FILLER" 
cap label var  "△" 
cap label var var4_50 "行動時間" 
cap label var var5_50 "符号" 
cap label var var6_50 "FILLER" 
cap label var  "△" 
cap label var var4_51 "行動時間" 
cap label var var5_51 "符号" 
cap label var var6_51 "FILLER" 
cap label var  "△" 
cap label var var4_52 "行動時間" 
cap label var var5_52 "符号" 
cap label var var6_52 "FILLER" 
cap label var  "△" 
cap label var var4_53 "行動時間" 
cap label var var5_53 "符号" 
cap label var var6_53 "FILLER" 
cap label var  "△" 
cap label var var4_54 "行動時間" 
cap label var var5_54 "符号" 
cap label var var6_54 "FILLER" 
cap label var  "△" 
cap label var var4_55 "行動時間" 
cap label var var5_55 "符号" 
cap label var var6_55 "FILLER" 
cap label var  "△" 
cap label var var4_56 "行動時間" 
cap label var var5_56 "符号" 
cap label var var6_56 "FILLER" 
cap label var  "△" 
cap label var var4_57 "行動時間" 
cap label var var5_57 "符号" 
cap label var var6_57 "FILLER" 
cap label var  "△" 
cap label var var4_58 "行動時間" 
cap label var var5_58 "符号" 
cap label var var6_58 "FILLER" 
cap label var  "△" 
cap label var var4_59 "行動時間" 
cap label var var5_59 "符号" 
cap label var var6_59 "FILLER" 
cap label var  "△" 
cap label var var4_60 "行動時間" 
cap label var var5_60 "符号" 
cap label var var6_60 "FILLER" 
cap label var  "△" 
cap label var var4_61 "行動時間" 
cap label var var5_61 "符号" 
cap label var var6_61 "FILLER" 
cap label var  "△" 
cap label var var4_62 "行動時間" 
cap label var var5_62 "符号" 
cap label var var6_62 "FILLER" 
cap label var  "△" 
cap label var var4_63 "行動時間" 
cap label var var5_63 "符号" 
cap label var var6_63 "FILLER" 
cap label var  "△" 
cap label var var4_64 "行動時間" 
cap label var var5_64 "符号" 
cap label var var6_64 "FILLER" 
cap label var  "△" 
cap label var var4_65 "行動時間" 
cap label var var5_65 "符号" 
cap label var var6_65 "FILLER" 
cap label var  "△" 
cap label var var4_66 "行動時間" 
cap label var var5_66 "符号" 
cap label var var6_66 "FILLER" 
cap label var  "△" 
cap label var var4_67 "行動時間" 
cap label var var5_67 "符号" 
cap label var var6_67 "FILLER" 
cap label var  "△" 
cap label var var4_68 "行動時間" 
cap label var var5_68 "符号" 
cap label var var6_68 "FILLER" 
cap label var  "△" 
cap label var var4_69 "行動時間" 
cap label var var5_69 "符号" 
cap label var var6_69 "FILLER" 
cap label var  "△" 
cap label var var4_70 "行動時間" 
cap label var var5_70 "符号" 
cap label var var6_70 "FILLER" 
cap label var  "△" 
cap label var var4_71 "行動時間" 
cap label var var5_71 "符号" 
cap label var var6_71 "FILLER" 
cap label var  "△" 
cap label var var4_72 "行動時間" 
cap label var var5_72 "符号" 
cap label var var6_72 "FILLER" 
cap label var  "△" 
cap label var var4_73 "行動時間" 
cap label var var5_73 "符号" 
cap label var var6_73 "FILLER" 
cap label var  "△" 
cap label var var4_74 "行動時間" 
cap label var var5_74 "符号" 
cap label var var6_74 "FILLER" 
cap label var  "△" 
cap label var var4_75 "行動時間" 
cap label var var5_75 "符号" 
cap label var var6_75 "FILLER" 
cap label var  "△" 
cap label var var4_76 "行動時間" 
cap label var var5_76 "符号" 
cap label var var6_76 "FILLER" 
cap label var  "△" 
cap label var var4_77 "行動時間" 
cap label var var5_77 "符号" 
cap label var var6_77 "FILLER" 
cap label var  "△" 
cap label var var4_78 "行動時間" 
cap label var var5_78 "符号" 
cap label var var6_78 "FILLER" 
cap label var  "△" 
cap label var var4_79 "行動時間" 
cap label var var5_79 "符号" 
cap label var var6_79 "FILLER" 
cap label var  "△" 
cap label var var4_80 "行動時間" 
cap label var var5_80 "符号" 
cap label var var6_80 "FILLER" 
cap label var  "△" 
cap label var var4_81 "行動時間" 
cap label var var5_81 "符号" 
cap label var var6_81 "FILLER" 
cap label var  "△" 
cap label var var4_82 "行動時間" 
cap label var var5_82 "符号" 
cap label var var6_82 "FILLER" 
cap label var  "△" 
cap label var var4_83 "行動時間" 
cap label var var5_83 "符号" 
cap label var var6_83 "FILLER" 
cap label var  "△" 
cap label var var4_84 "行動時間" 
cap label var var5_84 "符号" 
cap label var var6_84 "FILLER" 
cap label var  "△" 
cap label var var4_85 "行動時間" 
cap label var var5_85 "符号" 
cap label var var6_85 "FILLER" 
cap label var  "△" 
cap label var var4_86 "行動時間" 
cap label var var5_86 "符号" 
cap label var var6_86 "FILLER" 
cap label var  "△" 
cap label var var4_87 "行動時間" 
cap label var var5_87 "符号" 
cap label var var6_87 "FILLER" 
cap label var  "△" 
cap label var var4_88 "行動時間" 
cap label var var5_88 "符号" 
cap label var var6_88 "FILLER" 
cap label var  "△" 
cap label var var4_89 "行動時間" 
cap label var var5_89 "符号" 
cap label var var6_89 "FILLER" 
cap label var  "△" 
cap label var var4_90 "行動時間" 
cap label var var5_90 "符号" 
cap label var var6_90 "FILLER" 
cap label var  "△" 
cap label var var4_91 "行動時間" 
cap label var var5_91 "符号" 
cap label var var6_91 "FILLER" 
cap label var  "△" 
cap label var var4_92 "行動時間" 
cap label var var5_92 "符号" 
cap label var var6_92 "FILLER" 
cap label var  "△" 
cap label var var4_93 "行動時間" 
cap label var var5_93 "符号" 
cap label var var6_93 "FILLER" 
cap label var  "△" 
cap label var var4_94 "行動時間" 
cap label var var5_94 "符号" 
cap label var var6_94 "FILLER" 
cap label var  "△" 
cap label var var4_95 "行動時間" 
cap label var var5_95 "符号" 
cap label var var6_95 "FILLER" 
cap label var  "△" 
cap label var var4_96 "行動時間" 
cap label var var5_96 "符号" 
cap label var var6_96 "FILLER" 
