/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/ESSレイアウト/h9.xls
    Date: 2019/08/15 18:51:21
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str var1 4-7
        str var2 8-9
        str var3 12-13
        str var4 14-16
        str var5 17-18
        str var6 19-22
        str var7 72-84
        str var8 87-88
        str var9 89-90
        str var10 93-93
        str var11 96-97
        str var12 107-107
        str var13 108-108
        str var14 109-109
        str var15 110-110
        str var16 111-111
        str var17 112-112
        str var18 113-113
        str var19 114-114
        str var20 115-115
        str var21 116-116
        str var22 117-117
        str var23 118-118
        str var24 119-119
        str var25 120-120
        str var26 121-121
        str var27 122-123
        str var28 124-125
        str var29 146-147
        str var30 148-148
        str var31 149-149
        str var32 150-150
        str var33 151-151
        str var34 152-152
        str var35 153-153
        str var36 154-154
        str var37 155-155
        str var38 156-156
        str var39 157-157
        str var40 160-161
        str var41 167-167
        str var42 168-169
        str var43 170-170
        str var44 171-172
        str var45 173-173
        str var46 174-176
        str var47 177-178
        str var48 179-179
        str var49 180-180
        str var50 181-181
        str var51 182-183
        str var52 186-186
        str var53 187-187
        str var54 190-190
        str var55 201-201
        str var56 202-202
        str var57 204-204
        str var58 206-206
        str var59 207-208
        str var60 209-210
        str var61 211-212
        str var62 213-214
        str var63 215-216
        str var64 217-217
        str var65 218-218
        str var66 219-219
        str var67 220-221
        str var68 222-222
        str var69 223-223
        str var70 224-224
        str var71 225-225
        str var72 226-226
        str var73 229-229
        str var74 230-230
        str var75 232-232
        str var76 233-234
        str var77 235-236
        str var78 240-240
        str var79 241-242
        str var80 243-244
        str var81 245-245
        str var82 246-246
        str var83 247-247
        str var84 251-251
        str var85 252-252
        str var86 253-253
        str var87 254-254
        str var88 255-255
        str var89 256-256
        str var90 257-257
        str var91 258-258
        str var92 259-259
        str var93 260-260
        str var94 261-261
        str var95 265-265
        str var96 266-266
        str var97 267-268
        str var98 277-278
        str var99 279-279
        str var100 281-282
        str var101 283-284
        str var102 285-286
        str var103 287-288
        str var104 289-290
        str var105 291-292
        str var106 293-294
    using "${DataFilePathTemp}/L5_1997_RCD_DA2-kk_A_S.TXT";
#delimit cr
