/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/08/15 18:51:21
-----------------------------------------------------------------------------*/


capture count if var1==.
if r(N)==_N {
    display as error "Only missing value: {bf:var1} (調査年)"
}
capture assert inlist(var1, 1997, .)
if _rc!=0 {
    display as error "WARNING: {bf:var1} (調査年) may have invalid values (Check layout sheet)"
}


capture count if var2==.
if r(N)==_N {
    display as error "Only missing value: {bf:var2} (調査月)"
}
capture assert inlist(var2, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:var2} (調査月) may have invalid values (Check layout sheet)"
}


capture count if var3==.
if r(N)==_N {
    display as error "Only missing value: {bf:var3} (都道府県番号)"
}


capture count if var4==.
if r(N)==_N {
    display as error "Only missing value: {bf:var4} (市区町村番号)"
}


capture count if var5==.
if r(N)==_N {
    display as error "Only missing value: {bf:var5} (県番号)"
}


capture count if var6==.
if r(N)==_N {
    display as error "Only missing value: {bf:var6} (県内一連番号)"
}


capture count if var7==.
if r(N)==_N {
    display as error "Only missing value: {bf:var7} (集計用乗率)"
}


capture count if var8==.
if r(N)==_N {
    display as error "Only missing value: {bf:var8} (世帯番号)"
}


capture count if var9==.
if r(N)==_N {
    display as error "Only missing value: {bf:var9} (世帯員番号)"
}


capture count if var10==.
if r(N)==_N {
    display as error "Only missing value: {bf:var10} (一般・単身の別)"
}
capture assert inlist(var10, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var10} (一般・単身の別) may have invalid values (Check layout sheet)"
}


capture count if var11==.
if r(N)==_N {
    display as error "Only missing value: {bf:var11} (17区分)"
}
capture assert inlist(var11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, .)
if _rc!=0 {
    display as error "WARNING: {bf:var11} (17区分) may have invalid values (Check layout sheet)"
}


capture count if var12==.
if r(N)==_N {
    display as error "Only missing value: {bf:var12} (0歳)"
}
capture assert inlist(var12, 0, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var12} (0歳) may have invalid values (Check layout sheet)"
}


capture count if var13==.
if r(N)==_N {
    display as error "Only missing value: {bf:var13} (1歳)"
}


capture count if var14==.
if r(N)==_N {
    display as error "Only missing value: {bf:var14} (2歳)"
}


capture count if var15==.
if r(N)==_N {
    display as error "Only missing value: {bf:var15} (3歳)"
}


capture count if var16==.
if r(N)==_N {
    display as error "Only missing value: {bf:var16} (4歳)"
}


capture count if var17==.
if r(N)==_N {
    display as error "Only missing value: {bf:var17} (5歳)"
}


capture count if var18==.
if r(N)==_N {
    display as error "Only missing value: {bf:var18} (6歳)"
}


capture count if var19==.
if r(N)==_N {
    display as error "Only missing value: {bf:var19} (7歳)"
}


capture count if var20==.
if r(N)==_N {
    display as error "Only missing value: {bf:var20} (8歳)"
}


capture count if var21==.
if r(N)==_N {
    display as error "Only missing value: {bf:var21} (9歳)"
}


capture count if var22==.
if r(N)==_N {
    display as error "Only missing value: {bf:var22} (10歳)"
}


capture count if var23==.
if r(N)==_N {
    display as error "Only missing value: {bf:var23} (11歳)"
}


capture count if var24==.
if r(N)==_N {
    display as error "Only missing value: {bf:var24} (12歳)"
}


capture count if var25==.
if r(N)==_N {
    display as error "Only missing value: {bf:var25} (13歳)"
}


capture count if var26==.
if r(N)==_N {
    display as error "Only missing value: {bf:var26} (14歳)"
}


capture count if var27==.
if r(N)==_N {
    display as error "Only missing value: {bf:var27} (15歳未満の合計)"
}


capture count if var28==.
if r(N)==_N {
    display as error "Only missing value: {bf:var28} (15歳以上の合計)"
}


capture count if var29==.
if r(N)==_N {
    display as error "Only missing value: {bf:var29} (おもな収入)"
}
capture assert inlist(var29, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, .)
if _rc!=0 {
    display as error "WARNING: {bf:var29} (おもな収入) may have invalid values (Check layout sheet)"
}


capture count if var30==.
if r(N)==_N {
    display as error "Only missing value: {bf:var30} (賃金・給料)"
}


capture count if var31==.
if r(N)==_N {
    display as error "Only missing value: {bf:var31} (農業)"
}


capture count if var32==.
if r(N)==_N {
    display as error "Only missing value: {bf:var32} (その他の事業)"
}


capture count if var33==.
if r(N)==_N {
    display as error "Only missing value: {bf:var33} (内職)"
}


capture count if var34==.
if r(N)==_N {
    display as error "Only missing value: {bf:var34} (家賃・地代)"
}


capture count if var35==.
if r(N)==_N {
    display as error "Only missing value: {bf:var35} (利子・配当)"
}


capture count if var36==.
if r(N)==_N {
    display as error "Only missing value: {bf:var36} (恩給・年金)"
}


capture count if var37==.
if r(N)==_N {
    display as error "Only missing value: {bf:var37} (雇用保険)"
}


capture count if var38==.
if r(N)==_N {
    display as error "Only missing value: {bf:var38} (仕送り)"
}


capture count if var39==.
if r(N)==_N {
    display as error "Only missing value: {bf:var39} (その他)"
}


capture count if var40==.
if r(N)==_N {
    display as error "Only missing value: {bf:var40} (世帯の収入階級)"
}
capture assert inlist(var40, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:var40} (世帯の収入階級) may have invalid values (Check layout sheet)"
}


capture count if var41==.
if r(N)==_N {
    display as error "Only missing value: {bf:var41} (性別)"
}
capture assert inlist(var41, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var41} (性別) may have invalid values (Check layout sheet)"
}


capture count if var42==.
if r(N)==_N {
    display as error "Only missing value: {bf:var42} (続き柄)"
}
capture assert inlist(var42, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:var42} (続き柄) may have invalid values (Check layout sheet)"
}


capture count if var43==.
if r(N)==_N {
    display as error "Only missing value: {bf:var43} (元号)"
}
capture assert inlist(var43, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var43} (元号) may have invalid values (Check layout sheet)"
}


capture count if var44==.
if r(N)==_N {
    display as error "Only missing value: {bf:var44} (年)"
}


capture count if var45==.
if r(N)==_N {
    display as error "Only missing value: {bf:var45} (月区分)"
}
capture assert inlist(var45, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:var45} (月区分) may have invalid values (Check layout sheet)"
}


capture count if var46==.
if r(N)==_N {
    display as error "Only missing value: {bf:var46} (各歳)"
}


capture count if var47==.
if r(N)==_N {
    display as error "Only missing value: {bf:var47} (5歳階級)"
}
capture assert inlist(var47, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, .)
if _rc!=0 {
    display as error "WARNING: {bf:var47} (5歳階級) may have invalid values (Check layout sheet)"
}


capture count if var48==.
if r(N)==_N {
    display as error "Only missing value: {bf:var48} (10歳階級)"
}
capture assert inlist(var48, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:var48} (10歳階級) may have invalid values (Check layout sheet)"
}


capture count if var49==.
if r(N)==_N {
    display as error "Only missing value: {bf:var49} (配偶者の有無)"
}
capture assert inlist(var49, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var49} (配偶者の有無) may have invalid values (Check layout sheet)"
}


capture count if var50==.
if r(N)==_N {
    display as error "Only missing value: {bf:var50} (区分)"
}
capture assert inlist(var50, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var50} (区分) may have invalid values (Check layout sheet)"
}


capture count if var51==.
if r(N)==_N {
    display as error "Only missing value: {bf:var51} (県番号)"
}


capture count if var52==.
if r(N)==_N {
    display as error "Only missing value: {bf:var52} (教育区分)"
}
capture assert inlist(var52, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var52} (教育区分) may have invalid values (Check layout sheet)"
}


capture count if var53==.
if r(N)==_N {
    display as error "Only missing value: {bf:var53} (学校区分)"
}
capture assert inlist(var53, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:var53} (学校区分) may have invalid values (Check layout sheet)"
}


capture count if var54==.
if r(N)==_N {
    display as error "Only missing value: {bf:var54} (就業状態)"
}
capture assert inlist(var54, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var54} (就業状態) may have invalid values (Check layout sheet)"
}


capture count if var55==.
if r(N)==_N {
    display as error "Only missing value: {bf:var55} (8区分)"
}
capture assert inlist(var55, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var55} (8区分) may have invalid values (Check layout sheet)"
}


capture count if var56==.
if r(N)==_N {
    display as error "Only missing value: {bf:var56} (7区分)"
}
capture assert inlist(var56, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var56} (7区分) may have invalid values (Check layout sheet)"
}


capture count if var57==.
if r(N)==_N {
    display as error "Only missing value: {bf:var57} (経営組織)"
}
capture assert inlist(var57, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:var57} (経営組織) may have invalid values (Check layout sheet)"
}


capture count if var58==.
if r(N)==_N {
    display as error "Only missing value: {bf:var58} (農林・非農林)"
}
capture assert inlist(var58, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var58} (農林・非農林) may have invalid values (Check layout sheet)"
}


capture count if var59==.
if r(N)==_N {
    display as error "Only missing value: {bf:var59} (大分類)"
}
capture assert inlist(var59, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, .)
if _rc!=0 {
    display as error "WARNING: {bf:var59} (大分類) may have invalid values (Check layout sheet)"
}


capture count if var60==.
if r(N)==_N {
    display as error "Only missing value: {bf:var60} (中分類)"
}
capture assert inlist(var60, 1, 2, 3, 5, 9, 12, 14, 16, 18, 19, 20, 22, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 39, 40, 46, 47, 48, 54, 55, 56, 59, 60, 62, 70, 74, 75, 76, 77, 81, 84, 86, 88, 90, 91, 93, 95, 97, .)
if _rc!=0 {
    display as error "WARNING: {bf:var60} (中分類) may have invalid values (Check layout sheet)"
}


capture count if var61==.
if r(N)==_N {
    display as error "Only missing value: {bf:var61} (大分類)"
}
capture assert inlist(var61, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:var61} (大分類) may have invalid values (Check layout sheet)"
}


capture count if var62==.
if r(N)==_N {
    display as error "Only missing value: {bf:var62} (中分類)"
}
capture assert inlist(var62, 1, 2, 4, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var62} (中分類) may have invalid values (Check layout sheet)"
}


capture count if var63==.
if r(N)==_N {
    display as error "Only missing value: {bf:var63} (従業者規模)"
}
capture assert inlist(var63, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:var63} (従業者規模) may have invalid values (Check layout sheet)"
}


capture count if var64==.
if r(N)==_N {
    display as error "Only missing value: {bf:var64} (年間就業日数)"
}
capture assert inlist(var64, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:var64} (年間就業日数) may have invalid values (Check layout sheet)"
}


capture count if var65==.
if r(N)==_N {
    display as error "Only missing value: {bf:var65} (就業の規則性)"
}
capture assert inlist(var65, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var65} (就業の規則性) may have invalid values (Check layout sheet)"
}


capture count if var66==.
if r(N)==_N {
    display as error "Only missing value: {bf:var66} (週間就業時間)"
}
capture assert inlist(var66, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var66} (週間就業時間) may have invalid values (Check layout sheet)"
}


capture count if var67==.
if r(N)==_N {
    display as error "Only missing value: {bf:var67} (個人所得)"
}
capture assert inlist(var67, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, .)
if _rc!=0 {
    display as error "WARNING: {bf:var67} (個人所得) may have invalid values (Check layout sheet)"
}


capture count if var68==.
if r(N)==_N {
    display as error "Only missing value: {bf:var68} (就業希望意識)"
}
capture assert inlist(var68, 1, 2, 3, 4, .)
if _rc!=0 {
    display as error "WARNING: {bf:var68} (就業希望意識) may have invalid values (Check layout sheet)"
}


capture count if var69==.
if r(N)==_N {
    display as error "Only missing value: {bf:var69} (就業時間希望)"
}
capture assert inlist(var69, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var69} (就業時間希望) may have invalid values (Check layout sheet)"
}


capture count if var70==.
if r(N)==_N {
    display as error "Only missing value: {bf:var70} (転職希望理由)"
}
capture assert inlist(var70, 1, 2, 3, 4, 5, 6, 7, 8, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:var70} (転職希望理由) may have invalid values (Check layout sheet)"
}


capture count if var71==.
if r(N)==_N {
    display as error "Only missing value: {bf:var71} (希望仕事形態)"
}
capture assert inlist(var71, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:var71} (希望仕事形態) may have invalid values (Check layout sheet)"
}


capture count if var72==.
if r(N)==_N {
    display as error "Only missing value: {bf:var72} (求職活動の有無)"
}
capture assert inlist(var72, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var72} (求職活動の有無) may have invalid values (Check layout sheet)"
}


capture count if var73==.
if r(N)==_N {
    display as error "Only missing value: {bf:var73} (副業の有無)"
}
capture assert inlist(var73, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var73} (副業の有無) may have invalid values (Check layout sheet)"
}


capture count if var74==.
if r(N)==_N {
    display as error "Only missing value: {bf:var74} (5区分)"
}
capture assert inlist(var74, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var74} (5区分) may have invalid values (Check layout sheet)"
}


capture count if var75==.
if r(N)==_N {
    display as error "Only missing value: {bf:var75} (農林・非農林)"
}


capture count if var76==.
if r(N)==_N {
    display as error "Only missing value: {bf:var76} (大分類)"
}


capture count if var77==.
if r(N)==_N {
    display as error "Only missing value: {bf:var77} (中分類)"
}


capture count if var78==.
if r(N)==_N {
    display as error "Only missing value: {bf:var78} (継続就業か否か)"
}
capture assert inlist(var78, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var78} (継続就業か否か) may have invalid values (Check layout sheet)"
}


capture count if var79==.
if r(N)==_N {
    display as error "Only missing value: {bf:var79} (区分)"
}
capture assert inlist(var79, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, .)
if _rc!=0 {
    display as error "WARNING: {bf:var79} (区分) may have invalid values (Check layout sheet)"
}


capture count if var80==.
if r(N)==_N {
    display as error "Only missing value: {bf:var80} (年)"
}


capture count if var81==.
if r(N)==_N {
    display as error "Only missing value: {bf:var81} (1年前の就業状況)"
}
capture assert inlist(var81, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var81} (1年前の就業状況) may have invalid values (Check layout sheet)"
}


capture count if var82==.
if r(N)==_N {
    display as error "Only missing value: {bf:var82} (新規就業理由)"
}
capture assert inlist(var82, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var82} (新規就業理由) may have invalid values (Check layout sheet)"
}


capture count if var83==.
if r(N)==_N {
    display as error "Only missing value: {bf:var83} (前職の有無)"
}
capture assert inlist(var83, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var83} (前職の有無) may have invalid values (Check layout sheet)"
}


capture count if var84==.
if r(N)==_N {
    display as error "Only missing value: {bf:var84} (有無)"
}
capture assert inlist(var84, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var84} (有無) may have invalid values (Check layout sheet)"
}


capture count if var85==.
if r(N)==_N {
    display as error "Only missing value: {bf:var85} (理由)"
}
capture assert inlist(var85, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var85} (理由) may have invalid values (Check layout sheet)"
}


capture count if var86==.
if r(N)==_N {
    display as error "Only missing value: {bf:var86} (仕事の主従)"
}
capture assert inlist(var86, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var86} (仕事の主従) may have invalid values (Check layout sheet)"
}


capture count if var87==.
if r(N)==_N {
    display as error "Only missing value: {bf:var87} (仕事の形態)"
}
capture assert inlist(var87, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:var87} (仕事の形態) may have invalid values (Check layout sheet)"
}


capture count if var88==.
if r(N)==_N {
    display as error "Only missing value: {bf:var88} (有無)"
}
capture assert inlist(var88, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var88} (有無) may have invalid values (Check layout sheet)"
}


capture count if var89==.
if r(N)==_N {
    display as error "Only missing value: {bf:var89} (非求職理由)"
}
capture assert inlist(var89, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var89} (非求職理由) may have invalid values (Check layout sheet)"
}


capture count if var90==.
if r(N)==_N {
    display as error "Only missing value: {bf:var90} (求職方法)"
}
capture assert inlist(var90, 1, 2, 3, 4, 5, 6, 7, .)
if _rc!=0 {
    display as error "WARNING: {bf:var90} (求職方法) may have invalid values (Check layout sheet)"
}


capture count if var91==.
if r(N)==_N {
    display as error "Only missing value: {bf:var91} (求職期間)"
}
capture assert inlist(var91, 1, 2, 3, 4, 5, 6, .)
if _rc!=0 {
    display as error "WARNING: {bf:var91} (求職期間) may have invalid values (Check layout sheet)"
}


capture count if var92==.
if r(N)==_N {
    display as error "Only missing value: {bf:var92} (就業希望時期)"
}
capture assert inlist(var92, 1, 2, 3, .)
if _rc!=0 {
    display as error "WARNING: {bf:var92} (就業希望時期) may have invalid values (Check layout sheet)"
}


capture count if var93==.
if r(N)==_N {
    display as error "Only missing value: {bf:var93} (1年前の就業状況)"
}
capture assert inlist(var93, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var93} (1年前の就業状況) may have invalid values (Check layout sheet)"
}


capture count if var94==.
if r(N)==_N {
    display as error "Only missing value: {bf:var94} (前職の有無)"
}
capture assert inlist(var94, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var94} (前職の有無) may have invalid values (Check layout sheet)"
}


capture count if var95==.
if r(N)==_N {
    display as error "Only missing value: {bf:var95} (区分)"
}
capture assert inlist(var95, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var95} (区分) may have invalid values (Check layout sheet)"
}


capture count if var96==.
if r(N)==_N {
    display as error "Only missing value: {bf:var96} (元号)"
}
capture assert inlist(var96, 1, 2, .)
if _rc!=0 {
    display as error "WARNING: {bf:var96} (元号) may have invalid values (Check layout sheet)"
}


capture count if var97==.
if r(N)==_N {
    display as error "Only missing value: {bf:var97} (年)"
}


capture count if var98==.
if r(N)==_N {
    display as error "Only missing value: {bf:var98} (離職理由)"
}
capture assert inlist(var98, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, .)
if _rc!=0 {
    display as error "WARNING: {bf:var98} (離職理由) may have invalid values (Check layout sheet)"
}


capture count if var99==.
if r(N)==_N {
    display as error "Only missing value: {bf:var99} (8区分)"
}


capture count if var100==.
if r(N)==_N {
    display as error "Only missing value: {bf:var100} (大分類)"
}


capture count if var101==.
if r(N)==_N {
    display as error "Only missing value: {bf:var101} (中分類)"
}


capture count if var102==.
if r(N)==_N {
    display as error "Only missing value: {bf:var102} (大分類)"
}


capture count if var103==.
if r(N)==_N {
    display as error "Only missing value: {bf:var103} (中分類)"
}


capture count if var104==.
if r(N)==_N {
    display as error "Only missing value: {bf:var104} (従業者規模)"
}


capture count if var105==.
if r(N)==_N {
    display as error "Only missing value: {bf:var105} (区分)"
}
capture assert inlist(var105, 0, 1, 2, 3, 4, 5, 6, 7, 8, .)
if _rc!=0 {
    display as error "WARNING: {bf:var105} (区分) may have invalid values (Check layout sheet)"
}


capture count if var106==.
if r(N)==_N {
    display as error "Only missing value: {bf:var106} (年)"
}


