capture label variable var1 "調査年"
capture label variable var2 "調査コード"
capture label variable var3 "県番号"
capture label variable var4 "地区番号"
capture label variable var5 "単位区番号"
capture label variable var6 "世帯番号"
capture label variable var7 "スペース１"
capture label variable var8 "世帯内の認定者数"
capture label variable var9 "介護認定者の年齢"
capture label variable var10 "現在の要介護度"
capture label variable var11 "介護保険所得段階"
capture label variable var12 "収入"
capture label variable var13 "貯蓄"
capture label variable var14 "収・貯以外"
capture label variable var15 "年金・恩給"
capture label variable var16 "年・恩以外"
capture label variable var17 "介護認定者の年齢"
capture label variable var18 "現在の要介護度"
capture label variable var19 "介護サービス利用有無"
capture label variable var20 "1 家族介護で何とかやっていける"
capture label variable var21 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var22 "3 他人を家に入れたくない"
capture label variable var23 "4 外出するのが大変"
capture label variable var24 "5　どのようなサービスがあるかわからない"
capture label variable var25 "6 サービスを受ける手続きがわからない"
capture label variable var26 "7 利用者負担が払えない"
capture label variable var27 "8 受けたいサービスがない"
capture label variable var28 "9 入院していた"
capture label variable var29 "10 その他"
capture label variable var30 "11 不詳"
capture label variable var31 "費用額"
capture label variable var32 "介護保険所得段階"
capture label variable var33 "収入"
capture label variable var34 "貯蓄"
capture label variable var35 "収・貯以外"
capture label variable var36 "年金・恩給"
capture label variable var37 "年・恩以外"
capture label variable var38 "スペース２"
capture label variable var39 "拡大乗数"
capture label variable var40 "スペース３"
capture label variable var41_1 "介護票認定者番号"
capture label variable var42_1 "世帯票世帯員番号"
capture label variable var43_1 "調査票の回答者"
capture label variable var44_1 "性別"
capture label variable var45_1 "元号"
capture label variable var46_1 "年"
capture label variable var47_1 "月"
capture label variable var48_1 "年齢"
capture label variable var49_1 "配偶者の有無"
capture label variable var50_1 "変化"
capture label variable var51_1 "現在"
capture label variable var52_1 "１年前"
capture label variable var53_1 "1脳血管疾患（脳卒中）"
capture label variable var54_1 "2心疾患（心臓病）"
capture label variable var55_1 "3悪性新生物（がん）"
capture label variable var56_1 "4呼吸器疾患"
capture label variable var57_1 "5関節疾患"
capture label variable var58_1 "6認知症"
capture label variable var59_1 "7パーキンソン病"
capture label variable var60_1 "8糖尿病"
capture label variable var61_1 "9視覚・聴覚障害"
capture label variable var62_1 "10骨折・転倒"
capture label variable var63_1 "11脊髄損傷"
capture label variable var64_1 "12高齢による衰弱"
capture label variable var65_1 "13その他"
capture label variable var66_1 "14わからない"
capture label variable var67_1 "介護が必要となった主な原因"
capture label variable var68_1 "利用の有無"
capture label variable var69_1 "1 訪問系サービス"
capture label variable var70_1 "2 通所系サービス"
capture label variable var71_1 "3 短期入所サービス"
capture label variable var72_1 "4 居住系サービス（グループホーム）"
capture label variable var73_1 "5 小規模多機能型サービス等"
capture label variable var74_1 "6 配食サービス"
capture label variable var75_1 "7 外出支援サービス"
capture label variable var76_1 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_1 "1 家族介護で何とかやっていける"
capture label variable var78_1 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_1 "3 他人を家に入れたくない"
capture label variable var80_1 "4 外出するのが大変"
capture label variable var81_1 "5 どのようなサービスがあるかわからない"
capture label variable var82_1 "6 サービスを受ける手続きがわからない"
capture label variable var83_1 "7 利用者負担が払えない"
capture label variable var84_1 "8 受けたいサービスがない"
capture label variable var85_1 "9 入院していた"
capture label variable var86_1 "10 その他"
capture label variable var87_1 "11 不詳"
capture label variable var88_1 "費用額"
capture label variable var89_1 "介護保険所得段階"
capture label variable var90_1 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_1 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_1 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_1 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_1 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_1 "スペース４"
capture label variable var96_1 "主に介護する者の同別居"
capture label variable var97_1 "スペース５"
capture label variable var98_1 "続柄"
capture label variable var99_1 "性"
capture label variable var100_1 "年齢"
capture label variable var101_1 "配偶者の有無"
capture label variable var102_1 "スペース６"
capture label variable var103_1 "主に介護する者の介護時間"
capture label variable var104_1 "スペース７"
capture label variable var105_1 "その他介護者数"
capture label variable var106_1 "有無"
capture label variable var107_1 "同別居"
capture label variable var108_1 "性"
capture label variable var109_1 "年齢"
capture label variable var110_1 "続柄"
capture label variable var111_1 "介護頻度"
capture label variable var112_1 "スペース８"
capture label variable var113_1 "介護の有無"
capture label variable var114_1 "事業者（ホームヘルパー等）による介護"
capture label variable var115_1 "主に介護する者"
capture label variable var116_1 "その他の者"
capture label variable var117_1 "介護の有無"
capture label variable var118_1 "事業者（ホームヘルパー等）による介護"
capture label variable var119_1 "主に介護する者"
capture label variable var120_1 "その他の者"
capture label variable var121_1 "介護の有無"
capture label variable var122_1 "事業者（ホームヘルパー等）による介護"
capture label variable var123_1 "主に介護する者"
capture label variable var124_1 "その他の者"
capture label variable var125_1 "介護の有無"
capture label variable var126_1 "事業者（ホームヘルパー等）による介護"
capture label variable var127_1 "主に介護する者"
capture label variable var128_1 "その他の者"
capture label variable var129_1 "介護の有無"
capture label variable var130_1 "事業者（ホームヘルパー等）による介護"
capture label variable var131_1 "主に介護する者"
capture label variable var132_1 "その他の者"
capture label variable var133_1 "介護の有無"
capture label variable var134_1 "事業者（ホームヘルパー等）による介護"
capture label variable var135_1 "主に介護する者"
capture label variable var136_1 "その他の者"
capture label variable var137_1 "介護の有無"
capture label variable var138_1 "事業者（ホームヘルパー等）による介護"
capture label variable var139_1 "主に介護する者"
capture label variable var140_1 "その他の者"
capture label variable var141_1 "介護の有無"
capture label variable var142_1 "事業者（ホームヘルパー等）による介護"
capture label variable var143_1 "主に介護する者"
capture label variable var144_1 "その他の者"
capture label variable var145_1 "介護の有無"
capture label variable var146_1 "事業者（ホームヘルパー等）による介護"
capture label variable var147_1 "主に介護する者"
capture label variable var148_1 "その他の者"
capture label variable var149_1 "介護の有無"
capture label variable var150_1 "事業者（ホームヘルパー等）による介護"
capture label variable var151_1 "主に介護する者"
capture label variable var152_1 "その他の者"
capture label variable var153_1 "介護の有無"
capture label variable var154_1 "事業者（ホームヘルパー等）による介護"
capture label variable var155_1 "主に介護する者"
capture label variable var156_1 "その他の者"
capture label variable var157_1 "介護の有無"
capture label variable var158_1 "事業者（ホームヘルパー等）による介護"
capture label variable var159_1 "主に介護する者"
capture label variable var160_1 "その他の者"
capture label variable var161_1 "介護の有無"
capture label variable var162_1 "事業者（ホームヘルパー等）による介護"
capture label variable var163_1 "主に介護する者"
capture label variable var164_1 "その他の者"
capture label variable var165_1 "介護の有無"
capture label variable var166_1 "事業者（ホームヘルパー等）による介護"
capture label variable var167_1 "主に介護する者"
capture label variable var168_1 "その他の者"
capture label variable var169_1 "介護の有無"
capture label variable var170_1 "事業者（ホームヘルパー等）による介護"
capture label variable var171_1 "主に介護する者"
capture label variable var172_1 "その他の者"
capture label variable var173_1 "介護の有無"
capture label variable var174_1 "事業者（ホームヘルパー等）による介護"
capture label variable var175_1 "主に介護する者"
capture label variable var176_1 "その他の者"
capture label variable var177_1 "スペース９"
capture label variable var41_2 "介護票認定者番号"
capture label variable var42_2 "世帯票世帯員番号"
capture label variable var43_2 "調査票の回答者"
capture label variable var44_2 "性別"
capture label variable var45_2 "元号"
capture label variable var46_2 "年"
capture label variable var47_2 "月"
capture label variable var48_2 "年齢"
capture label variable var49_2 "配偶者の有無"
capture label variable var50_2 "変化"
capture label variable var51_2 "現在"
capture label variable var52_2 "１年前"
capture label variable var53_2 "1脳血管疾患（脳卒中）"
capture label variable var54_2 "2心疾患（心臓病）"
capture label variable var55_2 "3悪性新生物（がん）"
capture label variable var56_2 "4呼吸器疾患"
capture label variable var57_2 "5関節疾患"
capture label variable var58_2 "6認知症"
capture label variable var59_2 "7パーキンソン病"
capture label variable var60_2 "8糖尿病"
capture label variable var61_2 "9視覚・聴覚障害"
capture label variable var62_2 "10骨折・転倒"
capture label variable var63_2 "11脊髄損傷"
capture label variable var64_2 "12高齢による衰弱"
capture label variable var65_2 "13その他"
capture label variable var66_2 "14わからない"
capture label variable var67_2 "介護が必要となった主な原因"
capture label variable var68_2 "利用の有無"
capture label variable var69_2 "1 訪問系サービス"
capture label variable var70_2 "2 通所系サービス"
capture label variable var71_2 "3 短期入所サービス"
capture label variable var72_2 "4 居住系サービス（グループホーム）"
capture label variable var73_2 "5 小規模多機能型サービス等"
capture label variable var74_2 "6 配食サービス"
capture label variable var75_2 "7 外出支援サービス"
capture label variable var76_2 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_2 "1 家族介護で何とかやっていける"
capture label variable var78_2 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_2 "3 他人を家に入れたくない"
capture label variable var80_2 "4 外出するのが大変"
capture label variable var81_2 "5 どのようなサービスがあるかわからない"
capture label variable var82_2 "6 サービスを受ける手続きがわからない"
capture label variable var83_2 "7 利用者負担が払えない"
capture label variable var84_2 "8 受けたいサービスがない"
capture label variable var85_2 "9 入院していた"
capture label variable var86_2 "10 その他"
capture label variable var87_2 "11 不詳"
capture label variable var88_2 "費用額"
capture label variable var89_2 "介護保険所得段階"
capture label variable var90_2 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_2 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_2 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_2 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_2 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_2 "スペース４"
capture label variable var96_2 "主に介護する者の同別居"
capture label variable var97_2 "スペース５"
capture label variable var98_2 "続柄"
capture label variable var99_2 "性"
capture label variable var100_2 "年齢"
capture label variable var101_2 "配偶者の有無"
capture label variable var102_2 "スペース６"
capture label variable var103_2 "主に介護する者の介護時間"
capture label variable var104_2 "スペース７"
capture label variable var105_2 "その他介護者数"
capture label variable var106_2 "有無"
capture label variable var107_2 "同別居"
capture label variable var108_2 "性"
capture label variable var109_2 "年齢"
capture label variable var110_2 "続柄"
capture label variable var111_2 "介護頻度"
capture label variable var112_2 "スペース８"
capture label variable var113_2 "介護の有無"
capture label variable var114_2 "事業者（ホームヘルパー等）による介護"
capture label variable var115_2 "主に介護する者"
capture label variable var116_2 "その他の者"
capture label variable var117_2 "介護の有無"
capture label variable var118_2 "事業者（ホームヘルパー等）による介護"
capture label variable var119_2 "主に介護する者"
capture label variable var120_2 "その他の者"
capture label variable var121_2 "介護の有無"
capture label variable var122_2 "事業者（ホームヘルパー等）による介護"
capture label variable var123_2 "主に介護する者"
capture label variable var124_2 "その他の者"
capture label variable var125_2 "介護の有無"
capture label variable var126_2 "事業者（ホームヘルパー等）による介護"
capture label variable var127_2 "主に介護する者"
capture label variable var128_2 "その他の者"
capture label variable var129_2 "介護の有無"
capture label variable var130_2 "事業者（ホームヘルパー等）による介護"
capture label variable var131_2 "主に介護する者"
capture label variable var132_2 "その他の者"
capture label variable var133_2 "介護の有無"
capture label variable var134_2 "事業者（ホームヘルパー等）による介護"
capture label variable var135_2 "主に介護する者"
capture label variable var136_2 "その他の者"
capture label variable var137_2 "介護の有無"
capture label variable var138_2 "事業者（ホームヘルパー等）による介護"
capture label variable var139_2 "主に介護する者"
capture label variable var140_2 "その他の者"
capture label variable var141_2 "介護の有無"
capture label variable var142_2 "事業者（ホームヘルパー等）による介護"
capture label variable var143_2 "主に介護する者"
capture label variable var144_2 "その他の者"
capture label variable var145_2 "介護の有無"
capture label variable var146_2 "事業者（ホームヘルパー等）による介護"
capture label variable var147_2 "主に介護する者"
capture label variable var148_2 "その他の者"
capture label variable var149_2 "介護の有無"
capture label variable var150_2 "事業者（ホームヘルパー等）による介護"
capture label variable var151_2 "主に介護する者"
capture label variable var152_2 "その他の者"
capture label variable var153_2 "介護の有無"
capture label variable var154_2 "事業者（ホームヘルパー等）による介護"
capture label variable var155_2 "主に介護する者"
capture label variable var156_2 "その他の者"
capture label variable var157_2 "介護の有無"
capture label variable var158_2 "事業者（ホームヘルパー等）による介護"
capture label variable var159_2 "主に介護する者"
capture label variable var160_2 "その他の者"
capture label variable var161_2 "介護の有無"
capture label variable var162_2 "事業者（ホームヘルパー等）による介護"
capture label variable var163_2 "主に介護する者"
capture label variable var164_2 "その他の者"
capture label variable var165_2 "介護の有無"
capture label variable var166_2 "事業者（ホームヘルパー等）による介護"
capture label variable var167_2 "主に介護する者"
capture label variable var168_2 "その他の者"
capture label variable var169_2 "介護の有無"
capture label variable var170_2 "事業者（ホームヘルパー等）による介護"
capture label variable var171_2 "主に介護する者"
capture label variable var172_2 "その他の者"
capture label variable var173_2 "介護の有無"
capture label variable var174_2 "事業者（ホームヘルパー等）による介護"
capture label variable var175_2 "主に介護する者"
capture label variable var176_2 "その他の者"
capture label variable var177_2 "スペース９"
capture label variable var41_3 "介護票認定者番号"
capture label variable var42_3 "世帯票世帯員番号"
capture label variable var43_3 "調査票の回答者"
capture label variable var44_3 "性別"
capture label variable var45_3 "元号"
capture label variable var46_3 "年"
capture label variable var47_3 "月"
capture label variable var48_3 "年齢"
capture label variable var49_3 "配偶者の有無"
capture label variable var50_3 "変化"
capture label variable var51_3 "現在"
capture label variable var52_3 "１年前"
capture label variable var53_3 "1脳血管疾患（脳卒中）"
capture label variable var54_3 "2心疾患（心臓病）"
capture label variable var55_3 "3悪性新生物（がん）"
capture label variable var56_3 "4呼吸器疾患"
capture label variable var57_3 "5関節疾患"
capture label variable var58_3 "6認知症"
capture label variable var59_3 "7パーキンソン病"
capture label variable var60_3 "8糖尿病"
capture label variable var61_3 "9視覚・聴覚障害"
capture label variable var62_3 "10骨折・転倒"
capture label variable var63_3 "11脊髄損傷"
capture label variable var64_3 "12高齢による衰弱"
capture label variable var65_3 "13その他"
capture label variable var66_3 "14わからない"
capture label variable var67_3 "介護が必要となった主な原因"
capture label variable var68_3 "利用の有無"
capture label variable var69_3 "1 訪問系サービス"
capture label variable var70_3 "2 通所系サービス"
capture label variable var71_3 "3 短期入所サービス"
capture label variable var72_3 "4 居住系サービス（グループホーム）"
capture label variable var73_3 "5 小規模多機能型サービス等"
capture label variable var74_3 "6 配食サービス"
capture label variable var75_3 "7 外出支援サービス"
capture label variable var76_3 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_3 "1 家族介護で何とかやっていける"
capture label variable var78_3 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_3 "3 他人を家に入れたくない"
capture label variable var80_3 "4 外出するのが大変"
capture label variable var81_3 "5 どのようなサービスがあるかわからない"
capture label variable var82_3 "6 サービスを受ける手続きがわからない"
capture label variable var83_3 "7 利用者負担が払えない"
capture label variable var84_3 "8 受けたいサービスがない"
capture label variable var85_3 "9 入院していた"
capture label variable var86_3 "10 その他"
capture label variable var87_3 "11 不詳"
capture label variable var88_3 "費用額"
capture label variable var89_3 "介護保険所得段階"
capture label variable var90_3 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_3 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_3 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_3 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_3 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_3 "スペース４"
capture label variable var96_3 "主に介護する者の同別居"
capture label variable var97_3 "スペース５"
capture label variable var98_3 "続柄"
capture label variable var99_3 "性"
capture label variable var100_3 "年齢"
capture label variable var101_3 "配偶者の有無"
capture label variable var102_3 "スペース６"
capture label variable var103_3 "主に介護する者の介護時間"
capture label variable var104_3 "スペース７"
capture label variable var105_3 "その他介護者数"
capture label variable var106_3 "有無"
capture label variable var107_3 "同別居"
capture label variable var108_3 "性"
capture label variable var109_3 "年齢"
capture label variable var110_3 "続柄"
capture label variable var111_3 "介護頻度"
capture label variable var112_3 "スペース８"
capture label variable var113_3 "介護の有無"
capture label variable var114_3 "事業者（ホームヘルパー等）による介護"
capture label variable var115_3 "主に介護する者"
capture label variable var116_3 "その他の者"
capture label variable var117_3 "介護の有無"
capture label variable var118_3 "事業者（ホームヘルパー等）による介護"
capture label variable var119_3 "主に介護する者"
capture label variable var120_3 "その他の者"
capture label variable var121_3 "介護の有無"
capture label variable var122_3 "事業者（ホームヘルパー等）による介護"
capture label variable var123_3 "主に介護する者"
capture label variable var124_3 "その他の者"
capture label variable var125_3 "介護の有無"
capture label variable var126_3 "事業者（ホームヘルパー等）による介護"
capture label variable var127_3 "主に介護する者"
capture label variable var128_3 "その他の者"
capture label variable var129_3 "介護の有無"
capture label variable var130_3 "事業者（ホームヘルパー等）による介護"
capture label variable var131_3 "主に介護する者"
capture label variable var132_3 "その他の者"
capture label variable var133_3 "介護の有無"
capture label variable var134_3 "事業者（ホームヘルパー等）による介護"
capture label variable var135_3 "主に介護する者"
capture label variable var136_3 "その他の者"
capture label variable var137_3 "介護の有無"
capture label variable var138_3 "事業者（ホームヘルパー等）による介護"
capture label variable var139_3 "主に介護する者"
capture label variable var140_3 "その他の者"
capture label variable var141_3 "介護の有無"
capture label variable var142_3 "事業者（ホームヘルパー等）による介護"
capture label variable var143_3 "主に介護する者"
capture label variable var144_3 "その他の者"
capture label variable var145_3 "介護の有無"
capture label variable var146_3 "事業者（ホームヘルパー等）による介護"
capture label variable var147_3 "主に介護する者"
capture label variable var148_3 "その他の者"
capture label variable var149_3 "介護の有無"
capture label variable var150_3 "事業者（ホームヘルパー等）による介護"
capture label variable var151_3 "主に介護する者"
capture label variable var152_3 "その他の者"
capture label variable var153_3 "介護の有無"
capture label variable var154_3 "事業者（ホームヘルパー等）による介護"
capture label variable var155_3 "主に介護する者"
capture label variable var156_3 "その他の者"
capture label variable var157_3 "介護の有無"
capture label variable var158_3 "事業者（ホームヘルパー等）による介護"
capture label variable var159_3 "主に介護する者"
capture label variable var160_3 "その他の者"
capture label variable var161_3 "介護の有無"
capture label variable var162_3 "事業者（ホームヘルパー等）による介護"
capture label variable var163_3 "主に介護する者"
capture label variable var164_3 "その他の者"
capture label variable var165_3 "介護の有無"
capture label variable var166_3 "事業者（ホームヘルパー等）による介護"
capture label variable var167_3 "主に介護する者"
capture label variable var168_3 "その他の者"
capture label variable var169_3 "介護の有無"
capture label variable var170_3 "事業者（ホームヘルパー等）による介護"
capture label variable var171_3 "主に介護する者"
capture label variable var172_3 "その他の者"
capture label variable var173_3 "介護の有無"
capture label variable var174_3 "事業者（ホームヘルパー等）による介護"
capture label variable var175_3 "主に介護する者"
capture label variable var176_3 "その他の者"
capture label variable var177_3 "スペース９"
capture label variable var41_4 "介護票認定者番号"
capture label variable var42_4 "世帯票世帯員番号"
capture label variable var43_4 "調査票の回答者"
capture label variable var44_4 "性別"
capture label variable var45_4 "元号"
capture label variable var46_4 "年"
capture label variable var47_4 "月"
capture label variable var48_4 "年齢"
capture label variable var49_4 "配偶者の有無"
capture label variable var50_4 "変化"
capture label variable var51_4 "現在"
capture label variable var52_4 "１年前"
capture label variable var53_4 "1脳血管疾患（脳卒中）"
capture label variable var54_4 "2心疾患（心臓病）"
capture label variable var55_4 "3悪性新生物（がん）"
capture label variable var56_4 "4呼吸器疾患"
capture label variable var57_4 "5関節疾患"
capture label variable var58_4 "6認知症"
capture label variable var59_4 "7パーキンソン病"
capture label variable var60_4 "8糖尿病"
capture label variable var61_4 "9視覚・聴覚障害"
capture label variable var62_4 "10骨折・転倒"
capture label variable var63_4 "11脊髄損傷"
capture label variable var64_4 "12高齢による衰弱"
capture label variable var65_4 "13その他"
capture label variable var66_4 "14わからない"
capture label variable var67_4 "介護が必要となった主な原因"
capture label variable var68_4 "利用の有無"
capture label variable var69_4 "1 訪問系サービス"
capture label variable var70_4 "2 通所系サービス"
capture label variable var71_4 "3 短期入所サービス"
capture label variable var72_4 "4 居住系サービス（グループホーム）"
capture label variable var73_4 "5 小規模多機能型サービス等"
capture label variable var74_4 "6 配食サービス"
capture label variable var75_4 "7 外出支援サービス"
capture label variable var76_4 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_4 "1 家族介護で何とかやっていける"
capture label variable var78_4 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_4 "3 他人を家に入れたくない"
capture label variable var80_4 "4 外出するのが大変"
capture label variable var81_4 "5 どのようなサービスがあるかわからない"
capture label variable var82_4 "6 サービスを受ける手続きがわからない"
capture label variable var83_4 "7 利用者負担が払えない"
capture label variable var84_4 "8 受けたいサービスがない"
capture label variable var85_4 "9 入院していた"
capture label variable var86_4 "10 その他"
capture label variable var87_4 "11 不詳"
capture label variable var88_4 "費用額"
capture label variable var89_4 "介護保険所得段階"
capture label variable var90_4 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_4 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_4 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_4 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_4 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_4 "スペース４"
capture label variable var96_4 "主に介護する者の同別居"
capture label variable var97_4 "スペース５"
capture label variable var98_4 "続柄"
capture label variable var99_4 "性"
capture label variable var100_4 "年齢"
capture label variable var101_4 "配偶者の有無"
capture label variable var102_4 "スペース６"
capture label variable var103_4 "主に介護する者の介護時間"
capture label variable var104_4 "スペース７"
capture label variable var105_4 "その他介護者数"
capture label variable var106_4 "有無"
capture label variable var107_4 "同別居"
capture label variable var108_4 "性"
capture label variable var109_4 "年齢"
capture label variable var110_4 "続柄"
capture label variable var111_4 "介護頻度"
capture label variable var112_4 "スペース８"
capture label variable var113_4 "介護の有無"
capture label variable var114_4 "事業者（ホームヘルパー等）による介護"
capture label variable var115_4 "主に介護する者"
capture label variable var116_4 "その他の者"
capture label variable var117_4 "介護の有無"
capture label variable var118_4 "事業者（ホームヘルパー等）による介護"
capture label variable var119_4 "主に介護する者"
capture label variable var120_4 "その他の者"
capture label variable var121_4 "介護の有無"
capture label variable var122_4 "事業者（ホームヘルパー等）による介護"
capture label variable var123_4 "主に介護する者"
capture label variable var124_4 "その他の者"
capture label variable var125_4 "介護の有無"
capture label variable var126_4 "事業者（ホームヘルパー等）による介護"
capture label variable var127_4 "主に介護する者"
capture label variable var128_4 "その他の者"
capture label variable var129_4 "介護の有無"
capture label variable var130_4 "事業者（ホームヘルパー等）による介護"
capture label variable var131_4 "主に介護する者"
capture label variable var132_4 "その他の者"
capture label variable var133_4 "介護の有無"
capture label variable var134_4 "事業者（ホームヘルパー等）による介護"
capture label variable var135_4 "主に介護する者"
capture label variable var136_4 "その他の者"
capture label variable var137_4 "介護の有無"
capture label variable var138_4 "事業者（ホームヘルパー等）による介護"
capture label variable var139_4 "主に介護する者"
capture label variable var140_4 "その他の者"
capture label variable var141_4 "介護の有無"
capture label variable var142_4 "事業者（ホームヘルパー等）による介護"
capture label variable var143_4 "主に介護する者"
capture label variable var144_4 "その他の者"
capture label variable var145_4 "介護の有無"
capture label variable var146_4 "事業者（ホームヘルパー等）による介護"
capture label variable var147_4 "主に介護する者"
capture label variable var148_4 "その他の者"
capture label variable var149_4 "介護の有無"
capture label variable var150_4 "事業者（ホームヘルパー等）による介護"
capture label variable var151_4 "主に介護する者"
capture label variable var152_4 "その他の者"
capture label variable var153_4 "介護の有無"
capture label variable var154_4 "事業者（ホームヘルパー等）による介護"
capture label variable var155_4 "主に介護する者"
capture label variable var156_4 "その他の者"
capture label variable var157_4 "介護の有無"
capture label variable var158_4 "事業者（ホームヘルパー等）による介護"
capture label variable var159_4 "主に介護する者"
capture label variable var160_4 "その他の者"
capture label variable var161_4 "介護の有無"
capture label variable var162_4 "事業者（ホームヘルパー等）による介護"
capture label variable var163_4 "主に介護する者"
capture label variable var164_4 "その他の者"
capture label variable var165_4 "介護の有無"
capture label variable var166_4 "事業者（ホームヘルパー等）による介護"
capture label variable var167_4 "主に介護する者"
capture label variable var168_4 "その他の者"
capture label variable var169_4 "介護の有無"
capture label variable var170_4 "事業者（ホームヘルパー等）による介護"
capture label variable var171_4 "主に介護する者"
capture label variable var172_4 "その他の者"
capture label variable var173_4 "介護の有無"
capture label variable var174_4 "事業者（ホームヘルパー等）による介護"
capture label variable var175_4 "主に介護する者"
capture label variable var176_4 "その他の者"
capture label variable var177_4 "スペース９"
capture label variable var41_5 "介護票認定者番号"
capture label variable var42_5 "世帯票世帯員番号"
capture label variable var43_5 "調査票の回答者"
capture label variable var44_5 "性別"
capture label variable var45_5 "元号"
capture label variable var46_5 "年"
capture label variable var47_5 "月"
capture label variable var48_5 "年齢"
capture label variable var49_5 "配偶者の有無"
capture label variable var50_5 "変化"
capture label variable var51_5 "現在"
capture label variable var52_5 "１年前"
capture label variable var53_5 "1脳血管疾患（脳卒中）"
capture label variable var54_5 "2心疾患（心臓病）"
capture label variable var55_5 "3悪性新生物（がん）"
capture label variable var56_5 "4呼吸器疾患"
capture label variable var57_5 "5関節疾患"
capture label variable var58_5 "6認知症"
capture label variable var59_5 "7パーキンソン病"
capture label variable var60_5 "8糖尿病"
capture label variable var61_5 "9視覚・聴覚障害"
capture label variable var62_5 "10骨折・転倒"
capture label variable var63_5 "11脊髄損傷"
capture label variable var64_5 "12高齢による衰弱"
capture label variable var65_5 "13その他"
capture label variable var66_5 "14わからない"
capture label variable var67_5 "介護が必要となった主な原因"
capture label variable var68_5 "利用の有無"
capture label variable var69_5 "1 訪問系サービス"
capture label variable var70_5 "2 通所系サービス"
capture label variable var71_5 "3 短期入所サービス"
capture label variable var72_5 "4 居住系サービス（グループホーム）"
capture label variable var73_5 "5 小規模多機能型サービス等"
capture label variable var74_5 "6 配食サービス"
capture label variable var75_5 "7 外出支援サービス"
capture label variable var76_5 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_5 "1 家族介護で何とかやっていける"
capture label variable var78_5 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_5 "3 他人を家に入れたくない"
capture label variable var80_5 "4 外出するのが大変"
capture label variable var81_5 "5 どのようなサービスがあるかわからない"
capture label variable var82_5 "6 サービスを受ける手続きがわからない"
capture label variable var83_5 "7 利用者負担が払えない"
capture label variable var84_5 "8 受けたいサービスがない"
capture label variable var85_5 "9 入院していた"
capture label variable var86_5 "10 その他"
capture label variable var87_5 "11 不詳"
capture label variable var88_5 "費用額"
capture label variable var89_5 "介護保険所得段階"
capture label variable var90_5 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_5 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_5 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_5 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_5 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_5 "スペース４"
capture label variable var96_5 "主に介護する者の同別居"
capture label variable var97_5 "スペース５"
capture label variable var98_5 "続柄"
capture label variable var99_5 "性"
capture label variable var100_5 "年齢"
capture label variable var101_5 "配偶者の有無"
capture label variable var102_5 "スペース６"
capture label variable var103_5 "主に介護する者の介護時間"
capture label variable var104_5 "スペース７"
capture label variable var105_5 "その他介護者数"
capture label variable var106_5 "有無"
capture label variable var107_5 "同別居"
capture label variable var108_5 "性"
capture label variable var109_5 "年齢"
capture label variable var110_5 "続柄"
capture label variable var111_5 "介護頻度"
capture label variable var112_5 "スペース８"
capture label variable var113_5 "介護の有無"
capture label variable var114_5 "事業者（ホームヘルパー等）による介護"
capture label variable var115_5 "主に介護する者"
capture label variable var116_5 "その他の者"
capture label variable var117_5 "介護の有無"
capture label variable var118_5 "事業者（ホームヘルパー等）による介護"
capture label variable var119_5 "主に介護する者"
capture label variable var120_5 "その他の者"
capture label variable var121_5 "介護の有無"
capture label variable var122_5 "事業者（ホームヘルパー等）による介護"
capture label variable var123_5 "主に介護する者"
capture label variable var124_5 "その他の者"
capture label variable var125_5 "介護の有無"
capture label variable var126_5 "事業者（ホームヘルパー等）による介護"
capture label variable var127_5 "主に介護する者"
capture label variable var128_5 "その他の者"
capture label variable var129_5 "介護の有無"
capture label variable var130_5 "事業者（ホームヘルパー等）による介護"
capture label variable var131_5 "主に介護する者"
capture label variable var132_5 "その他の者"
capture label variable var133_5 "介護の有無"
capture label variable var134_5 "事業者（ホームヘルパー等）による介護"
capture label variable var135_5 "主に介護する者"
capture label variable var136_5 "その他の者"
capture label variable var137_5 "介護の有無"
capture label variable var138_5 "事業者（ホームヘルパー等）による介護"
capture label variable var139_5 "主に介護する者"
capture label variable var140_5 "その他の者"
capture label variable var141_5 "介護の有無"
capture label variable var142_5 "事業者（ホームヘルパー等）による介護"
capture label variable var143_5 "主に介護する者"
capture label variable var144_5 "その他の者"
capture label variable var145_5 "介護の有無"
capture label variable var146_5 "事業者（ホームヘルパー等）による介護"
capture label variable var147_5 "主に介護する者"
capture label variable var148_5 "その他の者"
capture label variable var149_5 "介護の有無"
capture label variable var150_5 "事業者（ホームヘルパー等）による介護"
capture label variable var151_5 "主に介護する者"
capture label variable var152_5 "その他の者"
capture label variable var153_5 "介護の有無"
capture label variable var154_5 "事業者（ホームヘルパー等）による介護"
capture label variable var155_5 "主に介護する者"
capture label variable var156_5 "その他の者"
capture label variable var157_5 "介護の有無"
capture label variable var158_5 "事業者（ホームヘルパー等）による介護"
capture label variable var159_5 "主に介護する者"
capture label variable var160_5 "その他の者"
capture label variable var161_5 "介護の有無"
capture label variable var162_5 "事業者（ホームヘルパー等）による介護"
capture label variable var163_5 "主に介護する者"
capture label variable var164_5 "その他の者"
capture label variable var165_5 "介護の有無"
capture label variable var166_5 "事業者（ホームヘルパー等）による介護"
capture label variable var167_5 "主に介護する者"
capture label variable var168_5 "その他の者"
capture label variable var169_5 "介護の有無"
capture label variable var170_5 "事業者（ホームヘルパー等）による介護"
capture label variable var171_5 "主に介護する者"
capture label variable var172_5 "その他の者"
capture label variable var173_5 "介護の有無"
capture label variable var174_5 "事業者（ホームヘルパー等）による介護"
capture label variable var175_5 "主に介護する者"
capture label variable var176_5 "その他の者"
capture label variable var177_5 "スペース９"
capture label variable var41_6 "介護票認定者番号"
capture label variable var42_6 "世帯票世帯員番号"
capture label variable var43_6 "調査票の回答者"
capture label variable var44_6 "性別"
capture label variable var45_6 "元号"
capture label variable var46_6 "年"
capture label variable var47_6 "月"
capture label variable var48_6 "年齢"
capture label variable var49_6 "配偶者の有無"
capture label variable var50_6 "変化"
capture label variable var51_6 "現在"
capture label variable var52_6 "１年前"
capture label variable var53_6 "1脳血管疾患（脳卒中）"
capture label variable var54_6 "2心疾患（心臓病）"
capture label variable var55_6 "3悪性新生物（がん）"
capture label variable var56_6 "4呼吸器疾患"
capture label variable var57_6 "5関節疾患"
capture label variable var58_6 "6認知症"
capture label variable var59_6 "7パーキンソン病"
capture label variable var60_6 "8糖尿病"
capture label variable var61_6 "9視覚・聴覚障害"
capture label variable var62_6 "10骨折・転倒"
capture label variable var63_6 "11脊髄損傷"
capture label variable var64_6 "12高齢による衰弱"
capture label variable var65_6 "13その他"
capture label variable var66_6 "14わからない"
capture label variable var67_6 "介護が必要となった主な原因"
capture label variable var68_6 "利用の有無"
capture label variable var69_6 "1 訪問系サービス"
capture label variable var70_6 "2 通所系サービス"
capture label variable var71_6 "3 短期入所サービス"
capture label variable var72_6 "4 居住系サービス（グループホーム）"
capture label variable var73_6 "5 小規模多機能型サービス等"
capture label variable var74_6 "6 配食サービス"
capture label variable var75_6 "7 外出支援サービス"
capture label variable var76_6 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_6 "1 家族介護で何とかやっていける"
capture label variable var78_6 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_6 "3 他人を家に入れたくない"
capture label variable var80_6 "4 外出するのが大変"
capture label variable var81_6 "5 どのようなサービスがあるかわからない"
capture label variable var82_6 "6 サービスを受ける手続きがわからない"
capture label variable var83_6 "7 利用者負担が払えない"
capture label variable var84_6 "8 受けたいサービスがない"
capture label variable var85_6 "9 入院していた"
capture label variable var86_6 "10 その他"
capture label variable var87_6 "11 不詳"
capture label variable var88_6 "費用額"
capture label variable var89_6 "介護保険所得段階"
capture label variable var90_6 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_6 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_6 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_6 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_6 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_6 "スペース４"
capture label variable var96_6 "主に介護する者の同別居"
capture label variable var97_6 "スペース５"
capture label variable var98_6 "続柄"
capture label variable var99_6 "性"
capture label variable var100_6 "年齢"
capture label variable var101_6 "配偶者の有無"
capture label variable var102_6 "スペース６"
capture label variable var103_6 "主に介護する者の介護時間"
capture label variable var104_6 "スペース７"
capture label variable var105_6 "その他介護者数"
capture label variable var106_6 "有無"
capture label variable var107_6 "同別居"
capture label variable var108_6 "性"
capture label variable var109_6 "年齢"
capture label variable var110_6 "続柄"
capture label variable var111_6 "介護頻度"
capture label variable var112_6 "スペース８"
capture label variable var113_6 "介護の有無"
capture label variable var114_6 "事業者（ホームヘルパー等）による介護"
capture label variable var115_6 "主に介護する者"
capture label variable var116_6 "その他の者"
capture label variable var117_6 "介護の有無"
capture label variable var118_6 "事業者（ホームヘルパー等）による介護"
capture label variable var119_6 "主に介護する者"
capture label variable var120_6 "その他の者"
capture label variable var121_6 "介護の有無"
capture label variable var122_6 "事業者（ホームヘルパー等）による介護"
capture label variable var123_6 "主に介護する者"
capture label variable var124_6 "その他の者"
capture label variable var125_6 "介護の有無"
capture label variable var126_6 "事業者（ホームヘルパー等）による介護"
capture label variable var127_6 "主に介護する者"
capture label variable var128_6 "その他の者"
capture label variable var129_6 "介護の有無"
capture label variable var130_6 "事業者（ホームヘルパー等）による介護"
capture label variable var131_6 "主に介護する者"
capture label variable var132_6 "その他の者"
capture label variable var133_6 "介護の有無"
capture label variable var134_6 "事業者（ホームヘルパー等）による介護"
capture label variable var135_6 "主に介護する者"
capture label variable var136_6 "その他の者"
capture label variable var137_6 "介護の有無"
capture label variable var138_6 "事業者（ホームヘルパー等）による介護"
capture label variable var139_6 "主に介護する者"
capture label variable var140_6 "その他の者"
capture label variable var141_6 "介護の有無"
capture label variable var142_6 "事業者（ホームヘルパー等）による介護"
capture label variable var143_6 "主に介護する者"
capture label variable var144_6 "その他の者"
capture label variable var145_6 "介護の有無"
capture label variable var146_6 "事業者（ホームヘルパー等）による介護"
capture label variable var147_6 "主に介護する者"
capture label variable var148_6 "その他の者"
capture label variable var149_6 "介護の有無"
capture label variable var150_6 "事業者（ホームヘルパー等）による介護"
capture label variable var151_6 "主に介護する者"
capture label variable var152_6 "その他の者"
capture label variable var153_6 "介護の有無"
capture label variable var154_6 "事業者（ホームヘルパー等）による介護"
capture label variable var155_6 "主に介護する者"
capture label variable var156_6 "その他の者"
capture label variable var157_6 "介護の有無"
capture label variable var158_6 "事業者（ホームヘルパー等）による介護"
capture label variable var159_6 "主に介護する者"
capture label variable var160_6 "その他の者"
capture label variable var161_6 "介護の有無"
capture label variable var162_6 "事業者（ホームヘルパー等）による介護"
capture label variable var163_6 "主に介護する者"
capture label variable var164_6 "その他の者"
capture label variable var165_6 "介護の有無"
capture label variable var166_6 "事業者（ホームヘルパー等）による介護"
capture label variable var167_6 "主に介護する者"
capture label variable var168_6 "その他の者"
capture label variable var169_6 "介護の有無"
capture label variable var170_6 "事業者（ホームヘルパー等）による介護"
capture label variable var171_6 "主に介護する者"
capture label variable var172_6 "その他の者"
capture label variable var173_6 "介護の有無"
capture label variable var174_6 "事業者（ホームヘルパー等）による介護"
capture label variable var175_6 "主に介護する者"
capture label variable var176_6 "その他の者"
capture label variable var177_6 "スペース９"
capture label variable var41_7 "介護票認定者番号"
capture label variable var42_7 "世帯票世帯員番号"
capture label variable var43_7 "調査票の回答者"
capture label variable var44_7 "性別"
capture label variable var45_7 "元号"
capture label variable var46_7 "年"
capture label variable var47_7 "月"
capture label variable var48_7 "年齢"
capture label variable var49_7 "配偶者の有無"
capture label variable var50_7 "変化"
capture label variable var51_7 "現在"
capture label variable var52_7 "１年前"
capture label variable var53_7 "1脳血管疾患（脳卒中）"
capture label variable var54_7 "2心疾患（心臓病）"
capture label variable var55_7 "3悪性新生物（がん）"
capture label variable var56_7 "4呼吸器疾患"
capture label variable var57_7 "5関節疾患"
capture label variable var58_7 "6認知症"
capture label variable var59_7 "7パーキンソン病"
capture label variable var60_7 "8糖尿病"
capture label variable var61_7 "9視覚・聴覚障害"
capture label variable var62_7 "10骨折・転倒"
capture label variable var63_7 "11脊髄損傷"
capture label variable var64_7 "12高齢による衰弱"
capture label variable var65_7 "13その他"
capture label variable var66_7 "14わからない"
capture label variable var67_7 "介護が必要となった主な原因"
capture label variable var68_7 "利用の有無"
capture label variable var69_7 "1 訪問系サービス"
capture label variable var70_7 "2 通所系サービス"
capture label variable var71_7 "3 短期入所サービス"
capture label variable var72_7 "4 居住系サービス（グループホーム）"
capture label variable var73_7 "5 小規模多機能型サービス等"
capture label variable var74_7 "6 配食サービス"
capture label variable var75_7 "7 外出支援サービス"
capture label variable var76_7 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_7 "1 家族介護で何とかやっていける"
capture label variable var78_7 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_7 "3 他人を家に入れたくない"
capture label variable var80_7 "4 外出するのが大変"
capture label variable var81_7 "5 どのようなサービスがあるかわからない"
capture label variable var82_7 "6 サービスを受ける手続きがわからない"
capture label variable var83_7 "7 利用者負担が払えない"
capture label variable var84_7 "8 受けたいサービスがない"
capture label variable var85_7 "9 入院していた"
capture label variable var86_7 "10 その他"
capture label variable var87_7 "11 不詳"
capture label variable var88_7 "費用額"
capture label variable var89_7 "介護保険所得段階"
capture label variable var90_7 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_7 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_7 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_7 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_7 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_7 "スペース４"
capture label variable var96_7 "主に介護する者の同別居"
capture label variable var97_7 "スペース５"
capture label variable var98_7 "続柄"
capture label variable var99_7 "性"
capture label variable var100_7 "年齢"
capture label variable var101_7 "配偶者の有無"
capture label variable var102_7 "スペース６"
capture label variable var103_7 "主に介護する者の介護時間"
capture label variable var104_7 "スペース７"
capture label variable var105_7 "その他介護者数"
capture label variable var106_7 "有無"
capture label variable var107_7 "同別居"
capture label variable var108_7 "性"
capture label variable var109_7 "年齢"
capture label variable var110_7 "続柄"
capture label variable var111_7 "介護頻度"
capture label variable var112_7 "スペース８"
capture label variable var113_7 "介護の有無"
capture label variable var114_7 "事業者（ホームヘルパー等）による介護"
capture label variable var115_7 "主に介護する者"
capture label variable var116_7 "その他の者"
capture label variable var117_7 "介護の有無"
capture label variable var118_7 "事業者（ホームヘルパー等）による介護"
capture label variable var119_7 "主に介護する者"
capture label variable var120_7 "その他の者"
capture label variable var121_7 "介護の有無"
capture label variable var122_7 "事業者（ホームヘルパー等）による介護"
capture label variable var123_7 "主に介護する者"
capture label variable var124_7 "その他の者"
capture label variable var125_7 "介護の有無"
capture label variable var126_7 "事業者（ホームヘルパー等）による介護"
capture label variable var127_7 "主に介護する者"
capture label variable var128_7 "その他の者"
capture label variable var129_7 "介護の有無"
capture label variable var130_7 "事業者（ホームヘルパー等）による介護"
capture label variable var131_7 "主に介護する者"
capture label variable var132_7 "その他の者"
capture label variable var133_7 "介護の有無"
capture label variable var134_7 "事業者（ホームヘルパー等）による介護"
capture label variable var135_7 "主に介護する者"
capture label variable var136_7 "その他の者"
capture label variable var137_7 "介護の有無"
capture label variable var138_7 "事業者（ホームヘルパー等）による介護"
capture label variable var139_7 "主に介護する者"
capture label variable var140_7 "その他の者"
capture label variable var141_7 "介護の有無"
capture label variable var142_7 "事業者（ホームヘルパー等）による介護"
capture label variable var143_7 "主に介護する者"
capture label variable var144_7 "その他の者"
capture label variable var145_7 "介護の有無"
capture label variable var146_7 "事業者（ホームヘルパー等）による介護"
capture label variable var147_7 "主に介護する者"
capture label variable var148_7 "その他の者"
capture label variable var149_7 "介護の有無"
capture label variable var150_7 "事業者（ホームヘルパー等）による介護"
capture label variable var151_7 "主に介護する者"
capture label variable var152_7 "その他の者"
capture label variable var153_7 "介護の有無"
capture label variable var154_7 "事業者（ホームヘルパー等）による介護"
capture label variable var155_7 "主に介護する者"
capture label variable var156_7 "その他の者"
capture label variable var157_7 "介護の有無"
capture label variable var158_7 "事業者（ホームヘルパー等）による介護"
capture label variable var159_7 "主に介護する者"
capture label variable var160_7 "その他の者"
capture label variable var161_7 "介護の有無"
capture label variable var162_7 "事業者（ホームヘルパー等）による介護"
capture label variable var163_7 "主に介護する者"
capture label variable var164_7 "その他の者"
capture label variable var165_7 "介護の有無"
capture label variable var166_7 "事業者（ホームヘルパー等）による介護"
capture label variable var167_7 "主に介護する者"
capture label variable var168_7 "その他の者"
capture label variable var169_7 "介護の有無"
capture label variable var170_7 "事業者（ホームヘルパー等）による介護"
capture label variable var171_7 "主に介護する者"
capture label variable var172_7 "その他の者"
capture label variable var173_7 "介護の有無"
capture label variable var174_7 "事業者（ホームヘルパー等）による介護"
capture label variable var175_7 "主に介護する者"
capture label variable var176_7 "その他の者"
capture label variable var177_7 "スペース９"
capture label variable var41_8 "介護票認定者番号"
capture label variable var42_8 "世帯票世帯員番号"
capture label variable var43_8 "調査票の回答者"
capture label variable var44_8 "性別"
capture label variable var45_8 "元号"
capture label variable var46_8 "年"
capture label variable var47_8 "月"
capture label variable var48_8 "年齢"
capture label variable var49_8 "配偶者の有無"
capture label variable var50_8 "変化"
capture label variable var51_8 "現在"
capture label variable var52_8 "１年前"
capture label variable var53_8 "1脳血管疾患（脳卒中）"
capture label variable var54_8 "2心疾患（心臓病）"
capture label variable var55_8 "3悪性新生物（がん）"
capture label variable var56_8 "4呼吸器疾患"
capture label variable var57_8 "5関節疾患"
capture label variable var58_8 "6認知症"
capture label variable var59_8 "7パーキンソン病"
capture label variable var60_8 "8糖尿病"
capture label variable var61_8 "9視覚・聴覚障害"
capture label variable var62_8 "10骨折・転倒"
capture label variable var63_8 "11脊髄損傷"
capture label variable var64_8 "12高齢による衰弱"
capture label variable var65_8 "13その他"
capture label variable var66_8 "14わからない"
capture label variable var67_8 "介護が必要となった主な原因"
capture label variable var68_8 "利用の有無"
capture label variable var69_8 "1 訪問系サービス"
capture label variable var70_8 "2 通所系サービス"
capture label variable var71_8 "3 短期入所サービス"
capture label variable var72_8 "4 居住系サービス（グループホーム）"
capture label variable var73_8 "5 小規模多機能型サービス等"
capture label variable var74_8 "6 配食サービス"
capture label variable var75_8 "7 外出支援サービス"
capture label variable var76_8 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_8 "1 家族介護で何とかやっていける"
capture label variable var78_8 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_8 "3 他人を家に入れたくない"
capture label variable var80_8 "4 外出するのが大変"
capture label variable var81_8 "5 どのようなサービスがあるかわからない"
capture label variable var82_8 "6 サービスを受ける手続きがわからない"
capture label variable var83_8 "7 利用者負担が払えない"
capture label variable var84_8 "8 受けたいサービスがない"
capture label variable var85_8 "9 入院していた"
capture label variable var86_8 "10 その他"
capture label variable var87_8 "11 不詳"
capture label variable var88_8 "費用額"
capture label variable var89_8 "介護保険所得段階"
capture label variable var90_8 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_8 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_8 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_8 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_8 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_8 "スペース４"
capture label variable var96_8 "主に介護する者の同別居"
capture label variable var97_8 "スペース５"
capture label variable var98_8 "続柄"
capture label variable var99_8 "性"
capture label variable var100_8 "年齢"
capture label variable var101_8 "配偶者の有無"
capture label variable var102_8 "スペース６"
capture label variable var103_8 "主に介護する者の介護時間"
capture label variable var104_8 "スペース７"
capture label variable var105_8 "その他介護者数"
capture label variable var106_8 "有無"
capture label variable var107_8 "同別居"
capture label variable var108_8 "性"
capture label variable var109_8 "年齢"
capture label variable var110_8 "続柄"
capture label variable var111_8 "介護頻度"
capture label variable var112_8 "スペース８"
capture label variable var113_8 "介護の有無"
capture label variable var114_8 "事業者（ホームヘルパー等）による介護"
capture label variable var115_8 "主に介護する者"
capture label variable var116_8 "その他の者"
capture label variable var117_8 "介護の有無"
capture label variable var118_8 "事業者（ホームヘルパー等）による介護"
capture label variable var119_8 "主に介護する者"
capture label variable var120_8 "その他の者"
capture label variable var121_8 "介護の有無"
capture label variable var122_8 "事業者（ホームヘルパー等）による介護"
capture label variable var123_8 "主に介護する者"
capture label variable var124_8 "その他の者"
capture label variable var125_8 "介護の有無"
capture label variable var126_8 "事業者（ホームヘルパー等）による介護"
capture label variable var127_8 "主に介護する者"
capture label variable var128_8 "その他の者"
capture label variable var129_8 "介護の有無"
capture label variable var130_8 "事業者（ホームヘルパー等）による介護"
capture label variable var131_8 "主に介護する者"
capture label variable var132_8 "その他の者"
capture label variable var133_8 "介護の有無"
capture label variable var134_8 "事業者（ホームヘルパー等）による介護"
capture label variable var135_8 "主に介護する者"
capture label variable var136_8 "その他の者"
capture label variable var137_8 "介護の有無"
capture label variable var138_8 "事業者（ホームヘルパー等）による介護"
capture label variable var139_8 "主に介護する者"
capture label variable var140_8 "その他の者"
capture label variable var141_8 "介護の有無"
capture label variable var142_8 "事業者（ホームヘルパー等）による介護"
capture label variable var143_8 "主に介護する者"
capture label variable var144_8 "その他の者"
capture label variable var145_8 "介護の有無"
capture label variable var146_8 "事業者（ホームヘルパー等）による介護"
capture label variable var147_8 "主に介護する者"
capture label variable var148_8 "その他の者"
capture label variable var149_8 "介護の有無"
capture label variable var150_8 "事業者（ホームヘルパー等）による介護"
capture label variable var151_8 "主に介護する者"
capture label variable var152_8 "その他の者"
capture label variable var153_8 "介護の有無"
capture label variable var154_8 "事業者（ホームヘルパー等）による介護"
capture label variable var155_8 "主に介護する者"
capture label variable var156_8 "その他の者"
capture label variable var157_8 "介護の有無"
capture label variable var158_8 "事業者（ホームヘルパー等）による介護"
capture label variable var159_8 "主に介護する者"
capture label variable var160_8 "その他の者"
capture label variable var161_8 "介護の有無"
capture label variable var162_8 "事業者（ホームヘルパー等）による介護"
capture label variable var163_8 "主に介護する者"
capture label variable var164_8 "その他の者"
capture label variable var165_8 "介護の有無"
capture label variable var166_8 "事業者（ホームヘルパー等）による介護"
capture label variable var167_8 "主に介護する者"
capture label variable var168_8 "その他の者"
capture label variable var169_8 "介護の有無"
capture label variable var170_8 "事業者（ホームヘルパー等）による介護"
capture label variable var171_8 "主に介護する者"
capture label variable var172_8 "その他の者"
capture label variable var173_8 "介護の有無"
capture label variable var174_8 "事業者（ホームヘルパー等）による介護"
capture label variable var175_8 "主に介護する者"
capture label variable var176_8 "その他の者"
capture label variable var177_8 "スペース９"
capture label variable var41_9 "介護票認定者番号"
capture label variable var42_9 "世帯票世帯員番号"
capture label variable var43_9 "調査票の回答者"
capture label variable var44_9 "性別"
capture label variable var45_9 "元号"
capture label variable var46_9 "年"
capture label variable var47_9 "月"
capture label variable var48_9 "年齢"
capture label variable var49_9 "配偶者の有無"
capture label variable var50_9 "変化"
capture label variable var51_9 "現在"
capture label variable var52_9 "１年前"
capture label variable var53_9 "1脳血管疾患（脳卒中）"
capture label variable var54_9 "2心疾患（心臓病）"
capture label variable var55_9 "3悪性新生物（がん）"
capture label variable var56_9 "4呼吸器疾患"
capture label variable var57_9 "5関節疾患"
capture label variable var58_9 "6認知症"
capture label variable var59_9 "7パーキンソン病"
capture label variable var60_9 "8糖尿病"
capture label variable var61_9 "9視覚・聴覚障害"
capture label variable var62_9 "10骨折・転倒"
capture label variable var63_9 "11脊髄損傷"
capture label variable var64_9 "12高齢による衰弱"
capture label variable var65_9 "13その他"
capture label variable var66_9 "14わからない"
capture label variable var67_9 "介護が必要となった主な原因"
capture label variable var68_9 "利用の有無"
capture label variable var69_9 "1 訪問系サービス"
capture label variable var70_9 "2 通所系サービス"
capture label variable var71_9 "3 短期入所サービス"
capture label variable var72_9 "4 居住系サービス（グループホーム）"
capture label variable var73_9 "5 小規模多機能型サービス等"
capture label variable var74_9 "6 配食サービス"
capture label variable var75_9 "7 外出支援サービス"
capture label variable var76_9 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_9 "1 家族介護で何とかやっていける"
capture label variable var78_9 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_9 "3 他人を家に入れたくない"
capture label variable var80_9 "4 外出するのが大変"
capture label variable var81_9 "5 どのようなサービスがあるかわからない"
capture label variable var82_9 "6 サービスを受ける手続きがわからない"
capture label variable var83_9 "7 利用者負担が払えない"
capture label variable var84_9 "8 受けたいサービスがない"
capture label variable var85_9 "9 入院していた"
capture label variable var86_9 "10 その他"
capture label variable var87_9 "11 不詳"
capture label variable var88_9 "費用額"
capture label variable var89_9 "介護保険所得段階"
capture label variable var90_9 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_9 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_9 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_9 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_9 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_9 "スペース４"
capture label variable var96_9 "主に介護する者の同別居"
capture label variable var97_9 "スペース５"
capture label variable var98_9 "続柄"
capture label variable var99_9 "性"
capture label variable var100_9 "年齢"
capture label variable var101_9 "配偶者の有無"
capture label variable var102_9 "スペース６"
capture label variable var103_9 "主に介護する者の介護時間"
capture label variable var104_9 "スペース７"
capture label variable var105_9 "その他介護者数"
capture label variable var106_9 "有無"
capture label variable var107_9 "同別居"
capture label variable var108_9 "性"
capture label variable var109_9 "年齢"
capture label variable var110_9 "続柄"
capture label variable var111_9 "介護頻度"
capture label variable var112_9 "スペース８"
capture label variable var113_9 "介護の有無"
capture label variable var114_9 "事業者（ホームヘルパー等）による介護"
capture label variable var115_9 "主に介護する者"
capture label variable var116_9 "その他の者"
capture label variable var117_9 "介護の有無"
capture label variable var118_9 "事業者（ホームヘルパー等）による介護"
capture label variable var119_9 "主に介護する者"
capture label variable var120_9 "その他の者"
capture label variable var121_9 "介護の有無"
capture label variable var122_9 "事業者（ホームヘルパー等）による介護"
capture label variable var123_9 "主に介護する者"
capture label variable var124_9 "その他の者"
capture label variable var125_9 "介護の有無"
capture label variable var126_9 "事業者（ホームヘルパー等）による介護"
capture label variable var127_9 "主に介護する者"
capture label variable var128_9 "その他の者"
capture label variable var129_9 "介護の有無"
capture label variable var130_9 "事業者（ホームヘルパー等）による介護"
capture label variable var131_9 "主に介護する者"
capture label variable var132_9 "その他の者"
capture label variable var133_9 "介護の有無"
capture label variable var134_9 "事業者（ホームヘルパー等）による介護"
capture label variable var135_9 "主に介護する者"
capture label variable var136_9 "その他の者"
capture label variable var137_9 "介護の有無"
capture label variable var138_9 "事業者（ホームヘルパー等）による介護"
capture label variable var139_9 "主に介護する者"
capture label variable var140_9 "その他の者"
capture label variable var141_9 "介護の有無"
capture label variable var142_9 "事業者（ホームヘルパー等）による介護"
capture label variable var143_9 "主に介護する者"
capture label variable var144_9 "その他の者"
capture label variable var145_9 "介護の有無"
capture label variable var146_9 "事業者（ホームヘルパー等）による介護"
capture label variable var147_9 "主に介護する者"
capture label variable var148_9 "その他の者"
capture label variable var149_9 "介護の有無"
capture label variable var150_9 "事業者（ホームヘルパー等）による介護"
capture label variable var151_9 "主に介護する者"
capture label variable var152_9 "その他の者"
capture label variable var153_9 "介護の有無"
capture label variable var154_9 "事業者（ホームヘルパー等）による介護"
capture label variable var155_9 "主に介護する者"
capture label variable var156_9 "その他の者"
capture label variable var157_9 "介護の有無"
capture label variable var158_9 "事業者（ホームヘルパー等）による介護"
capture label variable var159_9 "主に介護する者"
capture label variable var160_9 "その他の者"
capture label variable var161_9 "介護の有無"
capture label variable var162_9 "事業者（ホームヘルパー等）による介護"
capture label variable var163_9 "主に介護する者"
capture label variable var164_9 "その他の者"
capture label variable var165_9 "介護の有無"
capture label variable var166_9 "事業者（ホームヘルパー等）による介護"
capture label variable var167_9 "主に介護する者"
capture label variable var168_9 "その他の者"
capture label variable var169_9 "介護の有無"
capture label variable var170_9 "事業者（ホームヘルパー等）による介護"
capture label variable var171_9 "主に介護する者"
capture label variable var172_9 "その他の者"
capture label variable var173_9 "介護の有無"
capture label variable var174_9 "事業者（ホームヘルパー等）による介護"
capture label variable var175_9 "主に介護する者"
capture label variable var176_9 "その他の者"
capture label variable var177_9 "スペース９"
capture label variable var41_10 "介護票認定者番号"
capture label variable var42_10 "世帯票世帯員番号"
capture label variable var43_10 "調査票の回答者"
capture label variable var44_10 "性別"
capture label variable var45_10 "元号"
capture label variable var46_10 "年"
capture label variable var47_10 "月"
capture label variable var48_10 "年齢"
capture label variable var49_10 "配偶者の有無"
capture label variable var50_10 "変化"
capture label variable var51_10 "現在"
capture label variable var52_10 "１年前"
capture label variable var53_10 "1脳血管疾患（脳卒中）"
capture label variable var54_10 "2心疾患（心臓病）"
capture label variable var55_10 "3悪性新生物（がん）"
capture label variable var56_10 "4呼吸器疾患"
capture label variable var57_10 "5関節疾患"
capture label variable var58_10 "6認知症"
capture label variable var59_10 "7パーキンソン病"
capture label variable var60_10 "8糖尿病"
capture label variable var61_10 "9視覚・聴覚障害"
capture label variable var62_10 "10骨折・転倒"
capture label variable var63_10 "11脊髄損傷"
capture label variable var64_10 "12高齢による衰弱"
capture label variable var65_10 "13その他"
capture label variable var66_10 "14わからない"
capture label variable var67_10 "介護が必要となった主な原因"
capture label variable var68_10 "利用の有無"
capture label variable var69_10 "1 訪問系サービス"
capture label variable var70_10 "2 通所系サービス"
capture label variable var71_10 "3 短期入所サービス"
capture label variable var72_10 "4 居住系サービス（グループホーム）"
capture label variable var73_10 "5 小規模多機能型サービス等"
capture label variable var74_10 "6 配食サービス"
capture label variable var75_10 "7 外出支援サービス"
capture label variable var76_10 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_10 "1 家族介護で何とかやっていける"
capture label variable var78_10 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_10 "3 他人を家に入れたくない"
capture label variable var80_10 "4 外出するのが大変"
capture label variable var81_10 "5 どのようなサービスがあるかわからない"
capture label variable var82_10 "6 サービスを受ける手続きがわからない"
capture label variable var83_10 "7 利用者負担が払えない"
capture label variable var84_10 "8 受けたいサービスがない"
capture label variable var85_10 "9 入院していた"
capture label variable var86_10 "10 その他"
capture label variable var87_10 "11 不詳"
capture label variable var88_10 "費用額"
capture label variable var89_10 "介護保険所得段階"
capture label variable var90_10 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_10 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_10 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_10 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_10 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_10 "スペース４"
capture label variable var96_10 "主に介護する者の同別居"
capture label variable var97_10 "スペース５"
capture label variable var98_10 "続柄"
capture label variable var99_10 "性"
capture label variable var100_10 "年齢"
capture label variable var101_10 "配偶者の有無"
capture label variable var102_10 "スペース６"
capture label variable var103_10 "主に介護する者の介護時間"
capture label variable var104_10 "スペース７"
capture label variable var105_10 "その他介護者数"
capture label variable var106_10 "有無"
capture label variable var107_10 "同別居"
capture label variable var108_10 "性"
capture label variable var109_10 "年齢"
capture label variable var110_10 "続柄"
capture label variable var111_10 "介護頻度"
capture label variable var112_10 "スペース８"
capture label variable var113_10 "介護の有無"
capture label variable var114_10 "事業者（ホームヘルパー等）による介護"
capture label variable var115_10 "主に介護する者"
capture label variable var116_10 "その他の者"
capture label variable var117_10 "介護の有無"
capture label variable var118_10 "事業者（ホームヘルパー等）による介護"
capture label variable var119_10 "主に介護する者"
capture label variable var120_10 "その他の者"
capture label variable var121_10 "介護の有無"
capture label variable var122_10 "事業者（ホームヘルパー等）による介護"
capture label variable var123_10 "主に介護する者"
capture label variable var124_10 "その他の者"
capture label variable var125_10 "介護の有無"
capture label variable var126_10 "事業者（ホームヘルパー等）による介護"
capture label variable var127_10 "主に介護する者"
capture label variable var128_10 "その他の者"
capture label variable var129_10 "介護の有無"
capture label variable var130_10 "事業者（ホームヘルパー等）による介護"
capture label variable var131_10 "主に介護する者"
capture label variable var132_10 "その他の者"
capture label variable var133_10 "介護の有無"
capture label variable var134_10 "事業者（ホームヘルパー等）による介護"
capture label variable var135_10 "主に介護する者"
capture label variable var136_10 "その他の者"
capture label variable var137_10 "介護の有無"
capture label variable var138_10 "事業者（ホームヘルパー等）による介護"
capture label variable var139_10 "主に介護する者"
capture label variable var140_10 "その他の者"
capture label variable var141_10 "介護の有無"
capture label variable var142_10 "事業者（ホームヘルパー等）による介護"
capture label variable var143_10 "主に介護する者"
capture label variable var144_10 "その他の者"
capture label variable var145_10 "介護の有無"
capture label variable var146_10 "事業者（ホームヘルパー等）による介護"
capture label variable var147_10 "主に介護する者"
capture label variable var148_10 "その他の者"
capture label variable var149_10 "介護の有無"
capture label variable var150_10 "事業者（ホームヘルパー等）による介護"
capture label variable var151_10 "主に介護する者"
capture label variable var152_10 "その他の者"
capture label variable var153_10 "介護の有無"
capture label variable var154_10 "事業者（ホームヘルパー等）による介護"
capture label variable var155_10 "主に介護する者"
capture label variable var156_10 "その他の者"
capture label variable var157_10 "介護の有無"
capture label variable var158_10 "事業者（ホームヘルパー等）による介護"
capture label variable var159_10 "主に介護する者"
capture label variable var160_10 "その他の者"
capture label variable var161_10 "介護の有無"
capture label variable var162_10 "事業者（ホームヘルパー等）による介護"
capture label variable var163_10 "主に介護する者"
capture label variable var164_10 "その他の者"
capture label variable var165_10 "介護の有無"
capture label variable var166_10 "事業者（ホームヘルパー等）による介護"
capture label variable var167_10 "主に介護する者"
capture label variable var168_10 "その他の者"
capture label variable var169_10 "介護の有無"
capture label variable var170_10 "事業者（ホームヘルパー等）による介護"
capture label variable var171_10 "主に介護する者"
capture label variable var172_10 "その他の者"
capture label variable var173_10 "介護の有無"
capture label variable var174_10 "事業者（ホームヘルパー等）による介護"
capture label variable var175_10 "主に介護する者"
capture label variable var176_10 "その他の者"
capture label variable var177_10 "スペース９"
capture label variable var41_11 "介護票認定者番号"
capture label variable var42_11 "世帯票世帯員番号"
capture label variable var43_11 "調査票の回答者"
capture label variable var44_11 "性別"
capture label variable var45_11 "元号"
capture label variable var46_11 "年"
capture label variable var47_11 "月"
capture label variable var48_11 "年齢"
capture label variable var49_11 "配偶者の有無"
capture label variable var50_11 "変化"
capture label variable var51_11 "現在"
capture label variable var52_11 "１年前"
capture label variable var53_11 "1脳血管疾患（脳卒中）"
capture label variable var54_11 "2心疾患（心臓病）"
capture label variable var55_11 "3悪性新生物（がん）"
capture label variable var56_11 "4呼吸器疾患"
capture label variable var57_11 "5関節疾患"
capture label variable var58_11 "6認知症"
capture label variable var59_11 "7パーキンソン病"
capture label variable var60_11 "8糖尿病"
capture label variable var61_11 "9視覚・聴覚障害"
capture label variable var62_11 "10骨折・転倒"
capture label variable var63_11 "11脊髄損傷"
capture label variable var64_11 "12高齢による衰弱"
capture label variable var65_11 "13その他"
capture label variable var66_11 "14わからない"
capture label variable var67_11 "介護が必要となった主な原因"
capture label variable var68_11 "利用の有無"
capture label variable var69_11 "1 訪問系サービス"
capture label variable var70_11 "2 通所系サービス"
capture label variable var71_11 "3 短期入所サービス"
capture label variable var72_11 "4 居住系サービス（グループホーム）"
capture label variable var73_11 "5 小規模多機能型サービス等"
capture label variable var74_11 "6 配食サービス"
capture label variable var75_11 "7 外出支援サービス"
capture label variable var76_11 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_11 "1 家族介護で何とかやっていける"
capture label variable var78_11 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_11 "3 他人を家に入れたくない"
capture label variable var80_11 "4 外出するのが大変"
capture label variable var81_11 "5 どのようなサービスがあるかわからない"
capture label variable var82_11 "6 サービスを受ける手続きがわからない"
capture label variable var83_11 "7 利用者負担が払えない"
capture label variable var84_11 "8 受けたいサービスがない"
capture label variable var85_11 "9 入院していた"
capture label variable var86_11 "10 その他"
capture label variable var87_11 "11 不詳"
capture label variable var88_11 "費用額"
capture label variable var89_11 "介護保険所得段階"
capture label variable var90_11 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_11 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_11 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_11 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_11 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_11 "スペース４"
capture label variable var96_11 "主に介護する者の同別居"
capture label variable var97_11 "スペース５"
capture label variable var98_11 "続柄"
capture label variable var99_11 "性"
capture label variable var100_11 "年齢"
capture label variable var101_11 "配偶者の有無"
capture label variable var102_11 "スペース６"
capture label variable var103_11 "主に介護する者の介護時間"
capture label variable var104_11 "スペース７"
capture label variable var105_11 "その他介護者数"
capture label variable var106_11 "有無"
capture label variable var107_11 "同別居"
capture label variable var108_11 "性"
capture label variable var109_11 "年齢"
capture label variable var110_11 "続柄"
capture label variable var111_11 "介護頻度"
capture label variable var112_11 "スペース８"
capture label variable var113_11 "介護の有無"
capture label variable var114_11 "事業者（ホームヘルパー等）による介護"
capture label variable var115_11 "主に介護する者"
capture label variable var116_11 "その他の者"
capture label variable var117_11 "介護の有無"
capture label variable var118_11 "事業者（ホームヘルパー等）による介護"
capture label variable var119_11 "主に介護する者"
capture label variable var120_11 "その他の者"
capture label variable var121_11 "介護の有無"
capture label variable var122_11 "事業者（ホームヘルパー等）による介護"
capture label variable var123_11 "主に介護する者"
capture label variable var124_11 "その他の者"
capture label variable var125_11 "介護の有無"
capture label variable var126_11 "事業者（ホームヘルパー等）による介護"
capture label variable var127_11 "主に介護する者"
capture label variable var128_11 "その他の者"
capture label variable var129_11 "介護の有無"
capture label variable var130_11 "事業者（ホームヘルパー等）による介護"
capture label variable var131_11 "主に介護する者"
capture label variable var132_11 "その他の者"
capture label variable var133_11 "介護の有無"
capture label variable var134_11 "事業者（ホームヘルパー等）による介護"
capture label variable var135_11 "主に介護する者"
capture label variable var136_11 "その他の者"
capture label variable var137_11 "介護の有無"
capture label variable var138_11 "事業者（ホームヘルパー等）による介護"
capture label variable var139_11 "主に介護する者"
capture label variable var140_11 "その他の者"
capture label variable var141_11 "介護の有無"
capture label variable var142_11 "事業者（ホームヘルパー等）による介護"
capture label variable var143_11 "主に介護する者"
capture label variable var144_11 "その他の者"
capture label variable var145_11 "介護の有無"
capture label variable var146_11 "事業者（ホームヘルパー等）による介護"
capture label variable var147_11 "主に介護する者"
capture label variable var148_11 "その他の者"
capture label variable var149_11 "介護の有無"
capture label variable var150_11 "事業者（ホームヘルパー等）による介護"
capture label variable var151_11 "主に介護する者"
capture label variable var152_11 "その他の者"
capture label variable var153_11 "介護の有無"
capture label variable var154_11 "事業者（ホームヘルパー等）による介護"
capture label variable var155_11 "主に介護する者"
capture label variable var156_11 "その他の者"
capture label variable var157_11 "介護の有無"
capture label variable var158_11 "事業者（ホームヘルパー等）による介護"
capture label variable var159_11 "主に介護する者"
capture label variable var160_11 "その他の者"
capture label variable var161_11 "介護の有無"
capture label variable var162_11 "事業者（ホームヘルパー等）による介護"
capture label variable var163_11 "主に介護する者"
capture label variable var164_11 "その他の者"
capture label variable var165_11 "介護の有無"
capture label variable var166_11 "事業者（ホームヘルパー等）による介護"
capture label variable var167_11 "主に介護する者"
capture label variable var168_11 "その他の者"
capture label variable var169_11 "介護の有無"
capture label variable var170_11 "事業者（ホームヘルパー等）による介護"
capture label variable var171_11 "主に介護する者"
capture label variable var172_11 "その他の者"
capture label variable var173_11 "介護の有無"
capture label variable var174_11 "事業者（ホームヘルパー等）による介護"
capture label variable var175_11 "主に介護する者"
capture label variable var176_11 "その他の者"
capture label variable var177_11 "スペース９"
capture label variable var41_12 "介護票認定者番号"
capture label variable var42_12 "世帯票世帯員番号"
capture label variable var43_12 "調査票の回答者"
capture label variable var44_12 "性別"
capture label variable var45_12 "元号"
capture label variable var46_12 "年"
capture label variable var47_12 "月"
capture label variable var48_12 "年齢"
capture label variable var49_12 "配偶者の有無"
capture label variable var50_12 "変化"
capture label variable var51_12 "現在"
capture label variable var52_12 "１年前"
capture label variable var53_12 "1脳血管疾患（脳卒中）"
capture label variable var54_12 "2心疾患（心臓病）"
capture label variable var55_12 "3悪性新生物（がん）"
capture label variable var56_12 "4呼吸器疾患"
capture label variable var57_12 "5関節疾患"
capture label variable var58_12 "6認知症"
capture label variable var59_12 "7パーキンソン病"
capture label variable var60_12 "8糖尿病"
capture label variable var61_12 "9視覚・聴覚障害"
capture label variable var62_12 "10骨折・転倒"
capture label variable var63_12 "11脊髄損傷"
capture label variable var64_12 "12高齢による衰弱"
capture label variable var65_12 "13その他"
capture label variable var66_12 "14わからない"
capture label variable var67_12 "介護が必要となった主な原因"
capture label variable var68_12 "利用の有無"
capture label variable var69_12 "1 訪問系サービス"
capture label variable var70_12 "2 通所系サービス"
capture label variable var71_12 "3 短期入所サービス"
capture label variable var72_12 "4 居住系サービス（グループホーム）"
capture label variable var73_12 "5 小規模多機能型サービス等"
capture label variable var74_12 "6 配食サービス"
capture label variable var75_12 "7 外出支援サービス"
capture label variable var76_12 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_12 "1 家族介護で何とかやっていける"
capture label variable var78_12 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_12 "3 他人を家に入れたくない"
capture label variable var80_12 "4 外出するのが大変"
capture label variable var81_12 "5 どのようなサービスがあるかわからない"
capture label variable var82_12 "6 サービスを受ける手続きがわからない"
capture label variable var83_12 "7 利用者負担が払えない"
capture label variable var84_12 "8 受けたいサービスがない"
capture label variable var85_12 "9 入院していた"
capture label variable var86_12 "10 その他"
capture label variable var87_12 "11 不詳"
capture label variable var88_12 "費用額"
capture label variable var89_12 "介護保険所得段階"
capture label variable var90_12 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_12 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_12 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_12 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_12 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_12 "スペース４"
capture label variable var96_12 "主に介護する者の同別居"
capture label variable var97_12 "スペース５"
capture label variable var98_12 "続柄"
capture label variable var99_12 "性"
capture label variable var100_12 "年齢"
capture label variable var101_12 "配偶者の有無"
capture label variable var102_12 "スペース６"
capture label variable var103_12 "主に介護する者の介護時間"
capture label variable var104_12 "スペース７"
capture label variable var105_12 "その他介護者数"
capture label variable var106_12 "有無"
capture label variable var107_12 "同別居"
capture label variable var108_12 "性"
capture label variable var109_12 "年齢"
capture label variable var110_12 "続柄"
capture label variable var111_12 "介護頻度"
capture label variable var112_12 "スペース８"
capture label variable var113_12 "介護の有無"
capture label variable var114_12 "事業者（ホームヘルパー等）による介護"
capture label variable var115_12 "主に介護する者"
capture label variable var116_12 "その他の者"
capture label variable var117_12 "介護の有無"
capture label variable var118_12 "事業者（ホームヘルパー等）による介護"
capture label variable var119_12 "主に介護する者"
capture label variable var120_12 "その他の者"
capture label variable var121_12 "介護の有無"
capture label variable var122_12 "事業者（ホームヘルパー等）による介護"
capture label variable var123_12 "主に介護する者"
capture label variable var124_12 "その他の者"
capture label variable var125_12 "介護の有無"
capture label variable var126_12 "事業者（ホームヘルパー等）による介護"
capture label variable var127_12 "主に介護する者"
capture label variable var128_12 "その他の者"
capture label variable var129_12 "介護の有無"
capture label variable var130_12 "事業者（ホームヘルパー等）による介護"
capture label variable var131_12 "主に介護する者"
capture label variable var132_12 "その他の者"
capture label variable var133_12 "介護の有無"
capture label variable var134_12 "事業者（ホームヘルパー等）による介護"
capture label variable var135_12 "主に介護する者"
capture label variable var136_12 "その他の者"
capture label variable var137_12 "介護の有無"
capture label variable var138_12 "事業者（ホームヘルパー等）による介護"
capture label variable var139_12 "主に介護する者"
capture label variable var140_12 "その他の者"
capture label variable var141_12 "介護の有無"
capture label variable var142_12 "事業者（ホームヘルパー等）による介護"
capture label variable var143_12 "主に介護する者"
capture label variable var144_12 "その他の者"
capture label variable var145_12 "介護の有無"
capture label variable var146_12 "事業者（ホームヘルパー等）による介護"
capture label variable var147_12 "主に介護する者"
capture label variable var148_12 "その他の者"
capture label variable var149_12 "介護の有無"
capture label variable var150_12 "事業者（ホームヘルパー等）による介護"
capture label variable var151_12 "主に介護する者"
capture label variable var152_12 "その他の者"
capture label variable var153_12 "介護の有無"
capture label variable var154_12 "事業者（ホームヘルパー等）による介護"
capture label variable var155_12 "主に介護する者"
capture label variable var156_12 "その他の者"
capture label variable var157_12 "介護の有無"
capture label variable var158_12 "事業者（ホームヘルパー等）による介護"
capture label variable var159_12 "主に介護する者"
capture label variable var160_12 "その他の者"
capture label variable var161_12 "介護の有無"
capture label variable var162_12 "事業者（ホームヘルパー等）による介護"
capture label variable var163_12 "主に介護する者"
capture label variable var164_12 "その他の者"
capture label variable var165_12 "介護の有無"
capture label variable var166_12 "事業者（ホームヘルパー等）による介護"
capture label variable var167_12 "主に介護する者"
capture label variable var168_12 "その他の者"
capture label variable var169_12 "介護の有無"
capture label variable var170_12 "事業者（ホームヘルパー等）による介護"
capture label variable var171_12 "主に介護する者"
capture label variable var172_12 "その他の者"
capture label variable var173_12 "介護の有無"
capture label variable var174_12 "事業者（ホームヘルパー等）による介護"
capture label variable var175_12 "主に介護する者"
capture label variable var176_12 "その他の者"
capture label variable var177_12 "スペース９"
capture label variable var41_13 "介護票認定者番号"
capture label variable var42_13 "世帯票世帯員番号"
capture label variable var43_13 "調査票の回答者"
capture label variable var44_13 "性別"
capture label variable var45_13 "元号"
capture label variable var46_13 "年"
capture label variable var47_13 "月"
capture label variable var48_13 "年齢"
capture label variable var49_13 "配偶者の有無"
capture label variable var50_13 "変化"
capture label variable var51_13 "現在"
capture label variable var52_13 "１年前"
capture label variable var53_13 "1脳血管疾患（脳卒中）"
capture label variable var54_13 "2心疾患（心臓病）"
capture label variable var55_13 "3悪性新生物（がん）"
capture label variable var56_13 "4呼吸器疾患"
capture label variable var57_13 "5関節疾患"
capture label variable var58_13 "6認知症"
capture label variable var59_13 "7パーキンソン病"
capture label variable var60_13 "8糖尿病"
capture label variable var61_13 "9視覚・聴覚障害"
capture label variable var62_13 "10骨折・転倒"
capture label variable var63_13 "11脊髄損傷"
capture label variable var64_13 "12高齢による衰弱"
capture label variable var65_13 "13その他"
capture label variable var66_13 "14わからない"
capture label variable var67_13 "介護が必要となった主な原因"
capture label variable var68_13 "利用の有無"
capture label variable var69_13 "1 訪問系サービス"
capture label variable var70_13 "2 通所系サービス"
capture label variable var71_13 "3 短期入所サービス"
capture label variable var72_13 "4 居住系サービス（グループホーム）"
capture label variable var73_13 "5 小規模多機能型サービス等"
capture label variable var74_13 "6 配食サービス"
capture label variable var75_13 "7 外出支援サービス"
capture label variable var76_13 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_13 "1 家族介護で何とかやっていける"
capture label variable var78_13 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_13 "3 他人を家に入れたくない"
capture label variable var80_13 "4 外出するのが大変"
capture label variable var81_13 "5 どのようなサービスがあるかわからない"
capture label variable var82_13 "6 サービスを受ける手続きがわからない"
capture label variable var83_13 "7 利用者負担が払えない"
capture label variable var84_13 "8 受けたいサービスがない"
capture label variable var85_13 "9 入院していた"
capture label variable var86_13 "10 その他"
capture label variable var87_13 "11 不詳"
capture label variable var88_13 "費用額"
capture label variable var89_13 "介護保険所得段階"
capture label variable var90_13 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_13 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_13 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_13 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_13 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_13 "スペース４"
capture label variable var96_13 "主に介護する者の同別居"
capture label variable var97_13 "スペース５"
capture label variable var98_13 "続柄"
capture label variable var99_13 "性"
capture label variable var100_13 "年齢"
capture label variable var101_13 "配偶者の有無"
capture label variable var102_13 "スペース６"
capture label variable var103_13 "主に介護する者の介護時間"
capture label variable var104_13 "スペース７"
capture label variable var105_13 "その他介護者数"
capture label variable var106_13 "有無"
capture label variable var107_13 "同別居"
capture label variable var108_13 "性"
capture label variable var109_13 "年齢"
capture label variable var110_13 "続柄"
capture label variable var111_13 "介護頻度"
capture label variable var112_13 "スペース８"
capture label variable var113_13 "介護の有無"
capture label variable var114_13 "事業者（ホームヘルパー等）による介護"
capture label variable var115_13 "主に介護する者"
capture label variable var116_13 "その他の者"
capture label variable var117_13 "介護の有無"
capture label variable var118_13 "事業者（ホームヘルパー等）による介護"
capture label variable var119_13 "主に介護する者"
capture label variable var120_13 "その他の者"
capture label variable var121_13 "介護の有無"
capture label variable var122_13 "事業者（ホームヘルパー等）による介護"
capture label variable var123_13 "主に介護する者"
capture label variable var124_13 "その他の者"
capture label variable var125_13 "介護の有無"
capture label variable var126_13 "事業者（ホームヘルパー等）による介護"
capture label variable var127_13 "主に介護する者"
capture label variable var128_13 "その他の者"
capture label variable var129_13 "介護の有無"
capture label variable var130_13 "事業者（ホームヘルパー等）による介護"
capture label variable var131_13 "主に介護する者"
capture label variable var132_13 "その他の者"
capture label variable var133_13 "介護の有無"
capture label variable var134_13 "事業者（ホームヘルパー等）による介護"
capture label variable var135_13 "主に介護する者"
capture label variable var136_13 "その他の者"
capture label variable var137_13 "介護の有無"
capture label variable var138_13 "事業者（ホームヘルパー等）による介護"
capture label variable var139_13 "主に介護する者"
capture label variable var140_13 "その他の者"
capture label variable var141_13 "介護の有無"
capture label variable var142_13 "事業者（ホームヘルパー等）による介護"
capture label variable var143_13 "主に介護する者"
capture label variable var144_13 "その他の者"
capture label variable var145_13 "介護の有無"
capture label variable var146_13 "事業者（ホームヘルパー等）による介護"
capture label variable var147_13 "主に介護する者"
capture label variable var148_13 "その他の者"
capture label variable var149_13 "介護の有無"
capture label variable var150_13 "事業者（ホームヘルパー等）による介護"
capture label variable var151_13 "主に介護する者"
capture label variable var152_13 "その他の者"
capture label variable var153_13 "介護の有無"
capture label variable var154_13 "事業者（ホームヘルパー等）による介護"
capture label variable var155_13 "主に介護する者"
capture label variable var156_13 "その他の者"
capture label variable var157_13 "介護の有無"
capture label variable var158_13 "事業者（ホームヘルパー等）による介護"
capture label variable var159_13 "主に介護する者"
capture label variable var160_13 "その他の者"
capture label variable var161_13 "介護の有無"
capture label variable var162_13 "事業者（ホームヘルパー等）による介護"
capture label variable var163_13 "主に介護する者"
capture label variable var164_13 "その他の者"
capture label variable var165_13 "介護の有無"
capture label variable var166_13 "事業者（ホームヘルパー等）による介護"
capture label variable var167_13 "主に介護する者"
capture label variable var168_13 "その他の者"
capture label variable var169_13 "介護の有無"
capture label variable var170_13 "事業者（ホームヘルパー等）による介護"
capture label variable var171_13 "主に介護する者"
capture label variable var172_13 "その他の者"
capture label variable var173_13 "介護の有無"
capture label variable var174_13 "事業者（ホームヘルパー等）による介護"
capture label variable var175_13 "主に介護する者"
capture label variable var176_13 "その他の者"
capture label variable var177_13 "スペース９"
capture label variable var41_14 "介護票認定者番号"
capture label variable var42_14 "世帯票世帯員番号"
capture label variable var43_14 "調査票の回答者"
capture label variable var44_14 "性別"
capture label variable var45_14 "元号"
capture label variable var46_14 "年"
capture label variable var47_14 "月"
capture label variable var48_14 "年齢"
capture label variable var49_14 "配偶者の有無"
capture label variable var50_14 "変化"
capture label variable var51_14 "現在"
capture label variable var52_14 "１年前"
capture label variable var53_14 "1脳血管疾患（脳卒中）"
capture label variable var54_14 "2心疾患（心臓病）"
capture label variable var55_14 "3悪性新生物（がん）"
capture label variable var56_14 "4呼吸器疾患"
capture label variable var57_14 "5関節疾患"
capture label variable var58_14 "6認知症"
capture label variable var59_14 "7パーキンソン病"
capture label variable var60_14 "8糖尿病"
capture label variable var61_14 "9視覚・聴覚障害"
capture label variable var62_14 "10骨折・転倒"
capture label variable var63_14 "11脊髄損傷"
capture label variable var64_14 "12高齢による衰弱"
capture label variable var65_14 "13その他"
capture label variable var66_14 "14わからない"
capture label variable var67_14 "介護が必要となった主な原因"
capture label variable var68_14 "利用の有無"
capture label variable var69_14 "1 訪問系サービス"
capture label variable var70_14 "2 通所系サービス"
capture label variable var71_14 "3 短期入所サービス"
capture label variable var72_14 "4 居住系サービス（グループホーム）"
capture label variable var73_14 "5 小規模多機能型サービス等"
capture label variable var74_14 "6 配食サービス"
capture label variable var75_14 "7 外出支援サービス"
capture label variable var76_14 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_14 "1 家族介護で何とかやっていける"
capture label variable var78_14 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_14 "3 他人を家に入れたくない"
capture label variable var80_14 "4 外出するのが大変"
capture label variable var81_14 "5 どのようなサービスがあるかわからない"
capture label variable var82_14 "6 サービスを受ける手続きがわからない"
capture label variable var83_14 "7 利用者負担が払えない"
capture label variable var84_14 "8 受けたいサービスがない"
capture label variable var85_14 "9 入院していた"
capture label variable var86_14 "10 その他"
capture label variable var87_14 "11 不詳"
capture label variable var88_14 "費用額"
capture label variable var89_14 "介護保険所得段階"
capture label variable var90_14 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_14 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_14 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_14 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_14 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_14 "スペース４"
capture label variable var96_14 "主に介護する者の同別居"
capture label variable var97_14 "スペース５"
capture label variable var98_14 "続柄"
capture label variable var99_14 "性"
capture label variable var100_14 "年齢"
capture label variable var101_14 "配偶者の有無"
capture label variable var102_14 "スペース６"
capture label variable var103_14 "主に介護する者の介護時間"
capture label variable var104_14 "スペース７"
capture label variable var105_14 "その他介護者数"
capture label variable var106_14 "有無"
capture label variable var107_14 "同別居"
capture label variable var108_14 "性"
capture label variable var109_14 "年齢"
capture label variable var110_14 "続柄"
capture label variable var111_14 "介護頻度"
capture label variable var112_14 "スペース８"
capture label variable var113_14 "介護の有無"
capture label variable var114_14 "事業者（ホームヘルパー等）による介護"
capture label variable var115_14 "主に介護する者"
capture label variable var116_14 "その他の者"
capture label variable var117_14 "介護の有無"
capture label variable var118_14 "事業者（ホームヘルパー等）による介護"
capture label variable var119_14 "主に介護する者"
capture label variable var120_14 "その他の者"
capture label variable var121_14 "介護の有無"
capture label variable var122_14 "事業者（ホームヘルパー等）による介護"
capture label variable var123_14 "主に介護する者"
capture label variable var124_14 "その他の者"
capture label variable var125_14 "介護の有無"
capture label variable var126_14 "事業者（ホームヘルパー等）による介護"
capture label variable var127_14 "主に介護する者"
capture label variable var128_14 "その他の者"
capture label variable var129_14 "介護の有無"
capture label variable var130_14 "事業者（ホームヘルパー等）による介護"
capture label variable var131_14 "主に介護する者"
capture label variable var132_14 "その他の者"
capture label variable var133_14 "介護の有無"
capture label variable var134_14 "事業者（ホームヘルパー等）による介護"
capture label variable var135_14 "主に介護する者"
capture label variable var136_14 "その他の者"
capture label variable var137_14 "介護の有無"
capture label variable var138_14 "事業者（ホームヘルパー等）による介護"
capture label variable var139_14 "主に介護する者"
capture label variable var140_14 "その他の者"
capture label variable var141_14 "介護の有無"
capture label variable var142_14 "事業者（ホームヘルパー等）による介護"
capture label variable var143_14 "主に介護する者"
capture label variable var144_14 "その他の者"
capture label variable var145_14 "介護の有無"
capture label variable var146_14 "事業者（ホームヘルパー等）による介護"
capture label variable var147_14 "主に介護する者"
capture label variable var148_14 "その他の者"
capture label variable var149_14 "介護の有無"
capture label variable var150_14 "事業者（ホームヘルパー等）による介護"
capture label variable var151_14 "主に介護する者"
capture label variable var152_14 "その他の者"
capture label variable var153_14 "介護の有無"
capture label variable var154_14 "事業者（ホームヘルパー等）による介護"
capture label variable var155_14 "主に介護する者"
capture label variable var156_14 "その他の者"
capture label variable var157_14 "介護の有無"
capture label variable var158_14 "事業者（ホームヘルパー等）による介護"
capture label variable var159_14 "主に介護する者"
capture label variable var160_14 "その他の者"
capture label variable var161_14 "介護の有無"
capture label variable var162_14 "事業者（ホームヘルパー等）による介護"
capture label variable var163_14 "主に介護する者"
capture label variable var164_14 "その他の者"
capture label variable var165_14 "介護の有無"
capture label variable var166_14 "事業者（ホームヘルパー等）による介護"
capture label variable var167_14 "主に介護する者"
capture label variable var168_14 "その他の者"
capture label variable var169_14 "介護の有無"
capture label variable var170_14 "事業者（ホームヘルパー等）による介護"
capture label variable var171_14 "主に介護する者"
capture label variable var172_14 "その他の者"
capture label variable var173_14 "介護の有無"
capture label variable var174_14 "事業者（ホームヘルパー等）による介護"
capture label variable var175_14 "主に介護する者"
capture label variable var176_14 "その他の者"
capture label variable var177_14 "スペース９"
capture label variable var41_15 "介護票認定者番号"
capture label variable var42_15 "世帯票世帯員番号"
capture label variable var43_15 "調査票の回答者"
capture label variable var44_15 "性別"
capture label variable var45_15 "元号"
capture label variable var46_15 "年"
capture label variable var47_15 "月"
capture label variable var48_15 "年齢"
capture label variable var49_15 "配偶者の有無"
capture label variable var50_15 "変化"
capture label variable var51_15 "現在"
capture label variable var52_15 "１年前"
capture label variable var53_15 "1脳血管疾患（脳卒中）"
capture label variable var54_15 "2心疾患（心臓病）"
capture label variable var55_15 "3悪性新生物（がん）"
capture label variable var56_15 "4呼吸器疾患"
capture label variable var57_15 "5関節疾患"
capture label variable var58_15 "6認知症"
capture label variable var59_15 "7パーキンソン病"
capture label variable var60_15 "8糖尿病"
capture label variable var61_15 "9視覚・聴覚障害"
capture label variable var62_15 "10骨折・転倒"
capture label variable var63_15 "11脊髄損傷"
capture label variable var64_15 "12高齢による衰弱"
capture label variable var65_15 "13その他"
capture label variable var66_15 "14わからない"
capture label variable var67_15 "介護が必要となった主な原因"
capture label variable var68_15 "利用の有無"
capture label variable var69_15 "1 訪問系サービス"
capture label variable var70_15 "2 通所系サービス"
capture label variable var71_15 "3 短期入所サービス"
capture label variable var72_15 "4 居住系サービス（グループホーム）"
capture label variable var73_15 "5 小規模多機能型サービス等"
capture label variable var74_15 "6 配食サービス"
capture label variable var75_15 "7 外出支援サービス"
capture label variable var76_15 "8 寝具類等洗濯乾燥消毒サービス"
capture label variable var77_15 "1 家族介護で何とかやっていける"
capture label variable var78_15 "2 介護が必要な者（本人）でなんとかやっていける"
capture label variable var79_15 "3 他人を家に入れたくない"
capture label variable var80_15 "4 外出するのが大変"
capture label variable var81_15 "5 どのようなサービスがあるかわからない"
capture label variable var82_15 "6 サービスを受ける手続きがわからない"
capture label variable var83_15 "7 利用者負担が払えない"
capture label variable var84_15 "8 受けたいサービスがない"
capture label variable var85_15 "9 入院していた"
capture label variable var86_15 "10 その他"
capture label variable var87_15 "11 不詳"
capture label variable var88_15 "費用額"
capture label variable var89_15 "介護保険所得段階"
capture label variable var90_15 "介護が必要な者（あるいは配偶者）の収入を充てた"
capture label variable var91_15 "介護が必要な者（あるいは配偶者）の貯蓄を充てた"
capture label variable var92_15 "介護が必要な者（あるいは配偶者）以外の者のの収入・貯蓄を充てた"
capture label variable var93_15 "介護が必要な者（あるいは配偶者）の年金・恩給"
capture label variable var94_15 "介護が必要な者（あるいは配偶者）の年金・恩給以外"
capture label variable var95_15 "スペース４"
capture label variable var96_15 "主に介護する者の同別居"
capture label variable var97_15 "スペース５"
capture label variable var98_15 "続柄"
capture label variable var99_15 "性"
capture label variable var100_15 "年齢"
capture label variable var101_15 "配偶者の有無"
capture label variable var102_15 "スペース６"
capture label variable var103_15 "主に介護する者の介護時間"
capture label variable var104_15 "スペース７"
capture label variable var105_15 "その他介護者数"
capture label variable var106_15 "有無"
capture label variable var107_15 "同別居"
capture label variable var108_15 "性"
capture label variable var109_15 "年齢"
capture label variable var110_15 "続柄"
capture label variable var111_15 "介護頻度"
capture label variable var112_15 "スペース８"
capture label variable var113_15 "介護の有無"
capture label variable var114_15 "事業者（ホームヘルパー等）による介護"
capture label variable var115_15 "主に介護する者"
capture label variable var116_15 "その他の者"
capture label variable var117_15 "介護の有無"
capture label variable var118_15 "事業者（ホームヘルパー等）による介護"
capture label variable var119_15 "主に介護する者"
capture label variable var120_15 "その他の者"
capture label variable var121_15 "介護の有無"
capture label variable var122_15 "事業者（ホームヘルパー等）による介護"
capture label variable var123_15 "主に介護する者"
capture label variable var124_15 "その他の者"
capture label variable var125_15 "介護の有無"
capture label variable var126_15 "事業者（ホームヘルパー等）による介護"
capture label variable var127_15 "主に介護する者"
capture label variable var128_15 "その他の者"
capture label variable var129_15 "介護の有無"
capture label variable var130_15 "事業者（ホームヘルパー等）による介護"
capture label variable var131_15 "主に介護する者"
capture label variable var132_15 "その他の者"
capture label variable var133_15 "介護の有無"
capture label variable var134_15 "事業者（ホームヘルパー等）による介護"
capture label variable var135_15 "主に介護する者"
capture label variable var136_15 "その他の者"
capture label variable var137_15 "介護の有無"
capture label variable var138_15 "事業者（ホームヘルパー等）による介護"
capture label variable var139_15 "主に介護する者"
capture label variable var140_15 "その他の者"
capture label variable var141_15 "介護の有無"
capture label variable var142_15 "事業者（ホームヘルパー等）による介護"
capture label variable var143_15 "主に介護する者"
capture label variable var144_15 "その他の者"
capture label variable var145_15 "介護の有無"
capture label variable var146_15 "事業者（ホームヘルパー等）による介護"
capture label variable var147_15 "主に介護する者"
capture label variable var148_15 "その他の者"
capture label variable var149_15 "介護の有無"
capture label variable var150_15 "事業者（ホームヘルパー等）による介護"
capture label variable var151_15 "主に介護する者"
capture label variable var152_15 "その他の者"
capture label variable var153_15 "介護の有無"
capture label variable var154_15 "事業者（ホームヘルパー等）による介護"
capture label variable var155_15 "主に介護する者"
capture label variable var156_15 "その他の者"
capture label variable var157_15 "介護の有無"
capture label variable var158_15 "事業者（ホームヘルパー等）による介護"
capture label variable var159_15 "主に介護する者"
capture label variable var160_15 "その他の者"
capture label variable var161_15 "介護の有無"
capture label variable var162_15 "事業者（ホームヘルパー等）による介護"
capture label variable var163_15 "主に介護する者"
capture label variable var164_15 "その他の者"
capture label variable var165_15 "介護の有無"
capture label variable var166_15 "事業者（ホームヘルパー等）による介護"
capture label variable var167_15 "主に介護する者"
capture label variable var168_15 "その他の者"
capture label variable var169_15 "介護の有無"
capture label variable var170_15 "事業者（ホームヘルパー等）による介護"
capture label variable var171_15 "主に介護する者"
capture label variable var172_15 "その他の者"
capture label variable var173_15 "介護の有無"
capture label variable var174_15 "事業者（ホームヘルパー等）による介護"
capture label variable var175_15 "主に介護する者"
capture label variable var176_15 "その他の者"
capture label variable var177_15 "スペース９"
