cap label var Year "調査年月" 
cap label var N_City "市町村番号" 
cap label var N_Chosaku "調査区符号" 
cap label var N_Setai "世帯番号" 
cap label var N_Setaiin "世帯員番号" 
cap label var KC_Setaiinsu "10歳以上の世帯員数" 
cap label var KC_Setaiinsu_U10 "10歳未満の世帯員数" 
cap label var KC_Hitori "一人の世帯" 
cap label var KC_Sex "１男女の別" 
cap label var KC_Tsuduki "２世帯主との続き柄" 
cap label var KC_Gengo "３出生元号" 
cap label var KC_Year "３出生年" 
cap label var KC_Month "３出生月" 
cap label var KC_Haigu "４配偶者の有無" 
cap label var KC_Kyoiku "５教育（学校の種類）" 
cap label var KC_ChildHome "６あなたの子はどこに住んでいますか" 
cap label var KC_Kaigo1 "65歳以上の家族を介護(自宅内)" 
cap label var KC_Kaigo2 "65歳以上の家族を介護(自宅外・同一敷地内・近所)" 
cap label var KC_Kaigo3 "65歳以上の家族を介護(自宅外・その他)" 
cap label var KC_Kaigo4 "その他の家族を介護(自宅内)" 
cap label var KC_Kaigo5 "その他の家族を介護(自宅外・同一敷地内・近所)" 
cap label var KC_Kaigo6 "その他の家族を介護(自宅外・その他)" 
cap label var KC_Kaigo7 "介護はしていない" 
cap label var KC_Job "８ふだん仕事をしていますか" 
cap label var KC_WantJob "９仕事をしたいと思っていますか" 
cap label var KC_HopeWorkTime "10１週間に何時間くらい働きたいと思っていますか" 
cap label var KC_Tsutome "11勤めか自営かの別" 
cap label var KC_Keitai "12勤務形態" 
cap label var KC_Yukyu "13年次有給休暇の取得日数" 
cap label var KC_Shoku_Naiyo "記入の有無" 
cap label var KC_Shokugyo "職業符号" 
cap label var KC_Jyugyo "15勤め先・業主などの企業全体の従業者数" 
cap label var KC_Shugyo "16ふだんの１週間の就業時間" 
cap label var KC_ShugyokiboTime "17希望する1週間の就業時間" 
cap label var KC_Tsukin "18ふだんの片道の通勤時間" 
cap label var KC_Kenko "19ふだんの健康状態" 
cap label var KC_Shunyu_Kojin "20仕事からの１年間の収入または収益" 
cap label var KC_Time_Date "日にち" 
cap label var KC_Time_Kind1 "旅行・行楽" 
cap label var KC_Time_Kind2 "行事または冠婚葬祭" 
cap label var KC_Time_Kind3 "出張・研修など" 
cap label var KC_Time_Kind4 "在宅勤務" 
cap label var KC_Time_Kind5 "療養" 
cap label var KC_Time_Kind6 "休みの日" 
cap label var KC_Time_Kind7 "育児休業・子の看護休暇" 
cap label var KC_Time_Kind8 "介護休業・介護休暇" 
cap label var KC_Time_Kind9 "その他" 
cap label var KC_Time_Weather "天気" 
cap label var KC_House "27住居の種類" 
cap label var KC_Car "28自家用車の有無" 
cap label var KC_Shunyu_Setai "29世帯の年間収入(税込み)" 
cap label var KC_Help "30ふだん世帯以外の人から介護の手助けを受けていますか" 
cap label var KC_Tanshin1 "いない" 
cap label var KC_Tanshin2 "配偶者" 
cap label var KC_Tanshin3 "父母または配偶者の父母" 
cap label var KC_Tanshin4 "子または子の配偶者" 
cap label var KC_Tanshin5 "その他" 
cap label var KC_Nyuin1 "いない" 
cap label var KC_Nyuin2 "配偶者" 
cap label var KC_Nyuin3 "父母または配偶者の父母" 
cap label var KC_Nyuin4 "子または子の配偶者" 
cap label var KC_Nyuin5 "その他" 
cap label var KC_U10_Tsuduki1 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age1 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku1 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_11 "親族（祖父母など）から" 
cap label var KC_U10_Help_21 "近隣の知人・友人などから" 
cap label var KC_U10_Help_31 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_41 "受けていない" 
cap label var KC_U10_Tsuduki2 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age2 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku2 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_12 "親族（祖父母など）から" 
cap label var KC_U10_Help_22 "近隣の知人・友人などから" 
cap label var KC_U10_Help_32 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_42 "受けていない" 
cap label var KC_U10_Tsuduki3 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age3 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku3 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_13 "親族（祖父母など）から" 
cap label var KC_U10_Help_23 "近隣の知人・友人などから" 
cap label var KC_U10_Help_33 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_43 "受けていない" 
cap label var KC_U10_Tsuduki4 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age4 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku4 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_14 "親族（祖父母など）から" 
cap label var KC_U10_Help_24 "近隣の知人・友人などから" 
cap label var KC_U10_Help_34 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_44 "受けていない" 
cap label var KC_U10_Tsuduki5 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age5 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku5 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_15 "親族（祖父母など）から" 
cap label var KC_U10_Help_25 "近隣の知人・友人などから" 
cap label var KC_U10_Help_35 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_45 "受けていない" 
cap label var KC_U10_Tsuduki6 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age6 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku6 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_16 "親族（祖父母など）から" 
cap label var KC_U10_Help_26 "近隣の知人・友人などから" 
cap label var KC_U10_Help_36 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_46 "受けていない" 
cap label var KC_U10_Tsuduki7 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age7 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku7 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_17 "親族（祖父母など）から" 
cap label var KC_U10_Help_27 "近隣の知人・友人などから" 
cap label var KC_U10_Help_37 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_47 "受けていない" 
cap label var KC_U10_Tsuduki8 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age8 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku8 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_18 "親族（祖父母など）から" 
cap label var KC_U10_Help_28 "近隣の知人・友人などから" 
cap label var KC_U10_Help_38 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_48 "受けていない" 
cap label var KC_U10_Tsuduki9 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age9 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku9 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_19 "親族（祖父母など）から" 
cap label var KC_U10_Help_29 "近隣の知人・友人などから" 
cap label var KC_U10_Help_39 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_49 "受けていない" 
cap label var KC_U10_Tsuduki10 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age10 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku10 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_110 "親族（祖父母など）から" 
cap label var KC_U10_Help_210 "近隣の知人・友人などから" 
cap label var KC_U10_Help_310 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_410 "受けていない" 
cap label var KC_Age "年齢" 
cap label var Joritsu "集計用乗率" 
cap label var Ken "都道府県" 
cap label var City "市区町村" 
cap label var Daitoshi "大都市圏符号" 
cap label var Toshi "都市階級符号" 
cap label var DIDKbn "人口集中・非集中の別" 
cap label var Chiiki "14地域" 
cap label var Day "1日目か2日目か" 
cap label var Youbi7 "7区分（曜日）" 
cap label var  "行動時間" 
cap label var TimeCode_1 "時間区分" 
cap label var KC_ActKind_1 "行動の種類" 
cap label var KC_Alone_1 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_1 "家族（一緒にいた人）" 
cap label var KC_WithSchool_1 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_1 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_2 "時間区分" 
cap label var KC_ActKind_2 "行動の種類" 
cap label var KC_Alone_2 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_2 "家族（一緒にいた人）" 
cap label var KC_WithSchool_2 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_2 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_3 "時間区分" 
cap label var KC_ActKind_3 "行動の種類" 
cap label var KC_Alone_3 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_3 "家族（一緒にいた人）" 
cap label var KC_WithSchool_3 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_3 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_4 "時間区分" 
cap label var KC_ActKind_4 "行動の種類" 
cap label var KC_Alone_4 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_4 "家族（一緒にいた人）" 
cap label var KC_WithSchool_4 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_4 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_5 "時間区分" 
cap label var KC_ActKind_5 "行動の種類" 
cap label var KC_Alone_5 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_5 "家族（一緒にいた人）" 
cap label var KC_WithSchool_5 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_5 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_6 "時間区分" 
cap label var KC_ActKind_6 "行動の種類" 
cap label var KC_Alone_6 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_6 "家族（一緒にいた人）" 
cap label var KC_WithSchool_6 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_6 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_7 "時間区分" 
cap label var KC_ActKind_7 "行動の種類" 
cap label var KC_Alone_7 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_7 "家族（一緒にいた人）" 
cap label var KC_WithSchool_7 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_7 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_8 "時間区分" 
cap label var KC_ActKind_8 "行動の種類" 
cap label var KC_Alone_8 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_8 "家族（一緒にいた人）" 
cap label var KC_WithSchool_8 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_8 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_9 "時間区分" 
cap label var KC_ActKind_9 "行動の種類" 
cap label var KC_Alone_9 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_9 "家族（一緒にいた人）" 
cap label var KC_WithSchool_9 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_9 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_10 "時間区分" 
cap label var KC_ActKind_10 "行動の種類" 
cap label var KC_Alone_10 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_10 "家族（一緒にいた人）" 
cap label var KC_WithSchool_10 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_10 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_11 "時間区分" 
cap label var KC_ActKind_11 "行動の種類" 
cap label var KC_Alone_11 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_11 "家族（一緒にいた人）" 
cap label var KC_WithSchool_11 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_11 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_12 "時間区分" 
cap label var KC_ActKind_12 "行動の種類" 
cap label var KC_Alone_12 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_12 "家族（一緒にいた人）" 
cap label var KC_WithSchool_12 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_12 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_13 "時間区分" 
cap label var KC_ActKind_13 "行動の種類" 
cap label var KC_Alone_13 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_13 "家族（一緒にいた人）" 
cap label var KC_WithSchool_13 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_13 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_14 "時間区分" 
cap label var KC_ActKind_14 "行動の種類" 
cap label var KC_Alone_14 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_14 "家族（一緒にいた人）" 
cap label var KC_WithSchool_14 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_14 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_15 "時間区分" 
cap label var KC_ActKind_15 "行動の種類" 
cap label var KC_Alone_15 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_15 "家族（一緒にいた人）" 
cap label var KC_WithSchool_15 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_15 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_16 "時間区分" 
cap label var KC_ActKind_16 "行動の種類" 
cap label var KC_Alone_16 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_16 "家族（一緒にいた人）" 
cap label var KC_WithSchool_16 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_16 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_17 "時間区分" 
cap label var KC_ActKind_17 "行動の種類" 
cap label var KC_Alone_17 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_17 "家族（一緒にいた人）" 
cap label var KC_WithSchool_17 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_17 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_18 "時間区分" 
cap label var KC_ActKind_18 "行動の種類" 
cap label var KC_Alone_18 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_18 "家族（一緒にいた人）" 
cap label var KC_WithSchool_18 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_18 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_19 "時間区分" 
cap label var KC_ActKind_19 "行動の種類" 
cap label var KC_Alone_19 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_19 "家族（一緒にいた人）" 
cap label var KC_WithSchool_19 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_19 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_20 "時間区分" 
cap label var KC_ActKind_20 "行動の種類" 
cap label var KC_Alone_20 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_20 "家族（一緒にいた人）" 
cap label var KC_WithSchool_20 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_20 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_21 "時間区分" 
cap label var KC_ActKind_21 "行動の種類" 
cap label var KC_Alone_21 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_21 "家族（一緒にいた人）" 
cap label var KC_WithSchool_21 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_21 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_22 "時間区分" 
cap label var KC_ActKind_22 "行動の種類" 
cap label var KC_Alone_22 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_22 "家族（一緒にいた人）" 
cap label var KC_WithSchool_22 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_22 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_23 "時間区分" 
cap label var KC_ActKind_23 "行動の種類" 
cap label var KC_Alone_23 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_23 "家族（一緒にいた人）" 
cap label var KC_WithSchool_23 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_23 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_24 "時間区分" 
cap label var KC_ActKind_24 "行動の種類" 
cap label var KC_Alone_24 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_24 "家族（一緒にいた人）" 
cap label var KC_WithSchool_24 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_24 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_25 "時間区分" 
cap label var KC_ActKind_25 "行動の種類" 
cap label var KC_Alone_25 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_25 "家族（一緒にいた人）" 
cap label var KC_WithSchool_25 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_25 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_26 "時間区分" 
cap label var KC_ActKind_26 "行動の種類" 
cap label var KC_Alone_26 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_26 "家族（一緒にいた人）" 
cap label var KC_WithSchool_26 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_26 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_27 "時間区分" 
cap label var KC_ActKind_27 "行動の種類" 
cap label var KC_Alone_27 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_27 "家族（一緒にいた人）" 
cap label var KC_WithSchool_27 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_27 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_28 "時間区分" 
cap label var KC_ActKind_28 "行動の種類" 
cap label var KC_Alone_28 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_28 "家族（一緒にいた人）" 
cap label var KC_WithSchool_28 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_28 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_29 "時間区分" 
cap label var KC_ActKind_29 "行動の種類" 
cap label var KC_Alone_29 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_29 "家族（一緒にいた人）" 
cap label var KC_WithSchool_29 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_29 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_30 "時間区分" 
cap label var KC_ActKind_30 "行動の種類" 
cap label var KC_Alone_30 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_30 "家族（一緒にいた人）" 
cap label var KC_WithSchool_30 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_30 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_31 "時間区分" 
cap label var KC_ActKind_31 "行動の種類" 
cap label var KC_Alone_31 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_31 "家族（一緒にいた人）" 
cap label var KC_WithSchool_31 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_31 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_32 "時間区分" 
cap label var KC_ActKind_32 "行動の種類" 
cap label var KC_Alone_32 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_32 "家族（一緒にいた人）" 
cap label var KC_WithSchool_32 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_32 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_33 "時間区分" 
cap label var KC_ActKind_33 "行動の種類" 
cap label var KC_Alone_33 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_33 "家族（一緒にいた人）" 
cap label var KC_WithSchool_33 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_33 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_34 "時間区分" 
cap label var KC_ActKind_34 "行動の種類" 
cap label var KC_Alone_34 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_34 "家族（一緒にいた人）" 
cap label var KC_WithSchool_34 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_34 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_35 "時間区分" 
cap label var KC_ActKind_35 "行動の種類" 
cap label var KC_Alone_35 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_35 "家族（一緒にいた人）" 
cap label var KC_WithSchool_35 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_35 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_36 "時間区分" 
cap label var KC_ActKind_36 "行動の種類" 
cap label var KC_Alone_36 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_36 "家族（一緒にいた人）" 
cap label var KC_WithSchool_36 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_36 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_37 "時間区分" 
cap label var KC_ActKind_37 "行動の種類" 
cap label var KC_Alone_37 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_37 "家族（一緒にいた人）" 
cap label var KC_WithSchool_37 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_37 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_38 "時間区分" 
cap label var KC_ActKind_38 "行動の種類" 
cap label var KC_Alone_38 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_38 "家族（一緒にいた人）" 
cap label var KC_WithSchool_38 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_38 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_39 "時間区分" 
cap label var KC_ActKind_39 "行動の種類" 
cap label var KC_Alone_39 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_39 "家族（一緒にいた人）" 
cap label var KC_WithSchool_39 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_39 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_40 "時間区分" 
cap label var KC_ActKind_40 "行動の種類" 
cap label var KC_Alone_40 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_40 "家族（一緒にいた人）" 
cap label var KC_WithSchool_40 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_40 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_41 "時間区分" 
cap label var KC_ActKind_41 "行動の種類" 
cap label var KC_Alone_41 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_41 "家族（一緒にいた人）" 
cap label var KC_WithSchool_41 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_41 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_42 "時間区分" 
cap label var KC_ActKind_42 "行動の種類" 
cap label var KC_Alone_42 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_42 "家族（一緒にいた人）" 
cap label var KC_WithSchool_42 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_42 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_43 "時間区分" 
cap label var KC_ActKind_43 "行動の種類" 
cap label var KC_Alone_43 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_43 "家族（一緒にいた人）" 
cap label var KC_WithSchool_43 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_43 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_44 "時間区分" 
cap label var KC_ActKind_44 "行動の種類" 
cap label var KC_Alone_44 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_44 "家族（一緒にいた人）" 
cap label var KC_WithSchool_44 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_44 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_45 "時間区分" 
cap label var KC_ActKind_45 "行動の種類" 
cap label var KC_Alone_45 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_45 "家族（一緒にいた人）" 
cap label var KC_WithSchool_45 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_45 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_46 "時間区分" 
cap label var KC_ActKind_46 "行動の種類" 
cap label var KC_Alone_46 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_46 "家族（一緒にいた人）" 
cap label var KC_WithSchool_46 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_46 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_47 "時間区分" 
cap label var KC_ActKind_47 "行動の種類" 
cap label var KC_Alone_47 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_47 "家族（一緒にいた人）" 
cap label var KC_WithSchool_47 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_47 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_48 "時間区分" 
cap label var KC_ActKind_48 "行動の種類" 
cap label var KC_Alone_48 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_48 "家族（一緒にいた人）" 
cap label var KC_WithSchool_48 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_48 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_49 "時間区分" 
cap label var KC_ActKind_49 "行動の種類" 
cap label var KC_Alone_49 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_49 "家族（一緒にいた人）" 
cap label var KC_WithSchool_49 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_49 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_50 "時間区分" 
cap label var KC_ActKind_50 "行動の種類" 
cap label var KC_Alone_50 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_50 "家族（一緒にいた人）" 
cap label var KC_WithSchool_50 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_50 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_51 "時間区分" 
cap label var KC_ActKind_51 "行動の種類" 
cap label var KC_Alone_51 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_51 "家族（一緒にいた人）" 
cap label var KC_WithSchool_51 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_51 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_52 "時間区分" 
cap label var KC_ActKind_52 "行動の種類" 
cap label var KC_Alone_52 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_52 "家族（一緒にいた人）" 
cap label var KC_WithSchool_52 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_52 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_53 "時間区分" 
cap label var KC_ActKind_53 "行動の種類" 
cap label var KC_Alone_53 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_53 "家族（一緒にいた人）" 
cap label var KC_WithSchool_53 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_53 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_54 "時間区分" 
cap label var KC_ActKind_54 "行動の種類" 
cap label var KC_Alone_54 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_54 "家族（一緒にいた人）" 
cap label var KC_WithSchool_54 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_54 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_55 "時間区分" 
cap label var KC_ActKind_55 "行動の種類" 
cap label var KC_Alone_55 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_55 "家族（一緒にいた人）" 
cap label var KC_WithSchool_55 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_55 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_56 "時間区分" 
cap label var KC_ActKind_56 "行動の種類" 
cap label var KC_Alone_56 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_56 "家族（一緒にいた人）" 
cap label var KC_WithSchool_56 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_56 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_57 "時間区分" 
cap label var KC_ActKind_57 "行動の種類" 
cap label var KC_Alone_57 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_57 "家族（一緒にいた人）" 
cap label var KC_WithSchool_57 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_57 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_58 "時間区分" 
cap label var KC_ActKind_58 "行動の種類" 
cap label var KC_Alone_58 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_58 "家族（一緒にいた人）" 
cap label var KC_WithSchool_58 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_58 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_59 "時間区分" 
cap label var KC_ActKind_59 "行動の種類" 
cap label var KC_Alone_59 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_59 "家族（一緒にいた人）" 
cap label var KC_WithSchool_59 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_59 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_60 "時間区分" 
cap label var KC_ActKind_60 "行動の種類" 
cap label var KC_Alone_60 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_60 "家族（一緒にいた人）" 
cap label var KC_WithSchool_60 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_60 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_61 "時間区分" 
cap label var KC_ActKind_61 "行動の種類" 
cap label var KC_Alone_61 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_61 "家族（一緒にいた人）" 
cap label var KC_WithSchool_61 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_61 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_62 "時間区分" 
cap label var KC_ActKind_62 "行動の種類" 
cap label var KC_Alone_62 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_62 "家族（一緒にいた人）" 
cap label var KC_WithSchool_62 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_62 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_63 "時間区分" 
cap label var KC_ActKind_63 "行動の種類" 
cap label var KC_Alone_63 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_63 "家族（一緒にいた人）" 
cap label var KC_WithSchool_63 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_63 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_64 "時間区分" 
cap label var KC_ActKind_64 "行動の種類" 
cap label var KC_Alone_64 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_64 "家族（一緒にいた人）" 
cap label var KC_WithSchool_64 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_64 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_65 "時間区分" 
cap label var KC_ActKind_65 "行動の種類" 
cap label var KC_Alone_65 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_65 "家族（一緒にいた人）" 
cap label var KC_WithSchool_65 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_65 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_66 "時間区分" 
cap label var KC_ActKind_66 "行動の種類" 
cap label var KC_Alone_66 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_66 "家族（一緒にいた人）" 
cap label var KC_WithSchool_66 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_66 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_67 "時間区分" 
cap label var KC_ActKind_67 "行動の種類" 
cap label var KC_Alone_67 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_67 "家族（一緒にいた人）" 
cap label var KC_WithSchool_67 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_67 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_68 "時間区分" 
cap label var KC_ActKind_68 "行動の種類" 
cap label var KC_Alone_68 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_68 "家族（一緒にいた人）" 
cap label var KC_WithSchool_68 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_68 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_69 "時間区分" 
cap label var KC_ActKind_69 "行動の種類" 
cap label var KC_Alone_69 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_69 "家族（一緒にいた人）" 
cap label var KC_WithSchool_69 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_69 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_70 "時間区分" 
cap label var KC_ActKind_70 "行動の種類" 
cap label var KC_Alone_70 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_70 "家族（一緒にいた人）" 
cap label var KC_WithSchool_70 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_70 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_71 "時間区分" 
cap label var KC_ActKind_71 "行動の種類" 
cap label var KC_Alone_71 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_71 "家族（一緒にいた人）" 
cap label var KC_WithSchool_71 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_71 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_72 "時間区分" 
cap label var KC_ActKind_72 "行動の種類" 
cap label var KC_Alone_72 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_72 "家族（一緒にいた人）" 
cap label var KC_WithSchool_72 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_72 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_73 "時間区分" 
cap label var KC_ActKind_73 "行動の種類" 
cap label var KC_Alone_73 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_73 "家族（一緒にいた人）" 
cap label var KC_WithSchool_73 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_73 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_74 "時間区分" 
cap label var KC_ActKind_74 "行動の種類" 
cap label var KC_Alone_74 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_74 "家族（一緒にいた人）" 
cap label var KC_WithSchool_74 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_74 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_75 "時間区分" 
cap label var KC_ActKind_75 "行動の種類" 
cap label var KC_Alone_75 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_75 "家族（一緒にいた人）" 
cap label var KC_WithSchool_75 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_75 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_76 "時間区分" 
cap label var KC_ActKind_76 "行動の種類" 
cap label var KC_Alone_76 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_76 "家族（一緒にいた人）" 
cap label var KC_WithSchool_76 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_76 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_77 "時間区分" 
cap label var KC_ActKind_77 "行動の種類" 
cap label var KC_Alone_77 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_77 "家族（一緒にいた人）" 
cap label var KC_WithSchool_77 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_77 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_78 "時間区分" 
cap label var KC_ActKind_78 "行動の種類" 
cap label var KC_Alone_78 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_78 "家族（一緒にいた人）" 
cap label var KC_WithSchool_78 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_78 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_79 "時間区分" 
cap label var KC_ActKind_79 "行動の種類" 
cap label var KC_Alone_79 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_79 "家族（一緒にいた人）" 
cap label var KC_WithSchool_79 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_79 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_80 "時間区分" 
cap label var KC_ActKind_80 "行動の種類" 
cap label var KC_Alone_80 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_80 "家族（一緒にいた人）" 
cap label var KC_WithSchool_80 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_80 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_81 "時間区分" 
cap label var KC_ActKind_81 "行動の種類" 
cap label var KC_Alone_81 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_81 "家族（一緒にいた人）" 
cap label var KC_WithSchool_81 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_81 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_82 "時間区分" 
cap label var KC_ActKind_82 "行動の種類" 
cap label var KC_Alone_82 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_82 "家族（一緒にいた人）" 
cap label var KC_WithSchool_82 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_82 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_83 "時間区分" 
cap label var KC_ActKind_83 "行動の種類" 
cap label var KC_Alone_83 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_83 "家族（一緒にいた人）" 
cap label var KC_WithSchool_83 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_83 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_84 "時間区分" 
cap label var KC_ActKind_84 "行動の種類" 
cap label var KC_Alone_84 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_84 "家族（一緒にいた人）" 
cap label var KC_WithSchool_84 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_84 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_85 "時間区分" 
cap label var KC_ActKind_85 "行動の種類" 
cap label var KC_Alone_85 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_85 "家族（一緒にいた人）" 
cap label var KC_WithSchool_85 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_85 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_86 "時間区分" 
cap label var KC_ActKind_86 "行動の種類" 
cap label var KC_Alone_86 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_86 "家族（一緒にいた人）" 
cap label var KC_WithSchool_86 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_86 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_87 "時間区分" 
cap label var KC_ActKind_87 "行動の種類" 
cap label var KC_Alone_87 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_87 "家族（一緒にいた人）" 
cap label var KC_WithSchool_87 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_87 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_88 "時間区分" 
cap label var KC_ActKind_88 "行動の種類" 
cap label var KC_Alone_88 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_88 "家族（一緒にいた人）" 
cap label var KC_WithSchool_88 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_88 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_89 "時間区分" 
cap label var KC_ActKind_89 "行動の種類" 
cap label var KC_Alone_89 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_89 "家族（一緒にいた人）" 
cap label var KC_WithSchool_89 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_89 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_90 "時間区分" 
cap label var KC_ActKind_90 "行動の種類" 
cap label var KC_Alone_90 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_90 "家族（一緒にいた人）" 
cap label var KC_WithSchool_90 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_90 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_91 "時間区分" 
cap label var KC_ActKind_91 "行動の種類" 
cap label var KC_Alone_91 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_91 "家族（一緒にいた人）" 
cap label var KC_WithSchool_91 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_91 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_92 "時間区分" 
cap label var KC_ActKind_92 "行動の種類" 
cap label var KC_Alone_92 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_92 "家族（一緒にいた人）" 
cap label var KC_WithSchool_92 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_92 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_93 "時間区分" 
cap label var KC_ActKind_93 "行動の種類" 
cap label var KC_Alone_93 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_93 "家族（一緒にいた人）" 
cap label var KC_WithSchool_93 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_93 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_94 "時間区分" 
cap label var KC_ActKind_94 "行動の種類" 
cap label var KC_Alone_94 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_94 "家族（一緒にいた人）" 
cap label var KC_WithSchool_94 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_94 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_95 "時間区分" 
cap label var KC_ActKind_95 "行動の種類" 
cap label var KC_Alone_95 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_95 "家族（一緒にいた人）" 
cap label var KC_WithSchool_95 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_95 "その他の人（一緒にいた人）" 
cap label var  "行動時間" 
cap label var TimeCode_96 "時間区分" 
cap label var KC_ActKind_96 "行動の種類" 
cap label var KC_Alone_96 "一人で（一緒にいた人）" 
cap label var KC_WithFamily_96 "家族（一緒にいた人）" 
cap label var KC_WithSchool_96 "学校・職場の人（一緒にいた人）" 
cap label var KC_WithOther_96 "その他の人（一緒にいた人）" 
