cap label var Year "調査年月" 
cap label var N_City "市町村番号" 
cap label var N_Chosaku "調査区符号" 
cap label var N_Setai "世帯番号" 
cap label var N_Setaiin "世帯員番号" 
cap label var KC_Setaiinsu "10歳以上の世帯員数" 
cap label var KC_Setaiinsu_U10 "10歳未満の世帯員数" 
cap label var KC_Hitori "一人の世帯" 
cap label var KC_Sex "１男女の別" 
cap label var KC_Tsuduki "２世帯主との続き柄" 
cap label var KC_Gengo "３出生元号" 
cap label var KC_Year "３出生年" 
cap label var KC_Month "３出生月" 
cap label var KC_Haigu "４配偶者の有無" 
cap label var KC_Kyoiku "５教育（学校の種類）" 
cap label var KC_ChildHome "６あなたの子はどこに住んでいますか" 
cap label var KC_Kaigo1 "65歳以上の家族を介護(自宅内)" 
cap label var KC_Kaigo2 "65歳以上の家族を介護(自宅外・同一敷地内・近所)" 
cap label var KC_Kaigo3 "65歳以上の家族を介護(自宅外・その他)" 
cap label var KC_Kaigo4 "その他の家族を介護(自宅内)" 
cap label var KC_Kaigo5 "その他の家族を介護(自宅外・同一敷地内・近所)" 
cap label var KC_Kaigo6 "その他の家族を介護(自宅外・その他)" 
cap label var KC_Kaigo7 "介護はしていない" 
cap label var KC_Job "８ふだん仕事をしていますか" 
cap label var KC_WantJob "９仕事をしたいと思っていますか" 
cap label var KC_HopeWorkTime "10１週間に何時間くらい働きたいと思っていますか" 
cap label var KC_Tsutome "11勤めか自営かの別" 
cap label var KC_Keitai "12勤務形態" 
cap label var KC_Yukyu "13年次有給休暇の取得日数" 
cap label var KC_Shoku_Naiyo "記入の有無" 
cap label var KC_Shokugyo "職業符号" 
cap label var KC_Jyugyo "15勤め先・業主などの企業全体の従業者数" 
cap label var KC_Shugyo "16ふだんの１週間の就業時間" 
cap label var KC_ShugyokiboTime "17希望する1週間の就業時間" 
cap label var KC_Tsukin "18ふだんの片道の通勤時間" 
cap label var KC_Kenko "19ふだんの健康状態" 
cap label var KC_Shunyu_Kojin "20仕事からの１年間の収入または収益" 
cap label var KC_Time_Date "日にち" 
cap label var KC_Time_Kind1 "旅行・行楽" 
cap label var KC_Time_Kind2 "行事または冠婚葬祭" 
cap label var KC_Time_Kind3 "出張・研修など" 
cap label var KC_Time_Kind4 "在宅勤務" 
cap label var KC_Time_Kind5 "療養" 
cap label var KC_Time_Kind6 "休みの日" 
cap label var KC_Time_Kind7 "育児休業・子の看護休暇" 
cap label var KC_Time_Kind8 "介護休業・介護休暇" 
cap label var KC_Time_Kind9 "その他" 
cap label var KC_Time_Weather "天気" 
cap label var KC_House "27住居の種類" 
cap label var KC_Car "28自家用車の有無" 
cap label var KC_Shunyu_Setai "29世帯の年間収入(税込み)" 
cap label var KC_Help "30ふだん世帯以外の人から介護の手助けを受けていますか" 
cap label var KC_Tanshin1 "いない" 
cap label var KC_Tanshin2 "配偶者" 
cap label var KC_Tanshin3 "父母または配偶者の父母" 
cap label var KC_Tanshin4 "子または子の配偶者" 
cap label var KC_Tanshin5 "その他" 
cap label var KC_Nyuin1 "いない" 
cap label var KC_Nyuin2 "配偶者" 
cap label var KC_Nyuin3 "父母または配偶者の父母" 
cap label var KC_Nyuin4 "子または子の配偶者" 
cap label var KC_Nyuin5 "その他" 
cap label var KC_U10_Tsuduki1 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age1 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku1 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_11 "親族（祖父母など）から" 
cap label var KC_U10_Help_21 "近隣の知人・友人などから" 
cap label var KC_U10_Help_31 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_41 "受けていない" 
cap label var KC_U10_Tsuduki2 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age2 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku2 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_12 "親族（祖父母など）から" 
cap label var KC_U10_Help_22 "近隣の知人・友人などから" 
cap label var KC_U10_Help_32 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_42 "受けていない" 
cap label var KC_U10_Tsuduki3 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age3 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku3 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_13 "親族（祖父母など）から" 
cap label var KC_U10_Help_23 "近隣の知人・友人などから" 
cap label var KC_U10_Help_33 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_43 "受けていない" 
cap label var KC_U10_Tsuduki4 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age4 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku4 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_14 "親族（祖父母など）から" 
cap label var KC_U10_Help_24 "近隣の知人・友人などから" 
cap label var KC_U10_Help_34 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_44 "受けていない" 
cap label var KC_U10_Tsuduki5 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age5 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku5 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_15 "親族（祖父母など）から" 
cap label var KC_U10_Help_25 "近隣の知人・友人などから" 
cap label var KC_U10_Help_35 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_45 "受けていない" 
cap label var KC_U10_Tsuduki6 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age6 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku6 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_16 "親族（祖父母など）から" 
cap label var KC_U10_Help_26 "近隣の知人・友人などから" 
cap label var KC_U10_Help_36 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_46 "受けていない" 
cap label var KC_U10_Tsuduki7 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age7 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku7 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_17 "親族（祖父母など）から" 
cap label var KC_U10_Help_27 "近隣の知人・友人などから" 
cap label var KC_U10_Help_37 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_47 "受けていない" 
cap label var KC_U10_Tsuduki8 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age8 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku8 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_18 "親族（祖父母など）から" 
cap label var KC_U10_Help_28 "近隣の知人・友人などから" 
cap label var KC_U10_Help_38 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_48 "受けていない" 
cap label var KC_U10_Tsuduki9 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age9 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku9 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_19 "親族（祖父母など）から" 
cap label var KC_U10_Help_29 "近隣の知人・友人などから" 
cap label var KC_U10_Help_39 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_49 "受けていない" 
cap label var KC_U10_Tsuduki10 "32(10歳未満)世帯主との続き柄" 
cap label var KC_U10_Age10 "33(10歳未満)年齢" 
cap label var KC_U10_Zaigaku10 "34(10歳未満)在学・在園の状況" 
cap label var KC_U10_Help_110 "親族（祖父母など）から" 
cap label var KC_U10_Help_210 "近隣の知人・友人などから" 
cap label var KC_U10_Help_310 "その他（ベビーシッター・保育ママなど）から" 
cap label var KC_U10_Help_410 "受けていない" 
cap label var KC_Age "年齢" 
cap label var Joritsu "集計用乗率" 
cap label var Ken "都道府県" 
cap label var City "市区町村" 
cap label var Daitoshi "大都市圏符号" 
cap label var Toshi "都市階級符号" 
cap label var DIDKbn "人口集中・非集中の別" 
cap label var Chiiki "14地域" 
cap label var KC_Stu_Umu1 "学習・自己啓発・訓練(1)総数　実施の有無" 
cap label var var1 "FILLER" 
cap label var KC_Stu_Purpose1_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose1_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose1_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose1_4 "目的　その他" 
cap label var KC_Stu_Method1_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method1_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method1_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method1_4 "方法　講演会など" 
cap label var KC_Stu_Method1_5 "方法　通信教育" 
cap label var KC_Stu_Method1_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method1_7 "方法　職場での時間外" 
cap label var KC_Stu_Method1_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method1_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method1_10 "方法　その他" 
cap label var KC_Stu_Umu2 "学習・自己啓発・訓練(2)外国語　実施の有無" 
cap label var var2 "FILLER" 
cap label var KC_Stu_Purpose2_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose2_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose2_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose2_4 "目的　その他" 
cap label var KC_Stu_Method2_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method2_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method2_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method2_4 "方法　講演会など" 
cap label var KC_Stu_Method2_5 "方法　通信教育" 
cap label var KC_Stu_Method2_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method2_7 "方法　職場での時間外" 
cap label var KC_Stu_Method2_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method2_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method2_10 "方法　その他" 
cap label var KC_Stu_Umu3 "学習・自己啓発・訓練(3)英語　実施の有無" 
cap label var KC_Stu_Frequency3 "頻度" 
cap label var KC_Stu_FrequencyMedian3 "頻度階級中央値" 
cap label var KC_Stu_Purpose3_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose3_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose3_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose3_4 "目的　その他" 
cap label var KC_Stu_Method3_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method3_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method3_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method3_4 "方法　講演会など" 
cap label var KC_Stu_Method3_5 "方法　通信教育" 
cap label var KC_Stu_Method3_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method3_7 "方法　職場での時間外" 
cap label var KC_Stu_Method3_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method3_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method3_10 "方法　その他" 
cap label var KC_Stu_Umu4 "学習・自己啓発・訓練(4)英語以外の外国語　実施の有無" 
cap label var KC_Stu_Frequency4 "頻度" 
cap label var KC_Stu_FrequencyMedian4 "頻度階級中央値" 
cap label var KC_Stu_Purpose4_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose4_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose4_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose4_4 "目的　その他" 
cap label var KC_Stu_Method4_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method4_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method4_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method4_4 "方法　講演会など" 
cap label var KC_Stu_Method4_5 "方法　通信教育" 
cap label var KC_Stu_Method4_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method4_7 "方法　職場での時間外" 
cap label var KC_Stu_Method4_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method4_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method4_10 "方法　その他" 
cap label var KC_Stu_Umu5 "学習・自己啓発・訓練(5)商業・ビジネス(総数)　実施の有無" 
cap label var var3 "FILLER" 
cap label var KC_Stu_Purpose5_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose5_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose5_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose5_4 "目的　その他" 
cap label var KC_Stu_Method5_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method5_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method5_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method5_4 "方法　講演会など" 
cap label var KC_Stu_Method5_5 "方法　通信教育" 
cap label var KC_Stu_Method5_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method5_7 "方法　職場での時間外" 
cap label var KC_Stu_Method5_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method5_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method5_10 "方法　その他" 
cap label var KC_Stu_Umu6 "学習・自己啓発・訓練(6)パソコンなど…　実施の有無" 
cap label var KC_Stu_Frequency6 "頻度" 
cap label var KC_Stu_FrequencyMidian6 "頻度階級中央値" 
cap label var KC_Stu_Purpose6_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose6_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose6_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose6_4 "目的　その他" 
cap label var KC_Stu_Method6_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method6_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method6_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method6_4 "方法　講演会など" 
cap label var KC_Stu_Method6_5 "方法　通信教育" 
cap label var KC_Stu_Method6_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method6_7 "方法　職場での時間外" 
cap label var KC_Stu_Method6_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method6_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method6_10 "方法　その他" 
cap label var KC_Stu_Umu7 "学習・自己啓発・訓練(7)商業実務…　実施の有無" 
cap label var KC_Stu_Frequency7 "頻度" 
cap label var KC_Stu_FrequencyMidian7 "頻度階級中央値" 
cap label var KC_Stu_Purpose7_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose7_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose7_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose7_4 "目的　その他" 
cap label var KC_Stu_Method7_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method7_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method7_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method7_4 "方法　講演会など" 
cap label var KC_Stu_Method7_5 "方法　通信教育" 
cap label var KC_Stu_Method7_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method7_7 "方法　職場での時間外" 
cap label var KC_Stu_Method7_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method7_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method7_10 "方法　その他" 
cap label var KC_Stu_Umu8 "学習・自己啓発・訓練(8)介護関係　実施の有無" 
cap label var KC_Stu_Frequency8 "頻度" 
cap label var KC_Stu_FrequencyMidian8 "頻度階級中央値" 
cap label var KC_Stu_Purpose8_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose8_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose8_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose8_4 "目的　その他" 
cap label var KC_Stu_Method8_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method8_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method8_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method8_4 "方法　講演会など" 
cap label var KC_Stu_Method8_5 "方法　通信教育" 
cap label var KC_Stu_Method8_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method8_7 "方法　職場での時間外" 
cap label var KC_Stu_Method8_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method8_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method8_10 "方法　その他" 
cap label var KC_Stu_Umu9 "学習・自己啓発・訓練(9)家政・家事　実施の有無" 
cap label var KC_Stu_Frequency9 "頻度" 
cap label var KC_Stu_FrequencyMidian9 "頻度階級中央値" 
cap label var KC_Stu_Purpose9_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose9_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose9_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose9_4 "目的　その他" 
cap label var KC_Stu_Method9_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method9_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method9_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method9_4 "方法　講演会など" 
cap label var KC_Stu_Method9_5 "方法　通信教育" 
cap label var KC_Stu_Method9_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method9_7 "方法　職場での時間外" 
cap label var KC_Stu_Method9_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method9_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method9_10 "方法　その他" 
cap label var KC_Stu_Umu10 "学習・自己啓発・訓練(10)人文・社会・自然科学　実施の有無" 
cap label var KC_Stu_Frequency10 "頻度" 
cap label var KC_Stu_FrequencyMidian10 "頻度階級中央値" 
cap label var KC_Stu_Purpose10_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose10_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose10_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose10_4 "目的　その他" 
cap label var KC_Stu_Method10_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method10_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method10_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method10_4 "方法　講演会など" 
cap label var KC_Stu_Method10_5 "方法　通信教育" 
cap label var KC_Stu_Method10_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method10_7 "方法　職場での時間外" 
cap label var KC_Stu_Method10_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method10_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method10_10 "方法　その他" 
cap label var KC_Stu_Umu11 "学習・自己啓発・訓練(11)芸術・文化　実施の有無" 
cap label var KC_Stu_Frequency11 "頻度" 
cap label var KC_Stu_FrequencyMidian11 "頻度階級中央値" 
cap label var KC_Stu_Purpose11_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose11_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose11_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose11_4 "目的　その他" 
cap label var KC_Stu_Method11_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method11_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method11_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method11_4 "方法　講演会など" 
cap label var KC_Stu_Method11_5 "方法　通信教育" 
cap label var KC_Stu_Method11_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method11_7 "方法　職場での時間外" 
cap label var KC_Stu_Method11_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method11_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method11_10 "方法　その他" 
cap label var KC_Stu_Umu12 "学習・自己啓発・訓練(12)その他　実施の有無" 
cap label var var4 "FILLER" 
cap label var KC_Stu_Umu13 "学習・自己啓発・訓練(13)不詳　実施の有無" 
cap label var KC_Stu_Frequency13 "頻度" 
cap label var KC_Stu_FrequencyMidian13 "頻度階級中央値" 
cap label var KC_Stu_Purpose13_1 "目的　自分の教養を高めるため" 
cap label var KC_Stu_Purpose13_2 "目的　仕事につくため" 
cap label var KC_Stu_Purpose13_3 "目的　現在の仕事に役立てるため" 
cap label var KC_Stu_Purpose13_4 "目的　その他" 
cap label var KC_Stu_Method13_1 "方法　学級・講座・教室など（市町村等が行うもの）" 
cap label var KC_Stu_Method13_2 "方法　学級・講座・教室など（民間が行うもの）" 
cap label var KC_Stu_Method13_3 "方法　学級・講座・教室など（大学等が行うもの）" 
cap label var KC_Stu_Method13_4 "方法　講演会など" 
cap label var KC_Stu_Method13_5 "方法　通信教育" 
cap label var KC_Stu_Method13_6 "方法　テレビ・ラジオ" 
cap label var KC_Stu_Method13_7 "方法　職場での時間外" 
cap label var KC_Stu_Method13_8 "方法　各種学校・専修学校" 
cap label var KC_Stu_Method13_9 "方法　ハローワークを通じた職業訓練など" 
cap label var KC_Stu_Method13_10 "方法　その他" 
cap label var KC_Vol_Execution1 "ボランティア(1)総数　実施の有無" 
cap label var var5 "FILLER" 
cap label var KC_Vol_Group1_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group1_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group1_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group1_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group1_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group1 "団体に加入　総数" 
cap label var KC_Vol_Execution2 "ボランティア(2)健康や医療サービス…　実施の有無" 
cap label var KC_Vol_Frequency2 "頻度" 
cap label var KC_Vol_FrequencyMidian2 "頻度階級中央値" 
cap label var KC_Vol_Time2 "1日当たりの時間" 
cap label var KC_Vol_Group2_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group2_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group2_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group2_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group2_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group2 "団体に加入　総数" 
cap label var KC_Vol_Execution3 "ボランティア(3)高齢者を対象…　実施の有無" 
cap label var KC_Vol_Frequency3 "頻度" 
cap label var KC_Vol_FrequencyMedian3 "頻度階級中央値" 
cap label var KC_Vol_Time3 "1日当たりの時間" 
cap label var KC_Vol_Group3_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group3_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group3_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group3_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group3_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group3 "団体に加入　総数" 
cap label var KC_Vol_Execution4 "ボランティア(4)障害者を対象…　実施の有無" 
cap label var KC_Vol_Frequency4 "頻度" 
cap label var KC_Vol_FrequencyMedian4 "頻度階級中央値" 
cap label var KC_Vol_Time4 "1日当たりの時間" 
cap label var KC_Vol_Group4_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group4_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group4_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group4_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group4_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group4 "団体に加入　総数" 
cap label var KC_Vol_Execution5 "ボランティア(5)子供を対象…　実施の有無" 
cap label var KC_Vol_Frequency5 "頻度" 
cap label var KC_Vol_FrequencyMedian5 "頻度階級中央値" 
cap label var KC_Vol_Time5 "1日当たりの時間" 
cap label var KC_Vol_Group5_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group5_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group5_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group5_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group5_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group5 "団体に加入　総数" 
cap label var KC_Vol_Execution6 "ボランティア(6)スポーツ・文化…　実施の有無" 
cap label var KC_Vol_Frequency6 "頻度" 
cap label var KC_Vol_FrequencyMedian6 "頻度階級中央値" 
cap label var KC_Vol_Time6 "1日当たりの時間" 
cap label var KC_Vol_Group6_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group6_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group6_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group6_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group6_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group6 "団体に加入　総数" 
cap label var KC_Vol_Execution7 "ボランティア(7)まちづくり…　実施の有無" 
cap label var KC_Vol_Frequency7 "頻度" 
cap label var KC_Vol_FrequencyMedian7 "頻度階級中央値" 
cap label var KC_Vol_Time7 "1日当たりの時間" 
cap label var KC_Vol_Group7_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group7_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group7_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group7_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group7_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group7 "団体に加入　総数" 
cap label var KC_Vol_Execution8 "ボランティア(8)安全な生活…　実施の有無" 
cap label var KC_Vol_Frequency8 "頻度" 
cap label var KC_Vol_FrequencyMedian8 "頻度階級中央値" 
cap label var KC_Vol_Time8 "1日当たりの時間" 
cap label var KC_Vol_Group8_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group8_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group8_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group8_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group8_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group8 "団体に加入　総数" 
cap label var KC_Vol_Execution9 "ボランティア(9)自然や環境…　実施の有無" 
cap label var KC_Vol_Frequency9 "頻度" 
cap label var KC_Vol_FrequencyMedian9 "頻度階級中央値" 
cap label var KC_Vol_Time9 "1日当たりの時間" 
cap label var KC_Vol_Group9_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group9_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group9_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group9_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group9_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group9 "団体に加入　総数" 
cap label var KC_Vol_Execution10 "ボランティア(10)災害…　実施の有無" 
cap label var KC_Vol_Frequency10 "頻度" 
cap label var KC_Vol_FrequencyMedian10 "頻度階級中央値" 
cap label var KC_Vol_Time10 "1日当たりの時間" 
cap label var KC_Vol_Group10_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group10_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group10_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group10_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group10_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group10 "団体に加入　総数" 
cap label var KC_Vol_Execution11 "ボランティア(11)国際協力　実施の有無" 
cap label var KC_Vol_Frequency11 "頻度" 
cap label var KC_Vol_FrequencyMedian11 "頻度階級中央値" 
cap label var KC_Vol_Time11 "1日当たりの時間" 
cap label var KC_Vol_Group11_1 "団体に加入　ボランティアを目的とするクラブ・サークル　市民団体など" 
cap label var KC_Vol_Group11_2 "団体に加入　NPO（特定非営利活動法人）" 
cap label var KC_Vol_Group11_3 "団体に加入　地域社会とのつながりの強い町内会などの組織" 
cap label var KC_Vol_Group11_4 "団体に加入　その他の団体" 
cap label var KC_Vol_Group11_5 "団体などに加入しないで行っている" 
cap label var KC_Vol_Group11 "団体に加入　総数" 
cap label var KC_Vol_Execution12 "ボランティア(12)その他　実施の有無" 
cap label var var6 "FILLER" 
cap label var KC_Spo_Execution1 "スポーツ(1)総数　実施の有無" 
cap label var var7 "FILLER" 
cap label var KC_Spo_Execution2 "スポーツ(2)野球　実施の有無" 
cap label var KC_Spo_Frequency2 "頻度" 
cap label var KC_Spo_FrequencyMedian2 "頻度階級中央値" 
cap label var KC_Spo_Oya2 "親の行動の有無" 
cap label var KC_Spo_Execution3 "スポーツ(3)ソフトボール　実施の有無" 
cap label var KC_Spo_Frequency3 "頻度" 
cap label var KC_Spo_FrequencyMedian3 "頻度階級中央値" 
cap label var KC_Spo_Oya3 "親の行動の有無" 
cap label var KC_Spo_Execution4 "スポーツ(4)バレーボール　実施の有無" 
cap label var KC_Spo_Frequency4 "頻度" 
cap label var KC_Spo_FrequencyMedian4 "頻度階級中央値" 
cap label var KC_Spo_Oya4 "親の行動の有無" 
cap label var KC_Spo_Execution5 "スポーツ(5)バスケットボール　実施の有無" 
cap label var KC_Spo_Frequency5 "頻度" 
cap label var KC_Spo_FrequencyMedian5 "頻度階級中央値" 
cap label var KC_Spo_Oya5 "親の行動の有無" 
cap label var KC_Spo_Execution6 "スポーツ(6)サッカー　実施の有無" 
cap label var KC_Spo_Frequency6 "頻度" 
cap label var KC_Spo_FrequencyMedian6 "頻度階級中央値" 
cap label var KC_Spo_Oya6 "親の行動の有無" 
cap label var KC_Spo_Execution7 "スポーツ(7)卓球　実施の有無" 
cap label var KC_Spo_Frequency7 "頻度" 
cap label var KC_Spo_FrequencyMedian7 "頻度階級中央値" 
cap label var KC_Spo_Oya7 "親の行動の有無" 
cap label var KC_Spo_Execution8 "スポーツ(8)テニス　実施の有無" 
cap label var KC_Spo_Frequency8 "頻度" 
cap label var KC_Spo_FrequencyMedian8 "頻度階級中央値" 
cap label var KC_Spo_Oya8 "親の行動の有無" 
cap label var KC_Spo_Execution9 "スポーツ(9)バドミントン　実施の有無" 
cap label var KC_Spo_Frequency9 "頻度" 
cap label var KC_Spo_FrequencyMedian9 "頻度階級中央値" 
cap label var KC_Spo_Oya9 "親の行動の有無" 
cap label var KC_Spo_Execution10 "スポーツ(10)ゴルフ　実施の有無" 
cap label var KC_Spo_Frequency10 "頻度" 
cap label var KC_Spo_FrequencyMedian10 "頻度階級中央値" 
cap label var KC_Spo_Oya10 "親の行動の有無" 
cap label var KC_Spo_Execution11 "スポーツ(11)柔道　実施の有無" 
cap label var KC_Spo_Frequency11 "頻度" 
cap label var KC_Spo_FrequencyMedian11 "頻度階級中央値" 
cap label var KC_Spo_Oya11 "親の行動の有無" 
cap label var KC_Spo_Execution12 "スポーツ(12)剣道　実施の有無" 
cap label var KC_Spo_Frequency12 "頻度" 
cap label var KC_Spo_FrequencyMedian12 "頻度階級中央値" 
cap label var KC_Spo_Oya12 "親の行動の有無" 
cap label var KC_Spo_Execution13 "スポーツ(13)ゲートボール　実施の有無" 
cap label var KC_Spo_Frequency13 "頻度" 
cap label var KC_Spo_FrequencyMedian13 "頻度階級中央値" 
cap label var KC_Spo_Oya13 "親の行動の有無" 
cap label var KC_Spo_Execution14 "スポーツ(14)ボウリング　実施の有無" 
cap label var KC_Spo_Frequency14 "頻度" 
cap label var KC_Spo_FrequencyMedian14 "頻度階級中央値" 
cap label var KC_Spo_Oya14 "親の行動の有無" 
cap label var KC_Spo_Execution15 "スポーツ(15)つり　実施の有無" 
cap label var KC_Spo_Frequency15 "頻度" 
cap label var KC_Spo_FrequencyMedian15 "頻度階級中央値" 
cap label var KC_Spo_Oya15 "親の行動の有無" 
cap label var KC_Spo_Execution16 "スポーツ(16)水泳　実施の有無" 
cap label var KC_Spo_Frequency16 "頻度" 
cap label var KC_Spo_FrequencyMedian16 "頻度階級中央値" 
cap label var KC_Spo_Oya16 "親の行動の有無" 
cap label var KC_Spo_Execution17 "スポーツ(17)スキー・スノーボード　実施の有無" 
cap label var KC_Spo_Frequency17 "頻度" 
cap label var KC_Spo_FrequencyMedian17 "頻度階級中央値" 
cap label var KC_Spo_Oya17 "親の行動の有無" 
cap label var KC_Spo_Execution18 "スポーツ(18)登山・ハイキング　実施の有無" 
cap label var KC_Spo_Frequency18 "頻度" 
cap label var KC_Spo_FrequencyMedian18 "頻度階級中央値" 
cap label var KC_Spo_Oya18 "親の行動の有無" 
cap label var KC_Spo_Execution19 "スポーツ(19)サイクリング　実施の有無" 
cap label var KC_Spo_Frequency19 "頻度" 
cap label var KC_Spo_FrequencyMedian19 "頻度階級中央値" 
cap label var KC_Spo_Oya19 "親の行動の有無" 
cap label var KC_Spo_Execution20 "スポーツ(20)ジョギング・マラソン　実施の有無" 
cap label var KC_Spo_Frequency20 "頻度" 
cap label var KC_Spo_FrequencyMedian20 "頻度階級中央値" 
cap label var KC_Spo_Oya20 "親の行動の有無" 
cap label var KC_Spo_Execution21 "スポーツ(21)ウォーキング・軽い体操　実施の有無" 
cap label var KC_Spo_Frequency21 "頻度" 
cap label var KC_Spo_FrequencyMedian21 "頻度階級中央値" 
cap label var KC_Spo_Oya21 "親の行動の有無" 
cap label var KC_Spo_Execution22 "スポーツ(22)器具を使ったトレーニング　実施の有無" 
cap label var KC_Spo_Frequency22 "頻度" 
cap label var KC_Spo_FrequencyMedian22 "頻度階級中央値" 
cap label var KC_Spo_Oya22 "親の行動の有無" 
cap label var KC_Spo_Execution23 "スポーツ(23)その他　実施の有無" 
cap label var var8 "FILLER" 
cap label var KC_Spo_Oya23 "親の行動の有無" 
cap label var KC_Spo_Execution24 "スポーツ(24)不詳　実施の有無" 
cap label var KC_Spo_Frequency24 "頻度" 
cap label var KC_Spo_FrequencyMedian24 "頻度階級中央値" 
cap label var var9 "FILLER" 
cap label var KC_Hob_Execution1 "趣味・娯楽(1)総数　実施の有無" 
cap label var var10 "FILLER" 
cap label var KC_Hob_Execution2 "趣味・娯楽(2)スポーツ観覧　実施の有無" 
cap label var KC_Hob_Frequency2 "頻度" 
cap label var KC_Hob_FrequencyMedian2 "頻度階級中央値" 
cap label var KC_Hob_Oya2 "親の行動の有無" 
cap label var KC_Hob_Execution3 "趣味・娯楽(3)美術鑑賞　実施の有無" 
cap label var KC_Hob_Frequency3 "頻度" 
cap label var KC_Hob_FrequencyMedian3 "頻度階級中央値" 
cap label var KC_Hob_Oya3 "親の行動の有無" 
cap label var KC_Hob_Execution4 "趣味・娯楽(4)演芸・演劇・舞踊鑑賞　実施の有無" 
cap label var KC_Hob_Frequency4 "頻度" 
cap label var KC_Hob_FrequencyMedian4 "頻度階級中央値" 
cap label var KC_Hob_Oya4 "親の行動の有無" 
cap label var KC_Hob_Execution5 "趣味・娯楽(5)映画鑑賞　実施の有無" 
cap label var KC_Hob_Frequency5 "頻度" 
cap label var KC_Hob_FrequencyMedian5 "頻度階級中央値" 
cap label var KC_Hob_Oya5 "親の行動の有無" 
cap label var KC_Hob_Execution6 "趣味・娯楽(6)音楽会などによるクラシック音楽鑑賞　実施の有無" 
cap label var KC_Hob_Frequency6 "頻度" 
cap label var KC_Hob_FrequencyMedian6 "頻度階級中央値" 
cap label var KC_Hob_Oya6 "親の行動の有無" 
cap label var KC_Hob_Execution7 "趣味・娯楽(7)音楽会などによるポピュラー音楽…　実施の有無" 
cap label var KC_Hob_Frequency7 "頻度" 
cap label var KC_Hob_FrequencyMedian7 "頻度階級中央値" 
cap label var KC_Hob_Oya7 "親の行動の有無" 
cap label var KC_Hob_Execution8 "趣味・娯楽(8)ＣＤ・テープ…　実施の有無" 
cap label var KC_Hob_Frequency8 "頻度" 
cap label var KC_Hob_FrequencyMedian8 "頻度階級中央値" 
cap label var KC_Hob_Oya8 "親の行動の有無" 
cap label var KC_Hob_Execution9 "趣味・娯楽(9)ＤＶＤ・ビデオ…　実施の有無" 
cap label var KC_Hob_Frequency9 "頻度" 
cap label var KC_Hob_FrequencyMedian9 "頻度階級中央値" 
cap label var KC_Hob_Oya9 "親の行動の有無" 
cap label var KC_Hob_Execution10 "趣味・娯楽(10)楽器の演奏　実施の有無" 
cap label var KC_Hob_Frequency10 "頻度" 
cap label var KC_Hob_FrequencyMedian10 "頻度階級中央値" 
cap label var KC_Hob_Oya10 "親の行動の有無" 
cap label var KC_Hob_Execution11 "趣味・娯楽(11)邦楽　実施の有無" 
cap label var KC_Hob_Frequency11 "頻度" 
cap label var KC_Hob_FrequencyMedian11 "頻度階級中央値" 
cap label var KC_Hob_Oya11 "親の行動の有無" 
cap label var KC_Hob_Execution12 "趣味・娯楽(12)コーラス・声楽　実施の有無" 
cap label var KC_Hob_Frequency12 "頻度" 
cap label var KC_Hob_FrequencyMedian12 "頻度階級中央値" 
cap label var KC_Hob_Oya12 "親の行動の有無" 
cap label var KC_Hob_Execution13 "趣味・娯楽(13)邦舞・おどり　実施の有無" 
cap label var KC_Hob_Frequency13 "頻度" 
cap label var KC_Hob_FrequencyMedian13 "頻度階級中央値" 
cap label var KC_Hob_Oya13 "親の行動の有無" 
cap label var KC_Hob_Execution14 "趣味・娯楽(14)洋舞・社交ダンス　実施の有無" 
cap label var KC_Hob_Frequency14 "頻度" 
cap label var KC_Hob_FrequencyMedian14 "頻度階級中央値" 
cap label var KC_Hob_Oya14 "親の行動の有無" 
cap label var KC_Hob_Execution15 "趣味・娯楽(15)書道　実施の有無" 
cap label var KC_Hob_Frequency15 "頻度" 
cap label var KC_Hob_FrequencyMedian15 "頻度階級中央値" 
cap label var KC_Hob_Oya15 "親の行動の有無" 
cap label var KC_Hob_Execution16 "趣味・娯楽(16)華道　実施の有無" 
cap label var KC_Hob_Frequency16 "頻度" 
cap label var KC_Hob_FrequencyMedian16 "頻度階級中央値" 
cap label var KC_Hob_Oya16 "親の行動の有無" 
cap label var KC_Hob_Execution17 "趣味・娯楽(17)茶道　実施の有無" 
cap label var KC_Hob_Frequency17 "頻度" 
cap label var KC_Hob_FrequencyMedian17 "頻度階級中央値" 
cap label var KC_Hob_Oya17 "親の行動の有無" 
cap label var KC_Hob_Execution18 "趣味・娯楽(18)和裁・洋裁　実施の有無" 
cap label var KC_Hob_Frequency18 "頻度" 
cap label var KC_Hob_FrequencyMedian18 "頻度階級中央値" 
cap label var KC_Hob_Oya18 "親の行動の有無" 
cap label var KC_Hob_Execution19 "趣味・娯楽(19)編み物・手芸　実施の有無" 
cap label var KC_Hob_Frequency19 "頻度" 
cap label var KC_Hob_FrequencyMedian19 "頻度階級中央値" 
cap label var KC_Hob_Oya19 "親の行動の有無" 
cap label var KC_Hob_Execution20 "趣味・娯楽(20)趣味としての料理…　実施の有無" 
cap label var KC_Hob_Frequency20 "頻度" 
cap label var KC_Hob_FrequencyMedian20 "頻度階級中央値" 
cap label var KC_Hob_Oya20 "親の行動の有無" 
cap label var KC_Hob_Execution21 "趣味・娯楽(21)園芸・庭いじり…　実施の有無" 
cap label var KC_Hob_Frequency21 "頻度" 
cap label var KC_Hob_FrequencyMedian21 "頻度階級中央値" 
cap label var KC_Hob_Oya21 "親の行動の有無" 
cap label var KC_Hob_Execution22 "趣味・娯楽(22)日曜大工　実施の有無" 
cap label var KC_Hob_Frequency22 "頻度" 
cap label var KC_Hob_FrequencyMedian22 "頻度階級中央値" 
cap label var KC_Hob_Oya22 "親の行動の有無" 
cap label var KC_Hob_Execution23 "趣味・娯楽(23)絵画・彫刻の制作　実施の有無" 
cap label var KC_Hob_Frequency23 "頻度" 
cap label var KC_Hob_FrequencyMedian23 "頻度階級中央値" 
cap label var KC_Hob_Oya23 "親の行動の有無" 
cap label var KC_Hob_Execution24 "趣味・娯楽(24)陶芸・工芸　実施の有無" 
cap label var KC_Hob_Frequency24 "頻度" 
cap label var KC_Hob_FrequencyMedian24 "頻度階級中央値" 
cap label var KC_Hob_Oya24 "親の行動の有無" 
cap label var KC_Hob_Execution25 "趣味・娯楽(25)写真の撮影・プリント　実施の有無" 
cap label var KC_Hob_Frequency25 "頻度" 
cap label var KC_Hob_FrequencyMedian25 "頻度階級中央値" 
cap label var KC_Hob_Oya25 "親の行動の有無" 
cap label var KC_Hob_Execution26 "趣味・娯楽(26)詩・和歌…　実施の有無" 
cap label var KC_Hob_Frequency26 "頻度" 
cap label var KC_Hob_FrequencyMedian26 "頻度階級中央値" 
cap label var KC_Hob_Oya26 "親の行動の有無" 
cap label var KC_Hob_Execution27 "趣味・娯楽(27)趣味としての読書　実施の有無" 
cap label var KC_Hob_Frequency27 "頻度" 
cap label var KC_Hob_FrequencyMedian27 "頻度階級中央値" 
cap label var KC_Hob_Oya27 "親の行動の有無" 
cap label var KC_Hob_Execution28 "趣味・娯楽(28)囲碁　実施の有無" 
cap label var KC_Hob_Frequency28 "頻度" 
cap label var KC_Hob_FrequencyMedian28 "頻度階級中央値" 
cap label var KC_Hob_Oya28 "親の行動の有無" 
cap label var KC_Hob_Execution29 "趣味・娯楽(29)将棋　実施の有無" 
cap label var KC_Hob_Frequency29 "頻度" 
cap label var KC_Hob_FrequencyMedian29 "頻度階級中央値" 
cap label var KC_Hob_Oya29 "親の行動の有無" 
cap label var KC_Hob_Execution30 "趣味・娯楽(30)パチンコ　実施の有無" 
cap label var KC_Hob_Frequency30 "頻度" 
cap label var KC_Hob_FrequencyMedian30 "頻度階級中央値" 
cap label var KC_Hob_Oya30 "親の行動の有無" 
cap label var KC_Hob_Execution31 "趣味・娯楽(31)カラオケ　実施の有無" 
cap label var KC_Hob_Frequency31 "頻度" 
cap label var KC_Hob_FrequencyMedian31 "頻度階級中央値" 
cap label var KC_Hob_Oya31 "親の行動の有無" 
cap label var KC_Hob_Execution32 "趣味・娯楽(32)テレビゲーム…　実施の有無" 
cap label var KC_Hob_Frequency32 "頻度" 
cap label var KC_Hob_FrequencyMedian32 "頻度階級中央値" 
cap label var KC_Hob_Oya32 "親の行動の有無" 
cap label var KC_Hob_Execution33 "趣味・娯楽(33)遊園地，動植物園…　実施の有無" 
cap label var KC_Hob_Frequency33 "頻度" 
cap label var KC_Hob_FrequencyMedian33 "頻度階級中央値" 
cap label var KC_Hob_Oya33 "親の行動の有無" 
cap label var KC_Hob_Execution34 "趣味・娯楽(34)キャンプ　実施の有無" 
cap label var KC_Hob_Frequency34 "頻度" 
cap label var KC_Hob_FrequencyMedian34 "頻度階級中央値" 
cap label var KC_Hob_Oya34 "親の行動の有無" 
cap label var KC_Hob_Execution35 "趣味・娯楽(35)その他　実施の有無" 
cap label var var11 "FILLER" 
cap label var KC_Hob_Oya35 "親の行動の有無" 
cap label var KC_Hob__Execution36 "趣味・娯楽(36)不詳　実施の有無" 
cap label var KC_Hob_Frequency36 "頻度" 
cap label var KC_Hob_FrequencyMedian36 "頻度階級中央値" 
cap label var var12 "FILLER" 
cap label var KC_Tra_Execution1 "旅行・行楽(1)総数　実施の有無" 
cap label var var13 "FILLER" 
cap label var KC_Tra_Frequency1 "頻度" 
cap label var KC_Tra_Person1_1 "共にした人　家族と" 
cap label var KC_Tra_Person1_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person1_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person1_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person1_5 "共にした人　一人で" 
cap label var KC_Tra_Execution2 "旅行・行楽(2)行楽（日帰り）　実施の有無" 
cap label var KC_Tra_Frequency2_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency2_2 "頻度" 
cap label var KC_Tra_Person2_1 "共にした人　家族と" 
cap label var KC_Tra_Person2_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person2_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person2_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person2_5 "共にした人　一人で" 
cap label var KC_Tra_Execution3 "旅行・行楽(3)旅行（1泊2日以上）　実施の有無" 
cap label var var14 "FILLER" 
cap label var KC_Tra_Frequency3 "頻度" 
cap label var KC_Tra_Person3_1 "共にした人　家族と" 
cap label var KC_Tra_Person3_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person3_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person3_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person3_5 "共にした人　一人で" 
cap label var KC_Tra_Execution4 "旅行・行楽(4)国内　実施の有無" 
cap label var var15 "FILLER" 
cap label var KC_Tra_Frequency4 "頻度" 
cap label var KC_Tra_Person4_1 "共にした人　家族と" 
cap label var KC_Tra_Person4_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person4_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person4_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person4_5 "共にした人　一人で" 
cap label var KC_Tra_Execution5 "旅行・行楽(5)国内　観光旅行　実施の有無" 
cap label var KC_Tra_Frequency5_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency5_2 "頻度" 
cap label var KC_Tra_Person5_1 "共にした人　家族と" 
cap label var KC_Tra_Person5_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person5_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person5_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person5_5 "共にした人　一人で" 
cap label var KC_Tra_Execution6 "旅行・行楽(6)国内　帰省・訪問などの旅行　実施の有無" 
cap label var KC_Tra_Frequency6_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency6_2 "頻度" 
cap label var KC_Tra_Person6_1 "共にした人　家族と" 
cap label var KC_Tra_Person6_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person6_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person6_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person6_5 "共にした人　一人で" 
cap label var KC_Tra_Execution7 "旅行・行楽(7)国内　業務出張…　実施の有無" 
cap label var KC_Tra_Frequency7_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency7_2 "頻度" 
cap label var KC_Tra_Person7_1 "共にした人　家族と" 
cap label var KC_Tra_Person7_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person7_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person7_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person7_5 "共にした人　一人で" 
cap label var KC_Tra_Execution8 "旅行・行楽(8)海外　実施の有無" 
cap label var var16 "FILLER" 
cap label var KC_Tra_Frequency8 "頻度" 
cap label var KC_Tra_Person8_1 "共にした人　家族と" 
cap label var KC_Tra_Person8_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person8_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person8_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person8_5 "共にした人　一人で" 
cap label var KC_Tra_Execution9 "旅行・行楽(9)海外　観光旅行　実施の有無" 
cap label var KC_Tra_Frequency9_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency9_2 "頻度" 
cap label var KC_Tra_Person9_1 "共にした人　家族と" 
cap label var KC_Tra_Person9_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person9_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person9_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person9_5 "共にした人　一人で" 
cap label var KC_Tra_Execution10 "旅行・行楽(10)海外　業務出張…　実施の有無" 
cap label var KC_Tra_Frequency10_1 "頻度（最終チェック済データ）" 
cap label var KC_Tra_Frequency10_2 "頻度" 
cap label var KC_Tra_Person10_1 "共にした人　家族と" 
cap label var KC_Tra_Person10_2 "共にした人　学校・職場の人と" 
cap label var KC_Tra_Person10_3 "共にした人　地域の人と" 
cap label var KC_Tra_Person10_4 "共にした人　友人・知人・その他の人と" 
cap label var KC_Tra_Person10_5 "共にした人　一人で" 
cap label var var17 "スポーツ(2)野球　実施の有無（最終チェック済データ）" 
cap label var var18 "頻度（最終チェック済データ）" 
cap label var var19 "スポーツ(3)ソフトボール　実施の有無（最終チェック済データ）" 
cap label var var20 "頻度（最終チェック済データ）" 
cap label var var21 "スポーツ(4)バレーボール　実施の有無（最終チェック済データ）" 
cap label var var22 "頻度（最終チェック済データ）" 
cap label var var23 "スポーツ(5)バスケットボール　実施の有無（最終チェック済データ）" 
cap label var var24 "頻度（最終チェック済データ）" 
cap label var var25 "スポーツ(6)サッカー　実施の有無（最終チェック済データ）" 
cap label var var26 "頻度（最終チェック済データ）" 
cap label var var27 "スポーツ(7)卓球　実施の有無（最終チェック済データ）" 
cap label var var28 "頻度（最終チェック済データ）" 
cap label var var29 "スポーツ(8)テニス　実施の有無（最終チェック済データ）" 
cap label var var30 "頻度（最終チェック済データ）" 
cap label var var31 "スポーツ(9)バドミントン　実施の有無（最終チェック済データ）" 
cap label var var32 "頻度（最終チェック済データ）" 
cap label var var33 "スポーツ(10)ゴルフ　実施の有無（最終チェック済データ）" 
cap label var var34 "頻度（最終チェック済データ）" 
cap label var var35 "スポーツ(11)柔道　実施の有無（最終チェック済データ）" 
cap label var var36 "頻度（最終チェック済データ）" 
cap label var var37 "スポーツ(12)剣道　実施の有無（最終チェック済データ）" 
cap label var var38 "頻度（最終チェック済データ）" 
cap label var var39 "スポーツ(13)ゲートボール　実施の有無（最終チェック済データ）" 
cap label var var40 "頻度（最終チェック済データ）" 
cap label var var41 "スポーツ(14)ボウリング　実施の有無（最終チェック済データ）" 
cap label var var42 "頻度（最終チェック済データ）" 
cap label var var43 "スポーツ(15)つり　実施の有無（最終チェック済データ）" 
cap label var var44 "頻度（最終チェック済データ）" 
cap label var var45 "スポーツ(16)水泳　実施の有無（最終チェック済データ）" 
cap label var var46 "頻度（最終チェック済データ）" 
cap label var var47 "スポーツ(17)スキー・スノーボード　実施の有無（最終チェック済データ）" 
cap label var var48 "頻度（最終チェック済データ）" 
cap label var var49 "スポーツ(18)登山・ハイキング　実施の有無（最終チェック済データ）" 
cap label var var50 "頻度（最終チェック済データ）" 
cap label var var51 "スポーツ(19)サイクリング　実施の有無（最終チェック済データ）" 
cap label var var52 "頻度（最終チェック済データ）" 
cap label var var53 "スポーツ(20)ジョギング・マラソン　実施の有無（最終チェック済データ）" 
cap label var var54 "頻度（最終チェック済データ）" 
cap label var var55 "スポーツ(21)ウォーキング・軽い体操　実施の有無（最終チェック済データ）" 
cap label var var56 "頻度（最終チェック済データ）" 
cap label var var57 "スポーツ(22)器具を使ったトレーニング　実施の有無（最終チェック済データ）" 
cap label var var58 "頻度（最終チェック済データ）" 
cap label var var59 "スポーツ(23)その他　実施の有無（最終チェック済データ）" 
cap label var var60 "FILLER" 
cap label var var61 "趣味・娯楽(2)スポーツ観覧　実施の有無（最終チェック済データ）" 
cap label var var62 "頻度（最終チェック済データ）" 
cap label var var63 "趣味・娯楽(3)美術鑑賞　実施の有無（最終チェック済データ）" 
cap label var var64 "頻度（最終チェック済データ）" 
cap label var var65 "趣味・娯楽(4)演芸・演劇・舞踊鑑賞　実施の有無（最終チェック済データ）" 
cap label var var66 "頻度（最終チェック済データ）" 
cap label var var67 "趣味・娯楽(5)映画鑑賞　実施の有無（最終チェック済データ）" 
cap label var var68 "頻度（最終チェック済データ）" 
cap label var var69 "趣味・娯楽(6)音楽会などによるクラシック音楽鑑賞　実施の有無（最終チェック済データ）" 
cap label var var70 "頻度（最終チェック済データ）" 
cap label var var71 "趣味・娯楽(7)音楽会などによるポピュラー音楽…　実施の有無（最終チェック済データ）" 
cap label var var72 "頻度（最終チェック済データ）" 
cap label var var73 "趣味・娯楽(8)ＣＤ・テープ…　実施の有無（最終チェック済データ）" 
cap label var var74 "頻度（最終チェック済データ）" 
cap label var var75 "趣味・娯楽(9)ＤＶＤ・ビデオ…　実施の有無（最終チェック済データ）" 
cap label var var76 "頻度（最終チェック済データ）" 
cap label var var77 "趣味・娯楽(10)楽器の演奏　実施の有無（最終チェック済データ）" 
cap label var var78 "頻度（最終チェック済データ）" 
cap label var var79 "趣味・娯楽(11)邦楽　実施の有無（最終チェック済データ）" 
cap label var var80 "頻度（最終チェック済データ）" 
cap label var var81 "趣味・娯楽(12)コーラス・声楽　実施の有無（最終チェック済データ）" 
cap label var var82 "頻度（最終チェック済データ）" 
cap label var var83 "趣味・娯楽(13)邦舞・おどり　実施の有無（最終チェック済データ）" 
cap label var var84 "頻度（最終チェック済データ）" 
cap label var var85 "趣味・娯楽(14)洋舞・社交ダンス　実施の有無（最終チェック済データ）" 
cap label var var86 "頻度（最終チェック済データ）" 
cap label var var87 "趣味・娯楽(15)書道　実施の有無（最終チェック済データ）" 
cap label var var88 "頻度（最終チェック済データ）" 
cap label var var89 "趣味・娯楽(16)華道　実施の有無（最終チェック済データ）" 
cap label var var90 "頻度（最終チェック済データ）" 
cap label var var91 "趣味・娯楽(17)茶道　実施の有無（最終チェック済データ）" 
cap label var var92 "頻度（最終チェック済データ）" 
cap label var var93 "趣味・娯楽(18)和裁・洋裁　実施の有無（最終チェック済データ）" 
cap label var var94 "頻度（最終チェック済データ）" 
cap label var var95 "趣味・娯楽(19)編み物・手芸　実施の有無（最終チェック済データ）" 
cap label var var96 "頻度（最終チェック済データ）" 
cap label var var97 "趣味・娯楽(20)趣味としての料理…　実施の有無（最終チェック済データ）" 
cap label var var98 "頻度（最終チェック済データ）" 
cap label var var99 "趣味・娯楽(21)園芸・庭いじり…　実施の有無（最終チェック済データ）" 
cap label var var100 "頻度（最終チェック済データ）" 
cap label var var101 "趣味・娯楽(22)日曜大工　実施の有無（最終チェック済データ）" 
cap label var var102 "頻度（最終チェック済データ）" 
cap label var var103 "趣味・娯楽(23)絵画・彫刻の制作　実施の有無（最終チェック済データ）" 
cap label var var104 "頻度（最終チェック済データ）" 
cap label var var105 "趣味・娯楽(24)陶芸・工芸　実施の有無（最終チェック済データ）" 
cap label var var106 "頻度（最終チェック済データ）" 
cap label var var107 "趣味・娯楽(25)写真の撮影・プリント　実施の有無（最終チェック済データ）" 
cap label var var108 "頻度（最終チェック済データ）" 
cap label var var109 "趣味・娯楽(26)詩・和歌…　実施の有無（最終チェック済データ）" 
cap label var var110 "頻度（最終チェック済データ）" 
cap label var var111 "趣味・娯楽(27)趣味としての読書　実施の有無（最終チェック済データ）" 
cap label var var112 "頻度（最終チェック済データ）" 
cap label var var113 "趣味・娯楽(28)囲碁　実施の有無（最終チェック済データ）" 
cap label var var114 "頻度（最終チェック済データ）" 
cap label var var115 "趣味・娯楽(29)将棋　実施の有無（最終チェック済データ）" 
cap label var var116 "頻度（最終チェック済データ）" 
cap label var var117 "趣味・娯楽(30)パチンコ　実施の有無（最終チェック済データ）" 
cap label var var118 "頻度（最終チェック済データ）" 
cap label var var119 "趣味・娯楽(31)カラオケ　実施の有無（最終チェック済データ）" 
cap label var var120 "頻度（最終チェック済データ）" 
cap label var var121 "趣味・娯楽(32)テレビゲーム…　実施の有無（最終チェック済データ）" 
cap label var var122 "頻度（最終チェック済データ）" 
cap label var var123 "趣味・娯楽(33)遊園地，動植物園…　実施の有無（最終チェック済データ）" 
cap label var var124 "頻度（最終チェック済データ）" 
cap label var var125 "趣味・娯楽(34)キャンプ　実施の有無（最終チェック済データ）" 
cap label var var126 "頻度（最終チェック済データ）" 
cap label var var127 "趣味・娯楽(35)その他　実施の有無（最終チェック済データ）" 
