/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/Dropbox/fukai_toriyabe/レイアウト/03_1 平成07年全数・抽出詳細集計.xlsx
    Date: 2019/04/14 14:46:10
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str NENTUKI 3-8
        str KEN 9-10
        str CITY 11-13
        str SHUBAN 14-17
        str KOUCHI 18-18
        str BUNKATU 19-20
        str DTKBN 21-21
        str SETORG 22-24
        str SETINREN 32-35
        str RITSU 44-54
        str TOKEIKU 55-56
        str AZACODE 72-75
        str TANIKUCODE 76-80
        str ISKBN 93-93
        str TAN30 94-94
        str SETAI 96-96
        str TATE 97-97
        str KAISU 98-98
        str LIVE 99-99
        str JYUKYO 100-100
        str HEYA 101-102
        str NOBEAREA 107-111
        str NOBE14 112-113
        str SETJIN 115-118
        str TUZUKI 214-215
        str SEX 216-216
        str GENGO 217-217
        str NEN 218-219
        str TUKI 220-220
        str NENREI 221-223
        str HAIGU 226-226
        str KOKUSEKI 227-227
        str GAIKOKU 228-228
        str KOKU11 229-230
        str RODO3 231-231
        str RODO8 232-232
        str JYU3 233-233
        str JYU4 234-234
        str JYU6A 235-235
        str JYUKEN 236-237
        str JYUCITY 238-240
        str CHII6 243-243
        str ROUJYU 244-244
        str SAND 246-247
        str SANC 248-249
        str SANS 253-255
        str SHOKD 259-260
        str SHOKC 262-263
        str SHOKS 267-269
    using "data";
#delimit cr
