/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx
    Date: 2019/02/22 13:15:14
----------------------------------------------------------------------*/


// Base data: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査年"    "調査年"
    Variable Name:  "var1"    "Chosa_Nen" 
    Variable values:
        Base data:   2005~2009: ,
        Match data:  2014: 西暦,

----------------------------------------------------------------------*/
capture rename Chosa_Nen var1


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "府県ごとの括通し番号"    "府県ごとの括通し番号"
    Variable Name:  "var2"    "Katsu" 
    Variable values:
        Base data:   01~: ,
        Match data:  01--99: ,

----------------------------------------------------------------------*/
capture rename Katsu var2


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "都道府県番号"    "都道府県番号"
    Variable Name:  "var4"    "Ken" 
    Variable values:
        Base data:   01~47: ,
        Match data:  01--47: ,

----------------------------------------------------------------------*/
capture rename Ken var4


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所一連番号"    "事業所一連番号"
    Variable Name:  "var5"    "JigyoRen" 
    Variable values:
        Base data:   100010~: ,
        Match data:  10001--17262: , 18001--18100: , 50001--50107: , 58001--58100: ,

----------------------------------------------------------------------*/
capture rename JigyoRen var5


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "○○枚目"    "○○枚目"
    Variable Name:  "var6"    "Maime" 
    Variable values:
        Base data:   1~99: ,
        Match data:  1--99: ,

----------------------------------------------------------------------*/
capture rename Maime var6


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "労働者一連番号"    "労働者一連番号"
    Variable Name:  "var7"    "RouRen" 
    Variable values:
        Base data:   01~99: ,
        Match data:  01--99: ,

----------------------------------------------------------------------*/
capture rename RouRen var7


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "市区町村番号"    "市区町村番号"
    Variable Name:  "var8"    "Shiku" 
    Variable values:
        Base data:   101~: ,
        Match data:  101~: 経済センサスの数字,

----------------------------------------------------------------------*/
capture rename Shiku var8


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "基本調査区番号"    "基本調査区番号"
    Variable Name:  "var9"    "Kihon" 
    Variable values:
        Base data:   000001~: ,
        Match data:  0001~: 経済センサスの数字,

----------------------------------------------------------------------*/
capture rename Kihon var9


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "事業所番号"    "事業所番号"
    Variable Name:  "var10"    "Jigyosyo" 
    Variable values:
        Base data:   0001~: ,
        Match data:  0001~: 経済センサスの数字,

----------------------------------------------------------------------*/
capture rename Jigyosyo var10


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "調査票事業所規模"    "共通事業所コード"
    Variable Name:  "var18"    "var2" 
    Variable values:
        Base data:   0: 15,000人以上, 1: 5,000~14,999人, 2: 1,000~4,999人, 3: 500~999人, 4: 300~499人, 5: 100~299人, 6: 50~99人, 7: 30~49人, 8: 10~29人, 9: 5~9人,
        Match data:  000000000--999999999: ,

----------------------------------------------------------------------*/
capture rename var2 var18


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "抽出率事業所"    "共通事業所コード"
    Variable Name:  "var21"    "var2" 
    Variable values:
        Base data:   0001~: ,
        Match data:  000000000--999999999: ,

----------------------------------------------------------------------*/
capture rename var2 var21


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "復元倍率"    "復元倍率"
    Variable Name:  "var24"    "Fukugen" 
    Variable values:
        Base data:   000001~: ,
        Match data:  000001.000--999999.999: 事業所抽出率×[常用労働者抽出率(雇用形態1~4)、又は、臨時労働者抽出率(雇用形態5)、又は、事業所の労働者数/個人票の労働者数],

----------------------------------------------------------------------*/
capture rename Fukugen var24


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "本支区分"    "本・支区分"
    Variable Name:  "var25"    "Honshi" 
    Variable values:
        Base data:   1: 単独事業所, 2: 本社, 3: 支社,
        Match data:  1: 単独事業所, 2: 本社, 3: 支社、新設事業所,

----------------------------------------------------------------------*/
capture rename Honshi var25


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "民公区分"    "民・公区分"
    Variable Name:  "var26"    "Minko" 
    Variable values:
        Base data:   4: 民営事業所, 5: 公営事業所,
        Match data:  4: 民営事業所, 5: 公営事業所,

----------------------------------------------------------------------*/
capture rename Minko var26


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "種類"    "種類"
    Variable Name:  "var27"    "Syurui" 
    Variable values:
        Base data:   1: 国, 2: 都道府県, 3: 市区町村, 4: 独立行政法人, 5: その他,
        Match data:  1: 国, 2: 都道府県, 3: 市区町村, 4: 独立行政法人, 5: その他,

----------------------------------------------------------------------*/
capture rename Syurui var27


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員・男"    "常用労働者"
    Variable Name:  "var29"    "RodoRitsu" 
    Variable values:
        Base data:   00000~: ,
        Match data:  01--99: 産業・事業所規模別の規定値,

----------------------------------------------------------------------*/
capture rename RodoRitsu var29


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員・女"    "常用労働者"
    Variable Name:  "var30"    "RodoRitsu" 
    Variable values:
        Base data:   00000~: ,
        Match data:  01--99: 産業・事業所規模別の規定値,

----------------------------------------------------------------------*/
capture rename RodoRitsu var30


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員以外・男"    "常用労働者"
    Variable Name:  "var31"    "RodoRitsu" 
    Variable values:
        Base data:   00000~: ,
        Match data:  01--99: 産業・事業所規模別の規定値,

----------------------------------------------------------------------*/
capture rename RodoRitsu var31


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "常用労働者・正社員以外・女"    "常用労働者"
    Variable Name:  "var32"    "RodoRitsu" 
    Variable values:
        Base data:   00000~: ,
        Match data:  01--99: 産業・事業所規模別の規定値,

----------------------------------------------------------------------*/
capture rename RodoRitsu var32


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "臨時労働者数"    "臨時労働者数"
    Variable Name:  "var33"    "Rinji" 
    Variable values:
        Base data:   00000~: ,
        Match data:  00000--99999: ,

----------------------------------------------------------------------*/
capture rename Rinji var33


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "産業大分類"    "産業分類番号"
    Variable Name:  "var34"    "Sangyo" 
    Variable values:
        Base data:   D: 051~059:鉱業, E: 061~089:建設業, F: 091~329:製造業, G: 331~363:電気・ガス・熱供給・水道業, H: 371~415:情報通信業, I: 421~489:運輸業, J: 491~609:卸売・小売業, K: 611~675:金融・保険業, L: 681~694:不動産業, M: 701~711、713~729:飲食店、宿泊業, N: 731~736、742、749、751、753~759:医療、福祉, O: 761~779:教育、学習支援業, P: 781~792:複合サービス業, Q: 801~824、829、831、833~939:サービス業,
        Match data:  050--959: ,

----------------------------------------------------------------------*/
capture rename Sangyo var34


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "産業中分類"    "産業分類番号"
    Variable Name:  "var35"    "Sangyo" 
    Variable values:
        Base data:   05~93: ,
        Match data:  050--959: ,

----------------------------------------------------------------------*/
capture rename Sangyo var35


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "産業小分類"    "産業分類番号"
    Variable Name:  "var36"    "Sangyo" 
    Variable values:
        Base data:   1、: I481のみ,
        Match data:  050--959: ,

----------------------------------------------------------------------*/
capture rename Sangyo var36


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "性別"    "性別"
    Variable Name:  "var38"    "Sei" 
    Variable values:
        Base data:   1: 男, 2: 女,
        Match data:  1: 男, 2: 女,

----------------------------------------------------------------------*/
capture rename Sei var38


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "雇用形態"    "雇用形態"
    Variable Name:  "var39"    "Koyo" 
    Variable values:
        Base data:   1: 正社員・正職員のうち雇用期間の定めがない人, 2: 正社員・正職員のうち雇用期間の定めがある人, 3: 正社員・正職員以外のうち雇用期間の定めがない人, 4: 正社員・正職員以外のうち雇用期間の定めがある人, 5: 臨時労働者,
        Match data:  1: 正社員・正職員のうち雇用期間の定め無し, 2: 正社員・正職員のうち雇用期間の定め有り, 3: 正社員・正職員以外のうち雇用期間の定め無し, 4: 正社員・正職員以外のうち雇用期間の定め有り, 5: 臨時労働者,

----------------------------------------------------------------------*/
capture rename Koyo var39


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "就業形態"    "就業形態"
    Variable Name:  "var40"    "Syugyo" 
    Variable values:
        Base data:   1: 一般, 2: 短時間,
        Match data:  1: 一般, 2: 短時間,

----------------------------------------------------------------------*/
capture rename Syugyo var40


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "最終学歴"    "最終学歴"
    Variable Name:  "var41"    "Gakureki" 
    Variable values:
        Base data:   1: 中卒, 2: 高卒, 3: 高専・短大卒, 4: 大学・大学院卒,
        Match data:  1: 中学卒, 2: 高校卒, 3: 高専・短大卒, 4: 大学・大学院卒,

----------------------------------------------------------------------*/
capture rename Gakureki var41


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "年齢"    "年齢"
    Variable Name:  "var42"    "Nenrei" 
    Variable values:
        Base data:   15~79: ,
        Match data:  15--99: ,

----------------------------------------------------------------------*/
capture rename Nenrei var42


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "勤続年数"    "勤続年数"
    Variable Name:  "var43"    "Kinzoku" 
    Variable values:
        Base data:   00~: ,
        Match data:  00--99: ,

----------------------------------------------------------------------*/
capture rename Kinzoku var43


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "労働者の種類"    "労働者の種類"
    Variable Name:  "var44"    "RouSyu" 
    Variable values:
        Base data:   1: 生産(産業D~F、I481で事規0~8のみ), 2: 管理(産業D~F、I481で事規0~8のみ),
        Match data:  1: 生産, 2: 管理・事務・技術,

----------------------------------------------------------------------*/
capture rename RouSyu var44


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "役職・職種"    "役職・職種番号"
    Variable Name:  "var45"    "Syoku" 
    Variable values:
        Base data:   101: 部長級, 102: 課長級, 103: 係長級, 104: 職長級(産業D~Fのみ), 105: その他役職,
        Match data:  101--105: 役職, 201--864: 職種,

----------------------------------------------------------------------*/
capture rename Syoku var45


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "経験年数"    "経験年数"
    Variable Name:  "var46"    "Keiken" 
    Variable values:
        Base data:   1: 1年未満, 2: 1~4年, 3: 5~9年, 4: 10~14年, 5: 15年以上,
        Match data:  1: 1年未満, 2: 1~4年, 3: 5~9年, 4: 10~14年, 5: 15年以上,

----------------------------------------------------------------------*/
capture rename Keiken var46


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "実労働日数"    "実労働日数"
    Variable Name:  "var47"    "RouNissu" 
    Variable values:
        Base data:   00~31: ,
        Match data:  00--31: ,

----------------------------------------------------------------------*/
capture rename RouNissu var47


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "所定内実労働時間数"    "所定内実労働時間数"
    Variable Name:  "var48"    "SyoteiJikan" 
    Variable values:
        Base data:   000~: ,
        Match data:  000--999: ,

----------------------------------------------------------------------*/
capture rename SyoteiJikan var48


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "超過実労働時間数"    "超過実労働時間数"
    Variable Name:  "var49"    "ChokaJikan" 
    Variable values:
        Base data:   000~: ,
        Match data:  000--999: ,

----------------------------------------------------------------------*/
capture rename ChokaJikan var49


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "決まって支給する現金給与額"    "きまって支給する現金給与額"
    Variable Name:  "var50"    "Genkin" 
    Variable values:
        Base data:   00000~: ,
        Match data:  00000--99999: ,

----------------------------------------------------------------------*/
capture rename Genkin var50


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "超過労働給与額"    "超過労働給与額"
    Variable Name:  "var51"    "ChokaKyuyo" 
    Variable values:
        Base data:   0000~: ,
        Match data:  0000--9999: ,

----------------------------------------------------------------------*/
capture rename ChokaKyuyo var51


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "所定内給与額"    "所定内給与額"
    Variable Name:  "var52"    "SyoteiKyuyo" 
    Variable values:
        Base data:   00000~: ,
        Match data:  00000--99999: ,

----------------------------------------------------------------------*/
capture rename SyoteiKyuyo var52


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "うち精皆勤手当"    "精皆勤手当"
    Variable Name:  "var54"    "Seikin" 
    Variable values:
        Base data:   000~: ,
        Match data:  000--999: ,

----------------------------------------------------------------------*/
capture rename Seikin var54


/*----------------------------------------------------------------------
                        Base data .vs. Match data

    Description:     "昨年1年間の賞与期末手当等特別給与額"    "昨年1年間の賞与期末手当等特別給与額"
    Variable Name:  "var56"    "Tokubetsu" 
    Variable values:
        Base data:   000000~: ,
        Match data:  000000--999999: ,

----------------------------------------------------------------------*/
capture rename Tokubetsu var56


