/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2019/04/14 14:46:10
-----------------------------------------------------------------------------*/


capture label define NENTUKI 200010 "2000年10月" 
capture label values NENTUKI NENTUKI

capture label define KOUCHI 1 "一般の調査区" 2 "山岳・森林・原野地帯等の区域" 3 "都市的施設のある区域" 4 "社会施設・大きな病院のある区域" 5 "刑務所・拘置所のある区域" 6 "自衛隊区域" 7 "駐留軍区域" 8 "おおむね50人以上の単身者が居住している寄宿舎・寮等の区域" 9 "水面調査区" 
capture label values KOUCHI KOUCHI

capture label define SETAI 1 "一般の世帯" 2 "一人世帯(会社等の独身寮の入居者を含む)" 3 "寮・寄宿舎の学生・生徒" 4 "病院・療養所の入院者" 5 "社会施設の入所者" 6 "その他" 7 "自衛隊営舎居住" 8 "矯正施設入居者" 
capture label values SETAI SETAI

capture label define ISKBN 1 "一般世帯" 
capture label values ISKBN ISKBN

capture label define TAN30 1 "30人以上の施設等の世帯" 
capture label values TAN30 TAN30

capture label define TATE 1 "一戸建" 2 "長屋建" 3 "共同住宅" 4 "その他" 
capture label values TATE TATE

capture label define KAI4 1 "1・2階" 2 "3~5階" 3 "6~10階" 4 "11階以上" 
capture label values KAI4 KAI4

capture label define LIVE4 1 "1・2階" 2 "3~5階" 3 "6~10階" 4 "11階以上" 
capture label values LIVE4 LIVE4

capture label define JYUKYO 1 "持ち家" 2 "公営の借家" 3 "公団・公社の借家" 4 "民営の借家" 5 "給与住宅" 6 "間借り" 7 "会社等の独身寮・寄宿舎" 8 "その他" 
capture label values JYUKYO JYUKYO

capture label define JYUKYO4 1 "主世帯" 2 "間借り" 3 "住宅以外に住む一般世帯" 
capture label values JYUKYO4 JYUKYO4

capture label define NOBE14 1 "0~19m2" 2 "20~29m2" 3 "30~39m2" 4 "40~49m2" 5 "50~59m2" 6 "60~69m2" 7 "70~79m2" 8 "80~89m2" 9 "90~99m2" 10 "100~119m2" 11 "120~149m2" 12 "150~199m2" 13 "200~249m2" 14 "250m2以上" 
capture label values NOBE14 NOBE14

capture label define NOBE6 1 "0~29m2" 2 "30~49m2" 3 "50~69m2" 4 "70~99m2" 5 "100~149m2" 6 "150m2以上" 
capture label values NOBE6 NOBE6

capture label define SYUNYU 1 "賃金・給料" 2 "農業収入" 3 "農業以外の事業収入" 4 "内職収入" 5 "恩給・年金" 6 "仕送り" 7 "その他の収入" 
capture label values SYUNYU SYUNYU

capture label define JYUSYU1 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU1 JYUSYU1

capture label define JYUSYU2 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU2 JYUSYU2

capture label define JYUSYU3 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU3 JYUSYU3

capture label define JYUSYU4 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU4 JYUSYU4

capture label define JYUSYU5 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU5 JYUSYU5

capture label define JYUSYU6 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU6 JYUSYU6

capture label define JYUSYU7 0 "収入無し" 1 "収入有り" 
capture label values JYUSYU7 JYUSYU7

capture label define SYUNYU16 1 "賃金・給料が主な世帯" 2 "" 3 "" 4 "農業収入が主な世帯" 5 "" 6 "" 7 "農業収入以外の事業収入が主な世帯" 8 "" 9 "" 10 "内職収入が主な世帯" 11 "" 12 "" 13 "恩給・年金が主な世帯" 14 "" 15 "仕送りが主な世帯" 16 "その他の収入が主な世帯" 
capture label values SYUNYU16 SYUNYU16

capture label define SYUNYU11 1 "賃金・給料が主な世帯" 2 "" 3 "農業収入が主な世帯" 4 "" 5 "農業収入以外の事業収入が主な世帯" 6 "" 7 "内職収入が主な世帯" 8 "恩給・年金が主な世帯" 9 "" 10 "仕送りが主な世帯" 11 "その他の収入が主な世帯" 
capture label values SYUNYU11 SYUNYU11

capture label define TUZUKI 1 "世帯主または代表者" 2 "世帯主の配偶者" 3 "子" 4 "子の配偶者" 5 "世帯主の父母" 6 "世帯主の配偶者の父母" 7 "孫" 8 "祖父母" 9 "兄弟姉妹" 10 "他の親族" 11 "住み込みの雇人" 12 "その他" 
capture label values TUZUKI TUZUKI

capture label define SEX 1 "男" 2 "女" 
capture label values SEX SEX

capture label define GENGO 1 "明治" 2 "大正" 3 "昭和" 4 "平成" 5 "西暦" 
capture label values GENGO GENGO

capture label define TUKI4 1 "1~3月" 2 "4~6月" 3 "7~9月" 4 "10~12月" 
capture label values TUKI4 TUKI4

capture label define HAIGU 1 "未婚(幼児などを含む)" 2 "配偶者あり" 3 "死別" 4 "離別" 
capture label values HAIGU HAIGU

capture label define KOKUSEKI 1 "日本" 2 "外国" 
capture label values KOKUSEKI KOKUSEKI

capture label define GAIKOKU 1 "韓国,朝鮮" 2 "中国" 3 "ブラジル" 4 "フィリピン" 5 "アメリカ" 6 "ペルー" 7 "タイ" 8 "イギリス" 9 "東南アジア,南アジアの国(4,7以外)" 0 "その他の国" 
capture label values GAIKOKU GAIKOKU

capture label define KOKU11 1 "日本" 2 "韓国,朝鮮" 3 "中国" 4 "東南アジア,南アジア" 5 "" 6 "" 7 "イギリス" 8 "アメリカ" 9 "ブラジル" 10 "ペルー" 11 "その他" 
capture label values KOKU11 KOKU11

capture label define KIKAN 1 "出生時から" 2 "1年未満" 3 "1~5年未満" 4 "5~10年未満" 5 "10~20年未満" 6 "20年以上" 
capture label values KIKAN KIKAN

capture label define ZENJ4 1 "現在と同じ場所" 2 "同じ市区町村(区)の他の場所" 3 "他の市区町村(区)" 4 "外国" 
capture label values ZENJ4 ZENJ4

capture label define ZENJ6 1 "現住所" 2 "自市区町村内" 3 "自市内他区" 4 "県内他市区町村" 5 "他県" 6 "転入(国外から)" 
capture label values ZENJ6 ZENJ6

capture label define KYOIKU 1 "在学中" 2 "卒業" 3 "未就学" 
capture label values KYOIKU KYOIKU

capture label define KYOKBN 1 "小学・中学" 2 "高校・旧中" 3 "短大・高専" 4 "大学・大学院" 5 "幼稚園" 6 "保育園・保育所" 7 "乳児・その他" 
capture label values KYOKBN KYOKBN

capture label define RODO3 1 "就業者" 2 "完全失業者" 3 "非労働力人口" 
capture label values RODO3 RODO3

capture label define RODO5 1 "就業者" 2 "完全失業者" 3 "家事" 4 "通学" 5 "その他" 
capture label values RODO5 RODO5

capture label define RODO8 1 "主に仕事" 2 "家事などのほか仕事" 3 "通学のかたわら仕事" 4 "仕事を休んでいた(休業者)" 5 "仕事を探していた(完全失業者)" 6 "家事" 7 "通学" 8 "その他" 
capture label values RODO8 RODO8

capture label define JIKAN14 1 "休業者" 2 "1~4時間" 3 "5~9時間" 4 "10~14時間" 5 "15~19時間" 6 "20~24時間" 7 "25~29時間" 8 "30~34時間" 9 "35~39時間" 10 "40~44時間" 11 "45~49時間" 12 "50~54時間" 13 "55~59時間" 14 "60時間以上" 
capture label values JIKAN14 JIKAN14

capture label define JIKAN10 1 "休業者" 2 "1~4時間" 3 "5~9時間" 4 "10~14時間" 5 "15~29時間" 6 "30~34時間" 7 "35~39時間" 8 "40~48時間" 9 "49~59時間" 10 "60時間以上" 
capture label values JIKAN10 JIKAN10

capture label define JYU3 1 "自宅または住み込み" 2 "同じ区・市町村" 3 "他の市区町村" 
capture label values JYU3 JYU3

capture label define JYU4 1 "自宅就業者" 2 "通勤者" 3 "通学者" 4 "その他(労働力状態=5,6,8,Vのとき)" 
capture label values JYU4 JYU4

capture label define JYU6A 1 "従業も通学もしていない" 2 "自宅で従業" 3 "自宅外の自市区町村で従業・通学" 4 "自市内他区で従業・通学" 5 "県内他市区町村で従業・通学" 6 "他県で従業・通学" 
capture label values JYU6A JYU6A

capture label define TOHO 0 "利用していない" 1 "利用している" 
capture label values TOHO TOHO

capture label define JR 0 "利用していない" 1 "利用している" 
capture label values JR JR

capture label define BUS 0 "利用していない" 1 "利用している" 
capture label values BUS BUS

capture label define SBUS 0 "利用していない" 1 "利用している" 
capture label values SBUS SBUS

capture label define CAR 0 "利用していない" 1 "利用している" 
capture label values CAR CAR

capture label define TAXI 0 "利用していない" 1 "利用している" 
capture label values TAXI TAXI

capture label define BIKE 0 "利用していない" 1 "利用している" 
capture label values BIKE BIKE

capture label define BICY 0 "利用していない" 1 "利用している" 
capture label values BICY BICY

capture label define OTHER 0 "利用していない" 1 "利用している" 
capture label values OTHER OTHER

capture label define KOTU31 1 "徒歩のみ" 2 "鉄道・電車" 3 "乗合バス" 4 "勤め先・学校のバス" 5 "自家用車" 6 "ハイヤー・タクシー" 7 "オートバイ" 8 "自転車" 9 "その他" 10 "鉄道・電車及び乗合バス" 11 "鉄道・電車及び勤め先・学校のバス" 12 "鉄道・電車及び自家用車" 13 "鉄道・電車及びハイヤー・タクシー" 14 "鉄道・電車及びオートバイ" 15 "鉄道・電車及び自転車" 16 "乗合バス及び勤め先・学校のバス" 17 "乗合バス及び自家用車" 18 "乗合バス及びハイヤー・タクシー" 19 "乗合バス及びオートバイ" 20 "乗合バス及び自転車" 21 "その他利用交通手段が2種類" 22 "鉄道・電車,乗合バス及び勤め先・学校のバス" 23 "鉄道・電車,乗合バス及び自家用車" 24 "鉄道・電車,乗合バス及びハイヤー・タクシー" 25 "鉄道・電車,乗合バス及びオートバイ" 26 "鉄道・電車,乗合バス及び自転車" 27 "鉄道・電車,勤め先・学校バス及び自家用車" 28 "鉄道・電車,勤め先・学校バス及びオートバイ" 29 "鉄道・電車,勤め先・学校バス及び自転車" 30 "その他利用交通手段が3種類" 31 "利用交通手段が4種類以上" 
capture label values KOTU31 KOTU31

capture label define KOTU16 1 "徒歩のみ" 2 "鉄道・電車" 3 "乗合バス" 4 "勤め先・学校のバス" 5 "自家用車" 6 "ハイヤー・タクシー" 7 "オートバイ" 8 "自転車" 9 "その他" 10 "鉄道・電車及び乗合バス" 11 "鉄道・電車及び勤め先・学校のバス" 12 "鉄道・電車及び自家用車" 13 "鉄道・電車及びオートバイ" 14 "鉄道・電車及び自転車" 15 "その他利用交通手段が2種類" 16 "利用交通手段が3種類以上" 
capture label values KOTU16 KOTU16

capture label define CHII7 1 "雇用者" 2 "" 3 "役員" 4 "雇人のある業主" 5 "雇人のない業主" 6 "家族従業者" 7 "家庭内職者" 
capture label values CHII7 CHII7

capture label define CHII3 1 "雇用者(役員を含む)" 2 "自営業主(家庭内職者を含む)" 3 "家族従業者" 
capture label values CHII3 CHII3

capture label define ROUJYU 1 "雇用者(役員を含む)" 2 "雇人のある業主" 3 "雇人のない業主" 4 "家族従業者" 5 "家庭内職者" 6 "不詳" 7 "完全失業者" 8 "非労働力人口" 
capture label values ROUJYU ROUJYU

