/*----------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided by [URL].
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        _rename.do: Rename variable names to append several data

    WARNING:
        1. The generated do-files do not necessarily correct.
           If you find something wrong regarding the program or
           the resulting do-file(s), please send email to [Email Address].

        2. All variables are assumed to be numeric, if there is a variable
           with non-missing string value, modify _const.do and _val.do

        3. _validate.do checks if each variable has the values that it is
           supposed to have. (Categorical variables only)

        4. _rename.do is generated by finding a variable with a similar
           variable description and, if any, a similar variable name from
           the base data. So it is quite likely that some variables are
           renamed incorrectly. Please check and modify _rename.do.

        5. In addition, there is no file to make variable values consistent
           across different data.


    Source: 平成16～29年_賃金福祉基本統計調査_符号表(個人票).xlsx
    Date: 2019/02/25 04:50:10
----------------------------------------------------------------------*/


#delimit ;
    quietly infix
        var1 1-4
        var2 5-6
        var3 10-11
        var4 12-16
        var5 18-19
        var6 20-21
        var7 22-24
        var8 25-30
        var9 31-34
        var10 36-38
        var11 39-39
        var12 40-40
        var13 41-41
        var14 46-48
        var15 49-49
        var16 50-50
        var17 51-51
        var18 52-55
        var19 56-57
        var20 58-59
        var21 60-65
        var22 66-66
        var23 67-67
        var24 68-68
        var25 69-69
        var26 70-74
        var27 75-79
        var28 80-84
        var29 85-89
        var30 90-94
        var31 95-95
        var32 96-97
        var33 98-98
        var34 104-104
        var35 105-105
        var36 106-106
        var37 107-107
        var38 108-109
        var39 110-111
        var40 112-112
        var41 113-115
        var42 116-116
        var43 117-118
        var44 119-121
        var45 122-124
        var46 125-129
        var47 130-133
        var48 134-138
        var49 139-141
        var50 142-144
        var51 145-147
        var52 148-153
    using "/media/HD-LXU3/WageCensus_EmploymentTrend/raw/調査票情報/賃金構造基本統計調査/h01-29_k-chin/h18_k-chin.txt";
#delimit cr
